### ISSUE TITLE
bug/file_filename from partition is not ending up in metadata

### ISSUE THREAD

**Issue by qued** [Unstructured-IO/unstructured#1000]
**Describe the bug**
The docstring for `unstructured.partition.auto.partition` implies that the `file_filename` parameter's purpose is to provide a way to store the filename in metadata for cases when the filename is not otherwise provided (e.g. when the file is passed as a file object). However this doesn't actually seem to happen, and `file_filename` is only used for detecting the filetype.

**To Reproduce**
```python
from unstructured.partition.auto import partition
with open("example-docs/book-war-and-peace-1p.txt") as f:
  elements = partition(file=f, file_filename="book-war-and-peace-1p.txt")
print(elements[0].metadata)
```
(`filename` is `None` in the metadata.)

**Expected behavior**
I would expect `file_filename` to be used to populate the `filename` property of the metadata when the parameter is not `None`.

**Comment by six5532one** [comment]
Related: https://github.com/Unstructured-IO/unstructured/issues/1007

**Comment by qued** [comment]
Closing as address by #1002 . Thanks @ChrisPappalardo !
