### ISSUE TITLE
List items are detected as titles in OCR only mode

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#1010]
In some cases list items are detected as titles when partitioning PDFs using "ocr_only" mode. The goal of this issue to take a look and see if we can correct this behavior.

### Testing
```
from unstructured.partition.pdf import partition_pdf

filename = "example-docs/list-item-example.pdf"
elements = partition_pdf(filename, strategy="ocr_only")
```

**Comment by MthwRobinson** [comment]
Thanks @ztratar ! @LaverdeS and @benjats07 are actually working on a 2 column solution right now for "hi_res" and should have a PR up for that relatively soon. We'll keep you in the loop on that.

**Comment by ztratar** [comment]
Sweet! Would that likely fix line items too then? Happy to test with you. Thanks.
