### ISSUE TITLE
bug: too many tesseract errors are ignored

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#1086]
**Describe the bug**
While https://github.com/Unstructured-IO/unstructured/pull/1074 introduces an important fix where some PDF's or Images would fail to be partitioned, other valid Tesseract errors that should be bubbled up are also now ignored.

**Definition of Done**
test_unstructured/partition/test_image.py::test_partition_image_raises_with_invalid_language is no longer skipped (after  https://github.com/Unstructured-IO/unstructured/pull/1074 merges)

**Comment by awalker4** [comment]
Note - same adjustment should happen to https://github.com/Unstructured-IO/unstructured-inference/pull/183

**Comment by orlandounstructured** [comment]
@cragwolfe @awalker4 can you please confirm if good to close this issue?
