### ISSUE TITLE
feat/image-url-from-html

### ISSUE THREAD

**Issue by LaverdeS** [Unstructured-IO/unstructured#1117]
Some users are interested in extracting image-urls from HTML content.

**Describe the solution you'd like**
A new pattern in [patterns.py](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/nlp/patterns.py) and a new method (extraction 🧱) `extract_image_url_from_html` in [extract.py](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/cleaners/extract.py).

**Additional context**
Slack conversation [here](https://unstructuredw-kbe4326.slack.com/archives/C044N0YV08G/p1691742087315469).

**Comment by LaverdeS** [comment]
This regex can be a base (not tested):

```
IMAGE_URL_PATTERN = r"(https?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+\.jpg|\.jpeg|\.png|\.gif|\.bmp)"

def extract_image_urls_from_html(text: str) -> List[str]:
    return re.findall(IMAGE_URL_PATTERN, text)
```

**Comment by rbiseck3** [comment]
Image url might be using a local reference (`/this/is/an/image.jpg`) so enforcing http/https wouldn't always work.

**Comment by orlandounstructured** [comment]
Complete per https://github.com/Unstructured-IO/unstructured/pull/1212
