### ISSUE TITLE
Improve epub metadata.section

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#1126]
epub documents are partitioned using the `book.items` with `ebooklib`. The items, which are used to define the `section` of the elements it contains, do not line up exactly with the sections/chapters in the book, though. You can check this manually by finding the beginnings and endings of the text in `book.items` and comparing that to the book chapters.

This is a related open issue in `ebooklib` that might resolve this: https://github.com/aerkalov/ebooklib/issues/289

**Comment by qued** [comment]
Closing since `ebooklib` dependency has been removed.
