### ISSUE TITLE
API key on docker version of unstructured

### ISSUE THREAD

**Issue by simon-fernandes** [Unstructured-IO/unstructured#1130]
**Describe the bug**
When running Unstructured through Docker, there's no way to require an API for requests.

**To Reproduce**
Run Unstructured through docker - anyone can make requests to it

**Expected behavior**
I would like the ability to specify that my instance of unstructured requires an API key OR prevent connections outside of localhost. If this is already possible I can't see any docs on how to enable this

**Additional context**
I'm not sure if this is a bug, but as there's an public API that requires a key, I would assume that this security feature is also available through the docker version?

**Comment by awalker4** [comment]
Hi there! For api keys on our hosted api, we use our own auth service with no current plans to open source. You should be able to manage access to the api using FastAPI's [TrustedHostMiddleware](https://fastapi.tiangolo.com/advanced/middleware/#trustedhostmiddleware), or by checking the `request.client` value against a whitelist of ips.
