### ISSUE TITLE
chore: running `make test` has a side effect of creating new folders and files

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#1139]
When running `make test`, the following folders are created:
example-docs/copy-protected_images/
example-docs/layout-parser-paper-fast_images/

Desired behavior is not create or to clean up any created files and folders by `make test`

**Comment by Coniferish** [comment]
Duplicate of https://github.com/Unstructured-IO/unstructured-inference/issues/177

**Comment by cragwolfe** [comment]
> Duplicate of https://github.com/Unstructured-IO/unstructured-inference/issues/177

👍 
normally would close a dupe but let's leave it open to make sure upstream fix resolves the issue.
