### ISSUE TITLE
feat/ update _partition_pdf_or_image_with_ocr to optionally use PaddleOCR

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#1176]
Currently, `_partition_pdf_or_image_with_ocr` uses `pytesseract` to detect text in images. The goal of this issue is to enable ocr partitioning to optionally use PaddleOCR as an alternative text detection model. In addition to updating `_partition_pdf_or_image_with_ocr `, `add_pytesseract_bbox_to_elements` will also need to be updated as it expects the bounding box format from `pytesseract`.

https://pypi.org/project/paddleocr/

In paddle, `ocr.ocr(img)` returns similar data to `pytesseract.image_to_boxes(img)`

**Comment by yuanjie-ai** [comment]
https://github.com/yuanjie-ai/ChatLLM/blob/master/chatllm/llmchain/document_loaders/image.py

```python
    from chatllm.llmchain.document_loaders import UnstructuredImageLoader

    loader = UnstructuredImageLoader(
        "/Users/betterme/PycharmProjects/AI/MeUtils/meutils/ai_cv/invoice.jpg",
        strategy='ocr_only'
    )
    data = loader.load()
```

**Comment by yuanjie-ai** [comment]
> https://github.com/yuanjie-ai/ChatLLM/blob/master/chatllm/llmchain/document_loaders/image.py
> 
> ```python
>     from chatllm.llmchain.document_loaders import UnstructuredImageLoader
> 
>     loader = UnstructuredImageLoader(
>         "/Users/betterme/PycharmProjects/AI/MeUtils/meutils/ai_cv/invoice.jpg",
>         strategy='ocr_only'
>     )
>     data = loader.load()
> ```

add UnstructuredImageLoader-PaddleOCR

**Comment by yuming-long** [comment]
This PR https://github.com/Unstructured-IO/unstructured/pull/1811 is doing a `ocr_only` workflow refactor. And after the PR is merged, we might just need to add tests to double check paddle is working in `ocr_only` for this issue.
