### ISSUE TITLE
html elements are in a strange order

### ISSUE THREAD

**Issue by gevezex** [Unstructured-IO/unstructured#1184]
**Describe the bug**
if using partition_html the elements is not always in the same order as in the html document. Especially if there are "pre" tags this will be added at the end of the elements. 

**To Reproduce**
```python
elements = partition_html(filename=html_file)
all_text = []
for el in elements:
    el.apply(group_broken_paragraphs)
    el.apply(clean_extra_whitespace)
    print(el.to_dict()['text'])
```

**Expected behavior**
I would expect that the itered elements have the same order as in the html document.

**Environment Info**
unstructured==0.10.5

Is there a way I am not aware of and have the same order?

**Comment by MthwRobinson** [comment]
Thanks @gevezex ! #1197 will fix this issue
