### ISSUE TITLE
feat/min and max partition made available to all partitions

### ISSUE THREAD

**Issue by ron-unstructured** [Unstructured-IO/unstructured#1185]
**Is your feature request related to a problem? Please describe.**
Tried to use partition_html to download and chunk long webpage. However, min_partition and max_partition isn't an option.

**Describe the solution you'd like**
Right now, `min_partition` and `max_partition` are only available for XML, Text, PDF, Msg, Email partitions. These args can be made available for all `partition_` calls.

**Describe alternatives you've considered**
(1) Chunk the long, extracted texts from `partition_html` by element type, and (2) pass the texts from `partition_html` to partition_text to chunk the texts with min and max partitions. 

**Additional context**
Use decorator in `partition_` calls

**Comment by Coniferish** [comment]
@qued and @cragwolfe, for this issue it's looking like handling coordinates properly will be a challenge. Would it be acceptable to have two elements with the same coordinates if they originate from a single element that's broken into two because of `max_partition`? I'm not as familiar with all the requirements around coordinates.

**Comment by Coniferish** [comment]
Great. I haven't touched the unstructured-api repo yet, but do you want me to create an issue there? I can work on adding the `chuncking_strategy` parameter to the partition functions here, though

**Comment by Coniferish** [comment]
@cragwolfe Great. I haven't touched the unstructured-api repo yet, but do you want me to create an issue there? I can work on adding the `chuncking_strategy` parameter to the partition functions here, though

**Comment by orlandounstructured** [comment]
Closing due to #1222 ; reopen if still relevant

**Comment by scanny** [comment]
Just a note on this, in case anyone reopens later. In my view, an element (partition) is a _naturally bounded_ object, generally those bounds being the extent of the paragraph it came from.

Any _synthetic_ sizing should be performed by _chunking_ elements, which can divide large elements using text-splitting and combine small elements into larger ones if desired.

Maybe that's the conclusion the conversation around this ticket came to, just wanted to argue against adding size arguments to partitioners.
