### ISSUE TITLE
docs: how to view bounding box and ordering output

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#1208]
**Is your feature request related to a problem? Please describe.**
There are a few extremely very useful snippets floating around that show how view bounding boxes and ordering of elements for a given page or image.

This includes:

https://drive.google.com/file/d/1HgBvHNPnY-dXO043DftvvMeynlLPgQ_p/view?usp=drive_link
and the description of https://github.com/Unstructured-IO/unstructured/pull/1163 , https://github.com/Unstructured-IO/unstructured-inference/pull/208 , and probably others.

**Describe the solution you'd like**

These resources to be easily discoverable in documentation, if not included inline in documentation.

**Comment by orlandounstructured** [comment]
Closing because longer than 180 days;
reopen with comment if the issue is still relevant
