### ISSUE TITLE
bug: ListItem elements with no text

### ISSUE THREAD

**Issue by qued** [Unstructured-IO/unstructured#1228]
Document types that are being processed directly or indirectly by `partition_text` sometime produce `ListItem` elements that have an empty text field.

This was meant to be prevented by [this line of code](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/text.py#L250), but I suspect `ListItem`s are slipping through by the following mechanism:

1. `ctext` is checked, it's not empty
2. The text is routed as a `ListItem`
3. `clean_bullets` is applied, but this removes everything from the text
4. The element is returned

This should be validated as a mechanism by which empty `ListItem`s are slipping through, and the loophole should be closed. Perhaps by moving the check for empty text to after the element is created and just before it is returned.

**Comment by mallorih** [comment]
https://github.com/Unstructured-IO/unstructured/pull/1268

**Comment by orlandounstructured** [comment]
Complete with #1252 ; reopen with comment if a different solution is required
