### ISSUE TITLE
bug/`sort_page_elements` with empty coordinates (`chipper` output for `PDF`s)

### ISSUE THREAD

**Issue by LaverdeS** [Unstructured-IO/unstructured#1237]
**Describe the bug**
`AttributeError: 'NoneType' object has no attribute 'points'` when using the partition auto method with `chipper` model with a `.pdf` file as input. I see this happening because `chipper` returns empty bounding boxes information, and now the default method for sorting `SORT_MODE_XY_CUT` counts on having those. It breaks the [example notebook](https://github.com/Unstructured-IO/unstructured/blob/main/examples/chipper-local-inference/chipper-local-inference.ipynb) for chipper local inference.

**To Reproduce**
```python
from unstructured.partition.auto import partition
filename = 'layout-parser-paper-fast.pdf'
model_name = "chipper"
elements = partition(filename=filename, strategy='hi_res', model_name=model_name, pdf_image_dpi=300)

# to reproduce it with an image input (restart kernel first)
import os
os.environ['UNSTRUCTURED_HI_RES_MODEL_NAME'] = model_name
from unstructured.partition.auto import partition
filename = 'layout-parser-paper-fast.jpg'
model_name = "chipper"
elements = partition(filename=filename, strategy='hi_res')
```

**Expected behavior**
Unstructured elements output.

**Screenshots**
<img width="1580" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/38184042/8a8d767a-9c38-4d00-b44e-a8afabe41986">

**Environment Info**
I run this on a colab. I installed the libraries as:
```
!pip install unstructured --quiet
!pip install unstructured-inference --quiet
!apt-get update -y && apt-get install -y poppler-utils --quiet
!apt-get -qq install tesseract-ocr
!pip install -q --user --upgrade pillow
```

The full code is the [example notebook](https://github.com/Unstructured-IO/unstructured/blob/main/examples/chipper-local-inference/chipper-local-inference.ipynb) to run local inference with `chipper` which was working without bugs at the time of its creation. 

**Additional Context**
At first glance I see its related to last introduced changes to solve the double column sorting of elements in [sorting.py](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/utils/sorting.py). 
```python
sort_page_elements(
    page_elements: List[Element],
    sort_mode: str = SORT_MODE_XY_CUT,
```

**Comment by LaverdeS** [comment]
Temporary to use `chipper`: try to sneak in the sort_mode= via our kwargs anti-pattern https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/pdf.py#L378C29-L378C48

**Comment by badGarnet** [comment]
the code here https://github.com/Unstructured-IO/unstructured/blob/4c13d12dc33f6922f78d6bd2114b88816029dbcf/unstructured/partition/common.py#L459 suggests we tolerate coordinates being `None`
So my question is should we keep that expectation and just add checks in places or should we fix this expectation that the attribute shouldn't be `None`?

**Comment by badGarnet** [comment]
ok, so type definition definitely says optional 😬  https://github.com/Unstructured-IO/unstructured/blob/4c13d12dc33f6922f78d6bd2114b88816029dbcf/unstructured/documents/elements.py#L130

**Comment by cragwolfe** [comment]
coordinates could be none, e.g. for elements derived from plain text or html.

**Comment by badGarnet** [comment]
working on a solution but probably this is something needs more thinking than "if no coord then don't sort by xy cut":
- what if awe got some elements have coordinates and some don't
- are there other fallbacks we'd prefer if xy cut is not gonna work because we lack coordinates

**Comment by cragwolfe** [comment]
we should not sort at all if no coordinates.
if some elements have coords and not others -- that probably shouldn't happen in the first place and root issue should be addressed.

**Comment by cragwolfe** [comment]
btw, you can see that when the xycut sort was introduced here: https://github.com/Unstructured-IO/unstructured/pull/1161/files

it only effected images and pdf's in the `test_unstructured_ingest/expected-structured-output .json's`. so i don't think other doc types would make it to the xycut sorting path in the first place.
