### ISSUE TITLE
feat/github token

### ISSUE THREAD

**Issue by TuanaCelik** [Unstructured-IO/unstructured#1240]
The GitHub connector doesn't seem to accept the users GitHub token. And because we spawn a subprocess, even if I add it in my environment variables, it would get ignored. Would be great if unstructured could accept (optionally if possoble) a github token for the connector

**Comment by TuanaCelik** [comment]
For clarity: I often hit rate limiting without providing a token.

**Comment by ryannikolaidis** [comment]
Hey @TuanaCelik,
You should be able to specify a token with the `--git-access-token` flag. We also do this in our [Github ingest test](https://github.com/Unstructured-IO/unstructured/blob/00181b88df06bb133cf50f3a0902b71bdf25ba51/test_unstructured_ingest/test-ingest-github.sh#L13-L22) as we were hitting the same issue you described.
