### ISSUE TITLE
bug/`_partition_pdf_or_image_local` expects a PDF file input

### ISSUE THREAD

**Issue by LaverdeS** [Unstructured-IO/unstructured#1248]
**Describe the bug**
This one is not particulary breaking anything noticeable so far but is confusing method(s) name: `from unstructured.partition.pdf import _partition_pdf_or_image_local` now always expects a pdf so when using it with an image it throws a `PDFSyntaxError: No /Root object! - Is this really a PDF?` from `pdfminer`. I assume that images are taken care of in another method but isn't the name of the function `_partition_pdf_or_image_local` confusing now? In the main library, the method in question is called from paritition_pdf_or_image for instance... maybe the method needs to be renamed and that's all?

**To Reproduce**
```python
from unstructured.partition.pdf import _partition_pdf_or_image_local
model_name="chipper"
elements = _partition_pdf_or_image_local(filename='layout-parser-paper-fast.jpg', model_name=model_name)
```
(Can `model_name="chipper"` here be related to the bug?)

**Screenshots**
<img width="1072" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/38184042/d3c1ec32-d608-413b-829a-7f31f8c12ad2">

**Environment Info**
Run in a colab with unstructured `0.10.9`.

**Comment by badGarnet** [comment]
actually you can pass in image but need to specify `is_image=True` like 

```python
elements = _partition_pdf_or_image_local(filename=f, model_name=model_name, is_image=True)
```

now the question is should the function be automatically determining if an input is image? The name definitely makes is sound like it can...

**Comment by LaverdeS** [comment]
yes, I think that makes sense, checking if is an image is something we could add to the method but still leaving the param `is_image` so we avoid refactoring other calls/test to the method that potentially use it.
(this function is not intended to be used by users and is not breaking anything anyways)

**Comment by orlandounstructured** [comment]
Status update on this being worked in the backlog? 
If not planned to complete, will be marked as complete in 2 weeks

**Comment by MthwRobinson** [comment]
Closing since this is a non-public function.
