### ISSUE TITLE
bug/Not `chipper` output for image input (`chipper` output for JPG/PNG)

### ISSUE THREAD

**Issue by LaverdeS** [Unstructured-IO/unstructured#1256]
**Describe the bug**
When `chipper` is called to partition an image input through our main library, the output does not match to `unstructured-inference` for `chipper`. This means that the output the API/partition.auto gives corresponds to another model (tesseract). I suspected it was related to the use of the param `model_name` but it gives the same erroneous output when using the API (with `'hi_res_model_name'='chipper'`). 

**To Reproduce**
As shown in the screenshot, the code to reproduce the erroneous output is:
```python
from unstructured.partition.auto import partition
from unstructured.partition.utils.constants import SORT_MODE_BASIC
elements = partition(filename="double-column-A.jpg", strategy='hi_res', model_name=model_name, sort_mode=SORT_MODE_BASIC)
```

**Expected behaviour**
For using `chipper` directly through unstructured-inference, I would expect the error reported in bug #1237 (at least for unstructured versions ≥0.10.9).

If the bug is fixed then I would expect this output (considering the mapping of `chipper` elements to Unstructured elements does not change)
```
Header
UncategorizedText
UncategorizedText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
NarrativeText
```
If the call is made from within unstructured-inference, then I would expect the output:
```
Header
Header
Subheadline
Text
Text
Text
Text
Text
Text
Text
Text
Text
Text
Text
Text
Text
Text
Text
Text
```

**Screenshots**
Not-`chipper` output
<img width="753" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/38184042/4c00201d-c664-4df2-a6f0-8c6472683b66">

**Environment Info**
Run in a colab unstructured 0.10.9.

**Additional context**
When partitioning an image with `chipper` through our main library, the snippets fail If tesseract is not installed, which is another indication that `chipper` is not being used.

**Comment by qued** [comment]
After #1426 I've tested using the code you provided and gotten the results that are expected when the bug is fixed. Closing as resolved.
