### ISSUE TITLE
chore/ use word level bounding boxes for `add_pytesseract_bbox_to_elements`

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#1261]
Per discussion here (https://github.com/Unstructured-IO/unstructured/pull/1259/files#r1312235977), `add_pytesseract_bbox_to_elements` can be improved by using `pytesseract.image_to_data` and vector math to find the coordinates of elements.

**Comment by orlandounstructured** [comment]
Scheduled for 2024 Q3
