### ISSUE TITLE
tests: more robust element json serialization/deserialization tests

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#1285]
**Is your feature request related to a problem? Please describe.**
Tests exists to ensure that, in pseudo-code:

    output.json = elements_to_json(partition(raw_doc.<extension>))
    partition(output.json) == partition(raw_doc.<extension>)

However, it is testing individual element objects, which themselves do not compare all metadata fields in the [overloaded \_\_eq__ operator](https://github.com/Unstructured-IO/unstructured/blob/f6a745a/unstructured/documents/elements.py#L417-L423).

**Describe the solution you'd like**

Rather than comparing the element objects, compare the serialized json strings of the LHS and RHS. Pretty much all the tests that need to be updated are in: https://github.com/Unstructured-IO/unstructured/pull/1187

**Comment by scanny** [comment]
Fixed in https://github.com/Unstructured-IO/unstructured/pull/1681

**Comment by scanny** [comment]
Merged on Oct 12, 2023.
