### ISSUE TITLE
feat: support for CompositeElement inverse operations

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#1286]
**Is your feature request related to a problem? Please describe.**

Composite Elements were introduced in https://github.com/Unstructured-IO/unstructured/pull/1222 , the idea being that elements should be combined in an intelligent way before being stored downstream.

While this is important, it is also important to be able to recover the original elements that comprise the CompositeElement.

**Describe the solution you'd like**

Add a metadata field to `CompositeElement` named `orig_elements` that is the base64 encoded string of gzip'ed json representation of the original list of elements.

Of course, tests should be added that show, in pseudo-code:

    elements_to_json(elements) == decompress(
                                    composite_element.metadata.orig_elems)

Do not rely on element object equality but instead json serialization for the reason described in https://github.com/Unstructured-IO/unstructured/issues/1285 .

**Describe alternatives you've considered**

One could just nest the original elements directly, but that gets unwieldy pretty fast.

**Comment by maxburke** [comment]
This would be incredibly useful for my usecase

**Comment by punjabdhaputar** [comment]
+1 this would be fantastic for my usecase as well!

**Comment by scanny** [comment]
This feature was added in v0.13.0 of the library.
