### ISSUE TITLE
feat/nougat: integrate nougat from facebook research

### ISSUE THREAD

**Issue by happysalada** [Unstructured-IO/unstructured#1290]
**Is your feature request related to a problem? Please describe.**
Facebook released some package for improved pdf parsing https://github.com/facebookresearch/nougat

**Describe the solution you'd like**
it would be amazing if this was integrated into unstructured.

**Comment by dsanmart** [comment]
Nougat (Neural Optical Understanding for Academic Documents) is a 350M parameters ViT model that performs an OCR task for processing mathematical formulas of scientific documents into a markup language.

Scientific knowledge is predominantly stored in books and scientific journals, often in the form of PDFs. However, the PDF format leads to a loss of semantic information, particularly for mathematical expressions. This feature enhances accessibility to scientific knowledge in the digital age!

**Comment by ajjimeno** [comment]
We have an model with a similar architecture already integrated in Unstructured, please check Chipper in our documentation. https://github.com/Unstructured-IO/unstructured

**Comment by newelh** [comment]
You can also process documents with nougat and then feed the markdown output into unstructured which accepts markdown files
