### ISSUE TITLE
bug: chunk_by_title() chunks pdf elements incorrectly

### ISSUE THREAD

**Issue by ys-1234** [Unstructured-IO/unstructured#1310]
**Describe the bug**
When using chunk_by_title() function on partitioned pdf elements, the result chunks are smaller then expected. A section's title and content could be separated into different chunks. 

**To Reproduce**
```
elements = partition_pdf(file_path)
chunks = chunk_by_title(elements)
```

**Expected behavior**
A section's title and content should remain in the same chunk after chunk_by_title.

**Screenshots**
PDF section:
![warranty_unstructured_example](https://github.com/Unstructured-IO/unstructured/assets/106637777/df14f554-9a36-413e-8209-713ac3bc80d7)
Chunked result:
![unstructued_output](https://github.com/Unstructured-IO/unstructured/assets/106637777/06247c07-562d-4624-96f5-5a6d53fdf7f4)
Here is the pdf file input used and the full output log:
[XBOX ONE S MANUAL EN FR ES - US CA.pdf](https://github.com/Unstructured-IO/unstructured/files/12541218/XBOX.ONE.S.MANUAL.EN.FR.ES.-.US.CA.pdf)
[XBOX ONE S MANUAL EN FR ES - US CA.txt](https://github.com/Unstructured-IO/unstructured/files/12541222/XBOX.ONE.S.MANUAL.EN.FR.ES.-.US.CA.txt)

**Environment Info**
Output from `python scripts/collect_env.py`
```
OS version:  macOS-10.16-x86_64-i386-64bit
Python version:  3.8.6
unstructured version:  0.10.12
unstructured-inference is not installed
pytesseract is not installed
Torch is not installed
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version: file-5.41
magic file from /usr/share/file/magic
Traceback (most recent call last):
  File "/Users/ys/Downloads/collect_env.py", line 251, in <module>
    main()
  File "/Users/ys/Downloads/collect_env.py", line 243, in main
    libreoffice_version = get_libreoffice_version()
  File "/Users/ys/Downloads/collect_env.py", line 171, in get_libreoffice_version
    result = subprocess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'libreoffice'
```

**Additional context**
N/A

**Comment by ahmetmeleq** [comment]
Seems to be fixed, potentially after [this PR](https://github.com/Unstructured-IO/unstructured/pull/1374). Feel free to reopen if the same problem persists

(left side: @ys-1234 's results, right side: current results)
<img width="1728" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/39141206/4e02259b-d4c5-4add-9729-37854f08e0b5">

Used parameters:
`chunks=chunk_by_title(elements,combine_text_under_n_chars=100,new_after_n_chars=5000,max_characters=5000)`
