### ISSUE TITLE
feat: add data source properties for all connectors

### ISSUE THREAD

**Issue by ryannikolaidis** [Unstructured-IO/unstructured#1316]
**Is your feature request related to a problem? Please describe.**
We have abstractions for data source properties on IngestDocs which map to element metadata in partitioned results. We should realize these properties for all existing connectors so that users can benefit from this data.

**Describe the solution you'd like**
Add data source properties, where appropriate, for all connectors.

**Comment by MthwRobinson** [comment]
@ryannikolaidis - Do you know if `data_source` is added across the board now?

**Comment by ryannikolaidis** [comment]
> @ryannikolaidis - Do you know if `data_source` is added across the board now?

yep!
