### ISSUE TITLE
bug: weaviate and label_studio dependencies conflicts

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#1335]
**Describe the bug**

a couple of pip install's in CI and `make install` invalidate installed requirements installed in `requirements/*.txt`.

By calling `pip install weaviate-client` or `pip install argilla` in CI here:
https://github.com/Unstructured-IO/unstructured/blob/09cc4bf/.github/workflows/ci.yml#L148-L151

or in the Makefile here:
https://github.com/Unstructured-IO/unstructured/blob/main/Makefile#L49

we end up in a situation where the tested or local environments diverge from `requirements/*txt` and issues may be hard to reproduce.

both of these libraries have been updated since these pip installs were introduced, so it would be worth seeing if these extra installs can just be removed. otherwise, there should be ways of testing modified pip-install environments for each case separately, so that tests and install envs may be deterministic.

**Additional context**

**Comment by cragwolfe** [comment]
Addressed in https://github.com/Unstructured-IO/unstructured/pull/1408 , though ideally would avoid a weaviate pin per:

https://github.com/Unstructured-IO/unstructured/pull/1408#issuecomment-1718368331

**Comment by MthwRobinson** [comment]
This seems to be resolved now through some of the more recent dependency refactors.
