### ISSUE TITLE
Cannot use chunking by title? Module not found

### ISSUE THREAD

**Issue by Jimchoo91** [Unstructured-IO/unstructured#1359]
I am trying to test Chunking By Title and I receive this error:

```
from unstructured.chunking.title import chunk_by_title
ModuleNotFoundError: No module named 'unstructured.chunking'
```

Any idea why?

**Comment by cragwolfe** [comment]
This function was recently introduced in version 0.10.9. However, I'd suggest upgrading to latest version:

    pip install --upgrade "unstructured[all-docs]"
