### ISSUE TITLE
chore/ comprehensive review of how to handle metadata merges when chunking

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#1365]
We have a lot of metadata fields floating around now (some have more doc types that others, e.g. "emphasized_text" and "href's"), and chunking elements via `chunking_strategy` or `chunk_by_title` needs to appropriately handle the various metadata fields that are being chunked together.

Context:
https://github.com/Unstructured-IO/unstructured/pull/1304/#issuecomment-1711044387

**Comment by scanny** [comment]
@Coniferish pretty sure this is handled by #1947 which introduced a consolidation strategy for each of the `ElementMetadata` fields. Chunking uses those strategies to determine how to combine metadata fields across elements, including dropping those that cannot meaningfully be combined.

Closing this as resolved, but feel free to reopen if you think we've missed something :)
