### ISSUE TITLE
feat: Cleanup `update_source_metadata`

### ISSUE THREAD

**Issue by rvztz** [Unstructured-IO/unstructured#1378]
The `update_source_metadata` method and the `SourceMetadata` class were first introduced [on this PR](https://github.com/Unstructured-IO/unstructured/pull/1283). This was propagated to the other 5 PRs addressing the definition of data source properties. To ease development and testing, the `update_source_metadata` method was not set as an abstract method on the BaseInterface and a default value was set in it's place. Once the `data-source-properties-*` PRs are merged:

- Set `update_source_metadata` as an `@abstractmethod` on the [BaseIngestDoc](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/ingest/interfaces.py#L74)
- Replace the setting of `self.source_metadata`with an empty `SourceMetadata` with raising a NotImplementedError on that method.

**Comment by MthwRobinson** [comment]
@ryannikolaidis @potter-potter - Do either of you know if this is something we still need?

**Comment by potter-potter** [comment]
@MthwRobinson update_source_metadata is on the BaseIngestDoc. The NotImplementedError we don't really need. So I think we are good.

**Comment by MthwRobinson** [comment]
Thanks @potter-potter !
