### ISSUE TITLE
bug/suppress sphinx warning 

### ISSUE THREAD

**Issue by ron-unstructured** [Unstructured-IO/unstructured#1437]
**Describe the bug**
Sphinx `make html` generates `WARNING: Duplicate explicit target name`.

**To Reproduce**
1. cd `docs` folder and `rm -rf build`
2. `pip install -r requirements.txt` 
4. run `make html`

**Expected behavior**
Follow the sphinx convention to get rid of the warnings. 
Ref: https://github.com/sphinx-doc/sphinx/issues/3921

**Screenshots**
<img width="1028" alt="Screenshot 2023-09-15 at 4 01 25 PM" src="https://github.com/Unstructured-IO/unstructured/assets/138828701/456d2cb4-cfd4-49d4-b86c-49fac74d3a69">

**Environment Info**
sphinx==6.2.1

**Comment by MthwRobinson** [comment]
Closing since we're moving from `sphinx` to https://docs.unstructured.io
