### ISSUE TITLE
Add Python 3.9 and Python 3.10 to the CI test job

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#145]
Currently, we're only testing against `python3.8` in `.github/workflows/ci.yml`. The goal of this issue is to add `python3.9` and `python3.10` to make sure that we're compatible with later versions of Python.

**Comment by sparkbrains** [comment]
@cragwolfe 
I made the changes in ci.yml file. But I am unable to push the code. I am getting this error:
![Screenshot from 2023-02-10 10-56-02](https://user-images.githubusercontent.com/73577645/218008557-5326b489-839f-4260-b216-215f3fa4c10c.png)

Also I made a small change in html.py and pushed that code for the purpose of testing and it was successfully pushed.
