### ISSUE TITLE
feat/Automatic Corresponding Dependency Update for 'unstructured-inference' When Upgrading 'unstructured

### ISSUE THREAD

**Issue by dsanmart** [Unstructured-IO/unstructured#1458]
Upgrading the version of `unstructured` using `pip` doesn't upgrade `unstructured-inference` to the latest corresponding version. This may lead to bugs when trying out new features, as demonstrated in #1401 

**Solution**
Upgrading the version of `unstructured` also upgrades the version of `unstructured-inference` without any additional steps required. This ensures that both packages remain compatible and up-to-date, reducing the likelihood of encountering bugs when trying out new features, as seen in issue #1401.

**Comment by MthwRobinson** [comment]
Closing since we've refactored dependencies heavily since this issue opened. Please reopen if this or a similar issue resurfaces.
