### ISSUE TITLE
docx: include embedded images as Image elements

### ISSUE THREAD

**Issue by scanny** [Unstructured-IO/unstructured#1463]
An author can embed one or more images in a Word document.

Extract those during partitioning and include them in the element stream as an `Image` element if the partition strategy is "hi_res".

**Comment by MthwRobinson** [comment]
@scanny - Have you done this for Word docs already or is that still in progress?

**Comment by scanny** [comment]
@MthwRobinson still WIP.

**Comment by scanny** [comment]
Added in the API a couple months back.
