### ISSUE TITLE
feat/audio input

### ISSUE THREAD

**Issue by kulbinderdio** [Unstructured-IO/unstructured#1467]
**Is your feature request related to a problem? Please describe.**
Is there a way to load audio files directly into Unstructured?

**Describe the solution you'd like**
There are lots of documents in organisations that non text based and it would be useful to be able to break these down and search these (i.e. Audio Vectors)

**Describe alternatives you've considered**
I don't really want to transcribe the audio first if I can get away with it

**Additional context**

**Comment by MthwRobinson** [comment]
Closing this issue. We're not going to support audio in the OSS lib, but do plan to add support for audio files to our API.
