### ISSUE TITLE
bug/Tables are not being parsed from markdown files

### ISSUE THREAD

**Issue by phowat** [Unstructured-IO/unstructured#1486]
**Describe the bug**
Tables are being returned as UncategorizedText . 

**To Reproduce**

Example Markdown file:
```

# A table

Item | Price | # In stock
---|---|---
Juicy Apples | 1.99 | 739
Bananas | 1.89 | 6

```

**Expected behavior**
It should return a  Table element.

**Additional context**
The reason for this is because for python-markdown to support tables, it needs to have an extension enabled: https://python-markdown.github.io/extensions/tables/

Changing this:
`html = markdown.markdown(text)`
to this:
`html = markdown.markdown(text, extensions=['tables'])`
in partition_md, fixes the issue.

I can submit a pull request if that's an acceptable solution.

**Comment by qued** [comment]
Hi @phowat , I've verified the solution you propose works. If you're willing to put together a pull request, please do!

**Comment by cragwolfe** [comment]
CC @amanda103
