### ISSUE TITLE
bug/partition_json can't parse json file as one dictionary

### ISSUE THREAD

**Issue by yuming-long** [Unstructured-IO/unstructured#1498]
**Describe the bug**
a user saw error while partition this json subject:
```
{
    "id": 1234,
    "description": "this is a test"
}
```
error:
```
Traceback (most recent call last):
  File "/Users/yumingl/develops/unstructured/test.py", line 7, in <module>
    elements = partition(filename="test.json")
  File "/Users/yumingl/develops/unstructured/unstructured/partition/auto.py", line 371, in partition
    raise ValueError(
ValueError: Detected a JSON file that does not conform to the Unstructured schema. partition_json currently only processes serialized Unstructured output.
```

**To Reproduce**
save subject above as file `test.json` and run with `elements = partition(filename="test.json")`

**Expected behavior**
should get return elements output from the dict

**Additional context**
The bug here is we only accept [list of dict pattern]( https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/file_utils/filetype.py#L468) for json files, and we should expand it to accept json file with only one dictionary or more potential pattern of json file

**Comment by MthwRobinson** [comment]
Closing this in favor of #1038
