### ISSUE TITLE
feat/allow `partition_email` to extract texts without specifying `content_source` parameter

### ISSUE THREAD

**Issue by yuming-long** [Unstructured-IO/unstructured#1504]
**Is your feature request related to a problem? Please describe.**
`partition_email` use default `content_source=text/html`, and won't extract texts from the email if the content type of the body is `text/plain`.

for example, to partition [this email file](https://github.com/FlexConfirmMail/Thunderbird/blob/master/sample.eml) with plain texts body:  
`elements=partiton(filename=...)` will return `[]` result.
To get the texts output we need to run it with `elements=partiton(filename=..., content_source="text/plain")` since thats the correct content type.

**Describe the solution you'd like**
For better user experience, we want `partition` to auto detect the content type for the body of the email (html/plain text), and get 
the texts output without specifying the parameter.
For example, user can run `elements=partiton(filename=..)` with the example file above and still got texts output.

**Comment by MthwRobinson** [comment]
#2521 fixed this while addressing another problem.
