### ISSUE TITLE
feat/donut: consider using donut for document parsing

### ISSUE THREAD

**Issue by happysalada** [Unstructured-IO/unstructured#1512]
**Is your feature request related to a problem? Please describe.**
Currently table parsing and various image parsing in pdf can be a bit broken.

**Describe the solution you'd like**
Could donut be used to improve accuracy https://github.com/clovaai/donut

**Describe alternatives you've considered**
doing nothing

**Comment by MthwRobinson** [comment]
Closing since we don't intend to change the models available in the OSS package.
