### ISSUE TITLE
bug/DeltaTable ingest test

### ISSUE THREAD

**Issue by ryannikolaidis** [Unstructured-IO/unstructured#1537]
**Describe the bug**
The ingest test for the DeltaTable connector is failing intermittently. [Here](https://github.com/Unstructured-IO/unstructured/actions/runs/6316650106/job/17151970479) is an example failure.

**To Reproduce**
Run CI a couple of times until you encounter the failure (it's pretty frequent)

**Expected behavior**
The test should succeed.

**Environment Info**
CI

**Comment by ryannikolaidis** [comment]
likely a memory issue, hopefully resolved by: https://github.com/Unstructured-IO/unstructured/pull/1500

**Comment by MthwRobinson** [comment]
Closing since @ryannikolaidis mentioned it was resolved by #1500. Can reopen if we notice it again.
