### ISSUE TITLE
bug/'isalnum' referenced before assignment

### ISSUE THREAD

**Issue by nikunjgoel95** [Unstructured-IO/unstructured#1584]
**Describe the bug**
if char.isalnum() != isalnum:
UnboundLocalError: local variable 'isalnum' referenced before assignment

**To Reproduce**
Provide a code snippet that reproduces the issue.

from langchain.document_loaders import UnstructuredPDFLoader 

loader = UnstructuredPDFLoader(file_path, mode = "elements", strategy = "hi_res", pdf_infer_table_structure = True, hi_res_model_name = "chipper")

elements = loader.load()

**Expected behavior**
Expected for the contents of the PDF to load.

**Screenshots**
![image](https://github.com/Unstructured-IO/unstructured/assets/12533192/b09f843c-fe7e-4b90-ab8f-72d05216d22c)

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

**Additional context**

**Comment by Klaijan** [comment]
Hi @nikunjgoel95! if possible, would you mind sharing the document you were working on?

**Comment by arash-hajikhani** [comment]
I experienced the same issue and reported it here: https://github.com/langchain-ai/langchain/discussions/11247
It worked yesterday with my PDF sets and this has become an issue just in the previous hours.

**Comment by Acbet** [comment]
Yes, I just experienced the same issue. It worked a few days ago, and now it doesn't (no changes' made)

**Comment by rondinini** [comment]
Having the exact same issue

**Comment by xdurfina** [comment]
@Klaijan Hi, it is failing on this [pdf](https://documentation.nokia.com/sr/23-7-2/pdf/Interface_Configuration_Guide_23.7.R1.pdf). Hope it helps.

**Comment by pchalasani** [comment]
here's an error trace -- https://gist.github.com/pchalasani/802c91e897b6433551106ec51942a626

**Comment by paluskapter** [comment]
I have the same problem as well.

**Comment by awalker4** [comment]
FYI fix is almost in over here: https://github.com/Unstructured-IO/unstructured/pull/1586

**Comment by Klaijan** [comment]
Fix is merging real soon https://github.com/Unstructured-IO/unstructured/pull/1586/! Thank you all for reporting the issue!

**Comment by rondinini** [comment]
@Klaijan Thank you so much for your help!

**Comment by Klaijan** [comment]
It is merged now!

**Comment by asharda** [comment]
Upgraded to  0.0.312 but still getting the error "An error occurred: cannot access local variable 'isalnum' where it is not associated with a value" when i try to load a pdf using DirectoryLoader

**Comment by asharda** [comment]
Upgraded to langchain 0.0.312 but still getting error "An error occurred: cannot access local variable 'isalnum' where it is not associated with a value" when i try to load a pdf using UnstructuredPDFLoader

**Comment by awalker4** [comment]
Hi @asharda , can you make sure unstructured gets updated as well? `pip freeze` should show version 0.10.21. I'm not sure if langchain will pull in the latest automatically.
