### ISSUE TITLE
bug/error with 'fake' file and assigned name in partition_pdf function

### ISSUE THREAD

**Issue by Guiforge** [Unstructured-IO/unstructured#1644]
**Describe the bug**
When we use not real io file with name attribute partition_pdf failed with `no such file or directory`.
This can happen, for example, when you extract files from a zip file with ZipFile and [open](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.open)

**To Reproduce**
```python
import io

# Create a 'fake' file
file = io.BytesIO()
file.name = 'tmp.pdf'

# Call the partition_pdf function
result = partition_pdf(file=file)
```

**Expected behavior**
Same experience than spooltempfile with no attribute name

**Screenshots**
...

**Environment Info**
...

**Additional context**
- This issue occurs when using a file object with an assigned name.
- The bug can be reproduced when extracting a file from a ZIP archive, where the file has a name but does not exist in the filesystem.

**Comment by KristianMischke** [comment]
I think this is the same issue as https://github.com/Unstructured-IO/unstructured-inference/issues/303. Unless you have other evidence, this is a windows-only issue

The inference library has a `process_data_with_model` which creates a temp file and calls `process_file_with_model`

Similarly `process_data_with_ocr` creates a temp file and calls `process_file_with_ocr`

as in https://github.com/Unstructured-IO/unstructured-inference/pull/323, Python 3.12 seemingly has a one-liner solution
