### ISSUE TITLE
bug/Vertical text in pdf inverted

### ISSUE THREAD

**Issue by CorentinvdBdO** [Unstructured-IO/unstructured#1648]
**Describe the bug**
In a pdf, a line of vertical text is oriented text bottom facing page right. When doing "partition(filename)", the text is inverted and has random spaces added ("é fi i t r e c" instead of "certifié").
The rest of the text in the same page is properly treated.
This is not an OCR.

**To Reproduce**
Use a pdf with vertical text.

**Expected behavior**
Proper order conserved and no random spaces added. 
Pdfium or pypdf do it properly.

**Screenshots**
non applicable

**Environment Info**
non applicable.

**Additional context**
non applicable

**Comment by MthwRobinson** [comment]
Hi @CorentinvdBdO - if this is still an issue, could you provide an example document we could use to reproduce?

**Comment by Susensio** [comment]
Hello @MthwRobinson , sorry for bumping and old issue but I'm having the same problem, and I can provide an example document:
https://ddd.uab.cat/record/118259?ln=es
[trecom_a2006m12n21p7.pdf](https://github.com/user-attachments/files/16267158/trecom_a2006m12n21p7.pdf)
