### ISSUE TITLE
ImportError: cannot import name 'PDFResourceManager' from 'pdfminer.converter'

### ISSUE THREAD

**Issue by YaqiChen** [Unstructured-IO/unstructured#1649]
In unstructured/partition/pdf.py line 12:
    from pdfminer.converter import PDFPageAggregator, PDFResourceManager
There is no PDFResourceManager from pdfminer.converter

**Comment by Klaijan** [comment]
May I ask what python version and pdfminer.six you are on?

**Comment by andrecanteras** [comment]
you need to install 'pdfminer.six' and not only 'pdfminer'

**Comment by EliteLeadsAI** [comment]
i get the same error...
ImportError: cannot import name 'PDFResourceManager' from 'pdfminer.converter'

"""Requirement already satisfied: pdfminer.six in /Users/louiskanaj/anaconda3/lib/python3.11/site-packages (20191110)
Requirement already satisfied: pycryptodome in /Users/louiskanaj/anaconda3/lib/python3.11/site-packages (from pdfminer.six) (3.19.0)
Requirement already satisfied: six in /Users/louiskanaj/anaconda3/lib/python3.11/site-packages (from pdfminer.six) (1.12.0)
Requirement already satisfied: sortedcontainers in /Users/louiskanaj/anaconda3/lib/python3.11/site-packages (from pdfminer.six) (2.4.0)
Requirement already satisfied: chardet in /Users/louiskanaj/anaconda3/lib/python3.11/site-packages (from pdfminer.six) (3.0.4)
DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages."""

**Comment by chudichudichudi** [comment]
this commit seems to intruduced the bug https://github.com/Unstructured-IO/unstructured/commit/d26d591d6ab6cde8e067189e99a41ef7c22d1a46#diff-cefa2d296ae7ffcf5c28b5734d5c7d506fbdb225c05a0bc27c6b755d5424ffda

**Comment by giulioco** [comment]
Also getting this error and I have both 

pdfminer-six = "*"
pdfminer = "*"

installed. Python 3.10

**Comment by Coniferish** [comment]
I'm having trouble reproducing this error. Can someone please provide an example?

The following is working just fine for me:
```
>>> from langchain.document_loaders import UnstructuredPDFLoader
>>> loader = UnstructuredPDFLoader("example-docs/layout-parser-paper.pdf", mode='elements', strategy='fast')
>>> docs = loader.load()
```

That said, I am able to confirm that `PDFResourceManager` should be installed from `.pdfinterp` instead of `.converter`
https://github.com/euske/pdfminer/blob/423f851fc20ebd701bc4c8b5b7ba0e7904e18e3b/pdfminer/pdfinterp.py#L133

**Comment by giulioco** [comment]
when I run the same thing I get 

```
>>> from langchain.document_loaders import UnstructuredPDFLoade
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'UnstructuredPDFLoade' from 'langchain.document_loaders' (/Users/{username}/.local/share/virtualenvs/llava-rag-lBEJSBrY/lib/python3.10/site-packages/langchain/document_loaders/__init__.py)
```

I'm using Python 3.10 and pipenv, though I tried Python 3.9 and still getting the same issue

**Comment by Coniferish** [comment]
Update:
@qued seems to have pinpointed the issue with pdfminer.six and created a PR to close this here: https://github.com/Unstructured-IO/unstructured/pull/1797

**Comment by CowCat2016** [comment]
my python version is 3.10.4, i installed both pdfminer and pdfminer.six,still cannot solve the error
![image](https://github.com/Unstructured-IO/unstructured/assets/47969832/35fe286a-9e23-470d-9224-1a9c6b3e785d)
