### ISSUE TITLE
feat: support changelog-individual-file entries for -dev version changes

### ISSUE THREAD

**Issue by ryannikolaidis** [Unstructured-IO/unstructured#1659]
**Is your feature request related to a problem? Please describe.**
Now that we have [added merge queues](https://github.com/Unstructured-IO/unstructured/pull/1654), the CHANGELOG will be automerged as PRs move through the queue. This will likely lead to conflicts. 

**Describe the solution you'd like**
We should to move to a different scheme where CHANGELOG items accumulate as individual files in a directory rather than in a single file. A supporting release script should be written to accumulate all the -dev changelog-individual-file entries into the main CHANGELOG. This also implies updating our [changelog validation in CI](https://github.com/Unstructured-IO/unstructured/blob/main/.github/workflows/ci.yml#L381-L395) (which will now require some custom script to validate a new file was added rather than entry in CHANGELOG.md)

**Describe alternatives you've considered**
We could potentially have a single -dev changelog file with only changes since the last release. This is probably quite a bit less prone to conflicts than current flow and means you can see all latest changes in a single place.

**Additional context**

**Comment by MthwRobinson** [comment]
@ryannikolaidis @ahmetmeleq - Was this implemented in #300?

**Comment by ryannikolaidis** [comment]
> @ryannikolaidis @ahmetmeleq - Was this implemented in #300?

No, this would involve a change to how we currently add per-commit (to main) entries in the changelog. Instead this suggests we have individual changelog files per commit that all get rolled up on release. Advantage here would be that we wouldn't ever hit collisions in the merge queue solely because of changelog conflicts (which will occur on most commits)

**Comment by MthwRobinson** [comment]
Got it makes sense, we'll keep this open. @ahmetmeleq left a similar comment on one of the PRs yesterday. This looks like a good one to implement and we'll keep it open.

**Comment by ahmetmeleq** [comment]
@MthwRobinson @ryannikolaidis , it's [this](https://github.com/Unstructured-IO/unstructured/pull/2868#issuecomment-2115629385) one - I'll take another cycle at it when I got time 💪

**Comment by ryannikolaidis** [comment]
thanks! yea, I suspect this is far lower priority these days, but does make for less changelog management in the long run.

**Comment by scanny** [comment]
Closing as inactive. If someone is committed to making this happen we can reopen.

From my perspective, I'm not seeing a lot of merge failures due to version conflicts, possibly because merge frequency is low and fewer folks are contributing.
