### ISSUE TITLE
bug/zero-division-error-pdf

### ISSUE THREAD

**Issue by cdpierse** [Unstructured-IO/unstructured#1663]
**Describe the bug**
When trying to partition the pdf at the link below we run into a zero division error. https://www.ibm.com/docs/en/SSHT6S_8.2.0/com.ibm.izsam.doc/doc/pdf/IZSAM8.2_221012.pdf 
**To Reproduce**
Provide a code snippet that reproduces the issue.
```python
from unstructured.partition.auto import partition

elements = partition(
    filename="./IZSAM8.2_221012.pdf",
    strategy="fast",
)
```

**Comment by Winvoker** [comment]
I have the same problem with my pdf file.
