### ISSUE TITLE
bug/chore: fix import of `openpyxl` in metadata.py

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#1670]
`openpyxl` is imported at the top of metadata.py even though it is only used for excel documents. So if metadata.py is imported by any partitioner, `openpyxl` becomes a dependency, which should not be the case. Two possible solutions to fix this:

- Move the openpyxl import to occur inside the functions that need it, and add a requires_dependency decorator
- Move the excel related functions to their own module (maybe unstructured.file_utils.excel_metadata), put the import there, remove the import from metadata.py, and then chase down and replace the references to those functions where they occur.

**Comment by MthwRobinson** [comment]
This is fixed now
