### ISSUE TITLE
docs: update supported file types table in partition documenation

### ISSUE THREAD

**Issue by ryannikolaidis** [Unstructured-IO/unstructured#1691]
**Is your feature request related to a problem? Please describe.**
The [docs for partitioning](https://unstructured-io.github.io/unstructured/bricks/partition.html#partitioning) include a table of supported file types. It looks like these are missing a number of extensions -> file types that we map against in auto partitioning, looking [here](https://github.com/Unstructured-IO/unstructured/blob/f98d5e65ca34216e81be9954e7c6429f300e86ad/unstructured/file_utils/filetype.py#L154-L200).

**Describe the solution you'd like**
Documentation has a comprehensive list of file types supported.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by cragwolfe** [comment]
CC @amanda103
