### ISSUE TITLE
feat: per-process sessions for remaining connections - feasibility

### ISSUE THREAD

**Issue by potter-potter** [Unstructured-IO/unstructured#1697]
Currently on ingest, connections to data sources are happening once per document (per IngestDoc).

Per-process ingest for google-drive has been created:
https://github.com/Unstructured-IO/unstructured/pull/1058

This will explore the feasibility of adding that process to the other ingest connectors.

**Comment by MthwRobinson** [comment]
@potter-potter - Is this still something we'd like to do?

**Comment by potter-potter** [comment]
@MthwRobinson - Thanks for the question. This is no longer needed. The connection process is being updated with V2.
