### ISSUE TITLE
bug/ingest language should not default to 'eng' but None

### ISSUE THREAD

**Issue by rbiseck3** [Unstructured-IO/unstructured#1715]
**Describe the bug**
By defaulting to `eng`, this actually injects information that might not be accurate and breaks the language detection library being used. This should instead default to `None` and let the library do what it needs to to detect the language. 

**To Reproduce**
Running local connector on the `example-docs/language-docs/UDHR_first_article_all.txt` file produces only english languages.

**Expected behavior**
Running local connector on the `example-docs/language-docs/UDHR_first_article_all.txt` should result in `['ind', 'est']`

**Comment by Coniferish** [comment]
*Commenting to track this
