### ISSUE TITLE
bug/wrong import

### ISSUE THREAD

**Issue by kavya98** [Unstructured-IO/unstructured#1763]
**Describe the bug**
When using Unstructured with Langchain, the following is giving an import error:

**To Reproduce**
`loader = UnstructuredPDFLoader('pdf_path', mode='elements', strategy='fast')`

**Expected behavior**
No error

**Additional context**
This is because of this line of code -> [line which causes error](https://github.com/Unstructured-IO/unstructured/blob/282b8f700d9471b9430e8a37af73ca96b980e0f0/unstructured/partition/pdf.py#L12C1-L12C1)

**PDFResourceManager is not present in _pdfminer.converter_, but present in _pdfminer.pdfinterp_**, so the code should be changed to:
`from pdfminer.pdfinterp import PDFResourceManager`

**Comment by Coniferish** [comment]
Hi @kavya98! Can you provide the document that's raising this error? I'm having trouble reproducing it.
