### ISSUE TITLE
File detection doesn't work properly when using `partition` in hot reload mode in `ipython`

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#178]
Currently if you are using the `partition` brick in hot reload mode in `ipython`, an error related to file detection occur is you make a change to `partition.py`. 

### Steps to reproduce

```python
from unstructured.partition.auto import partition

elements = partition("example-docs/layout-parser-paper.pdf")
```

Make a change to `partition.py` and run the same code again. You'll get:

```python
ValueError: Invalid file /Users/mrobinson/data/sitreps/downsampled-data/docx/01_SOCN_DOWNREP_06-01.docx. File type not support in partition.
```

But if you run:

```python
from unstructured.file_utils.filetype import detect_filetype

partition("example-docs/layout-parser-paper.pdf")
```

You'll see that the filetype is correct. This may be related to how `Enum`s are handled during hot reloading. The workaround is to exit iPython and restart.

**Comment by sparkbrains** [comment]
Hello @cragwolfe ,
I tried reproducing the error on my local but it is working fine. Also the file mentioned partition.py is in nlp directory and not the partition directory. So is the file name correct?

**Comment by cragwolfe** [comment]
@sparkbrains , i think the issue is that it does work fine in plain old python, however when using "hot reload mode in ipython" there will be an error after `partition.py` is edited.

**Comment by MthwRobinson** [comment]
Yeah it's for the hot reload mode in iPython. Try running this in your iPython session and editing the file.

```python
%load_ext autoreload
%autoreload 2
```

**Comment by sparkbrains** [comment]
@cragwolfe 

https://www.loom.com/share/d01ac7bc70ac4bf8b2c0d9264e24a84f
This is the video for the steps I am following to reproduce the error for issue 178. Please check this and correct me if somewhere I am not following the steps properly.
