### ISSUE TITLE
bug/bad ordering on page numbers

### ISSUE THREAD

**Issue by benjats07** [Unstructured-IO/unstructured#1804]
**Describe the bug**
Some of the page numbers extracted from PDFs are misplaced in JSON outputs, frequently putting together two-page numbers that should be separated by content.

**To Reproduce**
Check ingest test outputs, in particular, structured-output>s3>small.pdf-set

**Expected behavior**
The page numbers should appear in reading order.

**Examples**

Silent-Giant-(1).pdf.json:
[Number 2](https://github.com/Unstructured-IO/unstructured/blob/00635744ed9d2b5a949baac403bbdda9419da644/test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json#L306C1-L306C1) 
[Number 4](https://github.com/Unstructured-IO/unstructured/blob/00635744ed9d2b5a949baac403bbdda9419da644/test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json#L792)
[Number 6](https://github.com/Unstructured-IO/unstructured/blob/00635744ed9d2b5a949baac403bbdda9419da644/test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json#L1062)
[Number 8](https://github.com/Unstructured-IO/unstructured/blob/00635744ed9d2b5a949baac403bbdda9419da644/test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/Silent-Giant-(1).pdf.json#L1602C9-L1602C9)

recalibrating-risk-report:
[Number 2](https://github.com/Unstructured-IO/unstructured/blob/00635744ed9d2b5a949baac403bbdda9419da644/test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json#L234)
[Number 4](https://github.com/Unstructured-IO/unstructured/blob/00635744ed9d2b5a949baac403bbdda9419da644/test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json#L1080)
[Number 6](https://github.com/Unstructured-IO/unstructured/blob/00635744ed9d2b5a949baac403bbdda9419da644/test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json#L1368)
[Number 8](https://github.com/Unstructured-IO/unstructured/blob/00635744ed9d2b5a949baac403bbdda9419da644/test_unstructured_ingest/expected-structured-output/s3/small-pdf-set/recalibrating-risk-report.pdf.json#L1530)

**Environment Info**

OS version:  macOS-14.0-arm64-arm-64bit
Python version:  3.8.17
unstructured version:  0.10.24
unstructured-inference version:  0.7.10.dev1
pytesseract version:  0.3.10
Torch version:  2.1.0
Detectron2 is not installed

**Comment by scanny** [comment]
Closing as inactive. If the problem persists and you can point to a particular problematic output element we can reopen.
