### ISSUE TITLE
bug/unstructured-inference bug: TypeError: UnstructuredYoloXModel.initialize() got an unexpected keyword argument 'extract_images_in_pdf'

### ISSUE THREAD

**Issue by 2710932616** [Unstructured-IO/unstructured#1834]
**Describe the bug**
Hello, I find a bug it's about Excess transfer parameters are not processed in initialize method.
The error msg is "TypeError: UnstructuredYoloXModel.initialize() got an unexpected keyword argument 'extract_images_in_pdf'"
I have submitted a issue and solution in unstructured-inference.

**Detailed**
Detailed information is here:Unstructured-IO/unstructured-inference#265

**Analysis**
The reason is the parameter `process_with_model_kwargs` (a dict has `extract_images_in_pdf` and `image_output_dir_path`) is passed in when calling the `process_file_with_model` method in `unstructured.partition.pdf`
https://github.com/Unstructured-IO/unstructured/blob/82c8adba3fed9c6fbe4743662f5888969c56944a/unstructured/partition/pdf.py#L375-L383
and the parameter  `process_with_model_kwargs (as **kwargs)` is passed in `get_model` method.

https://github.com/Unstructured-IO/unstructured-inference/blob/326f1809e33b05b0b2fb94b507200c3296a753c0/unstructured_inference/inference/layout.py#L492

then every `initialize_params` using **kwargs and it passed in each model.initialize method.
https://github.com/Unstructured-IO/unstructured-inference/blob/326f1809e33b05b0b2fb94b507200c3296a753c0/unstructured_inference/models/base.py#L72

**Comment by qued** [comment]
Resolved by #1810, but you will need to update to `unstructured-inference` 0.7.10.
