### ISSUE TITLE
Documentation Embedding issue, merge syntax leftover

### ISSUE THREAD

**Issue by gregtap** [Unstructured-IO/unstructured#1837]
**Describe the bug**

Embedding documentation page is showing `<<<<<<< HEAD`

**To Reproduce**
 
 Navigate to https://unstructured-io.github.io/unstructured/bricks/embedding.html

**Expected behavior**

No `<<<<<<< HEAD`

**Screenshots**

 
![image](https://github.com/Unstructured-IO/unstructured/assets/26057/9ee2c836-bf96-4160-9092-137851e9d0df)

**Environment Info**

N/A

**Additional context**
N/A

**Comment by MthwRobinson** [comment]
Closing, we're planning to remove the olds docs page in favor of https://docs.unstructured.io. Thanks for reporting!
