### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 42: invalid continuation bytebug/<short-name>

### ISSUE THREAD

**Issue by herofolk** [Unstructured-IO/unstructured#1838]
**Describe the bug**
I got a mistake when I load .doc file.
**To Reproduce**
Provide a code snippet that reproduces the issue.

**Expected behavior**

**Screenshots**
![image](https://github.com/Unstructured-IO/unstructured/assets/15681326/09088983-69ab-4b23-9f07-25904d589fff)

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.
python:3.9.18
unstructured:0.10.23
**Additional context**
"logger.info(output.decode().strip()) " in common.py
This code should be delete when convert .doc file to .docx , it is done converted to docx but this code may raise a mistake when output is not encode by 'utf8'.

**Comment by MthwRobinson** [comment]
@herofolk - If you're still having this issue, could you provide a doc that we could use to try and reproduce?

**Comment by danielbichuetti** [comment]
Here is another file that despise setting encoding correctly in partition, the processing doesn't work.

[samples.zip](https://github.com/user-attachments/files/17953604/procuracao-para-representacao-junto-a-companhia-de-abastecimento-de-agua-para-autorizacao-de-abertura-e-fechamento.doc.zip)
