### ISSUE TITLE
table structure issue - table element id and parent id not matching

### ISSUE THREAD

**Issue by samipshah100** [Unstructured-IO/unstructured#1887]
**Describe the bug**
table element id and parent id not matching. my use case is to get insights from a table. 

**To Reproduce**
used hi_res api
**Expected behavior**
table child element id shuold match its parentes element id

**Screenshots**
Element Id and parent ID matched incorrectly using Hi_res verison of unstructured. 

Hence there is no way for us to coreleate the table title and description, 
![image](https://github.com/Unstructured-IO/unstructured/assets/51622592/b50ab46e-9eef-4799-9ee4-cb35956c4b6b)

**Environment Info**
using unstrucured api with api key

**Additional context**

**Comment by scanny** [comment]
@samipshah100 the content in the slide you reference has a "tabular" layout, but it is not a PowerPoint table. Even if it was, there is no automatic hierarchical relationship assumed between a "column heading" and the text in the remaining cells of the column.

In the current implementation, all text in a table is partitioned into a single `Table` element. That element has a `table.metadata.text_as_html` attribute that preserves the row/column structure of the table text for uniform tables (tables without merged cells). That won't help in this case but might be something to know about for other cases.

I think what you'll find on this slide is that there are nine separate shapes, just manually aligned to a tabular appearance.

I'm going to close this as not-a-bug, but if you have any other questions or think I've missed something feel free to reopen or post additional comments.
