### ISSUE TITLE
feat/Hand-written OCR

### ISSUE THREAD

**Issue by l4b4r4b4b4** [Unstructured-IO/unstructured#1926]
Would be great to have OCR pipeline for hand-written text.

**Describe the solution you'd like**
1. Generate Bounding boxes for handwritten text on Document / Image.
2. Do OCR with an appropriate Solution.

**Additional context**
[OCR: Handwriting recognition with OpenCV, Keras, and TensorFlow](https://pyimagesearch.com/2020/08/24/ocr-handwriting-recognition-with-opencv-keras-and-tensorflow/)

**Comment by MthwRobinson** [comment]
Thanks @l4b4r4b4b4 . Closing this one, we're not going to support hand written text in the open source library. We may add that to our API in the future though.
