### ISSUE TITLE
OCR issue for pdf documents

### ISSUE THREAD

**Issue by khadkechetan** [Unstructured-IO/unstructured#1933]
**Describe the bug**
While doing the experiment I see multiple issue with ocr text out of pdf

Can we plug in Azure OCR to get the final output better?

**Comment by ahmetmeleq** [comment]
Hello @khadkechetan 👋 

Can you fill either of the two templates below and create a new issue?

a. If you see bad behavior in the library, please fill this ⬇️  so we can understand what's happening:
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Provide a code snippet that reproduces the issue.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

**Additional context**
Add any other context about the problem here.

```

b. If you just like to see `Azure OCR` in `unstructured` regardless of the current behavior, please fill this ⬇️  so we can understand in which cases this new feature can help you:
```
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

```

Looking forward to the new issue and others!

**Comment by lfglopes** [comment]
You can plug in Google Vision.

https://docs.unstructured.io/open-source/how-to/set-ocr-agent

Or write an agent for Azure https://github.com/Unstructured-IO/unstructured/blob/4e61acc1c6b924a4ff643a1cc145a3f59980d18c/unstructured/partition/utils/ocr_models/google_vision_ocr.py#L19
