### ISSUE TITLE
Invalid dictionary construct

### ISSUE THREAD

**Issue by drewB** [Unstructured-IO/unstructured#1984]
When I run a pdf through a locally hosted api I receive the following error:

```
Invalid dictionary construct: [/'Color', [20224, 32768, 32768], /'Dimmed', False, /'Editable', True, /'Preview', /b'tru', /b'e', /'Printed', True, /'Title', b'Layer 1', /'Visible', True]"}
```

I can't seem to find that error anywhere in the code base so don't even know where to get started on how to address.  Can anyone tell me what this means and how to address?

**Comment by scanny** [comment]
@drewB this appears to be a known (for three years now) problem with `pdfminer` for certain documents like yours that have invalid content but I expect still render using a reader application.

How frequently are you encountering this and do you know the provenance of the affected documents (like published via Word SaveAs PDF, etc.)?

**Comment by drewB** [comment]
Thanks for your reply and pointing to the pdfminer issue.  I was trying to fix an issue that I was running into with a different pdf lib  so only tried a couple pdfs.  As a result, can't really speak to the provenance.   This pdf was a book proof from the author but don't know how it was created.  I ended up switching to adobe's pdf extract api and that provided the solution I was looking for which was a more structured pdf output so I could exclude repeated things like page headers.  It also had no trouble with the pdf.

**Comment by drewB** [comment]
Researching a little more I did find this https://github.com/paperless-ngx/paperless-ngx/issues/900#issuecomment-1199358633.  I haven't tried the suggestion but might help others who run into this problem.

**Comment by scanny** [comment]
Thanks @drewB, that's good insight :)

I'm going to close this for now but feel free to reopen if you think there's something we can do :)

**Comment by demattosanthony** [comment]
I had the same issue and was able to resolve it using ghostscript to repair the pdf

```
gs -o output.pdf -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress input.pdf
```
