### ISSUE TITLE
XLSX Chunk by TItle HTML not working properly

### ISSUE THREAD

**Issue by TaylorN15** [Unstructured-IO/unstructured#1985]
I have noticed that the 'text_as_html' attribute in the chunk metadata contains the HTML for the entire sheet, as opposed to just the chunk (example code below). I am iterating the chunks and using the HTML if the category is Table. So the value in 'chunk.text' is correct, but chunk.metadata.text_as_html contains the same value as "elements". This seems to be caused by the below line of code, as the attribute is not located in the area it's looking.

```
from io import BytesIO
from unstructured.partition.xlsx import partition_xlsx
from unstructured.chunking.title import chunk_by_title

filepath = 'C:\\Path\\To\\file.xlsx'

with open(filepath, "rb") as fh:
    bytes_io = BytesIO(fh.read())

elements = partition_xlsx(file=bytes_io)

chunks = chunk_by_title(elements, multipage_sections=True)

for i, chunk in enumerate(chunks):
    if chunk.metadata.page_number is None:
        page_list = [1]
    else:
        page_list = [chunk.metadata.page_number]
    # substitute html if text is a table
    if chunk.category == 'Table':
        chunk_text = chunk.metadata.text_as_html
    else:
        chunk_text = chunk.text
```

https://github.com/Unstructured-IO/unstructured/blob/2f553333bd6fe7462b7f52a04f1c9f7fdf619e90/unstructured/chunking/title.py#L33

**Comment by scanny** [comment]
Ah, good catch @TaylorN15, just so. I'll get to work on that, shouldn't take me long :)
