### ISSUE TITLE
bug: pass partition arguments to api when partitioning with unstructured-ingest and --partition-by-api

### ISSUE THREAD

**Issue by ryannikolaidis** [Unstructured-IO/unstructured#2021]
**Describe the bug**
Currently when using the --partition-by-api flag via unstructured-ingest, none of the partition arguments are forwarded, meaning that these options are disregarded.

**To Reproduce**
```
PYTHONPATH=. ./unstructured/ingest/main.py \
    local \
    --output-dir /tmp/ingest-requests/with-tables \
    --verbose \
    --reprocess \
    --strategy hi_res \
    --partition-by-api \
    --pdf-infer-table-structure \
    --api-key "$API_KEY" \
    --input-path 'example-docs/layout-parser-paper-with-table.pdf'
```

**Expected behavior**
When running the reproduce steps, one should see `text_as_html` in the Table Element

**Comment by yuming-long** [comment]
duplicated issue: https://github.com/Unstructured-IO/unstructured/issues/1064

**Comment by ryannikolaidis** [comment]
ahh, thanks @yuming-long!

**Comment by ryannikolaidis** [comment]
closing as dupe of #1064
