### ISSUE TITLE
Cant install python-libmagic from the requirements.txt file. It is throwing ImportError: cannot import name 'Feature' from 'setuptools' (/tmp/pip-build-env-pu_rc9y0/overlay/lib/python3.11/site-packages/setuptools/__init__.py)

### ISSUE THREAD

**Issue by msunkarahend** [Unstructured-IO/unstructured#2034]
I need python-libmagic because I am sending file like object into the partition function.

            with BytesIO(blob_data.readall()) as f:
                elements = partition(file=f, unique_element_ids=True )
It is suggested in the documentation.
https://unstructured-io.github.io/unstructured/introduction/getting_started.html#:~:text=The%20partition%20function%20uses,libmagic%20is%20not%20installed%60.

However i am getting the following error. The below images shows the error.

![image](https://github.com/Unstructured-IO/unstructured/assets/142630126/d9494316-691a-4d68-9455-8db4db7b5bb6)
![image](https://github.com/Unstructured-IO/unstructured/assets/142630126/70c4ac30-3ca5-45e5-9359-d4abb8ecc0cb)

**Comment by scanny** [comment]
@msunkarahend would you please post the command you issued that produced this output?

Are you installing unstructured from scratch using the installation instructions or are you "patching" an installation using `pip` to install `python-libmagic` by itself?

**Comment by scanny** [comment]
Closing as inactive. @msunkarahend feel free to reopen if you still need help with this :)
