### ISSUE TITLE
bug/<'unstructured' is not a package>

### ISSUE THREAD

**Issue by Wendong-Fan** [Unstructured-IO/unstructured#2060]
**Describe the bug**
ModuleNotFoundError: No module named 'unstructured.partition'; 'unstructured' is not a package

**To Reproduce**
from unstructured.partition.pdf import partition_pdf
pdf_path = "camel/RAG/1911 Census Occupation Data Classification.pdf"
partitioned_data = partition_pdf(pdf_path, url=None)

**Expected behavior**

Traceback (most recent call last):
  File "/Users/enrei/Desktop/CAMEL/camel/RAG/test.py", line 1, in <module>
    from unstructured.partition.pdf import partition_pdf
ModuleNotFoundError: No module named 'unstructured.partition'; 'unstructured' is not a package

(CAMEL) yuanlingdeMacBook-Pro:CAMEL enrei$ pip list | grep unstructured
unstructured                  0.10.30
unstructured-inference        0.7.11
unstructured.pytesseract      0.3.12

**Screenshots**
<img width="827" alt="Screenshot 2023-11-13 at 20 01 15" src="https://github.com/Unstructured-IO/unstructured/assets/133094783/5410941c-7153-45b9-843d-72fbadd0c17b">

**Comment by scanny** [comment]
@Wendong-Fan do you by chance have a file named `unstructured.py` in the current directory when you run `test.py`? That particular message ("... is not a package") would indicate that `import unstructured` is resolving to a module (.py file) and not to a _package_ (directory with an __init__.py file in it).

**Comment by meftunca** [comment]
Ahhahaha I made the same mistake :D

**Comment by bannarisoftwares** [comment]
Same mistake :)
