### ISSUE TITLE
bug/word document (.doc) page number property missing

### ISSUE THREAD

**Issue by walsha2** [Unstructured-IO/unstructured#2061]
**Describe the bug**

The `page_number` metadata entry is not returned for a `.doc` document. The same exact document, as a `.docx` returns the page numbers correctly. With the `page_number` property, there is no way to tell which page each element comes from for teh `.doc` file.  See example below and attachments on how to reproduce.

**To Reproduce**

FILE ATTACHMENTS: 

[doc_example.zip](https://github.com/Unstructured-IO/unstructured/files/13335954/doc_example.zip)

Here is an example using a basic `.doc` file: 

```sh
curl -X 'POST' \
   'https://api.unstructured.io/general/v0/general' \
   -H 'accept: application/json' \
   -H 'Content-Type: multipart/form-data' \
   -H 'unstructured-api-key: UNSTRUCTURED_API_KEY' \
   -F 'files=@./test/files/doc_basic.doc' \
   -s | jq -C .
```

```json
{
  "type": "Title",
  "element_id": "d0e5cb42d9924bed3d7ed4f8db06ecaf",
  "metadata": {
    "filename": "doc_basic.doc",
    "filetype": "application/msword",
    "parent_id": "58e12fe9931b1aa659b16e9f15721d45",
    "category_depth": 0,
    "languages": [
      "eng"
    ]
  },
  "text": "CHAPTER I"
},
```

Here is the equivalent `.docx` file: 

```sh
curl -X 'POST' \
   'https://api.unstructured.io/general/v0/general' \
   -H 'accept: application/json' \
   -H 'Content-Type: multipart/form-data' \
   -H 'unstructured-api-key: UNSTRUCTURED_API_KEY' \
   -F 'files=@./test/files/docx_basic.docx' \
   -s | jq -C .
```

```json
{
  "type": "Title",
  "element_id": "d0e5cb42d9924bed3d7ed4f8db06ecaf",
  "metadata": {
    "filename": "docx_basic.docx",
    "filetype": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "parent_id": "58e12fe9931b1aa659b16e9f15721d45",
    "category_depth": 0,
    "languages": [
      "eng"
    ],
    "page_number": 1 <---- NOTE: page_number
  },
  "text": "CHAPTER I"
},
```

**Expected behavior**

The `page_number` metadata property will be available for the equivalent `.doc` file, just as it is for the `.doc`.

**Environment Info**

I tested this **both** locally using the latest version of `unstructured` and via the currently deployed API (same result):

```
unstructured             0.10.30
unstructured-inference   0.7.11
unstructured.pytesseract 0.3.12
```

**Comment by scanny** [comment]
@walsha2 what is the call you used to test locally? I want to make sure I'm reproducing with the same call you're using.

**Comment by walsha2** [comment]
> @walsha2 what is the call you used to test locally? I want to make sure I'm reproducing with the same call you're using.

@scanny nothing fancy. Try this with `.doc` and .`docx`. You should see that not page numbers are returned in the metadata for `.doc` file.

Content types:

* `.doc`: `application/msword`
* `.docx`: `application/vnd.openxmlformats-officedocument.wordprocessingml.document`

```python
elements: List[Element] = []
elements = partition(
    file=file,
    content_type=content_type,
    strategy="auto",
)
```

**Comment by scanny** [comment]
@walsha2 unfortunately I believe this is the best that can be done. Here's my best shot at a compact explanation:

- To understand this, we need the concept _rendered page break_. The idea is that an "actual" page-break (in a printed document or output-PDF) is not determined by the document author, rather those are determined by a _rendering engine_ (like Word itself) when it _flows_ the document content into a page, wrapping lines to fit between margins in a particular font, etc., and _starting a new page_ when it runs out of vertical space on a page. Note this is also true for the occasional  _hard page break_ an author may insert, which merely instructs the renderer to start a new page there.
- In the Word 2007+ (DOCX) format, rendered page-breaks are optional and only _sometimes_ indicated in the `.docx` XML. For Word, this appears to be _most of the time_. But there is no guarantee and their presence _depends on the renderer to insert them_.
- It's not clear whether the Word 97-2003 binary `.doc` format (DOC) actually contains rendered page-breaks. That format was secret up until about a year ago and knowledge about it outside Microsoft is spotty. I personally have worked with the DOCX format for a decade and never seen mention of that aspect for the DOC format.

So what is happening here is that either the DOC equivalent of `w:lastRenderedPageBreak` elements do not exist, or for whatever reason they are not making it through the `DOC -> DOCX` file conversion provided by LibreOffice, which is what we use for this job.

Either way, they are not present in the converted DOCX file and so we do not attempt to compute page-number metadata for the document.

**Comment by scanny** [comment]
@walsha2 feel free to reopen if you think there's something we might be able to do to improve this, but closing this now as not actionable.

**Comment by walsha2** [comment]
> ...unfortunately I believe this is the best that can be done

Understood, thanks for the explanation! The page numbers are really important else we just get back a block of elements. For a large document, the traceability back to a specific location in the document is lost. But I suppose that is application/user specific.

My "solution" to get around this for `.doc` files right now is to simply convert to a PDF first and process the PDF. Although that has its disadvantages.

> or for whatever reason they are not making it through the DOC -> DOCX file conversion provided by LibreOffice

I have a feeling that might be what is happening. Although, for giggles, I took the same `.doc` I attached above, opened it in MS Word, performed the `.docx` conversion using MS Word, and still saw the same issue. So maybe it might not be a `LibreOffice` specififc limitation 🤷 

-------------

Fine to close for now. I messed around with other intermediate formats to see if they played nicer with page breaks, but no such luck.

I wonder if there is a hacky way to accomplish this. To me, a parsed document is not as valuable without the page numbers so I might investigate further.

**Comment by scanny** [comment]
Hmm, that's a good datapoint on the doc -> docx using Word. I expect if they existed in the DOC form then Word would have placed them.

From that we could take that we would need a renderer to come along and not only paginate, but also update the XML with the `<w:lastRenderedPageBreak>` elements.

I was able to get Word to add these, but making a small change and saving wasn't enough. I had to do a SaveAs..., even though the filename and file-type were the same.

It _did_ occur to me that _possibly_ scripting LibreOffice to print to PDF (which forces it to paginate) and then having it save the file (or maybe just having it do a SaveAs...) could _maybe_ have it add those rendered page breaks, but I didn't try that. I don't even know if LibreOffice puts those in. Unfortunately scripting Word itself is much harder with no open-source solutions that I know of.

Anyway, we probably know a little better what we're up against now than this morning :)

**Comment by walsha2** [comment]
> It did occur to me that possibly scripting LibreOffice to print to PDF (which forces it to paginate) and then having it save the file (or maybe just having it do a SaveAs...) could maybe have it add those rendered page breaks, but I didn't try that

Precisely the "hacky" type of thing I was talking about ha. I would like to think there is a way to get this done, even if it requires an extra step. If I come across anything, I will report it back here.

Would be nice to bank on having as much parity as possible when processing a `.doc` vs a `.docx`.

**Comment by scanny** [comment]
One kind of theoretical question that occurred to me about this @walsha2, basically asking the question:

> Why do we need page-number for DOCX?

Not to propose we don't try to determine it the best we can, but to understand better the later steps in the process it is going to inform or enable.

My initial assumption would be we want to be able to "get back to" the page where a certain element came from, like we did a search, found a "match" for that element, and then wanted to "show" that page in the document.

But if we don't have a reliable way to "get back to" that position in the original document, what good would that do us?

I suppose another reason could be to compute some form of _proximity_, like "on-the-same-page" or "nearby-page-wise", but those could be addressed with other means, like character, word, or token offset in the document; page location being a pretty arbitrary function of things like page layout (margins, page-size, hyphenation policy, etc.).

Do you have any thoughts on that?
