### ISSUE TITLE
More meaningful warnings for unknown filetypes in `detect_filetype`

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#208]
Currently the `detect_filetype` function in `unstructured.file_utils.filetype` emits the following warning if it detects an unknown MIME type. This isn't especially helpful because you still don't know what the file type is. The goal of this issue is to update the warning to print out the file extension or filename so it's more obvious what filetype cause the issue.

`MIME type was inode/x-empty. This file type is not currently supported in unstructured.`

**Comment by sparkbrains** [comment]
@cragwolfe 

I have updated the code and added the filename in the warning message. But this happens when detect_filetype detects the file which is empty. So the warning message should be same or needs to be changed?
