### ISSUE TITLE
bug/Figure element maps to FigureCaption type

### ISSUE THREAD

**Issue by shreyanid** [Unstructured-IO/unstructured#2098]
**Describe the bug**
In the [elements.py TYPE_TO_TEXT_ELEMENT_MAP](https://github.com/Unstructured-IO/unstructured/blob/7a741c9ae6b25b4f308bd602c2178bbc41ddf2d5/unstructured/documents/elements.py#L841), Figure maps to FigureCaption and is therefore not a distinct element.

**Expected behavior**
Expect Figure to appropriately map to a Figure or maybe other Image type of element instead of a caption

**Comment by christinestraub** [comment]
@shreyanid Thanks for reporting this bug! I believe that the `Figure` should map to `Image` like `Picture`. CC: @cragwolfe @qued

**Comment by cragwolfe** [comment]
Agreed! I think there may be a hack involved here where some model mischaracterized a Figure as a FigureCaption and this swept it under the carpet, but maybe i'm making that up. CC @benjats07
