### ISSUE TITLE
bug/Docx with table and merged cell duplicates text

### ISSUE THREAD

**Issue by tkumpumak** [Unstructured-IO/unstructured#2106]
Docx table parsing. When table has merged cells, the text inside the merged cell gets outputted multiple times (repeat count is the number of merged cells).

Unstructured 0.10.30, python-docx 1.1.0

Reproduce: 
Parse example file, notice topmost merged cells text "DSFSFAD" get repeated on output.
[test_table.docx](https://github.com/Unstructured-IO/unstructured/files/13389144/test_table.docx)

**Comment by scanny** [comment]
@tkumpumak do you have a point-of-view (POV) on what would be the preferred behavior for merged cells?

I think it comes down to two choices:

1. ***Blank spanned cells.*** Include a cell for every row/column intersection in the table, but only show text appearing in a merged cell in the upper-left cell of the spanned cells.
2. ***Omit spanned cells.*** Only include cells that actually exist, i.e. the text of a merged cell appears when the top-left cell of that merge is encountered an all other spanned cells are omitted from the output.

The first option produces a uniform table as output, i.e. all rows have the same number of cells but includes "empty" cells. Option 2 on the other hand loses the relationship of columns and/or rows, like if row 3 has 2 cells and row 1 has 3 then you can't tell which cell might be the column heading for cell 3, 2 and you can't tell which other cells are in the same column as that cell either.

In either option you lose the relationship (perhaps as headings) of spanned cells to at least some of their rows/columns. This is probably the one good thing about the current behavior (which is rooted in how `python-docx` currently treats merges).

**Comment by tkumpumak** [comment]
If you are talking about the "text" output on element, then likely duplicated text should not be preset. If about the table "html_as_text" then it might be a bit more complicated.

Let me explain why I found this issue if it helps with the solution. I was checking some data and noticed there was lot's of duplicated text in the parsed documents. It turned out that these _docx_ files had layout done with tables. In this case the documents were CV:s and they had full paragraphs of text on each of these merged rows.

I guess the handling should be consistent between different file parsers. How is the table extraction doing it on pdf or other file formats that extract tables? What would be the least surprising result for the merged cell case? At least for me it would be that the text would not be duplicated. But cannot say that in behalf of other users.

**Comment by scanny** [comment]
Hmm, good point drawing the distinction between `.text` and `metadata.text_as_html`. Whatever we do with the latter it seems clear the former should have no repeated text that does not appear so in the document itself.

I think I can pick up this focused case this week and we'll see where we go with the HTML output separately. Thanks very much for the benefit of your perspective on this :)

**Comment by veredmm** [comment]
@scanny hi,

still having this duplicated text problem with this kind of table structure :

[merged_table2.docx](https://github.com/user-attachments/files/15886108/merged_table2.docx)

table doc:

![image](https://github.com/Unstructured-IO/unstructured/assets/169882103/658fc873-eaf8-4b56-ba0e-ee201362f570)

after partition_docx :

![image](https://github.com/Unstructured-IO/unstructured/assets/169882103/39814d6a-7b1d-4a58-b9bb-eb82c432d9c2)


python-docx                             1.1.2
unstructured                            0.14.3
