### ISSUE TITLE
bug/docx does not parse heading numbers

### ISSUE THREAD

**Issue by bernhardschaefer** [Unstructured-IO/unstructured#2142]
**Describe the bug**

Heading numbers are not parsed in `partition_docx`. 

**To Reproduce**
[test_heading_number.docx](https://github.com/Unstructured-IO/unstructured/files/13441634/test_heading_number.docx)

```python
from unstructured.partition.docx import partition_docx
elements = partition_docx(filename="/path/to/test_heading_number.docx")
for e in elements:
    print(e)
```

Actual output:
```
Introduction
Motivation
Problem Statement
```

**Expected behavior**

Expected output:
```
1. Introduction
1.1 Motivation
1.2 Problem Statement
```

**Screenshots**
Screenshot of the test word document
<img width="406" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/5171968/d5c9600a-ebc2-4d62-b514-54643f5e480e">

**Environment Info**
OS version:  macOS-14.1-arm64-arm-64bit
Python version:  3.11.6
unstructured version:  0.10.30

**Comment by bernhardschaefer** [comment]
Thanks for the clarification @scanny. There are two related reasons for which I need heading numbers:
1) Citing sources in RAG: I'm working on a RAG use case and I want the LLM to always reference the chapter and section from which it compiled the response, which is only really meaningful when I have the number of the heading.
2) chunk_by_heading: I'm trying to chunk the document by heading. Unfortunately the headings in the documents I'm parsing have been created as `Normal` text combined with a multi-level list, so unstructured parses them as type `ListItem` instead of `Title`. Therefore, I wanted to use a regex based on heading number to identify and convert the headings.

**Comment by jaycrossler** [comment]
Is there a way to add the Style value (since it is in the xml) to each element?  If we know that an element has Heading3 style, we can find the previous Heading2 style to determine the hierarchy in most cases.  That hierarchy does help in semantic lookups/inference.

**Comment by VaishnaviL** [comment]
@bernhardschaefer — If Unstructured does not provide a mechanism to extract heading numbers, how were you able to capture and retain heading numbering in your RAG use case? I am currently working on a similar implementation and need the heading numbers to be preserved so that the LLM can correctly reference and align responses with the corresponding document sections.

**Comment by bernhardschaefer** [comment]
@VaishnaviL I used pandoc to convert docx to markdown followed by a regex step to extract and add them to the unstructured output. Quite hacky, I suppose there's a better way.
