### ISSUE TITLE
feat/Add support for epub format

### ISSUE THREAD

**Issue by nestordemeure** [Unstructured-IO/unstructured#215]
**Is your feature request related to a problem? Please describe.**
One of the leading open format for books is `epub`. Thus, when running algorithms on books I often have to find a way to process them.

**Describe the solution you'd like**
An `epub` is a compressed `html`. As `unstructured` already supports `html`, it would be very straightforward to add support for epub.

**Describe alternatives you've considered**
I am currently using [pandoc](https://pandoc.org/) to convert my `epub` data to `html`. This is straightforward but adds a special case to my pipelines.

**Comment by MthwRobinson** [comment]
@nestordemeure - Thanks for adding this issue! We're tracking it and will prioritize it as soon as we can.
