### ISSUE TITLE
tables to dataframe 

### ISSUE THREAD

**Issue by philip-shinra** [Unstructured-IO/unstructured#2157]
how to convert tables into dataframe ?

**Comment by jojogh** [comment]
seems it is not the function of unstructured, but, as unstructured also use table transformer project, you can refer microsoft table transformer project, or this article:
https://medium.com/@lidores98/image-table-to-dataframe-using-python-ocr-773c8afb713d
Hope this can help

**Comment by cragwolfe** [comment]
If you are working with unstructured output, a `Table` element has a `metadata.text_as_html` field which you could read into a pandas dataframe (google "html to pandas dataframe").

**Comment by avirlrma** [comment]
I couldn't find any reference of microsoft's table transformer in unstructured IO's documentation. Is there any document on how unstructured makes use of table transformer?

**Comment by shriharshan** [comment]
> If you are working with unstructured output, a `Table` element has a `metadata.text_as_html` field which you could read into a pandas dataframe (google "html to pandas dataframe").

i am receiving a KeyError while trying to access text_as_html. Can you please provide the code or any help regarding this?

**Comment by scanny** [comment]
@shriharshan please open a new issue for your problem as it is not strictly related to the original post.

Provide a snippet of how you call the partitioning function and the full stack trace you receive when you get the KeyError. Also, make sure you're using the latest version of `unstructured`.

An `ElementMetadata` object will never raise `KeyError` on accessing `element.metadata.text_as_html`. However accessing the `dict` form of an element could. You'll need to use `element["metadata"].get("text_as_html")` in that case and properly handle the possible `None` case.

Closing original post as resolved.
