### ISSUE TITLE
feat/add unit tests to `conform_dict`

### ISSUE THREAD

**Issue by rvztz** [Unstructured-IO/unstructured#2181]
**Is your feature request related to a problem? Please describe.**
- `conform_dict` is a method used in at least 3 destination connectors.
- Merge usage of the `conform_dict` method on destination connectors into a single one
- This method applies formatting to the input elements dictionaries to fit the schema in the remote source

**Describe the solution you'd like**
- Add unit tests for the `conform_dict` methodI(s)

**Comment by potter-potter** [comment]
I think this should be about extracting conform_dict so that the 3+ destination connectors can use it.

**Comment by potter-potter** [comment]
Was done by Roman.
