### ISSUE TITLE
offline mode to install 

### ISSUE THREAD

**Issue by joeylin** [Unstructured-IO/unstructured#2184]
**Describe the bug**
My environment with unstructrued was unable to access the network， So I need install it offline, and preload model file In the cache
but I found tables_agent(tables.py) load model with hard code "microsoft/table-transformer-structure-recognition" param, 
![image](https://github.com/Unstructured-IO/unstructured/assets/2030833/69813791-851d-48f9-8680-9d30d77fb44c)
cloud pls use params, so i can use local loaded model 

thx

**Expected behavior**
install offline

**Screenshots**

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

**Additional context**

**Comment by MthwRobinson** [comment]
This looks like a nice option to add.

**Comment by MthwRobinson** [comment]
This will work without internet connectivity, but you'll need to move the model files to your HF local cache, such as `.cache/huggingface/hub/`. You can control the cache location with the `HF_HOME` or `HF_HUB_CACHE` environment variables (see [here](https://huggingface.co/docs/huggingface_hub/en/package_reference/environment_variables#hfhome) for details). The function in `unstructured-inference` that downloads the model is below for reference.

https://github.com/Unstructured-IO/unstructured-inference/blob/64cd41c37fe4535702b3be9c6b58f380ca4c7edd/unstructured_inference/utils.py#L188-L195

**Comment by yzztin** [comment]
If you have already obtained the model files locally, but still require online verification with huggingface.co, you can set the environment variables as follows:
`export HF_HUB_OFFLINE=1`
