### ISSUE TITLE
bug/UUIDs should be reflected in the `parent_id` field when `unique_element_ids=True`

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#2193]
As noted in [this comment](https://github.com/Unstructured-IO/unstructured/pull/1085#issuecomment-1833511282), UUIDs do not appear in the `parent_id` field when `unique_element_ids=True`. The goal of this issue is to update the behavior so that `parent_id` and `element_id` fields are consistent.

**Comment by scanny** [comment]
Closing as resolved.
