### ISSUE TITLE
[Question] Use of Image Element object

### ISSUE THREAD

**Issue by gabrieldiem** [Unstructured-IO/unstructured#2196]
Hi!
I would like to understand how can I use the Image object `unstructured.documents.elements.Image`. I processed a PDF with `partition_pdf` with `high_res` strategy, it picked up the 2 images that were present in that PDF of 1 page, I confirmed this because the `.text` property of them (I assume OCR'ed) contained the text information visible in the image. The thing is I don't know how to continue from this point on, how can I work with this recognized image as an actual image (compose new documents or export it as png or jpeg).

I couldn't find a part of the documentation that talked about the API of the elements.

I'm looking forward to see this open source project grow 😊

**Comment by cragwolfe** [comment]
Yes, for example [this notebook](https://github.com/langchain-ai/langchain/blob/master/cookbook/Semi_structured_and_multi_modal_RAG.ipynb) includes an example of extracting images within a PDF:
![image](https://github.com/Unstructured-IO/unstructured/assets/28578599/8ac5d9ff-3564-45a5-8a2c-ec66079b9feb)
you can also pass [the parameter](https://github.com/Unstructured-IO/unstructured/blob/92dae8c/unstructured/partition/pdf.py#L134) `image_output_dir_path` to specify where to save the `Images`. The resulting `Image` elements will have the metadata field `.image_path`.

Thanks!

**Comment by gabrieldiem** [comment]
Thanks for the insights!
