### ISSUE TITLE
bug/partition_pdf UnidentifiedImageError - cannot identify image file

### ISSUE THREAD

**Issue by kritinyoupane** [Unstructured-IO/unstructured#2197]
While reading pdfs file consisting of images and tables using partition_pdf 
![image](https://github.com/Unstructured-IO/unstructured/assets/46289798/6a26b948-24cd-463c-b4b4-17577fa4bb41)

Always shows this error
![image](https://github.com/Unstructured-IO/unstructured/assets/46289798/af801d31-561f-4332-bb94-5d9e8d499bd8)

**Comment by krish240574** [comment]
Ya, this happens with any PDF file, here is a sample:
[Quarterly Financial Report Template.pdf](https://github.com/Unstructured-IO/unstructured/files/13622465/Quarterly.Financial.Report.Template.pdf)

**Comment by christinestraub** [comment]
Hi @krish240574, thanks for sharing a sample! What versions of the `unstructured` and `unstructured-inference` libraries did you use?

**Comment by krish240574** [comment]
Name: unstructured
Version: 0.10.5
Summary: A library that prepares raw documents for downstream ML tasks.
Home-page: https://github.com/Unstructured-IO/unstructured
Author: Unstructured Technologies
Author-email: devops@unstructuredai.io
License: Apache-2.0
Location: /root/spock/lib/python3.10/site-packages
Requires: beautifulsoup4, chardet, emoji, filetype, lxml, nltk, python-magic, requests, tabulate
Required-by: 
========================================================================================
Name: unstructured-inference
Version: 0.5.16
Summary: A library for performing inference using trained models.
Home-page: https://github.com/Unstructured-IO/unstructured-inference
Author: Unstructured Technologies
Author-email: devops@unstructuredai.io
License: Apache-2.0
Location: /root/spock/lib/python3.10/site-packages
Requires: huggingface-hub, layoutparser, onnxruntime, opencv-python, python-multipart, transformers
Required-by:

**Comment by krish240574** [comment]
pip install langchain unstructured==0.11.2 unstructured-inference==0.7.15 pydantic lxml
pip uninstall pdfminer.six --y
pip install pikepdf pypdf wrapt pdfminer.six 
pip install unstructured_pytesseract
apt-get install poppler-utils
apt-get install tesseract-ocr

I installed all the above, in addition to unstructured==0.11.2 and unstructured-inference==0.7.15 and I'm good to go.

Thanks again .

**Comment by piegu** [comment]
@christinestraub and @awalker4: you can now (15/12/2023) install the last versions of `unstructured` (0.11.4) and `unstructured-inference` (0.7.18):

```
apt-get install poppler-utils
apt-get install tesseract-ocr
pip install unstructured[all-docs] unstructured-inference
pip install langchain pydantic lxml # if needed

# [ IMPORTANT ] restart session on Google Colab
```

... and import `partition_pdf ` as follows:

`from unstructured.partition.pdf_image.pdf import partition_pdf`

... and it works.

**Comment by adi-kmt** [comment]
> @christinestraub and @awalker4: you can now (18/12/2023) install the last versions of `unstructured` (0.11.5) and `unstructured-inference` (0.7.19):
> 
> ```
> apt-get install poppler-utils
> apt-get install tesseract-ocr
> pip install unstructured[all-docs] unstructured-inference
> pip install langchain pydantic lxml # if needed
> 
> # [ IMPORTANT ] restart session on Google Colab
> ```
> 
> ... and import `partition_pdf ` as follows:
> 
> `from unstructured.partition.pdf import partition_pdf`
> 
> ... and it works.

I'm getting `Cannot install unstructured-inference==0.7.19 and unstructured[all-docs]==0.11.5 because these package versions have conflicting dependencies.` @piegu

**Comment by awalker4** [comment]
Hi there, can you try jumping to the latest of unstructured? That should pull the correct version of inference:
```
pip install -U unstructured[all-docs]
```
