### ISSUE TITLE
No module named 'pikepdf'

### ISSUE THREAD

**Issue by dirudiez** [Unstructured-IO/unstructured#2200]
I am using unstructured version 0.11.0, python 3.9

When I use the `UnstructuredURLLoader()` constructor I get the following error: _No module named 'pikepdf'._

When I install it, I get other errors about missing libraries such as `opencv-python `or `unstructured-pytesseract` or `unstructured_inference` but I don't use any of these libraries.

This change to a newer version is because I need to use a new method to get the html tables (`UnstructuredHTMLLoader()`). Before I use 0.10.19

**Comment by awalker4** [comment]
Hi there, pikepdf was recently added as a dependency, but just for pdf files. Does it work if you do `pip install unstructured[all-docs]`?

**Comment by awalker4** [comment]
I'll close this now, but please reopen if this is still an issue.
