### ISSUE TITLE
Problem when dealing with nested tables / tables inside tables [HTML]

### ISSUE THREAD

**Issue by gabrieldiem** [Unstructured-IO/unstructured#2205]
Hi Unstructured team!

I've been doing a project where I need to deal with the old way of structuring webpages, when the common structure was to make everything inside the "main table" like a frame for the website.
So, while using the Unstructured library I noticed the parsing of the html (when partitioned from an html file) was kinda weird, it did not keep the table nesting or parsed it correctly. So I tried with a simpler example of a table inside a table and I got a pretty similar behaviour.

This is the table nesting example I inputed to the library:
<img width="340" alt="Screenshot 2023-12-04 at 10 57 47" src="https://github.com/Unstructured-IO/unstructured/assets/72816870/8f0b0dd9-c40c-4f29-9d85-5bc071d9108d">

And this is the parsing result:
<img width="1199" alt="Screenshot 2023-12-04 at 10 58 02" src="https://github.com/Unstructured-IO/unstructured/assets/72816870/03f0689e-797d-4021-b870-a4ea8cb81227">

It sort of expands it to the side, which is something that also happened with the real html website.
These are the partition parameters:

``` python
params = {
    "filename": "./test.html",
    "url": None,
    "strategy": "hi_res",
    "languages": ["eng"],
    "ocr_languages": "eng"
}

tableNesting = partition_html(**params)
```

And here is the code for the tables:
- Input html:

``` html
<table border="1">
        <tr>
            <th>Header 1</th>
            <th>Header 2</th>
            <th>Header 3</th>
        </tr>
        <tr>
            <td>Row 1, Cell 1</td>
            <td>Row 1, Cell 2</td>
            <td>Row 1, Cell 3</td>
        </tr>
        <tr>
            <td colspan="3">
                <!-- Nested Table -->
                <table border="1" width="100%">
                    <tr>
                        <th>Nested Header 1</th>
                        <th>Nested Header 2</th>
                    </tr>
                    <tr>
                        <td>Nested Row 1, Cell 1</td>
                        <td>Nested Row 1, Cell 2</td>
                    </tr>
                    <tr>
                        <td>Nested Row 2, Cell 1</td>
                        <td>Nested Row 2, Cell 2</td>
                    </tr>
                </table>
                <!-- End of Nested Table -->
            </td>
        </tr>
        <tr>
            <td>Row 3, Cell 1</td>
            <td>Row 3, Cell 2</td>
            <td>Row 3, Cell 3</td>
        </tr>
    </table>
```

Parsed html:
``` html
<table border="1">
  <tr>
    <td><br /></td>
    <td>Header 1</td>
    <td><br /></td>
    <td>Header 2</td>
    <td><br /></td>
    <td>Header 3</td>
    <td><br /></td>
  </tr>
  <tr>
    <td><br /></td>
    <td>Row 1, Cell 1</td>
    <td><br /></td>
    <td>Row 1, Cell 2</td>
    <td><br /></td>
    <td>Row 1, Cell 3</td>
    <td><br /></td>
  </tr>
  <tr>
    <td><br /></td>
    <td>
      <br />
      <br />
    </td>
    <td><br /></td>
    <td><br /></td>
    <td>Nested Header 1</td>
    <td><br /></td>
    <td>Nested Header 2</td>
    <td><br /></td>
    <td><br /></td>
    <td><br /></td>
    <td>Nested Row 1, Cell 1</td>
    <td><br /></td>
    <td>Nested Row 1, Cell 2</td>
    <td><br /></td>
    <td><br /></td>
    <td><br /></td>
    <td>Nested Row 2, Cell 1</td>
    <td><br /></td>
    <td>Nested Row 2, Cell 2</td>
    <td><br /></td>
    <td><br /></td>
    <td>
      <br />
      <br />
    </td>
    <td><br /></td>
  </tr>
  <tr>
    <td><br /></td>
    <td>Row 3, Cell 1</td>
    <td><br /></td>
    <td>Row 3, Cell 2</td>
    <td><br /></td>
    <td>Row 3, Cell 3</td>
    <td><br /></td>
  </tr>
</table>
```

**Comment by scanny** [comment]
Hi @gabrieldiem, I believe this behavior was changed a while back.

This is the `.metadata.text_as_html` that is produced when partitioning your sample table with the current version and this is the expected behavior:

<table>
  <tr>
    <td>Header 1</td>
    <td>Header 2</td>
    <td>Header 3</td>
  </tr>
  <tr>
    <td>Row 1, Cell 1</td>
    <td>Row 1, Cell 2</td>
    <td>Row 1, Cell 3</td>
  </tr>
  <tr>
    <td>Nested Header 1 Nested Header 2 Nested Row 1, Cell 1 Nested Row 1, Cell 2 Nested Row 2,
        Cell 1 Nested Row 2, Cell 2</td>
  </tr>
  <tr>
    <td>Row 3, Cell 1</td>
    <td>Row 3, Cell 2</td>
    <td>Row 3, Cell 3</td>
  </tr>
</table>

In particular:
1. All text of a nested table appears within the cell in which the nested table appeared.
2. Cell merging is ignored.

Closing for now as assumed resolved, but feel free to reopen or leave additional comments if needed.

**Comment by gabrieldiem** [comment]
Thanks for the info and the clarification!
