### ISSUE TITLE
feat/extract-only-text

### ISSUE THREAD

**Issue by kyteinsky** [Unstructured-IO/unstructured#2251]
**Is your feature request related to a problem? Please describe.**
I am working on a project where I just need the raw text from various kinds of document formats like ppt(x), doc(x), etc. I would like to just extract text with the table formatting and skip the tokenization part completely.

**Describe the solution you'd like**
Use of `include_metadata` or addition of a new option in `partition_*` methods to be able to control if only `Text` element is present in the output or others are also inferred and included.

**Describe alternatives you've considered**
This library is a massive convenience for me for all kinds of document parsing, thank you. Different libraries for every file type would not be ideal. Another solution that can be done is to use another category like `partition` to just parse and output a string value but would again call the partition methods and need change there anyway.

**Additional context**
`partition` files that make use of tokenization are ppt, pptx, doc, docx, xls, xlsx, text.

**Comment by scanny** [comment]
@kyteinsky I'm not getting what you mean by "tokenization"; the PPTX and DOCX parsers do not tokenize the text and you should be able to get what you want by reading the element `.text` attribute and selecting the metadata (like `.metadata.text_as_html`) that you care about.

Closing as assumed resolved, but feel free to elaborate if you think I've missed something and we can continue the conversation.
