### ISSUE TITLE
feat/table-header-rows

### ISSUE THREAD

**Issue by hynky1999** [Unstructured-IO/unstructured#2256]
**Is your feature request related to a problem? Please describe.**
- I have a huge table which I need to embed. I thus need to split the table, the problem is that the returned Type from unstrucutred Table doesn't have a field, which would directly provide the header nor have rows as list.
- This is problem, because we can't do rows aware chunking. E.g We Combine multiple rows into one batch which we embed.

**Describe the solution you'd like**
I would like to either (preference based on order):
1. Add field to Table type for storing header as list
3. Add field to Table type for storing rows as list of strings

**Describe alternatives you've considered**
One can scrape the header from the text_as_html attribute, but that's everything but user friendly.

I have no problem with implementing this feature, just want to make sure the PR will get merge eventualy.

**Comment by veredmm** [comment]
@scanny  - anything new about this enhancement ?

**Comment by scanny** [comment]
Row-aware chunking was added awhile back, so chunks of an oversized table now contain an integer number of whole rows and `TableChunk.text` matches the text in `TableChunk.metadata.text_as_html`.

Row header(s) detection is a distinct issue and not something we can reliably accomplish without use of a model. If that's something you're proposing we should address that in a different ticket.
