### ISSUE TITLE
bug: pdfminer occasionally fails to decode text and returns `cid` codes instead

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#2264]
**Describe the bug**
A known issue with `pdfminer` is that it will sometimes return `cid` values instead of the actual text that is visible in a PDF. This is because "a PDF has two different representations of each character. Each character is mapped to a glyph that determines how the character is shown in a PDF viewer. And each character is also mapped to its unicode value that is used when copy-pasting the character. Some PDF’s have incomplete unicode mappings and therefore it is impossible to convert the character to unicode. In these cases pdfminer.six defaults to showing the raw character id (cid:x)" (see more [here](https://pdfminersix.readthedocs.io/en/latest/faq.html#why-are-there-cid-x-values-in-the-textual-output)).

**Expected behavior**
for `hi_res` mode we should fall back to `ocr_only` if pdfminer fails to decode.

**Comment by christinestraub** [comment]
@Coniferish We're handling this issue on PR #2259. CC: @badGarnet
