### ISSUE TITLE
(PDF) yolox generates slightly different content in `text_as_html` and `text` values

### ISSUE THREAD

**Issue by piegu** [Unstructured-IO/unstructured#2271]
**Describe the bug**

[ EDIT on 18/12/2023 - see similar issue with PDF, JSON files and notebook in this [issue #2290](https://github.com/Unstructured-IO/unstructured/issues/2290) ]

When running `partition_pdf` on a PDF file with table, we get a list of elements (list of json). For the table element, we get both the keys `text_as_html` and `text`. Out of the table html tags, the content of the corresponding values is slightly different.

**To Reproduce**
```
from unstructured.partition.pdf import partition_pdf

filename = 'filename.pdf'

elements = partition_pdf(
    filename=filename,
    strategy="hi_res",
    infer_table_structure=True,
    model_name="yolox")

from unstructured.staging.base import elements_to_json
elements_to_json(elements, filename=f"{filename}.json")

with open(f"{filename}.json", 'r') as file:
    data = json.load(file)

# Iterate over the JSON data and extract required table elements
for entry in data:
    if entry["type"] == "Table":
          print(entry["text"])
          print(entry["metadata"]["text_as_html"])
```

**Expected behavior**
Out of the table html tags, we expect the exact same content in both values.

**Environment Info**
unstructured==0.11.2 
unstructured-inference==0.7.1

**Comment by scanny** [comment]
Closing as inactive, assumed resolved.
