### ISSUE TITLE
bug: docker image is broken

### ISSUE THREAD

**Issue by eXamadeus** [Unstructured-IO/unstructured#2274]
**Describe the bug**
I was trying to use the official docker image in some deployed pipelines, but kept running into issues with the python modules not working. I backtracked to the simplest possible run of the image and even the base image seems busted.

**To Reproduce**
Following the [documentation instructions](https://unstructured-io.github.io/unstructured/installation/docker.html#using-the-docker-image) will land you here, but I will write out step by step what I'm seeing.

1. Create the container
    ```
    docker run -dt --name unstructured downloads.unstructured.io/unstructured-io/unstructured:latest
    ```
2. Run the container
    ```
    docker exec -it unstructured bash
    ```
3. Start a python shell
    ```
    python 3
    ```
4. Try to import anything, while in the shell
    ```
    from unstructured.partition.pdf import partition_pdf
    ```

**Expected behavior**
I would expect the function to import.

**Screenshots**
It blows up with the following error:

```
>>> from unstructured.partition.pdf import partition_pdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'unstructured.partition.pdf'
```

**Environment Info**
This doesn't seem to work either:

```
➜  unstructured git:(main) python3 scripts/collect_env.py
/Users/***/unstructured/scripts/collect_env.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "/Users/***/unstructured/scripts/collect_env.py", line 7, in <module>
    from unstructured.utils import dependency_exists
ModuleNotFoundError: No module named 'unstructured'
```

**Comment by eXamadeus** [comment]
I'd love to find out that I'm just doing something wrong. I've tried quite a few different ways to do it, but I have to manually install the library in the container for it to run.

While that's not the worst thing, it kinda defeats the purpose of the official container.

**Comment by MthwRobinson** [comment]
We've switched over to a new base image in [`Dockerfile-amd64`](https://github.com/Unstructured-IO/unstructured/blob/main/Dockerfile-amd64) and run the unit tests inside that container as part of CI now. I'd give that a try if you haven't already. If this issue recurs, let us know and we can reopen.
