### ISSUE TITLE
Add filetype check based on file extension if `libmagic` isn't available

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#228]
Currently we use libmagic to determine the filetype for input files. However, `magic` requires the `libmagic` library, which not all users have available. The goal of this issue is to add a fallback that determines the filetype based on the file extension if `libmagic` is not available. If `libmagic` is available, `detect_filetype` should continue to use `magic`, as it does currently.

**Comment by firedragonironfist** [comment]
Hey I'd love to contribute by working on it. Would it be possible for me to take on this issue? If so, please assign it to me or let me know what the next steps are. Thank you for your time and consideration!

**Comment by firedragonironfist** [comment]
Thank you so much for assigning this issue to me! I'm excited to get started and make a contribution to the project. I really appreciate the opportunity and I'll do my best to resolve this issue as quickly and efficiently as possible. Please let me know if you have any additional guidance or if there's anything else I should know. Thanks again!

**Comment by MthwRobinson** [comment]
Sure thing, thanks for picking it up! One note, just updated the issue description. We'll want the following behavior:
- Determine the filetype with `magic` if `libmagic` available
- If `libmagic` is not available, fall back to using the file extension

**Comment by firedragonironfist** [comment]
Dear Contributor, based on my understanding of the issue at hand, I believe that adding try and catch statements in the function detect_filetype is a good approach. In the try statement, I can attempt to load the libmagic library, and if that fails, I can use the except statement to recognize the file types using the splittext() function and map the file extensions to their corresponding MIME types. This will ensure that the function is robust and able to handle unexpected errors that may arise when attempting to load the library but I am not sure if this is the right approach can you please let me know

**Comment by firedragonironfist** [comment]
Hey MthwRobinson, based on my understanding of the issue at hand, I believe that adding try and catch statements in the function detect_filetype is a good approach. In the try statement, I can attempt to load the libmagic library, and if that fails, I can use the except statement to recognize the file types using the splittext() function and map the file extensions to their corresponding MIME types. This will ensure that the function is robust and able to handle unexpected errors that may arise when attempting to load the library but I am not sure if this is the right approach will you please let me know is my implementation is right?

**Comment by MthwRobinson** [comment]
@firedragonironfist - Thanks! That generally sounds like the right approach, added a couple of inline comments to your PR.

**Comment by firedragonironfist** [comment]
Hey MthwRobinson I have updated my changes and also verified black --line-length 100 command and now it is showing 2 files reformatted so I think it is working fine now can you please reassign me the issue so that i can make pull request again

**Comment by MthwRobinson** [comment]
@firedragonironfist - You're still assigned to this issue. You're good to go to open a fresh PR whenever you're ready.

**Comment by firedragonironfist** [comment]
![Screenshot_20230223_203634](https://user-images.githubusercontent.com/91149240/220946298-de456734-7384-4391-8957-19559cfb640f.png)
I Dunno why I am getting this error when I am trying to push the commits I tried Searching the internet It is suggesting that repository owner must give some access or Can you guide me why I am getting  this error

**Comment by MthwRobinson** [comment]
You'll want to make a branch on your fork (https://github.com/firedragonironfist/unstructured) instead of https://github.com/Unstructured-IO/unstructured and then you can up a PR from there.

**Comment by firedragonironfist** [comment]
Thank you so much will do
