### ISSUE TITLE
`extract_tables_in_pdf` is mentioned in the file `pdf.py` but not implemented

### ISSUE THREAD

**Issue by piegu** [Unstructured-IO/unstructured#2280]
**Describe the bug**
`extract_tables_in_pdf` is mentioned in the file [pdf.py](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/pdf_image/pdf.py#L172) but not implemented in the function [partition_pdf](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/pdf_image/pdf.py#L124).

**Environment Info**
unstructured 0.11.4

**Comment by christinestraub** [comment]
@piegu The `extract_tables_in_pdf` mentioned in the pdf.py file will be removed in a future version. If you want to extract tables, you can pass `extract_element_types=['Table']` to the `partition_pdf()` function.

**Comment by piegu** [comment]
Thank you @christinestraub.

And in the case of the `partition_via_api`, it looks like `extract_tables_in_pdf` does not work (this parameter is not listed in [api parameters page](https://unstructured-io.github.io/unstructured/apis/api_parameters.html). 

What is the parameter to get images of the table? Thank you.

**Comment by christinestraub** [comment]
@awalker4 CC: @cragwolfe

**Comment by Coniferish** [comment]
@piegu and @christinestraub, this issue will add table image extraction to the api if you want to track it:
https://github.com/Unstructured-IO/unstructured-api/issues/306
