### ISSUE TITLE
(PDF) The model `chipper via api` duplicates in the JSON the found textual content from PDF and with different `type`

### ISSUE THREAD

**Issue by piegu** [Unstructured-IO/unstructured#2291]
**Describe the bug**

The model `chipper via api` duplicates in the JSON the found textual content from PDF and with different `type`.

I did the test with a PDF I created using `LibreOffice Writer >> Export to PDF` : [test_with_chipper_text_por.pdf](https://github.com/piegu/language-models/blob/master/docs/tests/test_with_chipper_text_por.pdf)

Characteristics of this PDF:
- written in Portuguese
- a table created inside the LibreOffice Writer with the menu Table

JSON file as output (see link to notebook in the paragraph "To Reproduce"):
- from `chipper via api` (use of `partition_via_api`): [test_with_chipper_text_por_pdf_api_chipper.json](https://github.com/piegu/language-models/blob/master/docs/tests/test_with_chipper_text_por_pdf_api_chipper.json)

I did notice the following points:
- **language**
  - `chipper via api` does not use the information about language given in the parameter `languages`: in its json file, you can verify that each element gets `"languages": ["eng"]` even if I passed `"languages": ["por"]`.
- **element**
  -  A lot of textual content (element) are duplicated in the json and with a different type. See the following example:
```
{
        "element_id": "61faf2d2aca915b09d2148a87100fa58",
        "metadata": {
            "filename": "test_with_chipper_text_por.pdf",
            "filetype": "application/pdf",
            "languages": [
                "eng"
            ],
            "page_number": 1,
            "text_as_html": "*Este nao e um texto em ingles, mas em portugues."
        },
        "text": "*Este nao e um texto em ingles, mas em portugues.",
        "type": "NarrativeText"
    },
    {
        "element_id": "8574e2c8393e19b24cb3b7a164abaff6",
        "metadata": {
            "filename": "test_with_chipper_text_por.pdf",
            "filetype": "application/pdf",
            "languages": [
                "eng"
            ],
            "page_number": 1
        },
        "text": "Este n\u00e3o \u00e9 um texto em ingl\u00eas, mas em portugu\u00eas.",
        "type": "ListItem"
    },
```

**To Reproduce**

Notebook to get JSON from this PDF both with `chipper via api`: [Unstructured_PDF_to_json_with_chipper_via_api.ipynb](https://github.com/piegu/language-models/blob/master/docs/tests/Unstructured_PDF_to_json_with_chipper_via_api.ipynb)

**Expected behavior**

I expected to get just once in the json file each textual content (element) of the PDF when using `chipper via api`. Unfortunately, it is not the case.

**Environment Info**
- unstructured 0.11.5
- unstructured-inference 0.7.19
- Google Colab

**Comment by MthwRobinson** [comment]
Hi @piegu - the `languages` parameter controls what language to use for OCR. Since Chipper doesn't use OCR, so the `languages` parameter doesn't do anything when used in conjunction with chipper.
