### ISSUE TITLE
bug/SLow processing of pdf document

### ISSUE THREAD

**Issue by kulbinderdio** [Unstructured-IO/unstructured#2300]
**Describe the bug**
Processing a 6MB pdf document takes around a minute

**To Reproduce**
```
docker run -it -p 8000:8000 downloads.unstructured.io/unstructured-io/unstructured-api:c30a2b8

curl -X 'POST' 'http://localhost:8000/general/v0/general' -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F 'files=@NIST.SP.800-53r5.pdf' | jq -C .
```

**Expected behavior**
Expected a few seconds at the most

**Screenshots**

**Environment Info**
Using docker container
image: downloads.unstructured.io/unstructured-io/unstructured-api:c30a2b8

**Additional context**
This issue occurred while running with bionicGPT and an associated issue was raised there before I recreated with curl command
https://github.com/bionic-gpt/bionic-gpt/issues/211

[NIST.SP.800-53r5.pdf](https://github.com/Unstructured-IO/unstructured/files/13728176/NIST.SP.800-53r5.pdf)

**Comment by ianpurton** [comment]
I'm also having this issue.

**Comment by cds-code** [comment]
I'm also having this issue.

**Comment by christinestraub** [comment]
Similar to https://github.com/Unstructured-IO/unstructured/issues/3217, a long runtime is expected on a PDF of that length. If you need to process that fast, try using our [API](https://docs.unstructured.io/api-reference/api-services/overview) through our [client SDK](https://github.com/Unstructured-IO/unstructured-python-client). That will split up the PDF and make run partition across multiple workers.
