### ISSUE TITLE
bug/table parsing on embedded text tables

### ISSUE THREAD

**Issue by maxjeblick** [Unstructured-IO/unstructured#2301]
**Describe the bug**

Table inference uses ocr to infer the text within the table, [see here](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/pdf_image/ocr.py#L230). To me, this seems suboptimal, as tables are very often embedded in the pdf and the individual entries could be parsed directly.

**To Reproduce**
When using table inferer with paddle ocr model, I get a lot of parsing errors.
```
import os
os.environ["OCR_AGENT"] = "paddle"

from unstructured.partition.auto import partition
elements = partition(filename="ast_sci_data_tables_sample.pdf",
                     skip_infer_table_types=[],
                     pdf_infer_table_structure=True)

from IPython.core.display import display, HTML

html = " ".join([element.metadata.text_as_html for element in elements
              if element.metadata.text_as_html is not None])
display(HTML(html))
```
with the pdf downloaded from `https://sedl.org/afterschool/toolkits/science/pdf/ast_sci_data_tables_sample.pdf`

When using tesseract, the results are actually worse, the second table in the pdf isn't recognized at all.

**Expected behavior**

All tables from the example pdf are parsed correctly.

**Screenshots**

Example of wrong table (should be 3, 5, 4)
```
Nuber of Coils	Number of Paperclips
5	3,,4
10	7,,6
15	11,10,12
20	15, 13, 14
```

**Environment Info**
```
OS version:  Linux-5.15.0-91-generic-x86_64-with-glibc2.31
Python version:  3.10.13
unstructured version:  0.11.5
unstructured-inference version:  0.7.18
pytesseract version:  0.3.10
Torch version:  2.1.1
Detectron2 is not installed
PaddleOCR version:  2.5.2
Libmagic version: file-5.38
magic file from /etc/magic:/usr/share/misc/magic
LibreOffice version:  LibreOffice 6.4.7.2 40(Build:2)
```

**Comment by MthwRobinson** [comment]
Thanks for reporting! Closing out this one. We have a more powerful table extraction model available in our [SaaS API](https://unstructured.io/api-key-hosted) that I would suggest trying. Future table extraction improvements will be deployed there.
