### ISSUE TITLE
Add email header information to metadata

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#231]
The `partition_email` function has the ability to parse out header information from emails, like `to:`, `from:` and `subject:`. The goal of this issue is to add this to the `unstructured` metadata when partitioning emails.

**Comment by tomaarsen** [comment]
@MthwRobinson
How exactly does this differ from using `partition_email(..., include_headers=True)`? Do you want this metadata to be captured here?
https://github.com/Unstructured-IO/unstructured/blob/30ac3e6daa3e3a014e71d69031df08d607b8ba34/unstructured/partition/email.py#L229

- Tom Aarsen

**Comment by MthwRobinson** [comment]
Yeah that information should be captured in `element.metadata` now. We'll keep the `include_headers` kwarg in there in case someone is using it, but we'll discourage people from using that kwarg (I'd output a warning if someone uses it).

**Comment by MthwRobinson** [comment]
Addressed in #439
