### ISSUE TITLE
partition_pdf giving 'UnidentifiedImageError' error (partition_pdf(filename="Bunge_2022.pdf", infer_table_structure=True, extract_images_in_pdf=False, url=None))/partition_pdf issue

### ISSUE THREAD

**Issue by sravan1320** [Unstructured-IO/unstructured#2314]
**Describe the bug**

Installations:
# !apt-get install poppler-utils
# !apt-get install libmagic-dev
# !apt-get install poppler-utils
# !sudo apt install tesseract-ocr
# ! pip install langchain unstructured[all-docs] pydantic lxml pdfminer.six pdf2image

Hello i am using this way in **Google Colab**

**Working Case:**
from unstructured.partition.auto import partition

elements = partition("Bunge_2022.pdf")
print("\n\n".join([str(el) for el in elements]))

**Issue Scenario:**
from typing import Any
from pydantic import BaseModel
from unstructured.partition.pdf import partition_pdf
elements = partition_pdf(filename="Bunge_2022.pdf", infer_table_structure=True, extract_images_in_pdf=False, url=None)

it giving this error 
"UnidentifiedImageError: cannot identify image file '/tmp/tmpx58pqpr0/9a43bade-a339-482a-967b-90d458eefbcb-001.ppm'"

![image](https://github.com/Unstructured-IO/unstructured/assets/55118375/0f22119b-b54b-41c5-a4f5-12c6ddf43690)

**Environment Info**
Trying it in Google Colab TPU/TPU-GPU/CPU

**Comment by sravan1320** [comment]
Please provide clear example to use in local environment, like which models we have to download if we don't have internet access..

**Comment by cragwolfe** [comment]
hi @sravan1320 , can you provide the version of unstructured you have installed, and provide the file that you are testing with, Bunge_2022.pdf?

**Comment by sravan1320** [comment]
Hey @cragwolfe , thanks for quick reply. Please find below

![image](https://github.com/Unstructured-IO/unstructured/assets/55118375/aebacf45-4f9a-4b3a-900c-87ddd0e42331)

[Bunge_2022.pdf](https://github.com/Unstructured-IO/unstructured/files/13751792/Bunge_2022.pdf)

**Comment by cragwolfe** [comment]
CC @christinestraub

**Comment by christinestraub** [comment]
Hi @sravan1320, Can you also provide the version of `unstructured-inference` you have installed?

I tested `partition_pdf()` on the shared doc and didn't get the error.

```
elements = partition_pdf(filename="Bunge_2022.pdf", infer_table_structure=True, extract_images_in_pdf=False, url=None)
```

Environment Info
```
unstructured==0.11.6
unstructured-inference==0.7.18
unstructured.pytesseract==0.3.12
pdf2image==1.16.3
pdfminer.six==20221105
pikepdf==8.8.0
pypdf==3.17.1
```

You can also refer to this issue - https://github.com/Unstructured-IO/unstructured/issues/2197

**Comment by sravan1320** [comment]
Hi Hope it will work now, but can you please provide deeper details... while we are running this 

"**elements = partition_pdf(filename="Bunge_2022.pdf", infer_table_structure=True, extract_images_in_pdf=True, url=None)**".

which all models will download from internet.

Currently i am facing re-connecting issue in google colab. If you provide details, i will download into locally and try to verify it.

Please provide code snippet how to take reference from local as well. it would really helpful :)

**Comment by christinestraub** [comment]
Closing as resolved. @sravan1320 feel free to reopen if you're still having trouble.
