### ISSUE TITLE
ISD dictionaries are not JSON serializable if the filename has a POSIX path

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#232]
Currently if a filename has a path like "../../my-file.txt", the ISD dictionary is not JSON serializable. The goal of this issue is to only include the filename and not the full path in the metadata so that the ISD dictionary is JSON serializable.

**Comment by firedragonironfist** [comment]
Hi MthwRobinson, I'm a new contributor to this project and I'm currently working on this issue. I'm a bit stuck and not sure how to proceed to resolve the issue. Could you please provide me with some guidance on how to move forward? Any help would be greatly appreciated!

**Comment by MthwRobinson** [comment]
Thanks @firedragonironfist for your interest in contributing! #233 will close this issue, but maybe checkout #228 if you'd like to make a first contribution. Just make sure to assign the issue to yourself so we know you're working on it.

**Comment by firedragonironfist** [comment]
Thank you so much I will check it out

**Comment by MthwRobinson** [comment]
Oh nevermind that was you! I think I misread the username. Just assigned you #228 .
