### ISSUE TITLE
bug: some extracted images have content clipped

### ISSUE THREAD

**Issue by ryannikolaidis** [Unstructured-IO/unstructured#2320]
**Describe the bug**
In some cases images extracted from a pdf are clipped (cutting off image content)

**To Reproduce**
Process this pdf with `extract_images_in_pdf=True`
[LM339-D.PDF](https://github.com/Unstructured-IO/unstructured/files/13781511/LM339-D.PDF)

**Expected behavior**
Extracted images should contain complete image content.

**Screenshots**
Some of the images in here will have clipped content. e.g.
![figure-2-4](https://github.com/Unstructured-IO/unstructured/assets/1208590/c995e720-cd6a-4fb6-b70b-ce5fdad0ce45)

**Comment by nidhi-kulhari** [comment]
did the problem get solved? cause i tried doing what you guys said and it's still clipping off some content
