### ISSUE TITLE
bug/Unable to parse xlsx files

### ISSUE THREAD

**Issue by sundaraa-deshaw** [Unstructured-IO/unstructured#2326]
**Describe the bug**
Using the unstructured library (via Langchain) and directly to read an excel file (.xlsx). Fails during the partition step.

**To Reproduce**
from unstructured.partition.xlsx import partition_xlsx
partition_xlsx("./new1.xlsx")

**Expected behavior**
Expected the file to be partitioned.

**Screenshots**
This is the file content. It is a simple xlsx file.
![image](https://github.com/Unstructured-IO/unstructured/assets/151128501/602fe4bf-6daf-423c-9f9c-4510e0ccad5c)

**Environment Info**
Am using unstructured-0.11.6, which is a transitive dependency from langchain.

**Additional context**
Error trace:
![image](https://github.com/Unstructured-IO/unstructured/assets/151128501/8a517d97-f394-4614-809d-749df8b9efdf)

**Comment by lfc07** [comment]
the same problem for me.

**Comment by scanny** [comment]
Closing as inactive and stale. Let us know if you're still having a problem and we'll take another look.
