### ISSUE TITLE
bug/html_table_extraction

### ISSUE THREAD

**Issue by logan-markewich** [Unstructured-IO/unstructured#2339]
**Describe the bug**
HTML partitioning performance appears to have degraded, specifically for tables.

In llama-index, we have tool to extract tables from HTML documents using unstructured. We remove any tables that don't have a consistent number of columns.

In v0.10.30, this works fine. But the same code using v0.11.X ends up filtering out all tables, since every table does not meet the filtering requirements above. To me, this feels like table extraction got much noisier?

You can see our filtering code here
https://github.com/run-llama/llama_index/blob/1736097a5902ef39fd289a645ad9765058f1c8b3/llama_index/node_parser/relational/unstructured_element.py#L99

**To Reproduce**
You can install llama-index and unstructured, and run this notebook. https://docs.llamaindex.ai/en/stable/examples/query_engine/sec_tables/tesla_10q_table.html#extract-elements

But more specifically, I've narrowed it down to loading the HTML and running `partition_html(text=text)` and seeing that the extracted tables are different.

**Expected behavior**
Uniform tables extracted.

**Comment by MthwRobinson** [comment]
@logan-markewich - Are you able to check out the branch from #2345 and verify that it resolves your issue?

**Comment by MthwRobinson** [comment]
cc @scanny

**Comment by logan-markewich** [comment]
@MthwRobinson yea this seems to fix the issue! I think less tables are found before, but they seem to be higher quality extractions now which is fine by me

**Comment by scanny** [comment]
@logan-markewich The reason your table count may be lower is that tables that are empty of text are no longer emitted to the element stream. I believe the 10k documents contain a couple tables like that. Such tables could contain images or other non-text content so might have a purpose in the original document, but cannot contribute to the extracted text.

**Comment by scanny** [comment]
Note that a `.text_as_html` table will still be non-uniform (have varying cell-count by row) when there are merged cells in the table (which makes the original table non-uniform).

**Comment by logan-markewich** [comment]
yea that makes sense! (merged cell tables are expected, and hard to process into a dataframe)
