### ISSUE TITLE
https://unstructured-io.github.io/unstructured/examples.html document struture is wrong

### ISSUE THREAD

**Issue by qingtian1771** [Unstructured-IO/unstructured#2343]
**Describe the bug**
https://unstructured-io.github.io/unstructured/examples.html document struture is wrong
**To Reproduce**
you can open the link to check.
https://unstructured-io.github.io/unstructured/examples.html

**Expected behavior**
the document struture should be OK

**Comment by MthwRobinson** [comment]
Closing, docs have moved to https://docs.unstructured.io
