### ISSUE TITLE
bug/`partition_pdf` produces TypeError: got an unexpected keyword argument 'pdf_objects'

### ISSUE THREAD

**Issue by ron-unstructured** [Unstructured-IO/unstructured#2354]
**Describe the bug**
Running the code below produces `TypeError: PageLayout.get_elements_from_layout() got an unexpected keyword argument 'pdf_objects'`

**To Reproduce**
```
from unstructured.partition.pdf import partition_pdf

elements = partition_pdf(pdf_filename, 
                         strategy="hi_res",
                         hi_res_model_name="chipper",
                         infer_table_structure=True,
                        )
```

**Expected behavior**
`partition_pdf` should return Unstructured Elements.

**Screenshots**
![Screenshot 2024-01-04 at 8 50 40 PM](https://github.com/Unstructured-IO/unstructured/assets/138828701/77819b24-5251-4c12-9b7f-9707d3ab7089)

**Environment Info**
- OS version:  macOS-14.2.1-arm64-arm-64bit
- Python version:  3.10.12
- unstructured version:  0.11.7
- unstructured-inference version:  0.7.18
- pytesseract version:  0.3.10
- Torch version:  2.1.1
- Detectron2 is not installed
- PaddleOCR is not installed
- Libmagic version:  ==> libmagic: stable 5.45 (bottled)
- LibreOffice version:  ==> libreoffice: 7.6.4 

**Additional context**
Tried different PDF and hi_res_model_name, but keep getting the same error.

**Comment by christinestraub** [comment]
Hi @ron-unstructured, can you please provide the file that you are testing with, `alphabet_10k_20230203_abbrev.pdf`?

**Comment by ron-unstructured** [comment]
Hi @christinestraub thanks for checking this issue. Here's the PDF file that I tried to parse.
I'll try to run it on a different environment as well.

[alphabet_10K_20230203_abbrev.pdf](https://github.com/Unstructured-IO/unstructured/files/13844476/alphabet_10K_20230203_abbrev.pdf)

**Comment by ron-unstructured** [comment]
Hi @christinestraub  it looks like my notebook may be corrupted. I no longer get this error when I create a new notebook. Therefore, I'll close this issue for now. Thanks.

**Comment by AntoninLeroy** [comment]
I have the same issue. I tried to do it in a new notebook like mentioned but it does the same error.

**Comment by ron-unstructured** [comment]
Hi @AntoninLeroy Thanks for reporting the issue. I'm reopening this ticket.

**Comment by christinestraub** [comment]
> I have the same issue. I tried to do it in a new notebook like mentioned but it does the same error.

Hi @AntoninLeroy, can you provide the versions of `unstructured` and `unstructured-inference` you have installed, and provide the file that you are testing?

**Comment by AntoninLeroy** [comment]
@christinestraub Hi, sorry for the late reply. The issue was indeed that because my machine has no access to the internet the installation of the package has not been correctly done. I manually re-installed all the .whl in the right order (+ unstructured-inference) and the issue stopped.
