### ISSUE TITLE
bug/no unique ids in partition

### ISSUE THREAD

**Issue by stdweird** [Unstructured-IO/unstructured#2356]
release 0.11.8

```
from unstructured.partition.auto import partition
source = 'https://helpdesk.ugent.be/account/wachtwoord.php'
part = partition(url=source) 
```
gives
```
>>> pids=[p.id for p in part]
>>> pidsm={p.id:1 for p in part}
>>> len(pidsm)
59
>>> len(pids)
70
```
so the ids are not unique. 

this is annoying because i don't know what the parent ids in the metadata refer to

**Comment by stdweird** [comment]
in slack it was mentioned as a feature https://unstructured-io.github.io/unstructured/introduction/getting_started.html#unique-element-ids

but one might reconsider some warning or at least updating the docs if someone relies on `parent_id` without unique ids

feel free to close this without any further changes

**Comment by beyer-martin** [comment]
How are we supposed to use the parent ids with this in mind? I am trying to build a tree of elements

**Comment by stdweird** [comment]
@beyer-martin monkeypatch it until fixed
```
# Fix uuid crap: just force uuid, don't use the unique_element_ids=True
#part = partition(url=source, unique_element_ids=True)
# patch element_id = str(uuid.uuid4()) on L756 in documents/elements.py
from unstructured.documents.elements import Text
import uuid
orig_init = Text.__init__
def new_init(self, *args, **kwargs):
    orig_init(self, *args, **kwargs)
    self.id = str(uuid.uuid4())
Text.__init__ = new_init
```
