### ISSUE TITLE
bug/Import packages fail

### ISSUE THREAD

**Issue by Pablongo24** [Unstructured-IO/unstructured#2358]
**Describe the bug**
Running some functions after a clean pip install results in many ModuleNotFoundErrors, e.g. pdfminer or pdf2image

**To Reproduce**
from unstructured.nlp.partition import is_possible_narrative_text

**Expected behavior**
I expect the code to run with no ModuleNotFoundErrors. These modules should be installed along with the unstructured package.

**Comment by MthwRobinson** [comment]
`pip install "unstructured[pdf]"` will install the missing modules
