### ISSUE TITLE
bug/parent_id is still a hash with unique_element_ids=True

### ISSUE THREAD

**Issue by stdweird** [Unstructured-IO/unstructured#2359]
with 0.11.8

```
>> part = partition(url=source, unique_element_ids=True)
>> part[5].id
'80aeff2c-f406-470e-b82e-512723f1bdd3'
>>> part[5].metadata.to_dict()['parent_id']
'11364a4c8f174651156e7203a53f4c1a'
```

it makes the whole parent_id unusable

**Comment by stdweird** [comment]
i had a quick look at the code, i think the easiest fix would be to add a `_parent` to the metadata class, and make a `parent_id` property to return `_parent.id`.
and then in `unstructured/partition/common` set `_parent` to `topelement`

**Comment by stdweird** [comment]
for now i just swapped the has code on https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/documents/elements.py#L755 to the uuid code of the next elif block, and ofcourse disabled the `unique_element_ids=True` (since that would regenerate the id)

being able to toggle this behaviour is a quick hack ofcourse

**Comment by scanny** [comment]
Closing, fixed months back.
