### ISSUE TITLE
bug/narrative-text-inconsistency-colon

### ISSUE THREAD

**Issue by ahmetmeleq** [Unstructured-IO/unstructured#2373]
**Describe the bug**
There is an inconsistency on element type assignment for narrative texts in certain cases. 

For the case we have here, nltk seems to be detecting `Delete` as a verb while not detecting `Enter` as a verb, causing inconsistency, and then categorizing `Delete saved passwords:` as narrative text while not categorizing `Enter your new password:` as narrative text.

For more details: https://unstructuredw-kbe4326.slack.com/archives/C044N0YV08G/p1704734698370019?thread_ts=1704724859.242509&cid=C044N0YV08G

**To Reproduce**
```
>>> is_possible_narrative_text('Enter your new password:')
False
>>> is_possible_narrative_text('Delete saved passwords:')
True
```

**Expected behavior**
Whether narrative or not, consistency between these two examples presented.

**Suggested approach:** If there is a colon `:` at the end of a one-sentence element, categorize it as a `Title`, bypassing narrative text categorization.

**Comment by scanny** [comment]
Closing as will not fix.
