### ISSUE TITLE
Create a data connector for Google Drive

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#244]
Create a data connector that pulls documents from Google Drive, stores them locally (at least temporarily for processing), and runs them through [unstructured.partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py).

See [Adding Data Connectors](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#adding-data-connectors) for details on how to get started. Make sure to include a link to this issue when submitting a PR.

**Definition of Done**

* The [checklist](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#the-checklist) has been completed.
* The connector is able to process a single document.
* The connector is able to process all documents in a Google Drive folder, recursively.
* For now, it is OK to process only doc types that [unstructured.partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py) is capable of processing. Google Drive documents should be converted to PDF or Word Doc for processing (unless there is a better way).
* Bonus points: the ability to filter by document type.

**Comment by HAKSOAT** [comment]
Hi @cragwolfe I'd like to give this a shot.

**Comment by cragwolfe** [comment]
@HAKSOAT , sounds good, please go ahead! Thanks for mentioning it. :)

**Comment by alvarobartt** [comment]
Hi @cragwolfe what about creating a separate issue to create a connector for Google Cloud Storage (GCS) too? If so I'd like to contribute and tackle that 👍🏻

**Comment by cragwolfe** [comment]
Good idea, added https://github.com/Unstructured-IO/unstructured/issues/301 .
