### ISSUE TITLE
Multiprocessing when partitioning PDFs

### ISSUE THREAD

**Issue by thomascerbelaud** [Unstructured-IO/unstructured#2440]
Hello,

Thanks for this amazing package!

I am dealing with large PDFs and would like to speed things up by parallelizing each page partitioning. Is it in the current short-term roadmap? Is there an easy workaround?

Thanks!

**Comment by awalker4** [comment]
Hi there - we don't currently have plans for parallelism within the library itself. However, we do recommend that you send large pdfs in chunks when working with the api. Here's some [example code](https://gist.github.com/awalker4/38a69938442157f1d657abfecedfd92a), and our python client now has [an option for this](https://github.com/Unstructured-IO/unstructured-python-client?tab=readme-ov-file#splitting-pdf-by-pages) as well.
