### ISSUE TITLE
bug/`partition()` treats double quote enclosed text file as JSON and errors

### ISSUE THREAD

**Issue by chandrasekharan98** [Unstructured-IO/unstructured#2444]
**Describe the bug**
While trying to call `partition()` on a text file which only has text enclosed in double quotes it recognizes it as JSON and fails with the following error
`Detected a JSON file that does not conform to the Unstructured schema. partition_json currently only processes serialized Unstructured output`

**Version used**
`unstructured[all-docs]==0.10.10`

**To Reproduce**
```python
import io
from unstructured.partition.auto import partition
    # `file` passed has no extension though
    def extract_text(file: str) -> str:
        """Extract text from file."""
        try:
            with open(file, mode="rb") as input_file_obj:
                bytes_io = io.BytesIO(input_file_obj.read())
                elements = partition(file=bytes_io)
        except Exception as e:
            print(f"Error partitioning file: {e}")
        text = "\n\n".join([str(el) for el in elements])
        return text

```

**Expected behavior**
The file has to be partitioned and we should be able to extract the text contents from it

**Additional context**
The following contents in a file with no extension can help reproduce the issue.
It fails with the mentioned error in this case
```
"Sample input file that gets mistaken as JSON"
```
However this gets partitioned fine (notice the absence of double-quotes on the text)
```
Sample input file that gets partitioned correctly
```
I also tried the below which works too - if its of any help
```
"Sample input file that also gets partitioned" correctly
```

Thanks in advance :)

**Comment by MthwRobinson** [comment]
Hi @chandrasekharan98 - will take a look this week. Thanks for reporting!
