### ISSUE TITLE
bug/PDF elements out of order

### ISSUE THREAD

**Issue by ron-unstructured** [Unstructured-IO/unstructured#2448]
**Describe the bug**
There is a discrepancy in the element order when partitioning a PDF. From the screenshots, the blue and red circles intended to highlight text are switched in position in the output image, compared to their correct placement in the original PDF.

**To Reproduce**
Run PDF partition using Python SDK with `auto`, `fast`, and `hi_res` strategy.

**Expected behavior**
The expected behavior is that the element order in the output image should match the placement and color coding (blue and red circles) as they are in the original PDF document.

**Screenshots**
![PDF](https://github.com/Unstructured-IO/unstructured/assets/138828701/e93bb82c-4129-40cb-97aa-18a7721baf2d)
![partition](https://github.com/Unstructured-IO/unstructured/assets/138828701/eb359838-1eb1-4a97-aa55-fb3df19fb19e)

**Environment Info**
OS version:  macOS-14.2.1-arm64-arm-64bit
Python version:  3.10.12
unstructured version:  0.12.1.dev11
unstructured-inference version:  0.7.18
pytesseract version:  0.3.10
Torch version:  2.1.1
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version:  ==> libmagic: stable 5.45 (bottled)
LibreOffice version:  ==> libreoffice: 7.6.4

**Additional context**
similar issue: https://github.com/Unstructured-IO/unstructured/issues/2208

**Comment by cragwolfe** [comment]
CC @christinestraub

**Comment by MthwRobinson** [comment]
@christinestraub - Would your recent reading order updates have fixed this?

**Comment by christinestraub** [comment]
@ron-unstructured Can you please share the PDF document used to reproduce this bug?

**Comment by ron-unstructured** [comment]
Hi @christinestraub please see the attachment for the PDF file
source: https://www.researchgate.net/publication/335361817_Software_Engineering_for_Machine_Learning_A_Case_Study
[Software_Engineering_for_ML.pdf](https://github.com/Unstructured-IO/unstructured/files/15408857/Software_Engineering_for_ML.pdf)

**Comment by koernerfelicia** [comment]
Hi @christinestraub do you have any updates on this? I am still seeing this bug on version 0.15.12. This pdf produces this output (note the wrong order of the titles):
[model_y_manual_de.pdf](https://github.com/user-attachments/files/17096112/model_y_manual_de.pdf)
<img width="432" alt="Screenshot 2024-09-23 at 12 28 56" src="https://github.com/user-attachments/assets/976b2cc9-76cd-407a-8f43-2cae6970edb7">


```Aufbewahrung im Innenraum
<=> T
Mittelkonsole
Kleiderbügel
Neben einem RFID-Transmitter, der Schlüssel und Schlüsselkarten liest (siehe Schlüsselkarte), beinhaltet die Mittelkonsole Getränkehalter, zwei Staufächer und ein drahtloses Telefonladegerät (siehe Aufbewahrung im Innenraum).
Model Y verfügt über einen Kleiderbügel auf jeder Fahrzeugseite in der zweiten Reihe neben der Leseleuchte. Drücken Sie gegen den Kleiderbügel, um ihn zu lösen. Drücken Sie erneut dagegen, um ihn einzufahren.
Um das Hauptfach zu öffnen, ziehen Sie die Abdeckung nach oben. Öffnen Sie das vordere Staufach, indem Sie die Abdeckung nach vorne schieben.

Hintere Konsole
Handschuhfach
Model Y verfügt über eine hintere Konsole, die in die Mitte der Rückenlehne in der zweiten Reihe integriert ist. Ziehen Sie die Konsole nach unten, um Zugang zu den hinteren Getränkehaltern zu erhalten, oder verwenden Sie sie als Armlehne.

Um das Handschuhfach zu öffnen, berühren Sie Fahrzeug > Handschuhfach. Das Handschuhfach öffnet sich automatisch, und die zugehörige Beleuchtung schaltet sich ein.

Um das Handschuhfach zu schließen, drücken Sie es nach oben, bis es in seine geschlossene Position einrastet.
Staufächer
37```

**Comment by scanny** [comment]
Closing as inactive.
