### ISSUE TITLE
bug/.docx figures are ignored by partition

### ISSUE THREAD

**Issue by Krogsager** [Unstructured-IO/unstructured#2477]
**Describe the bug**
The text inside shapes is not extracted using unstructured.partition. The shapes are ignored altogether.

**To Reproduce**
In Microsoft Word, create a shape and enter some text into it.
![image](https://github.com/Unstructured-IO/unstructured/assets/27994384/073d24b5-45e9-4b80-85e2-9731616b13d4)

**Expected behavior**
The text inside the shape shoud be returned by 
```python
from unstructured.partition.auto import partition
output = partition("path-to-my-file.docx")
print(output)
# something like  >>>{"Title": "here"}
```

**Environment Info**
N/A

**Additional context**
For example Word2md extracts text in shapes per default
https://github.com/benbalter/word-to-markdown

**Comment by ds-filipknefel** [comment]
We've merged a feature which detects text inside inline shapes (shapes anchored **as character**) and includes them into paragraph's text.
![image](https://github.com/Unstructured-IO/unstructured/assets/158048836/1000f933-a3bb-4f03-95d2-10daabb6c7a1)
e.g. in such document you'd get two elements with the following text respectively:
- "Paragraph with single \<inline-image\> within."
- "Paragraph with \<inline-image1\> and \<inline-image2\> within."

This PR doesn't address floating shapes, for now they're not supported. Not detecting text inside floating shapes should be considered a non-existing feature rather then a bug and could be discussed in under an `enhacement` issue.

**Comment by ds-filipknefel** [comment]
We consider this addition a new feature rather then a bug fix, I've updated the title and tags to reflect this.
