### ISSUE TITLE
PDF links are not recognised and not added to the metadata

### ISSUE THREAD

**Issue by MiXiBo** [Unstructured-IO/unstructured#2482]
**Describe the bug**
When we try to load a PDF file with links that was generated by Word then the links are not recognised. In comparison when we load the unstructured sample PDF the links are extracted. When we use a tool such as pdfx we can see that the links are in the document.

**To Reproduce**
Load attached PDF file with unstructured 

**Expected behavior**
Extract the link 'Klick Here' with link to 'https://ebay.com'

**Screenshots**

![Screenshot 2024-01-31 at 11 44 38](https://github.com/Unstructured-IO/unstructured/assets/34360898/43facdb1-5ad4-45f3-997c-1cbeb914a14e)

![Screenshot 2024-01-31 at 11 44 48](https://github.com/Unstructured-IO/unstructured/assets/34360898/e94a29af-757d-4f83-82ec-5547b246a072)

[pdf-link.pdf](https://github.com/Unstructured-IO/unstructured/files/14110595/pdf-link.pdf)

[embedded-link.pdf](https://github.com/Unstructured-IO/unstructured/files/14110573/embedded-link.pdf)

![Screenshot 2024-01-31 at 11 47 23](https://github.com/Unstructured-IO/unstructured/assets/34360898/44a6dac1-148a-44b0-bf0a-b44b6521a205)

We do use unstructured version 0.12.3

**Comment by MiXiBo** [comment]
We can read the links. We had to set the threshold to a lower value:

https://github.com/Unstructured-IO/unstructured/blob/dd6576c603da10f42b39a71d13aef7fcc8b99528/unstructured/partition/pdf.py#L1179

**Comment by sjoerd222888** [comment]
What would be potential side effects of setting a lower threshold value?

**Comment by sjoerd222888** [comment]
Currently it seems this cannot be passed as a parameter, but would be nice to allow to configure this from the outside if needed?

**Comment by MiXiBo** [comment]
I have refactored 'threshold' to 'annotation_threshold' and made it an optional parameter in '_process_pdfminer_pages' by keeping the default at 0.9.

With that we do have the option to make it configurable. It would be very helpful if @christinestraub you could merge that. We do have automated deployments which makes it complicated and cumbersome to workaround.

https://github.com/Unstructured-IO/unstructured/pull/2537


Thanks!

**Comment by sjoerd222888** [comment]
Is there any interest to address this? I know sometimes open-source projects are like this. Dead slow and nobody cares.
Do we need to consider forking or move to another library?

There is a bug, you labeled it as a bug, so you I assume you acknowledge there is a problem. There is a MR, the change is damn simple, you only need a single minute to read it.

Would be great if somebody can comment somehow. Otherwise we can assume while it's a great library it's not really maintained. If you want to an open source library accepting community MR please have capacity to review them!

"We don't care" would also already be a comment.

**Comment by christinestraub** [comment]
Hi @MiXiBo @sjoerd222888 thanks for your contribution to address this issue. I have been involved in working on urgent tasks . I have time to look at your PRs now and will update you as soon as possible.

**Comment by christinestraub** [comment]
addressed by PR [#2537](https://github.com/Unstructured-IO/unstructured/pull/2537).
