### ISSUE TITLE
email partitioner / partition_eml .ps7 mime type support

### ISSUE THREAD

**Issue by jeanbapt** [Unstructured-IO/unstructured#2489]
**Is your feature request related to a problem? Please describe.**
When using an eml file with attachment, partition_eml, I get an .UNK filetype error. 
After discussion with unstructured, it seems to require *.ps7 mime attachment* support.

I use Langchain UnstructuredEmailLoader, 
I tried using directly unstructured.io partition_eml, 
got the same result. 

**Describe the solution you'd like**
Need this to work , not producing the .UNK filetype error and reading the attachment. 

```python
elements = partition_email(
        filename=eml_file, 
        process_attachments=True, 
        attachment_partitioner=partition)
    
    print(elements)
```

**Describe alternatives you've considered**
I used python *email* to test if I could read my eml ok and yes. 

**Additional context**

```code

Error msg : 
Une exception s'est produite : ValueError
Invalid file /var/folders/2v/f76959fd4h320hm6wlk20p3w0000gn/T/tmp5ivv6vqw/smime.p7s. The FileType.UNK file type is not supported in partition.
  File "/GitHub/simple-doc/document-classifier/main.py", line 52, in main
    doc = loader.load()
  File "/GitHub/simple-doc/document-classifier/main.py", line 139, in <module>
    main()
ValueError: Invalid file /var/folders/2v/f76959fd4h320hm6wlk20p3w0000gn/T/tmp5ivv6vqw/smime.p7s. The FileType.UNK file type is not supported in partition.

```

**Comment by jeanbapt** [comment]
More info / test : 
When the eml file has an attachement, unstructured won't return even the body and header informations , just []. 
When I try a file with no attachement, with the exact same instruction, the body and header content is returned. 

- Suggestion:  if unstructured cannot process the .UNK filletype , raise exception and carry on returning the rest.

**Comment by MthwRobinson** [comment]
@jeanbapt - Do you need to extract content from the `.p7s` file, or do you just want `partition_email` to run without hitting the exception in cases where there's a `.p7s` attachment?

**Comment by jeanbapt** [comment]
Ideally I'd prefer to get the content of the attachement extracted so that I can process it. 

I understand this could be challenging but if is can just take de header and body info , Ok : that would be useful for sure instead of returning an empty array. 

Thank you!

**Comment by MthwRobinson** [comment]
Sounds good! I think we ought to be able to pull the content out of those. Will take a look at this over the next few days.
