### ISSUE TITLE
bug/ list index out of range

### ISSUE THREAD

**Issue by gaofengucsd** [Unstructured-IO/unstructured#2490]
**Describe the bug**
File ~/.local/lib/python3.11/site-packages/unstructured_inference/models/tables.py:99, in UnstructuredTableTransformerModel.run_prediction(self, x, pad_for_structure_detection, ocr_tokens, result_format)
     97 if ocr_tokens is None:
     98     raise ValueError("Cannot predict table structure with no OCR tokens")
---> 99 prediction = recognize(outputs_structure, x, tokens=ocr_tokens)[0]
    100 if result_format == "html":
    101     # Convert cells to HTML
    102     prediction = cells_to_html(prediction) or ""

IndexError: list index out of range

when doing  partition_pdf_or_image   with extract image = True ,infer_table_structure = True
looks like it will have error when OCR can't recognize 

**Expected behavior**

**Screenshots**

![image](https://github.com/Unstructured-IO/unstructured/assets/57117747/1bcb0a3b-aa67-4f15-8027-90d7c2f1a19c)
**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

additional error 
--> 206 return partition_pdf_or_image(
    207     filename=filename,
    208     file=file,
    209     include_page_breaks=include_page_breaks,
    210     strategy=strategy,
    211     infer_table_structure=infer_table_structure,
    212     languages=languages,
    213     metadata_last_modified=metadata_last_modified,
    214     hi_res_model_name=hi_res_model_name,
    215     extract_images_in_pdf=extract_images_in_pdf,
    216     extract_image_block_types=extract_image_block_types,
    217     extract_image_block_output_dir=extract_image_block_output_dir,
    218     extract_image_block_to_payload=extract_image_block_to_payload,
    219     **kwargs,
    220 )

File ~/.local/lib/python3.11/site-packages/unstructured/partition/pdf.py:537, in partition_pdf_or_image(filename, file, is_image, include_page_breaks, strategy, infer_table_structure, ocr_languages, languages, metadata_last_modified, hi_res_model_name, extract_images_in_pdf, extract_image_block_types, extract_image_block_output_dir, extract_image_block_to_payload, **kwargs)
    535     with warnings.catch_warnings():
    536         warnings.simplefilter("ignore")
--> 537         elements = _partition_pdf_or_image_local(
    538             filename=filename,
    539             file=spooled_to_bytes_io_if_needed(file),
    540             is_image=is_image,
    541             infer_table_structure=infer_table_structure,
    542             include_page_breaks=include_page_breaks,
    543             languages=languages,
    544             metadata_last_modified=metadata_last_modified or last_modification_date,
    545             hi_res_model_name=hi_res_model_name,
    546             pdf_text_extractable=pdf_text_extractable,
    547             extract_images_in_pdf=extract_images_in_pdf,
    548             extract_image_block_types=extract_image_block_types,
    549             extract_image_block_output_dir=extract_image_block_output_dir,
    550             extract_image_block_to_payload=extract_image_block_to_payload,
    551             **kwargs,
    552         )
    553         out_elements = _process_uncategorized_text_elements(elements)
    555 elif strategy == PartitionStrategy.FAST:

File ~/.local/lib/python3.11/site-packages/unstructured/utils.py:214, in requires_dependencies.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    205 if len(missing_deps) > 0:
    206     raise ImportError(
    207         f"Following dependencies are missing: {', '.join(missing_deps)}. "
    208         + (
   (...)
    212         ),
    213     )
--> 214 return func(*args, **kwargs)

File ~/.local/lib/python3.11/site-packages/unstructured/partition/pdf.py:377, in _partition_pdf_or_image_local(filename, file, is_image, infer_table_structure, include_page_breaks, languages, ocr_mode, model_name, hi_res_model_name, pdf_image_dpi, metadata_last_modified, pdf_text_extractable, extract_images_in_pdf, extract_image_block_types, extract_image_block_output_dir, extract_image_block_to_payload, analysis, analyzed_image_output_dir_path, **kwargs)
    375         if hasattr(file, "seek"):
    376             file.seek(0)
--> 377         final_document_layout = process_data_with_ocr(
    378             file,
    379             merged_document_layout,
    380             is_image=is_image,
    381             infer_table_structure=infer_table_structure,
    382             ocr_languages=ocr_languages,
    383             ocr_mode=ocr_mode,
    384             pdf_image_dpi=pdf_image_dpi,
    385         )
    387 # NOTE(alan): starting with v2, chipper sorts the elements itself.
    388 if hi_res_model_name == "chipper":

File ~/.local/lib/python3.11/site-packages/unstructured/partition/pdf_image/ocr.py:85, in process_data_with_ocr(data, out_layout, is_image, infer_table_structure, ocr_languages, ocr_mode, pdf_image_dpi)
     83 tmp_file.write(data.read() if hasattr(data, "read") else data)
     84 tmp_file.flush()
---> 85 merged_layouts = process_file_with_ocr(
     86     filename=tmp_file.name,
     87     out_layout=out_layout,
     88     is_image=is_image,
     89     infer_table_structure=infer_table_structure,
     90     ocr_languages=ocr_languages,
     91     ocr_mode=ocr_mode,
     92     pdf_image_dpi=pdf_image_dpi,
     93 )
     94 return merged_layouts

File ~/.local/lib/python3.11/site-packages/unstructured/partition/pdf_image/ocr.py:171, in process_file_with_ocr(filename, out_layout, is_image, infer_table_structure, ocr_languages, ocr_mode, pdf_image_dpi)
    169 except Exception as e:
    170     if os.path.isdir(filename) or os.path.isfile(filename):
--> 171         raise e
    172     else:
    173         raise FileNotFoundError(f'File "{filename}" not found!') from e

File ~/.local/lib/python3.11/site-packages/unstructured/partition/pdf_image/ocr.py:160, in process_file_with_ocr(filename, out_layout, is_image, infer_table_structure, ocr_languages, ocr_mode, pdf_image_dpi)
    158 for i, image_path in enumerate(image_paths):
    159     with PILImage.open(image_path) as image:
--> 160         merged_page_layout = supplement_page_layout_with_ocr(
    161             out_layout.pages[i],
    162             image,
    163             infer_table_structure=infer_table_structure,
    164             ocr_languages=ocr_languages,
    165             ocr_mode=ocr_mode,
    166         )
    167         merged_page_layouts.append(merged_page_layout)
    168 return DocumentLayout.from_pages(merged_page_layouts)

File ~/.local/lib/python3.11/site-packages/unstructured/partition/pdf_image/ocr.py:237, in supplement_page_layout_with_ocr(page_layout, image, infer_table_structure, ocr_languages, ocr_mode)
    234     if tables.tables_agent is None:
    235         raise RuntimeError("Unable to load table extraction agent.")
--> 237     page_layout.elements[:] = supplement_element_with_table_extraction(
    238         elements=cast(List[LayoutElement], page_layout.elements),
    239         image=image,
    240         tables_agent=tables.tables_agent,
    241         ocr_languages=ocr_languages,
    242         ocr_agent=ocr_agent,
    243     )
    245 return page_layout

File ~/.local/lib/python3.11/site-packages/unstructured/partition/pdf_image/ocr.py:274, in supplement_element_with_table_extraction(elements, image, tables_agent, ocr_languages, ocr_agent)
    263         cropped_image = image.crop(
    264             (
    265                 padded_element.bbox.x1,
   (...)
    269             ),
    270         )
    271         table_tokens = get_table_tokens(
    272             image=cropped_image, ocr_languages=ocr_languages, ocr_agent=ocr_agent
    273         )
--> 274         element.text_as_html = tables_agent.predict(cropped_image, ocr_tokens=table_tokens)
    275 return elements

File ~/.local/lib/python3.11/site-packages/unstructured_inference/models/tables.py:47, in UnstructuredTableTransformerModel.predict(self, x, ocr_tokens)
     31 """Predict table structure deferring to run_prediction with ocr tokens
     32 
     33 Note:
   (...)
     44 FIXME: refactor token data into a dataclass so we have clear expectations of the fields
     45 """
     46 super().predict(x)
---> 47 return self.run_prediction(x, ocr_tokens=ocr_tokens)

File ~/.local/lib/python3.11/site-packages/unstructured_inference/models/tables.py:99, in UnstructuredTableTransformerModel.run_prediction(self, x, pad_for_structure_detection, ocr_tokens, result_format)
     97 if ocr_tokens is None:
     98     raise ValueError("Cannot predict table structure with no OCR tokens")
---> 99 prediction = recognize(outputs_structure, x, tokens=ocr_tokens)[0]
    100 if result_format == "html":
    101     # Convert cells to HTML
    102     prediction = cells_to_html(prediction) or ""

IndexError: list index out of range

**Comment by MthwRobinson** [comment]
@gaofengucsd - Can you share an example file that we could use to reproduce the error?
