### ISSUE TITLE
bug/syntaxerror with anaconda and python 3.11

### ISSUE THREAD

**Issue by bodlan** [Unstructured-IO/unstructured#2495]
**Describe the bug**
```
.venv/lib/python3.11/site-packages/unstructured/partition/auto.py:7: in <module>
    from unstructured.file_utils.filetype import (
.venv/lib/python3.11/site-packages/unstructured/file_utils/filetype.py:15: in <module>
    from unstructured.file_utils.encoding import detect_file_encoding, format_encoding_str
.venv/lib/python3.11/site-packages/unstructured/file_utils/encoding.py:5: in <module>
    from unstructured.partition.common import convert_to_bytes
.venv/lib/python3.11/site-packages/unstructured/partition/common.py:38: in <module>
    from unstructured.nlp.patterns import ENUMERATED_BULLETS_RE, UNICODE_BULLETS_RE
E     File "/home/bodlan/PycharmProjects/project/.venv/lib/python3.11/site-packages/unstructured/nlp/patterns.py", line 56
E       "\*",  # noqa: W605 NOTE(robinson) - skipping qa because we need the escape for the regex
E       ^^^^
E   SyntaxError: invalid escape sequence '\*'
```
Note: It's only 1 bug, from sequence of syntaxerror bugs there.

**To Reproduce**
### On Ubuntu/Windows:

1. Install anaconda: https://docs.anaconda.com/free/anaconda/install/index.html
2. Create environment: `conda create --name project python=3.11`
3. Activate environment:  `conda activate project`
4. Install dependacies: `pip install unstructured==0.12.3`
5. Make an import `from unstructured.partition.auto import partition as partition_auto`
6. Run the file with python.

**Expected behavior**
Module import without an error

**Comment by MthwRobinson** [comment]
Closing since we don't officially support anaconda

**Comment by scanny** [comment]
Okay, looks like this problem is not specific to anaconda, although it occurring as `SyntaxError` and not `SyntaxWarning` (which does not interrupt execution) may be a setting, perhaps something like this:
```bash
python -W error myprogram.py
# -- OR --
export PYTHONWARNINGS=error
```

In any case they are easy enough to fix so we'll do that. These just need to be made "raw" strings by adding the `r` suffix, like `r"\*"` in this case.
