### ISSUE TITLE
partition_html incorrect encoding

### ISSUE THREAD

**Issue by asai95** [Unstructured-IO/unstructured#250]
**Describe the bug**
`partition_html` function incorrectly handles cyrillic (and probably other non-latin) text.
This happens when an html do not have correct encoding specified in a meta tag.

**To Reproduce**
```
from unstructured.partition.html import partition_html
text = '<html><body><p>Привет</p></body></html>'
parts = partition_html(text=text)
print(parts[0].text)
```
Prints `Ð\x9fÑ\x80Ð¸Ð²ÐµÑ\x82`

**Expected behavior**
```
from unstructured.partition.html import partition_html
text = '<html><body><p>Привет</p></body></html>'
parts = partition_html(text=text)
print(parts[0].text)
```
Prints `Привет`

**Desktop (please complete the following information):**
 - OS: mac
 - Python version: 3.9.9

**Additional context**
As a possible solution, I would suggest to add an ability to provide your own parser to `partition_html` function.
This way we could use `lxml.etree.HTMLParser` with initialized with desired `encoding` argument.

**Comment by MthwRobinson** [comment]
@asai95 - Thanks for opening this issue! We're tracking it and will pick it up as soon as we can.
