### ISSUE TITLE
Vendored work for rs-document

### ISSUE THREAD

**Issue by cam-barts** [Unstructured-IO/unstructured#2501]
Hello! 👋🏽

Not a bug, but I just wanted to be a good citizen and bring awareness to my project https://github.com/cam-barts/rs_document. The reason I'm bringing your awareness to it is because I vendored some of the cleaners in this project in that one. I reimplemented most of them in rust, and I am using this [vendored file](https://github.com/cam-barts/rs_document/blob/main/python/rs_document/post_processors.py) in my tests to ensure that the project is doing what it set out to do, which is speed up some of that cleaning work. You can see the test [here](https://github.com/cam-barts/rs_document/blob/main/python/tests/test_all.py). As far as licensing is concerned, I'd like my project to be MIT, but I know you are Apache 2. I don't intend to use your post processors for anything other than testing, but in any case I'm willing to make any modifications you see fit to adhere to your license requirements, just let me know how you'd like that done.

Additionally, I know not every project wants to take in new dependancies, especially dependancies in another language like rust, but if you'd be interested, I'd also like to offer to create a PR here to bring in my package so speed up part of that pipeline for this project.  The rust rewrite in my testing creates between a 40 and 75x performance improvement when cleaning and splitting large numbers of documents. 

Thank you so much!

**Comment by MthwRobinson** [comment]
Hi @cam-barts ! Appreciate you flagging this. Going to close this for now, but if we make a broader move toward rust in the future we'll certainly revisit.
