### ISSUE TITLE
bug/opencv-python should be `headless` to avoid dependency on Xorg

### ISSUE THREAD

**Issue by tigerinus** [Unstructured-IO/unstructured#2503]
**Describe the bug**

Getting following error when loading PDF files on a container image to be hosted in cloud:

```shell
  ...
  File "/DATA/junk/test2/lib/python3.11/site-packages/unstructured/partition/auto.py", line 81, in <module>
    from unstructured.partition.pdf import partition_pdf
  File "/DATA/junk/test2/lib/python3.11/site-packages/unstructured/partition/pdf.py", line 76, in <module>
    from unstructured.partition.ocr import (
  File "/DATA/junk/test2/lib/python3.11/site-packages/unstructured/partition/ocr.py", line 6, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

However `libGL.so.1` is part of Xorg binaries. We could switch to a full Linux distro to resolve this, but a better option is to have `opencv-python-headless` in dependency requirements instead of `opencv-python`.

**Comment by mhfarahani** [comment]
Having the same issue when importing partition_pdf

`from unstructured.partition.pdf import partition_pdf`

**Comment by adi-kmt** [comment]
Is there a workaround @tigerinus ?

**Comment by micmarty-deepsense** [comment]
@tigerinus, @mhfarahani what base image are you using? I'd like to replicate the described behavior on my side

**Comment by tigerinus** [comment]
> @tigerinus, @mhfarahani what base image are you using? I'd like to replicate the described behavior on my side

any distro that doesn't come with the required binary `libGL.so.1` should be able to reproduce this issue

In our case, it's a highly customized embedded linux (`buildroot` based).

**Comment by micmarty-deepsense** [comment]
As far as I can tell, there's a quite relevant dependency: `layoutparser` which relies on `opencv-python`.
I've seen that there is a similar request to yours: https://github.com/Layout-Parser/layout-parser/issues/170
 
We have two options:
a) we'd need to create a PR in their package, or
b) let them know that it's important/pressuring to introduce the headless version in their repo and wait until it's fixed there

@tigerinus @adi-kmt @mhfarahani 
If you need a workaround now, I'd say you should modify your Dockerfiles in the following way:
``` 
# install unstructured library as usual

# uninstall the full version, install headless
RUN pip uninstall -y opencv-python opencv-contrib-python && pip install opencv-python-headless==4.8.0.76
```
if `opencv-python-headless` is not sufficient, try with `opencv-contrib-python-headless`

Please let me know if that helps 🤝

**Comment by FilippTrigub** [comment]
Facing the same problem. The workaround works, thank you!

**Comment by laurazpm** [comment]
I've tried the workaround but now the error when importing partition_pdf is: ModuleNotFoundError: No module named 'cv2.typing'; 'cv2' is not a package

**Comment by Robs-Git-Hub** [comment]
Hitting the same issue. Is there any news on whether this could be changed to the headless version?

**Comment by MthwRobinson** [comment]
Thanks everyone, we're going to take a look at this.

**Comment by pjaol** [comment]
The workaround works, just make sure that you do your uninstall after you've done your requirements install

```Dockerfile
FROM apache/airflow:2.9.1
USER root
RUN apt-get update 
RUN apt-get install -y build-essential
USER airflow
ADD requirements.txt .
RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt
RUN pip uninstall -y opencv-python opencv-contrib-python && pip install opencv-python-headless==4.8.0.76
```

**Comment by scanny** [comment]
Closing as inactive.

**Comment by skr3178** [comment]
Worked well. 

Got error
 
unstructured ModuleNotFoundError: No module named 'cv2.typing'

`pip uninstall -y opencv-python opencv-contrib-python && pip install opencv-python-headless==4.8.0.76`
> As far as I can tell, there's a quite relevant dependency: `layoutparser` which relies on `opencv-python`. I've seen that there is a similar request to yours: [Layout-Parser/layout-parser#170](https://github.com/Layout-Parser/layout-parser/issues/170)
> 
> We have two options: a) we'd need to create a PR in their package, or b) let them know that it's important/pressuring to introduce the headless version in their repo and wait until it's fixed there
> 
> [@tigerinus](https://github.com/tigerinus) [@adi-kmt](https://github.com/adi-kmt) [@mhfarahani](https://github.com/mhfarahani) If you need a workaround now, I'd say you should modify your Dockerfiles in the following way:
> 
> ```
> # install unstructured library as usual
> 
> # uninstall the full version, install headless
> RUN pip uninstall -y opencv-python opencv-contrib-python && pip install opencv-python-headless==4.8.0.76
> ```
> 
> if `opencv-python-headless` is not sufficient, try with `opencv-contrib-python-headless`
> 
> Please let me know if that helps 🤝
