### ISSUE TITLE
bug/Table Structure Inconsistency

### ISSUE THREAD

**Issue by Plemeur** [Unstructured-IO/unstructured#2505]
**Describe the bug**
Using the partition_pdf or auto partition, different table styles will give different output for the tables, sometimes even separating table elements from the whole table

**To Reproduce**
Can be tested using those two files
[IntroRev9.PDF.pdf](https://github.com/Unstructured-IO/unstructured/files/14159497/IntroRev9.PDF.pdf)
[MoE-LLaVA_ Mixture of Experts for Large Vision-Language Models.pdf](https://github.com/Unstructured-IO/unstructured/files/14159498/MoE-LLaVA_.Mixture.of.Experts.for.Large.Vision-Language.Models.pdf)

**Expected behavior**
I would expect tables to be read in a more "human like" format, i.e row by row like they are for csv at least based on this sample file
[username.csv](https://github.com/Unstructured-IO/unstructured/files/14159555/username.csv)

**Environment Info**
```
OS version:  Linux-6.6.6-76060606-generic-x86_64-with-glibc2.35
Python version:  3.10.12
unstructured version:  0.12.4.dev5
unstructured-inference version:  0.7.23
pytesseract version:  0.3.10
Torch version:  2.1.2
Detectron2 is not installed

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
PaddleOCR is not installed
Libmagic version: file-5.41
magic file from /etc/magic:/usr/share/misc/magic
LibreOffice version:  LibreOffice 7.3.7.2 30(Build:2)
```

**Comment by MthwRobinson** [comment]
Closing, future improvements to the table extraction model will be available through our SaaS API.
