### ISSUE TITLE
bug/by_title chunking strategy doesn't split by title

### ISSUE THREAD

**Issue by willemvdb42** [Unstructured-IO/unstructured#2508]
**Describe the bug**
The `chunk_by_title` function does not actually separate chunks when it encounters a new title, contrary to the [documentation](https://unstructured-io.github.io/unstructured/core/chunking.html#by-title-chunking-strategy).

**To Reproduce**
```python
from unstructured.chunking.title import chunk_by_title
from unstructured.documents.elements import NarrativeText, Title, ElementMetadata

elements = []
elements.append(Title(element_id='0', text='TITLE1', metadata=ElementMetadata()))
elements.append(NarrativeText(element_id='1', text='text', metadata=ElementMetadata()))
elements.append(Title(element_id='2', text='TITLE2', metadata=ElementMetadata()))
elements.append(NarrativeText(element_id='3', text='text', metadata=ElementMetadata()))

chunks = chunk_by_title(elements, max_characters=10000)

for i, chunk in enumerate(chunks):
    print(f"================ chunk {i} ======================")
    print(chunk)
```
The result:

> ================ chunk 0 ======================
> TITLE1
> 
> text
> 
> TITLE2
> 
> text

It did not split by title.

**Expected behavior**
The [documentation](https://unstructured-io.github.io/unstructured/core/chunking.html#by-title-chunking-strategy) states:

> When a `Title` element is encountered, the prior chunk is closed and a new chunk started, even if the `Title` element would fit in the prior chunk.

As such, the expected behaviour for the above example would be to end up with 2 chunks, with the second chunk starting at TITLE2.

**Environment Info**
python 3.10
unstructured 0.12.2

**Comment by scanny** [comment]
@willemvdb42 short version is I think you want to add `combine_text_under_n_chars=0` to your `chunk_by_title()` call.

I believe what you're seeing here is "chunk-combining", controlled by the optional `combine_text_under_n_chars` argument to `chunk_by_title()`. This combines sequential small chunks to maximally fill the specified chunking window (`max_characters`, defaults to `500`). When omitted, the `combine_text_under_n_chars` argument defaults to the same size as `max_characters`, which means it combines sequential chunks whenever possible (they will together fit in the chunking window).

If you never want to combine sections (`Title` is a section heading and introduces a new section), you can set `combine_text_under_n_chars` to `0`.

Some documents, including some spreadsheets and other document formats in certain cases, contain many short phrases in sequence as distinct "paragraphs" that get classified as `Title` elements. These produce "over-chunking" with the `by_title` strategy and this chunk-combining behavior is one remedy for that.

**Comment by scanny** [comment]
Closing as resolved.
