### ISSUE TITLE
No module named 'unstructured.chunking.basic'

### ISSUE THREAD

**Issue by doganaktarr** [Unstructured-IO/unstructured#2518]
Hi everyone, when i try to import chunk_elements same in [Chunking Documentation](https://unstructured-io.github.io/unstructured/core/chunking.html) i get error.

```py
from unstructured.chunking.basic import chunk_elements
```
```terminal
ModuleNotFoundError: No module named 'unstructured.chunking.basic'
```

and my second question is how can i chunk after this step:
```py
loaders = UnstructuredPDFLoader(file_path,
                 strategy="fast",
                 mode="elements",
                 post_processors=[clean_extra_whitespace])
            
loader = loaders.load()
```

**Comment by qued** [comment]
Hi @doganaktarr , what version of Unstructured do you have? That module was added relatively recently, and that error message is expected if you don't have at least version 0.12.1.

**Comment by doganaktarr** [comment]
> Hi @doganaktarr , what version of Unstructured do you have? That module was added relatively recently, and that error message is expected if you don't have at least version 0.12.1.

unstructured==0.11.8
unstructured-client==0.17.0
unstructured-inference==0.7.18
unstructured.pytesseract==0.3.12

**Comment by doganaktarr** [comment]
Hey @qued i couldn't find any example that uses unstructured's chunker and saves the document's to chromadb. Is there any source for that or can you help me for this issue?

**Comment by cragwolfe** [comment]
Hi @doganaktarr , to write to chormadb, you would need to use `unstructured-ingest`. Here is a test script for reference that does just that:

https://github.com/Unstructured-IO/unstructured/blob/main/test_unstructured_ingest/dest/chroma.sh

See also https://unstructured-io.github.io/unstructured/ingest/index.html

**Comment by doganaktarr** [comment]
> Hi @doganaktarr , to write to chormadb, you would need to use `unstructured-ingest`. Here is a test script for reference that does just that:
> 
> https://github.com/Unstructured-IO/unstructured/blob/main/test_unstructured_ingest/dest/chroma.sh
> 
> See also https://unstructured-io.github.io/unstructured/ingest/index.html

Thank you so much @cragwolfe, but this seems harder than I can do and I need to change my current system.

```python
text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap)
            
loaders = UnstructuredPDFLoader(file_path,
                                strategy="fast",
                                mode="elements")

loader = loaders.load()
splitted_doc = text_splitter.split_documents(loader)
documents = chromautils.filter_complex_metadata(splitted_doc)

collection = Chroma.from_documents(documents=documents, embedding=my_embeddings, persist_directory=my_db_path)
 ```
 
 This is my current code, in her i just want to use unstructureds chunker, is there any easy way to implement it?

**Comment by scanny** [comment]
Closing as the original issue is resolved. @doganaktarr if you still have questions feel free to open a new issue :)
