### ISSUE TITLE
Is there any way for using unstructured chunker for chromadb entegration

### ISSUE THREAD

**Issue by doganaktarr** [Unstructured-IO/unstructured#2527]
```python
text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap)
            
loaders = UnstructuredPDFLoader(file_path,
                                strategy="fast",
                                mode="elements")

loader = loaders.load()
splitted_doc = text_splitter.split_documents(loader)
documents = chromautils.filter_complex_metadata(splitted_doc)

collection = Chroma.from_documents(documents=documents, embedding=my_embeddings, persist_directory=my_db_path)
 ```
 
 I am a beginner to LLM projects, this is my current code, in here i just want to use unstructureds chunker and partition instead of langchain, is there any easy way to implement it?

**Comment by ahmetmeleq** [comment]
Hello Doğan, please join to our [community slack](https://join.slack.com/t/unstructuredw-kbe4326/shared_invite/zt-2c5l7egav-Qereux8931g782~pLSEsDQ) and check the channels to ask questions - we're answering usage questions in the slack channel

If you have a feature request or a bug report in the future, feel free to open an issue again 👍
