### ISSUE TITLE
Create a data connector for processing the biomedical literature

### ISSUE THREAD

**Issue by ajjimeno** [Unstructured-IO/unstructured#254]
Create a data connector that:
* fetches PDF files from [PMC Open Access Subset](https://www.ncbi.nlm.nih.gov/pmc/tools/openftlist).
* stores the files locally (at least temporarily for processing), and runs them through [unstructured.partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py).

See [Adding Data Connectors](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#adding-data-connectors) for details on how to get started. Make sure to include a link to this issue when submitting a PR.

**Definition of Done**

* The [checklist](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#the-checklist) has been completed.
* The connector is able to process all files from the [PMC Open Access Subset FTP directory](https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf).
* The connector is able to process a document using the [Individual article download](https://www.ncbi.nlm.nih.gov/pmc/tools/ftp/#indart).
* The connector is able to process a document using the [PDF download](https://www.ncbi.nlm.nih.gov/pmc/tools/ftp/#indart:~:text=a%20single%20article-,PDF%20download,-Available%20for%3A).
* The connector can accept any credentials, if necessary.
* The connector should be able of processing the PDF documents through [unstructured.partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py).

**Comment by cragwolfe** [comment]
LGTM!
