### ISSUE TITLE
bug/<OneDriveNotConnectedException>

### ISSUE THREAD

**Issue by tuhiindass** [Unstructured-IO/unstructured#2543]
I'm getting exception Please someone help me. 

office365.runtime.client_request_exception.ClientRequestException: ('AccessDenied', 'Either scp or roles claim need to be present in the token.', '403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/users/tuhin.das@clou.dio/drive')

![image](https://github.com/Unstructured-IO/unstructured/assets/60917433/fc7eb3ac-b137-4654-a9d0-c67dd6b148c6)

**Comment by MthwRobinson** [comment]
@tuhiindass - Could you provide the code you ran to produce the error and information about the OneDrive instance you're looking to connect to?
