### ISSUE TITLE
Create a data connector for processing social media sites

### ISSUE THREAD

**Issue by ajjimeno** [Unstructured-IO/unstructured#255]
Create a data connector that:

* fetches data from social media sites such as Twitter or Facebook.
* stores the content locally (at least temporarily for processing), and runs them through [unstructured.partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py).
* indicate the social media site you are working on by commenting on the issue. 

See [Adding Data Connectors](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#adding-data-connectors) for details on how to get started. Make sure to include a link to this issue when submitting a PR.

**Definition of Done**

* The [checklist](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#the-checklist) has been completed.
* The connector is able to process posts using the API of the media site.
* The connector is able to process a single post.
* The connector is able to process several posts.
* The connector can accept any credentials, if necessary.
* The connector should be able of processing documents through [unstructured.partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py).

**Comment by scanny** [comment]
This looks closely related to the genera-purpose JSON partitioner I'm working on which can be rapidly and declaratively configured to partition an arbitrary REST API response payload (in JSON format). Assigning myself here like a "collaborator", not as the developer of the actual connector.
