### ISSUE TITLE
bug/ppt files registering as xlsx files in docker container

### ISSUE THREAD

**Issue by Jayman3639** [Unstructured-IO/unstructured#2559]
**Describe the bug**

I am using LangChain's AzureBlobStorageContainerLoader which depends on unstructured.

This error occurs in a docker container using an apache/airflow:2.8.1 image. The line for unstructured in requirements.txt is currently `unstructured[pdf, docx, ppt, pptx, xlsx]`. 

The host is an image of an Ubuntu 20.04 OS running on a VM and the same code works there with no issues. I did have to install LibreOffice to get it to work in a Jupyter Notebook, and so I installed it in the docker container as well. I found out that without LibreOffice installed the docker container throws the same error either way.

I have a blob storage container filled with pdf, pptx, docx, and, ppt documents only.

In the airflow logs I can see the code making requests to the container and receiving each document. When it first happened, before I included the xlsx library in the unstructured package, for the first ppt file it received it threw the error: `ImportError: partition_xlsx is not available. Install the xlsx dependencies with pip install “unstructured[xlsx]”` I deleted that specific file thinking maybe the file itself was the issue, but it just threw the same error for the ppt file that was after it.

So I followed the instruction and included xlsx in the requirements.txt. On the next try it threw this error: `xlrd.biffh.XLRDError: Can't find workbook in OLE2 compound document`. This led me to this info: “[Excel-protected files cannot be read by xlrd](https://stackoverflow.com/questions/45725645/pandas-unable-to-open-this-excel-file)”

My main thought is why are ppt files being registered as xlsx files?

Thank you for any guidance/assistance you can provide. 

**To Reproduce**
Provide a code snippet that reproduces the issue.

```
@task()
def scrape_documents():
    from langchain_community.document_loaders import AzureBlobStorageContainerLoader
    docs = AzureBlobStorageContainerLoader(conn_str=CONN_STR, container=CONTAINER_NAME, prefix=CONTAINER_PREFIX).load()
    # Processing code	
```

**Expected behavior**

Easily scrape text from the ppt files just like it does for the pptx, docx, and pdf files. It does it successfully in the Jupyter Notebook on the host machine.

**Comment by 315930399** [comment]
hi, have you solved this problem ?

**Comment by Jayman3639** [comment]
I did end up solving this problem. Since I was using LangChain, I did not thoroughly review Unstructured's repo. It turned out after looking at your README on github I needed to add libmagic-dev and tesseract-ocr to my Dockerfile for installation. Usually any dependencies I needed were presented to me through the error which was useful, so I was relying on that.

I still think the error was strange, given the files were ppt and the error mentioned xlsx.

Thanks for reaching out though and hopefully this may help someone else.

**Comment by Jayman3639** [comment]
I did end up solving this problem. It turned out after looking at your README on github I needed to add libmagic-dev and tesseract-ocr to my Dockerfile for installation. Usually any dependencies I needed were presented to me through the error which was useful, so I was relying on that.

I still think the error was strange, given the files were ppt and the error mentioned xlsx.

Thanks for reaching out though and hopefully this may help someone else.

**Comment by 315930399** [comment]
> I did end up solving this problem. It turned out after looking at your README on github I needed to add libmagic-dev and tesseract-ocr to my Dockerfile for installation. Usually any dependencies I needed were presented to me through the error which was useful, so I was relying on that.
> 
> I still think the error was strange, given the files were ppt and the error mentioned xlsx.
> 
> Thanks for reaching out though and hopefully this may help someone else.

Thanks for your reply. I alse use langchain and I meet the same error as you while my input document is .doc file. I decide to use the docker image provided by this repo.  Hope that can solve this problem.
