### ISSUE TITLE
Create a data conector for Github repos Part 1 (all supported filetypes but no source code)

### ISSUE THREAD

**Issue by benjats07** [Unstructured-IO/unstructured#256]
Create a data connector that pulls data from GIthub repo.

See [Adding Data Connectors](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#adding-data-connectors) for details on how to get started. Make sure to include a link to this issue when submitting a PR.

**Definition of Done**

- The [checklist](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#the-checklist) has been completed.
- The connector is able to process a single repository and recursively the entire documents in a repo.
- Should ignore code.
- Should process only doc types supported in [partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py), including markdown files.

    
Bonus points: the ability to filter by document type.

**Comment by tomaarsen** [comment]
I'd like to have a go at this! What CLI arguments would you recommend that I introduce?
I imagine something along the lines of:
* `--repository_url` or `--github-url`.
and optionally
* `--filetypes` or `--glob` or `--fileglob`, etc.

Would love to hear your thoughts.

**Comment by tomaarsen** [comment]
> Should process only doc types supported in [partition.auto](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py), including markdown files.

How should this be handled? To the best of my knowledge, there is no `partition_markdown`. Should markdown be parsed using `partition_text`?
