### ISSUE TITLE
Images and tables getting cut off at the edges when using hi res strategy

### ISSUE THREAD

**Issue by briantenison** [Unstructured-IO/unstructured#2561]
I'm using unstructured to partition pdfs and extract tables and images. I'm using the hi res strategy, and still a lot of the images and tables are being extracted with the edges cut off resulting in a loss of information. In most cases, it's just cutting off half of the letters that are on the edge of the image. This is all very new to me, but does anyone know if there's an easy way to tweak the parameters so that the library uses a slightly wider lens when taking a "snapshot" of these images and tables? As far as I can tell, there are only a few strategies one can use, and this is a very common use case for the library, so I'm stumped as to why it isn't accurately extracting this stuff.

**Comment by longcw** [comment]
I had the same issue. Why was this issue closed, are there any solutions?

**Comment by scanny** [comment]
Hmm, not sure, the OP closed it himself.

@briantenison what was the resolution for this?

**Comment by christinestraub** [comment]
Hi @longcw 

If some extracted images have content clipped, you can adjust the padding by specifying two environment variables “EXTRACT_IMAGE_BLOCK_CROP_HORIZONTAL_PAD” and “EXTRACT_IMAGE_BLOCK_CROP_VERTICAL_PAD” (for example, EXTRACT_IMAGE_BLOCK_CROP_HORIZONTAL_PAD = 20, EXTRACT_IMAGE_BLOCK_CROP_VERTICAL_PAD = 10).

Documentation: https://unstructured-io.github.io/unstructured/core/partition.html#partition-pdf
