### ISSUE TITLE
Create a data conector for Azure Blob Storage

### ISSUE THREAD

**Issue by benjats07** [Unstructured-IO/unstructured#257]
Create a data connector that pulls data from [Azure Blob Storage ](https://learn.microsoft.com/en-us/azure/storage/blobs/)

See [Adding Data Connectors](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#adding-data-connectors) for details on how to get started. Make sure to include a link to this issue when submitting a PR.

**Definition of Done**

- The [checklist](https://github.com/Unstructured-IO/unstructured/blob/main/Ingest.md#the-checklist) has been completed.
- The connector is able to process a single object or a container.
- The connector is able to process the entire container.
- For private files, it requires the credentials of access.
- For now, it is OK to process only doc types that [partition.auto()](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/auto.py) is capable of processing. 
    
Bonus points: the ability to filter by document type.

**Comment by alvarobartt** [comment]
Hi @benjats07 I'd like to actually tackle this issue, can I? Thanks

**Comment by benjats07** [comment]
@alvarobartt sure, we are receiving multiple solutions to all issues in the repo, so go for it!

**Comment by benjats07** [comment]
Currently, we don't have any container for that, feel free to create an account for that, the free tier should be enough for that.

**Comment by alvarobartt** [comment]
As mentioned in https://github.com/Unstructured-IO/unstructured/pull/318#issuecomment-1450619852, there are still some things to improve, such as the naming and also to add integration tests. For the latter, I'd appreciate it if someone from @unstructured-io could "clone" somehow the files from S3 to Azure Blob Storage (which can be done under the free-tier AFAIU) so that I can develop the integration tests using that URL.

**Comment by alvarobartt** [comment]
Did you get the chance to think about the naming for this connector @benjats07? I kept `ABSConnector` but ABS acronym is not as well known/common as S3 for AWS S3 or GCS for Google Cloud Storage, so I'm happy to open the naming to discussion 👍🏻

**Comment by benjats07** [comment]
Sorry about the delay @alvarobartt.
Could you check with this [link](https://datalakebenja22.blob.core.windows.net/demo-files?sp=r&st=2023-03-03T18:11:01Z&se=2023-04-04T01:11:01Z&sv=2021-06-08&sr=c&sig=%2FF3fRTWUJE1JWpdYhnMUjVBP7LZW6g8nSrVbotltL7k%3D) ? 

And, about the naming, maybe AzureBlobStorage is better just for clarity 🤔

**Comment by alvarobartt** [comment]
Sure @benjats07 I'll try that out either later today or tomorrow morning! Hopefully this weekend I can submit some more PRs before the competition ends 👍🏻 

Also, I agree with using `AzureBlobStorageConnector` instead of `ABS` since that may be a little confusing!

**Comment by alvarobartt** [comment]
Thanks @benjats07, just some questions regarding the URL that you shared:
* Just like for `S3Connector`, the expected URL should come in the format of a `fsspec` path i.e. `abfs://<container>/<blob>`
* The link that you sent me is for DataLake Storage, so do you also want me to add support for both DataLake Gen1&2 and Blob Storage?
* Is the data publicly accessible? Like e.g. `s3://utic-dev-tech-fixtures/small-pdf-set/`

**Comment by alvarobartt** [comment]
BTW I've tested it with some minor tweaks and it does work, I'll send you here the clean output of its trigger from the `unstructured-ingest` CLI :)

**Comment by alvarobartt** [comment]
Hi again @benjats07, it works fine! Please clone the code at https://github.com/alvarobartt/unstructured/tree/a8271d7c89ff97a4c715f1ffc18d1cf52a6eabde, and run it either via `bash` running the script at `examples/ingest/azure/ingest.sh` or just via CLI with:

```bash
unstructured-ingest \               
   --azure-url abfs://demo-files/ \
   --azure-account-name datalakebenja22 \
   --structured-output-dir azure-demo-files-output \
   --num-processes 2
```

Note that you'll need to `pip install ".[azure]" first, or run `make install-ingest-azure` 👍🏻  Feel free to ping me if you have any other doubt (I'll be around the whole weekend)

**Comment by alvarobartt** [comment]
> Hi again @benjats07, it works fine! Please clone the code at https://github.com/alvarobartt/unstructured/tree/a8271d7c89ff97a4c715f1ffc18d1cf52a6eabde, and run it either via `bash` running the script at `examples/ingest/azure/ingest.sh` or just via CLI with:
> 
> ```shell
> unstructured-ingest \               
>    --azure-url abfs://demo-files/ \
>    --azure-account-name datalakebenja22 \
>    --structured-output-dir azure-demo-files-output \
>    --num-processes 2
> ```
> 
> Note that you'll need to `pip install ".[azure]"` first, or run `make install-ingest-azure` 👍🏻 Feel free to ping me if you have any other doubts (I'll be around the whole weekend)

Everything but https://github.com/Unstructured-IO/unstructured/issues/338 works, but maybe for the sake of testing the integration it's just better to re-upload the S3 PDF documents there?
