### ISSUE TITLE
feat/conda-package

### ISSUE THREAD

**Issue by lordsoffallen** [Unstructured-IO/unstructured#2573]
**Is your feature request related to a problem? Please describe.**
I am heavy conda user and I like unstructured so far but relying on pip sometimes makes me look for other packages. I see there is a guide on conda but for windows and not in a direct way to install `conda install unstuctured`.

**Describe the solution you'd like**
To be able to install in a proper conda way (conda-forge is fine)

**Additional context**
I have this issue as completed but I still don't see any guide: https://github.com/Unstructured-IO/unstructured/issues/448

**Comment by MthwRobinson** [comment]
Closing out, as we don't plan to support a `conda` package at this time.
