### ISSUE TITLE
bug/<OpenAIEmbeddingEncoder.__init__() got an unexpected keyword argument 'api_key'>

### ISSUE THREAD

**Issue by StatsAI** [Unstructured-IO/unstructured#2576]
**Describe the bug**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-51-ed5a79cfe785>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 # Initialize the encoder with OpenAI credentials
----> 8 embedding_encoder = OpenAIEmbeddingEncoder(api_key=open_ai_api_key)

TypeError: OpenAIEmbeddingEncoder.__init__() got an unexpected keyword argument 'api_key'

**To Reproduce**
```
!pip install "unstructured[all-docs]"

from google.colab import userdata
open_ai_api_key = userdata.get('open_ai_api_key')

from unstructured.documents.elements import Text
from unstructured.embed.openai import OpenAIEmbeddingEncoder

# Initialize the encoder with OpenAI credentials
embedding_encoder = OpenAIEmbeddingEncoder(api_key=open_ai_api_key)
```

**Expected behavior**
See OpenAI section here: https://unstructured-io.github.io/unstructured/core/embedding.html

**Environment Info**
Google Colab

**Comment by ryannikolaidis** [comment]
@StatsAI from a look I think the docs you referenced are incorrect / need an update. 

In the meantime, you should be able to instantiate OpenAIEmbeddingEncoder like this: 

```
OpenAIEmbeddingEncoder(config=OpenAiEmbeddingConfig(api_key=api_key))
```

**Comment by StatsAI** [comment]
> @StatsAI from a look I think the docs you referenced are incorrect / need an update.
> 
> In the meantime, you should be able to instantiate OpenAIEmbeddingEncoder like this:
> 
> ```
> OpenAIEmbeddingEncoder(config=OpenAiEmbeddingConfig(api_key=api_key))
> ```

I tried that and got the following: 

`NameError: name 'OpenAIEmbeddingConfig' is not defined`

**Comment by ryannikolaidis** [comment]
> > @StatsAI from a look I think the docs you referenced are incorrect / need an update.
> > In the meantime, you should be able to instantiate OpenAIEmbeddingEncoder like this:
> > ```
> > OpenAIEmbeddingEncoder(config=OpenAiEmbeddingConfig(api_key=api_key))
> > ```
> 
> Thanks. Agreed. I tried that but got the following: `NameError: name 'OpenAIEmbeddingConfig' is not defined`

Agh, yea, sorry. So, there's another issue going on, someone refactored the casing on the the Encoder class but not on the config so it is: `OpenAiEmbeddingConfig` (note the lower case i). And yes, we need to fix that too. :)

**Comment by MthwRobinson** [comment]
Closing out, looks like the name of that class is now `OpenAIEmbeddingConfig`

https://github.com/Unstructured-IO/unstructured/blob/9b83330b5ad39a7e9cfcbab596a54ed1eb636d3a/unstructured/embed/openai.py#L18
