### ISSUE TITLE
bug/`get_elements_from_api()` got `file type None is not supported` error in `>=0.11.4`

### ISSUE THREAD

**Issue by kozistr** [Unstructured-IO/unstructured#2584]
**Describe the bug**

I'm calling `get_elements_from_api()` function with the following arguments.

```
file = <some byte stream>  # downloaded from the AWS S3

documents = get_elements_from_api(
    file_path=None,
    api_key='<api-key>',
    api_url='<api-url>',
    file=file,  # BytesIO type. just a simple pdf file that contains only text
    mode='elements',
    content_type='application/pdf',  # corresponding MIME type with file
    metadata_filename='asdf',  # filename, but without extension (e.g. .pdf)
)
```

It's okay with the `0.11.2` version. `unstructured` recognizes file type with `content_type` and stores the `metadata_filename` in element metadata.

However, from the `>=0.11.4`. It does not behave as expected. It starts to give `File type None is not supported.` error.

I looked into the code and found that from `0.11.4`, in `unstructured/partition/api.py line 83 ~ 86`, It looks like that `metadata_filename` is assigned to `file_name` and passed to the `unstructured API server`.

```
        files = shared.Files(
            content=file,
            file_name=metadata_filename,
        )
```

Finally, `unstructured` seems to use `file_name` to recognize the file type instead of the `content_type`. (You can also check that `unstructured` does not use `content_type` by removing the `content_type` parameter from the `get_elements_from_api()` API).

The below code works fine in `>=0.11.4`. (but not intended)

```
documents = get_elements_from_api(
    file_path=None,
    api_key='<api-key>',
    api_url='<api-url>',
    file=file,  # BytesIO type
    mode='elements',
    # content_type='application/pdf',  # corresponding MIME type with file
    metadata_filename='asdf.pdf',  # filename with extension
)
```

**To Reproduce**

* pass the file with the byte stream.
* set the proper content_type.
* set `metadata_filename` without the extension.

```
file = <some byte stream>  # which is downloaded from the AWS S3

documents = get_elements_from_api(
    file_path=None,
    api_key='<api-key>',
    api_url='<api-url>',
    file=file,  # BytesIO type
    mode='elements',
    content_type='application/pdf',  # corresponding MIME type with file
    metadata_filename='asdf',  # filename, but there's no extension
)
```

**Expected behavior**

* In `0.11.2`, no error
* In `>=0.11.4`, got `File type None is not supported.` error.

To wrap it all up, I want `unstructured` to behave like `0.11.2`, which recognizes the file type from the `content_type` and can use `metadata_filename` w/ or w/o the extension.

**Screenshots**

**Environment Info**

I also tested on different OS (e.g. ubuntu, macos) and with the latest `unstructured` version.

```
OS version:  Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python version:  3.11.6
unstructured version:  0.11.4
unstructured-inference is not installed
pytesseract version:  0.3.10
Torch version:  2.1.1+cu118
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version: file-5.41
magic file from /etc/magic:/usr/share/misc/magic
LibreOffice version:  LibreOffice 7.3.7.2 30(Build:2)
```

**Additional context**

Anyway, thanks for maintaining the epic project. I'm a big fan of `unstructured` :)

**Comment by kozistr** [comment]
@Coniferish hi! could you please check this issue when you are available? thanks in advance for your help :)

**Comment by Coniferish** [comment]
@kozistr, `content-type` is on the road map for being supported by the python SDK once we [migrate the python SDK to v2](https://github.com/Unstructured-IO/unstructured-python-client/tree/python-v2-migration). `partition_via_api` depends on the client, so that will address this issue once it is merged.

**Comment by kozistr** [comment]
> @kozistr, `content-type` is on the road map for being supported by the python SDK once we [migrate the python SDK to v2](https://github.com/Unstructured-IO/unstructured-python-client/tree/python-v2-migration). `partition_via_api` depends on the client, so that will address this issue once it is merged.

thanks for letting me know :)

**Comment by awalker4** [comment]
Hi @kozistr we've deployed an improved filetype detection in the API to replace the naive file extension check. This should fix all cases of `file type None is not supported`. Additionally we've added a `content-type` form parameter for the rare cases where you may want to override the check. The new param will be in the hosted API some time this week.

**Comment by kozistr** [comment]
> Hi @kozistr we've deployed an improved filetype detection in the API to replace the naive file extension check. This should fix all cases of `file type None is not supported`. Additionally we've added a `content-type` form parameter for the rare cases where you may want to override the check. The new param will be in the hosted API some time this week.

awesome! thanks for your work :)
