### ISSUE TITLE
feat/GPU acceleration with tessract

### ISSUE THREAD

**Issue by RobertHH-IS** [Unstructured-IO/unstructured#2590]
**Is your feature request related to a problem? Please describe.**
Enable the ability to toggle GPU acceleration, which is already built into Tessract.  It would be ideal if we could also enable Yolox models.

**Comment by muazhari** [comment]
UPP!!!

**Comment by MthwRobinson** [comment]
On the Yolox models, see #2506. If Tesseract has built in GPU support already I think we ought to be able to add a toggle for that.

**Comment by cragwolfe** [comment]
There is not much perf. gain with tesseract on GPU vs. CPU.

**Comment by muazhari** [comment]
> There is not much perf. gain with tesseract on GPU vs. CPU.

You should focus on overall processing to be significant too like optimizing using many recognition instances in parallel.
