### ISSUE TITLE
Image extract to payload is not giving base64 metadata

### ISSUE THREAD

**Issue by AlokRanjanSwain** [Unstructured-IO/unstructured#2603]
**Describe the bug**
I want to extract the image in base64 format for the pdf elements. 
Apparently, I am able to extract only the compositeElement and Table as the elements. 
The metadata of Table as base64 image string, but there is no such base64 string for the images that were present.

```python
raw_pdf_elements = partition_pdf(
    filename=path+file_name,
    extract_images_in_pdf= True,
    chunking_strategy="by_title",
    max_characters=2000, # chunk into n chars 
    new_after_n_chars=1800, #cut off chunks after this many chars
    combine_text_under_n_chars=1000, # combine chars under "title" to reach 2000 if <2000
    extract_image_block_types=["Image", "Table"],   
    extract_image_block_to_payload=True
)
```

when I do 
```python
for element in raw_pdf_elements: 
   print(element.category)
   print(element.metadata.to_dict())

```

Only table elements have base64 image str as metadata

**Comment by christinestraub** [comment]
Hi @AlokRanjanSwain, Can you share the pdf document you're trying?

**Comment by varun508** [comment]
@AlokRanjanSwain 
remove chunking_strategy="by_title" and it'll work. I think it merges other elements when creating the chunks and converts it toCompositeElement hence losing the metadata.

**Comment by varun508** [comment]
> @AlokRanjanSwain remove chunking_strategy="by_title" and it'll work. I think it merges other elements when creating the chunks and converts it to CompositeElement hence losing the metadata.

@christinestraub can you explain a bit more on why this happens? Also, if there any way to retrieve images as base64 while providing the chunk_strategy as "by_title"

**Comment by AlokRanjanSwain** [comment]
@christinestraub , 
This is the pdf I was trying to extract 
[Link](https://arxiv.org/pdf/2304.08485.pdf)

**Comment by AlokRanjanSwain** [comment]
Hi @varun508 , 
This is correct, if I do chunking strategy is "by_title". I am not getting the image category, only the composite text category is shown. 
I think it will be good to separate out the image category as well during that chunking strategy.

**Comment by scanny** [comment]
@AlokRanjanSwain Somewhat oversimplified, but chunking consolidates elements to achieve the desired chunk-size `max_characters`. So in general a chunk can be composed of more than one element. The text of the elements is "joined" but also the element metadata must be consolidated.

Image metadata (`.metadata.image_base64` etc.), cannot be preserved in the general case because there can be multiple images in the same chunk, so the type would need to change from `str` to `list[str]`. So the behavior you're seeing is intentional.

As it stands you'll need to choose between chunking and accessing image metadata.

**Comment by AlokRanjanSwain** [comment]
Thanks for the info @scanny ,
If I want to retrieve the image on the folder, the chunking strategy `by_title` is working fine, 
Is there a workaround for getting `image` category similar to the `table` category during the chunking strategy. 
It does not seem optimal to lose the image context during some particular chunking strategy. 
We can either have list of `base64_image` in the composite text, OR `image` category all together separately.

**Comment by scanny** [comment]
@AlokRanjanSwain I'm not understanding your question. When you say "category" do you mean "element"? Also, what does "retrieve the image on the folder" mean?

The only workaround to the current behavior I can think of to get an `image_base64s: list[str]` field in the metadata of a chunk is to write your own chunker that does that. If you look at `unstructured.chunking.title.chunk_by_title()` you can see a chunker is surprisingly little code:
https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/chunking/title.py#L81-L85

```python
    pre_chunks = PreChunkCombiner(
        PreChunker.iter_pre_chunks(elements, opts), opts=opts
    ).iter_combined_pre_chunks()

    return [chunk for pre_chunk in pre_chunks for chunk in pre_chunk.iter_chunks()]
```

You could possibly inspect pre-chunks before calling `.iter_chunks()` on them and modify the metadata of the chunk to add a list of image_base64 values. Something roughly like:

```python
def iter_pre_chunk_image_pairs(elements, opts) -> Iterator[tuple[PreChunk, str]]:
    for pre_chunk in PreChunker.iter_pre_chunks(elements, opts):
        image_base64s = [e.metadata.image_base64 for e in pre_chunk._elements if e.metadata.image_base64]
        yield pre_chunk, image_base64s
```

That's a little more radical surgery than most folks would expect to do, and it is special purpose to your use case, but if you have the skills and desire that's one possible approach.

**Comment by AlokRanjanSwain** [comment]
Yes @scanny , 
your understanding is correct and this is what I was looking for. Thanks for the update. I will try to implement it.

**Comment by muazhari** [comment]
Are there any updates? Until now, the image_base64 and image_mime_type were not set and are still using traditional image_path. Is it only on my side because I used the wrong steps? If yes, how can it be expected to get image_base64 and image_mime_type without using saved image_path?

**Comment by scanny** [comment]
This code should get you all the original elements, as they were after partitioning and before the chunking step.
```python
chunks = partition_pdf(...)
orig_elements = [
    e
    for chunk in chunks if not chunk.metadata.is_continuation
    for e in chunk.metadata.orig_elements
]
```

**Comment by weissenbacherpwc** [comment]
I have the same problem (v 0.16.9).
@scanny I tried your code and did this:

```
raw_pdf_elements = partition_pdf(
    filename="/Users/mweissenba001/Downloads/2304.08485v2.pdf",
    # Using pdf format to find embedded image blocks
    extract_images_in_pdf=True,
    extract_image_block_types=['Table', 'Image'],
    # Use layout model (YOLOX) to get bounding boxes (for tables) and find titles
    # Titles are any sub-section of the document
    infer_table_structure=True,
    # Post processing to aggregate text once we have the title
    chunking_strategy="by_title",
    # Chunking params to aggregate text blocks
    # Attempt to create a new chunk 3800 chars
    # Attempt to keep chunks > 2000 chars
    # Hard max on chunks
    max_characters=4000,
    new_after_n_chars=3800,
    combine_text_under_n_chars=2000,
    extract_image_block_output_dir=path,
    extract_image_block_to_payload=True,
    unique_element_ids=True
)

orig_elements = [
    e
    for chunk in raw_pdf_elements if not chunk.metadata.is_continuation
    for e in chunk.metadata.orig_elements
]
```

But I am getting this error: `AttributeError: 'ElementMetadata' object has no attribute 'orig_elements'`

Do you know why?

**Comment by scanny** [comment]
Hmm, that seems odd. What version are you running? That field was added in March of this year:
https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/documents/elements.py#L190

**Comment by scanny** [comment]
Hmm, okay, I see you mentioned `0.16.9`. What do you get for `chunk.metadata._known_field_names`? Also mention the Python version (and type, CPython, Pypy, etc.) you're using.

**Comment by weissenbacherpwc** [comment]
I see an image path in the frozenset. How can I access the image path as it is not part of the metada?

**Comment by scanny** [comment]
How are you determining the `unstructured` version? The collection of fields in `_known_field_names` you provided is missing fields added after about March this year and also includes fields removed on or about that time. That leads me to believe the `unstructured` library being used by your code is an old version. Depending on how you are running the code you may have `unstructured` installed more than once and the code ends up using the old version.

The `.image_path` metadata field is a path to an extracted image file. I will only be populated when images are extracted and you have instructed the partitioner to save those images to a local directory.
