### ISSUE TITLE
bug/PDFPageCountError

### ISSUE THREAD

**Issue by adi-kmt** [Unstructured-IO/unstructured#2630]
**Describe the bug**
Unable to run [unstructured chunking](https://unstructured-io.github.io/unstructured/core/chunking.html#calling-a-chunking-function). 
I'm getting PDFPageCountError.

**To Reproduce**
Same as above

**Expected behavior**
Run smoothly

**Screenshots**

**Environment Info**
Ran the following installs
`apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config poppler-utils`
`pip install unstructured[all-docs]==0.11.5 unstructured-inference==0.7.18`

**Comment by scanny** [comment]
Hi @adi-kmt please post the full traceback.
