### ISSUE TITLE
feat(chunking): add .metadata.is_continuation for text-split Text chunks

### ISSUE THREAD

**Issue by scanny** [Unstructured-IO/unstructured#2634]
`ElementMetadata.is_continuation` indicates second and later chunks formed from an oversized element by text-splitting.  (Oversized means having text longer than `max_characters` so won't fit in single chunk).

Currently this metadata is only applied to `TableChunk` chunks formed from an oversized `Table` element.

Also include this metadata for second-and-later `CompositeElement` chunks formed from an oversized text/non-table element.

This field will be important for #1286 to distinguish continuation chunks which may contain the same `.orig_element` as the first text-split chunk formed from that element.

For example, if you wanted to recover the original element-stream from the chunks without introducing duplicate elements you would use something like this:
```python
[
    e
    for c in chunks
    if not c.metadata.is_continuation
    for e in c.orig_elements
]
```

**Comment by maplessssy** [comment]
Nice, looking forward to this feature.

**Comment by scanny** [comment]
@maplessssy glad you mentioned this, this feature was added recently as part of some other work. Should work now such that all second-and-later chunks formed by text-splitting an oversized element will have `.metadata.is_continuation == True`. Might need to update your version depending on what version you're currently running :)
