### ISSUE TITLE
License questions regarding pillow-heif

### ISSUE THREAD

**Issue by joennlae** [Unstructured-IO/unstructured#2664]
First of all, really cool software 💯 

While doing a license check, I noticed that the `pillow-heif` dependency is actually GPLv2 with the binary wheels.

Source: https://github.com/bigcat88/pillow_heif/issues/111

I think we should use `pi-heif`: https://pypi.org/project/pi-heif/ but IANAL :-)

Just thought it would make sense to communicate that while I stumbled upon it.

**Comment by MthwRobinson** [comment]
@joennlae - Thanks for reporting this! `pillow_heif` looks like it has a [BSD license](https://github.com/bigcat88/pillow_heif?tab=BSD-3-Clause-1-ov-file#readme), which is one of the license we accept for dependencies. The bindings to GPL licensed system dependencies are good to go from our stand point.

**Comment by PhorstenkampFuzzy** [comment]
For us it looks like the code has a BSD license but the Wheel has a GPLV2. How do you reconsile this?

**Comment by nylocx** [comment]
We came across the same issue and would have to patch unstructured as the binary wheels for pillow-heif is GPLv2 licensed. The author of pillow-heif is releasing pi-heif with the info:

> This is a light version of [Pillow-Heif](https://github.com/bigcat88/pillow_heif) with more permissive license for binary wheels. [...] All codebase are the same, refer to [pillow-heif docs](https://pillow-heif.readthedocs.io/).

So please reconsider changing the dependency as it should be a drop in replacement and resolve GPL compatibility issues.

**Comment by MthwRobinson** [comment]
Thanks for the clarification. We're working on replacing `pillow-heif` with `pi-heif`.

**Comment by PhorstenkampFuzzy** [comment]
🙇

**Comment by MthwRobinson** [comment]
We're now using `py-heif`. That changed was released in `0.15.8`. Thanks all!
