### ISSUE TITLE
ModuleNotFoundError: No module named 'unstructured.documents.pdf'

### ISSUE THREAD

**Issue by iliasmansouri** [Unstructured-IO/unstructured#267]
Hello,

Following the documentation for parsing a pdf as found here: https://unstructured-io.github.io/unstructured/examples.html#pdf-parsing

It seems that the import statement:
`from unstructured.documents.pdf import PDFDocument
`
results in a not found error.

Indeed, checking unstructured/unstructured/documents, I can't seem to find anything relevant for PDF parsing.

Thank you

**Comment by MthwRobinson** [comment]
@iliasmansouri - Thanks for this issue. That looks like outdated documentation. We'll get that fixed as soon as we can.

**Comment by iliasmansouri** [comment]
> @iliasmansouri - Thanks for this issue. That looks like outdated documentation. We'll get that fixed as soon as we can.

@MthwRobinson: Thanks for the quick response. Meanwhile, can you point out on how to use the pdf-related modules?

**Comment by MthwRobinson** [comment]
@iliasmansouri - Yep check out these links. You'll need `unstructured[local-inference]` from the quick start docs to use the PDF capabilities. Feel free to drop us a line in our community slack if you run into any issues.

- `partition_pdf`: https://unstructured-io.github.io/unstructured/bricks.html#partition-pdf
- quick start: https://unstructured-io.github.io/unstructured/installing.html#quick-start
- Slack: https://join.slack.com/t/unstructuredw-kbe4326/shared_invite/zt-1nlh1ot5d-dfY7zCRlhFboZrIWLA4Qgw
