### ISSUE TITLE
Is there any specific reason to use `dataclasses-json-speakeasy` rather than `dataclasses-json`? 

### ISSUE THREAD

**Issue by jan-janssen** [Unstructured-IO/unstructured#2689]
As far as I can see the features were merged up-stream: https://github.com/speakeasy-api/dataclasses-json

**Comment by awalker4** [comment]
Hi there, @simplesagar can confirm, but I believe the issue was that our python client had a git commit pinned, and couldn't be published that way. If the relevant changes have been merged, we may be able to go back to upstream.
