### ISSUE TITLE
bug: no elements returned when `strategy='fast'`

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#2830]
**Describe the bug**
An empty array of elements are returned from the attached pdf when strategy='fast'

**To Reproduce**
```
from unstructured.partition.auto import partition
filename = "Hydrophobicity-Hydrophilicity_and_Silane_Surface_Modification (2).pdf"
elements = partition(filename, strategy="fast")
```

**Expected behavior**
partitioning should fall back to "ocr_only" if the "fast" strategy will not work.
[Hydrophobicity-Hydrophilicity_and_Silane_Surface_Modification (2).pdf](https://github.com/Unstructured-IO/unstructured/files/14828788/Hydrophobicity-Hydrophilicity_and_Silane_Surface_Modification.2.pdf)

**Additional context**
User raised the issue here: https://unstructuredw-kbe4326.slack.com/archives/C06JJHC9G4U/p1711992090841549?thread_ts=1711963289.876729&cid=C06JJHC9G4U

**Comment by cragwolfe** [comment]
> partitioning should fall back to "ocr_only" if the "fast" strategy will not work.
[Hydrophobicity-Hydrophilicity_and_Silane_Surface_Modification (2).pdf](https://github.com/Unstructured-IO/unstructured/files/14828788/Hydrophobicity-Hydrophilicity_and_Silane_Surface_Modification.2.pdf)

This should not automatically be the case. running OCR against a page is going to be more than 10x the compute of `ocr_only`.

**Comment by Coniferish** [comment]
@cragwolfe, good to know. The documentation partition_pdf says "If the PDF text is not extractable, partition_pdf will fall back to 'ocr_only'", though. Should that be updated or clarify when it does fall back? 

tagging @christinestraub

**Comment by christinestraub** [comment]
@Coniferish The `fast` strategy should not fall back to a more expensive strategy - https://github.com/Unstructured-IO/unstructured/pull/2055
