### ISSUE TITLE
File Not Found Error  nlp/english-words.txt

### ISSUE THREAD

**Issue by taaha3244** [Unstructured-IO/unstructured#2859]
Hello Everyone!!,
I am trying to setup unstructured on google colab

I am facing a "FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/unstructured/nlp/english-words.txt'"

**Code is as below
! pip install -U langchain openai qdrant-client langchain_openai  langchain-experimental
! pip install "unstructured[all-docs]" pillow pydantic lxml pillow matplotlib  tiktoken numpy
!pip install popper utils tesseract-ocr  
!pip install "detectron2@git+https://github.com/facebookresearch/detectron2.git@v0.6#egg=detectron2"

from langchain_text_splitters import CharacterTextSplitter
from unstructured.partition.auto import partition

![image](https://github.com/Unstructured-IO/unstructured/assets/120934618/2b4835a4-0fa0-4da7-8475-299338915aee)

Will  appreciate help

**Comment by cragwolfe** [comment]
This was an issue with `unstructured==0.13.1` but should be fixed as of 0.13.2 , initially tracked here: https://github.com/Unstructured-IO/unstructured/issues/2855 .
