### ISSUE TITLE
Add-pipenv-for-env-pinning-and-setup/pipenv

### ISSUE THREAD

**Issue by james-see** [Unstructured-IO/unstructured#286]
**Is your feature request related to a problem? Please describe.**
It is painful to maintain versions of python and pip installed dependancies, even with having to setup virtualenv. 

**Describe the solution you'd like**
Pipenv combines both of these things in a simple paradigm.
https://www.makeuseof.com/pipenv-python-environment/

**Describe alternatives you've considered**
Poetry, venv, virtualenv, Makefile, Gradlew, anaconda (ugh), pyenv with no venv.

**Comment by MthwRobinson** [comment]
Hi @james-see. We're not opposed to `pipenv` but don't want to be overly opinionated on what solution people use for virtual environments. We do have requirement files available under `requirements/*.txt`, you can create a `pipenv` environment from those files using [these instructions](https://pipenv-fork.readthedocs.io/en/latest/basics.html#importing-from-requirements-txt).

**Comment by james-see** [comment]
Including a pipenv dotfile does not force people to use it, it basically adds pipenv as an option without them having the frieze out from requirements.txt to pipenv. Saves them a step. Could have the circle-ci auto keep the pipenv dotfile up to date.
