### ISSUE TITLE
update-quick-start/readme

### ISSUE THREAD

**Issue by james-see** [Unstructured-IO/unstructured#288]
**Is your feature request related to a problem? Please describe.**
It was not clear how to get output from the readme quickstart example.

**Describe the solution you'd like**
I had to add
```
for item in elements:
        print(item.text)
```
To get the example to print the result properly to confirm working.

**Describe alternatives you've considered**
I considered trying to parse to json or looking up the internal methods to transform, but took too long.

**Comment by MthwRobinson** [comment]
@james-see - Thanks for this! Could you link to the part of the quick start docs that were unclear? We'll get those updated as soon as we can.

**Comment by james-see** [comment]
@MthwRobinson It looks like the section near line 84 in the README.md
