### ISSUE TITLE
Unable to import unstructured.partition.xyz

### ISSUE THREAD

**Issue by flaviobrienza** [Unstructured-IO/unstructured#2888]
I am trying to use the Unstructured library locally using the Python 3.10.2 version. 
Everytime I try to import unstructured.partition.something, for example "from unstructured.partition.pdf import partition_pdf" the kernel dies. 
I followed all the steps to install the library, but it keeps occurring. 
Unstructured version == 0.13.2
Unstructured-inference version == 0.7.25

**Comment by scanny** [comment]
Hi @flaviobrienza, I'm unable to reproduce any behavior that meets this description on my machine. We'll need some more specifics:
- What operating sytem and distro/version you're running
- A full copy and paste of the entire error message you receive. Also if you can be more descriptive about what you mean when you say "the kernel dies".
- What procedure you used to install `unstructured` on your machine.

**Comment by flaviobrienza** [comment]
Hello, 
I'm currently running Windows 11.
The problem is that I don't receive any message. When I try to make the import, for example 
`from unstructured.partition.html import partition_html`
It assumes two different behaviors, either the cell starts running and never stops or I receive the message "the kernel died" from my Jupyter Notebook.
I followed the Unstructured procedure to install all the dependencies.

**Comment by scanny** [comment]
Ah, interesting. So the kernel that's doing the dying is the Jupyter Notebook kernel.

Try running `from unstructured.partition.html import partition_html` from the Python command prompt and see what it does. That should give a more descriptive error.

**Comment by flaviobrienza** [comment]
This happens:

End of stack trace (more stack frames may be present)
  61485 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50
  64026 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50
  70491 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50
  71163 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50
  75280 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50
  78059 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50
  79348 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50
  80287 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50
  80845 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50
  82362 [main] python (17296)
C:\Users\FLAVIO\AppData\Local\Programs\Python\Python310\python.exe: ***
fatal error - Internal error: TP_NUM_C_BUFS too small: 50

Il Lun 15 Apr 2024, 20:31 Steve Canny ***@***.***> ha scritto:

**Comment by flaviobrienza** [comment]
Thanks, I'll try


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Privo
di virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 15 apr 2024 alle ore 21:22 Steve Canny <
***@***.***> ha scritto:

**Comment by flaviobrienza** [comment]
I checked, I already have all the libraries required.

Il giorno mar 16 apr 2024 alle ore 12:13 Flavio Brienza <
***@***.***> ha scritto:

**Comment by mk-devc** [comment]
I've experienced the same issue as well.

**Comment by flaviobrienza** [comment]
Did you solve it?

Il Ven 19 Apr 2024, 05:29 Mohan Kumar ***@***.***> ha scritto:

**Comment by mk-devc** [comment]
Nope just that I was able to run it on google colab.

**Comment by scanny** [comment]
Closing as inactive.
