### ISSUE TITLE
when pip install unstructured ,  why all versions of related modules are installed

### ISSUE THREAD

**Issue by ZJLi2013** [Unstructured-IO/unstructured#2890]
**Describe the bug**

![recycle_python_modules](https://github.com/Unstructured-IO/unstructured/assets/3397714/b8e42572-9d7c-48ca-8bdb-e55575befd33)

**To Reproduce**
`pip install unstructured` 

**Expected behavior**
only specific version should installed, not all versions

**Comment by scanny** [comment]
@ZJLi2013 I see it downloading multiple versions but I don't see it installing more than one. What is the full messages that begins with: "INFO: pip is downloading multiple versions to determine whi..."?

**Comment by scanny** [comment]
Closing as resolved. @ZJLi2013 if you're still having trouble with this and can provide more information, please feel free to reopen.
