### ISSUE TITLE
Got `NameError: name 'sort_page_elements' is not defined` when tried to extract tables. 

### ISSUE THREAD

**Issue by d1pankarmedhi** [Unstructured-IO/unstructured#2909]
**Describe the bug**
Followed the documentation for extracting text from tables but got an error instead. 

[Auto Partition example](https://unstructured-io.github.io/unstructured/best_practices/table_extraction_pdf.html)

**To Reproduce**
Run the sample from the above documentation.
```python
from unstructured.partition.auto import partition

filename = "example-docs/layout-parser-paper.pdf"

elements = partition(filename=filename,
                     strategy='hi_res',
           )

tables = [el for el in elements if el.category == "Table"]

print(tables[0].text)
print(tables[0].metadata.text_as_html)
```

**Expected behavior**
Should have returned a list of tables 

**Screenshots**
![image](https://github.com/Unstructured-IO/unstructured/assets/136924835/618f870d-d122-4f83-8562-f330f8cf9a72)

**Environment Info**
python version: Python 3.10.14
os: ubuntu 20.04

**Comment by christinestraub** [comment]
Hi @d1pankarmedhi 

Try to make sure that you're using the latest versions of unstructured(`0.13.2`) and unstructured-inference(`0.7.27`) libraries? I did not get this bug in those versions.

**Comment by scanny** [comment]
@d1pankarmedhi this could indicate that either `numpy` or `opencv-python` (or both) are not installed on your system.

You can check using:
```bash
$ pip list | grep numpy
# -- and --
$ pip list | grep opencv
```

These are both installed by the `[pdf]` extra like so (double-quotes required as shown):
```bash
$ pip install "unstructured[pdf]"
```

Why don't you try that out and let us know how you go :)

**Comment by scanny** [comment]
Completed by #2880.

**Comment by scanny** [comment]
Oops, closed wrong issue :)

**Comment by d1pankarmedhi** [comment]
> @d1pankarmedhi this could indicate that either `numpy` or `opencv-python` (or both) are not installed on your system.
> 
> You can check using:
> 
> ```shell
> $ pip list | grep numpy
> # -- and --
> $ pip list | grep opencv
> ```
> 
> These are both installed by the `[pdf]` extra like so (double-quotes required as shown):
> 
> ```shell
> $ pip install "unstructured[pdf]"
> ```
> 
> Why don't you try that out and let us know how you go :)

Thanks. This worked

**Comment by scanny** [comment]
Glad you got it working @d1pankarmedhi, and thanks for letting us know! :)

**Comment by jfantab** [comment]
I tried running `pip install "unstructured[pdf]"` but it still didn't work.
