### ISSUE TITLE
Cannot install unstructured properly no partition module found. 

### ISSUE THREAD

**Issue by j316chuck** [Unstructured-IO/unstructured#292]
**Describe the bug**

Cannot install unstructured properly no partition module found. 

```
(open-mmlab) ➜  ~ pip install "unstructured[local-inference]"
Requirement already satisfied: unstructured[local-inference] in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (0.2.0)
WARNING: unstructured 0.2.0 does not provide the extra 'local-inference'
Requirement already satisfied: nltk in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from unstructured[local-inference]) (3.6.7)
Requirement already satisfied: lxml in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from unstructured[local-inference]) (4.9.2)
Requirement already satisfied: click in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from nltk->unstructured[local-inference]) (8.0.3)
Requirement already satisfied: joblib in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from nltk->unstructured[local-inference]) (1.1.0)
Requirement already satisfied: regex>=2021.8.3 in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from nltk->unstructured[local-inference]) (2021.8.3)
Requirement already satisfied: tqdm in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from nltk->unstructured[local-inference]) (4.64.0)
Requirement already satisfied: importlib-metadata in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from click->nltk->unstructured[local-inference]) (4.2.0)
Requirement already satisfied: importlib-resources in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from tqdm->nltk->unstructured[local-inference]) (5.2.3)
Requirement already satisfied: zipp>=0.5 in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from importlib-metadata->click->nltk->unstructured[local-inference]) (3.6.0)
Requirement already satisfied: typing-extensions>=3.6.4 in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from importlib-metadata->click->nltk->unstructured[local-inference]) (3.10.0.2)
(open-mmlab) ➜  ~ python3
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from unstructured.partition.auto import partition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'unstructured.partition'
```

**Comment by tomaarsen** [comment]
I suspect that this is because you are using an older version of `unstructured`: version 0.2.0. That version did not yet have the `local-inference` extra. Consider trying this:
```
pip install -U "unstructured[local-inference]"
```
This installs a newer version of `unstructured` due to the `-U` (upgrade) flag, which should have access to `local-inference`.

- Tom Aarsen

**Comment by j316chuck** [comment]
(open-mmlab) ➜  ~ pip install -U "unstructured[local-inference]"

Requirement already satisfied: unstructured[local-inference] in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (0.2.0)
Collecting unstructured[local-inference]
  Using cached unstructured-0.2.1-py3-none-any.whl
WARNING: unstructured 0.2.1 does not provide the extra 'local-inference'
Requirement already satisfied: lxml in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from unstructured[local-inference]) (4.9.2)
Requirement already satisfied: nltk in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from unstructured[local-inference]) (3.6.7)
Requirement already satisfied: tqdm in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from nltk->unstructured[local-inference]) (4.64.0)
Requirement already satisfied: regex>=2021.8.3 in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from nltk->unstructured[local-inference]) (2021.8.3)
Requirement already satisfied: click in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from nltk->unstructured[local-inference]) (8.0.3)
Requirement already satisfied: joblib in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from nltk->unstructured[local-inference]) (1.1.0)
Requirement already satisfied: importlib-metadata in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from click->nltk->unstructured[local-inference]) (4.2.0)
Requirement already satisfied: importlib-resources in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from tqdm->nltk->unstructured[local-inference]) (5.2.3)
Requirement already satisfied: typing-extensions>=3.6.4 in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from importlib-metadata->click->nltk->unstructured[local-inference]) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in ./anaconda3/envs/open-mmlab/lib/python3.6/site-packages (from importlib-metadata->click->nltk->unstructured[local-inference]) (3.6.0)
Installing collected packages: unstructured
  Attempting uninstall: unstructured
    Found existing installation: unstructured 0.2.0
    Uninstalling unstructured-0.2.0:
      Successfully uninstalled unstructured-0.2.0
Successfully installed unstructured-0.2.1
(open-mmlab) ➜  ~ python3
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from unstructured.partition.auto import partition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'unstructured.partition'

Still getting this error

**Comment by tomaarsen** [comment]
Ah, I see now. The newest version of `unstructured` on PyPI is [0.4.15](https://pypi.org/project/unstructured/) at the time of writing, but it has required Python 3.7 onwards for some time now, as Python 3.6 has been [deprecated for over a year now](https://endoflife.date/python).
I'm afraid that you will either have to upgrade to a newer Python version, or rely only on features from the [older codebase](https://github.com/Unstructured-IO/unstructured/tree/0.2.1). I would recommend the former.

- Tom Aarsen

**Comment by j316chuck** [comment]
Thanks! Upgraded to python3.8 and it worked 👍

**Comment by Setsofia-lab** [comment]
My python version is 3.10.12 but i still encounter the error

**Comment by Setsofia-lab** [comment]
what could be causing this. I have already installed unstructured
