### ISSUE TITLE
chore: Update unstructured-client

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#2924]
The pinned version of unstructured-client was changed from `>=0.15.1` to `<=0.18.0` because more recent versions of the client broke some functionality. This needs to be changed back and any relevant updates need to be made.

In addition to fixing any errors that come from updating the client, there are some newer sdk parameters that will be supported. `test_unstructured_ingest/unit/pipeline/reformat/test_chunking.py` and `unstructured/ingest/pipeline/reformat/chunking.py` will need to be updated to reflect this.

**Comment by MthwRobinson** [comment]
@Coniferish - Are we ready to make this update or do we still need to wait for the next release?

**Comment by Coniferish** [comment]
@MthwRobinson Waiting for the next release

**Comment by Coniferish** [comment]
Closed by https://github.com/Unstructured-IO/unstructured/pull/3298
