### ISSUE TITLE
 ValueError: Detected a JSON file that does not conform to the Unstructured schema. partition_json currently only processes serialized Unstructured output.

### ISSUE THREAD

**Issue by NicoleNL** [Unstructured-IO/unstructured#2930]
When trying to load json file using S3FileLoader which uses Unstructured to load files, it's showing this error :
ValueError: Detected a JSON file that does not conform to the Unstructured schema. partition_json currently only processes serialized Unstructured output.

This is my json file:
{
  "bakery": {
    "name": "Delicious Delights Bakery",
    "location": "Cityville",
    "contact": {
      "phone": "1234",
      "email": "abc@email.com"
    },
    "opening_hours": {
      "Monday": "8:00 AM - 6:00 PM",
      "Tuesday": "8:00 AM - 6:00 PM",
      "Wednesday": "8:00 AM - 6:00 PM",
      "Thursday": "8:00 AM - 6:00 PM",
      "Friday": "8:00 AM - 8:00 PM",
      "Saturday": "9:00 AM - 8:00 PM",
      "Sunday": "10:00 AM - 4:00 PM"
    },
    "products": [
      {
        "name": "Croissant",
        "price": "$2.50"
      },
      {
        "name": "Baguette",
        "price": "$3.00"
      },
      {
        "name": "Cupcake",
        "price": "$2.00"
      },
      {
        "name": "Sourdough Bread",
        "price": "$4.00"
      }
    ]
  }
}

Would like to check how can this error be resolved?

**Comment by MthwRobinson** [comment]
Closing in favor of #1038, which will add better support for JSON files that aren't serialized Unstructured output.
