### ISSUE TITLE
feat/partition_metadata

### ISSUE THREAD

**Issue by Falven** [Unstructured-IO/unstructured#2933]
**Is your feature request related to a problem? Please describe.**
I need to be able to extract additional metadata from HTML documents. Specifically I would like to extract favicons and `head > title` elements. 

**Describe the solution you'd like**
Some flexible way to define additional metadata to extract per document type. Text file types could be via regex [(as currently seemingly supported)](https://unstructured-io.github.io/unstructured/metadata.html#extract-metadata-with-regexes), html via selectors, etc.

**Describe alternatives you've considered**
Doing it post partitioning, before indexing, but it's not elegant nor efficient.

**Additional context**
Even using LLM's to extract metadata [as orchestration frameworks support](https://docs.llamaindex.ai/en/stable/module_guides/indexing/metadata_extraction/) would be great.

**Comment by scanny** [comment]
Closing as this is not on the current roadmap so not actionable just now. We may revisit later.
