### ISSUE TITLE
feat/add the possibility to choose between tesseract and paddle in partition() function

### ISSUE THREAD

**Issue by Timotheevin** [Unstructured-IO/unstructured#2958]
It seems that PaddleOCR is supported by the package but I can't find any parameter in the function partition() or partition_pdf() to let the user decide wether to choose Paddle or Tesseract. By changing a few lines in the source code :

in _unstructured\partition\utils\config.py_

```
def OCR_AGENT(self) -> str:
    """error margin when comparing if a ocr region is within the table element when preparing
    table tokens
    """
    
    if self.OCR_METHOD == "paddle":
        print("Loading paddle for unstructured")
        return self._get_string("OCR_AGENT", OCR_AGENT_PADDLE)
    elif self.OCR_METHOD == "tesseract":
        print("Loading tesseract for unstructured")
        return self._get_string("OCR_AGENT", OCR_AGENT_TESSERACT)
    else:
        raise NotImplementedError("OCR METHOD not valid, please choose between 'paddle' and 'tesseract'")
```

Something like this seems to work, but the self.OCR_METHOD is not a native parameter, I added it myself...
Have I missed something in the way I try to use the partition() function with PaddleOCR ?
Is it a feature that will be added soon ?

Also, I am using unstructured 0.13.2, maybe it has its importance.

**Comment by yuming-long** [comment]
Hi there!
You should be able to specify OCR agent with env `OCR_AGENT` from [link](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/utils/config.py#L81).

Please set it like `export OCR_AGENT="unstructured.partition.utils.ocr_models.paddle_ocr.OCRAgentPaddle"` from the constant definition [here](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/utils/constants.py#L32).

**Comment by Coniferish** [comment]
Hi @Timotheevin! We need to update our documentation, but you can specify which agent you want to use or even provide your own using an `OCR_AGENT` environment variable. 
Here's the commit where this was added: https://github.com/Unstructured-IO/unstructured/pull/2462/files

**Comment by peixin-lin** [comment]
> Hi there! You should be able to specify OCR agent with env `OCR_AGENT` from [link](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/utils/config.py#L81).
> 
> Please set it like `export OCR_AGENT="unstructured.partition.utils.ocr_models.paddle_ocr.OCRAgentPaddle"` from the constant definition [here](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/utils/constants.py#L32).

Hi, may I ask which version I should use to enable this feature?

**Comment by Coniferish** [comment]
Hi @peixin-lin  
It looks like that was introduced in version 0.12.4, so any version after that should be fine.
