### ISSUE TITLE
partition_pdf: no text orientation detection?

### ISSUE THREAD

**Issue by vivien000** [Unstructured-IO/unstructured#2966]
Hi! I'm using `partition_pdf` on a PDF file that includes tables that have been rotated 90° to the left (ie. the top left cell is on the bottom left part of the page). The OCR step does not take into account this and the output text is incorrect. For example: the output text starts with `n o i t a t r o p s n a r T` (`transportation` is the header of the column on the right of the table).

Do I understand correctly that there is no possibility with `partition_pdf` to detect text orientation before performing OCR?

Thanks!

**Comment by christinestraub** [comment]
Hi @vivien000, We don't officially support detecting text orientation before performing OCR on rotated text at the moment, though it's something we could add support for in the future.
