### ISSUE TITLE
bug/Partition Pdf throwing key error

### ISSUE THREAD

**Issue by swathithiyan** [Unstructured-IO/unstructured#2972]
**Describe the bug**
Using the partition_pdf, I am trying to get the detailed extraction of a document in my file system. I have set the strategy as "strategy=PartitionStrategy.FAST". On calling the method am getting error , KeyError
KeyError: '2d2e9ceb1db2bc94a266f3e8b24b8f55'

**To Reproduce**

import os
os.environ['PATH'] = 'Users/swathinarayanan/vir1_env/myenv/bin:/Users/swathinarayanan/.nvm/versions/node/v15.14.0/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/opt/homebrew/Cellar/poppler/24.04.0/bin/:/opt/homebrew/Cellar/poppler/24.04.0/bin/:/opt/homebrew/Cellar/tesseract/5.3.4_1/bin/'

from unstructured.partition.auto import partition_pdf
from unstructured.partition.utils.constants import (
    UNSTRUCTURED_INCLUDE_DEBUG_METADATA,
    PartitionStrategy,
)
elements = partition_pdf(filename="/Users/swathinarayanan/Desktop/Desktop/Jovita/Bank/Federal_bank_IR.pdf",strategy=PartitionStrategy.FAST)
for ele in elements:
    print("Inside for ")
    print(f"Element Id : {ele._element_id}")
    print(f"category Id : {ele.category}")
    print(f"Text Id : {ele.text}")

**Expected behavior**
Document and its metadata to be extracted.

**Screenshots**
If applicable, add screenshots 
<img width="1180" alt="Screenshot 2024-05-06 at 11 27 17 AM" src="https://github.com/Unstructured-IO/unstructured/assets/125479417/c968e9d3-3404-4942-a4e9-c1cd7352e44b">
to help explain your problem.

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

Python 3.9.6 (default, May  7 2023, 23:32:44) 

**Additional context**

**Comment by scanny** [comment]
@swathithiyan This bug was fixed a couple versions back. If you upgrade to the latest release (v0.13.6) this should go away :)
```
$ pip install -U unstructured
```
