### ISSUE TITLE
Following dependencies are missing: pikepdf. Please install them using `pip install pikepdf`.

### ISSUE THREAD

**Issue by OLR-Nadia** [Unstructured-IO/unstructured#2984]
Currently I developing RAG using libraries from langchain and unstructured for read pdf file. but I have an issue and cannot solve the error, which makes it unable to move to the next code.

from unstructured.partition.pdf import partition_pdf
fpath = "files/"
fname = "darlie-brief.pdf"

- Extract elements from PDF
```
def extract_pdf_elements(path, fname):
    """
    Extract images, tables, and chunk text from a PDF file.
    path: File path, which is used to dump images (.jpg)
    fname: File name
    """
    return partition_pdf(
        filename=path + fname,
        # extract_images_in_pdf=True,
        infer_table_structure=True,
        chunking_strategy="by_title",
        max_characters=4000,
        new_after_n_chars=3800,
        combine_text_under_n_chars=2000,
        strategy="fast",
        # image_output_dir_path=path,
    )
```

- Get elements
```
raw_pdf_elements = extract_pdf_elements(fpath, fname)
```

printed error message:

Following dependencies are missing: pikepdf. Please install them using `pip install pikepdf`.
PDF text extraction failed, skip text extraction...

current version I'm using:
- python 3.10.11
- unstructured==0.13.6
- unstructured-client==0.18.0
- unstructured-inference==0.7.29
- unstructured.pytesseract==0.3.12

all libraries installed in venv

**Comment by scanny** [comment]
@OLR-Nadia please paste in the exact error message with full stack trace so we can see where this message is arising.

**Comment by scanny** [comment]
Also, please mention how you installed `unstructured` and what OSS you're on (Linux, macOS, Linux).

**Comment by OLR-Nadia** [comment]
@scanny Hi Steve, for the error message, it shows like the printed messages (see the image with the green mark)
And, I installed `unstructured ` library inside my virtual environment like this (see the image with the blue mark). I'm using Windows 11 OSS.
![image](https://github.com/Unstructured-IO/unstructured/assets/140383979/dbe70ee3-a15a-4b8d-96f7-1e931d02b538)

**Comment by scanny** [comment]
All of these commands should be run after activating your virtualenv.

First, you'll need to install `unstructured` with some extras, minimally:
```bash
> pip install unstructured[pdf]
```

Then you should be able to see `pikepdf` in the list when you run:
```bash
> pip list
```

And this command should produce no error messages:
```bash
> python -c "import pikepdf"
```

If that all works try again and let us know how you go.

**Comment by OLR-Nadia** [comment]
I already followed your instructions and still got the same error message.

![image](https://github.com/Unstructured-IO/unstructured/assets/140383979/ac8e0529-7f36-4e2d-bf22-d673d4b038dd)
![image](https://github.com/Unstructured-IO/unstructured/assets/140383979/54d12227-edcc-40c6-9b20-4a83745af448)
![image](https://github.com/Unstructured-IO/unstructured/assets/140383979/4d810505-89bf-479f-87ea-c1e0e0d6e812)

**Comment by scanny** [comment]
Ok, next thing to try is running this outside of VSCode, like in a terminal/command-line application. I don't completely understand why, but we've had other reports like this where the VSCode terminal was doing something unexpected.

It's possible it's related to the VSCode environment setting: https://code.visualstudio.com/docs/python/environments#_creating-environments

Anyway, we'll want to eliminate VSCode subtleties for diagnostic purposes and running it directly from the command-line in the activated virtualenv should do that.

Btw are you using `conda` for Python and have you checked the installation docs here?:
https://docs.unstructured.io/open-source/installation/full-installation#installation-with-conda-on-windows

**Comment by OLR-Nadia** [comment]
Hi Steve,

I wanted to update you that the issue has been solved. I initially tried installing and uninstalling the library via the command line, outside of VSCode, and encountered a LongPathEnabled issue on my Windows system, which prevented the installation of the unstructured-inference library.

After addressing this, I successfully installed the unstructured-inference and pikepdf libraries separately.

Thank you for your assistance.

**Comment by scanny** [comment]
@OLR-Nadia glad you got it working :)

Can you say any more about the `LongPathEnabled` problem like how it presented itself and how you resolved it? I expect others will face the same problem so it would be a big help here to have an idea how to resolve the problem :)

**Comment by OLR-Nadia** [comment]
Previously, while I was installing the unstructured-inference library, one of the dependencies was stopped installing due to the path being too long (see the warning below)
![image](https://github.com/Unstructured-IO/unstructured/assets/140383979/b69287b9-eee1-42cb-ae2d-9dd9a555973f)

So, I googled it and found that the issue was with the LongPathEnabled setting on my Windows. You can access it by opening the Registry Editor on Windows, searching for LongPathEnabled, and changing the value from 0 to 1 to enable it. If it still can't be changed, try running your laptop as Administrator. After that, I re-installed the libraries and it worked.

Hope this helps!

**Comment by scanny** [comment]
@OLR-Nadia This is terrific, thanks so much for this Nadia! :)

**Comment by ham7a7** [comment]
@OLR-Nadia Well done Nadia, thanks alot.
