### ISSUE TITLE
bug: `starting_page_number` parameter is missing from `partition_image()`

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#2985]
`starting_page_number` argument should be present in all partitioning functions that assign `element.metadata.page_number`. This small change is useful for users who partition only fragments of their PDF documents or images. This is also related to the following issue: https://github.com/Unstructured-IO/unstructured/issues/2461

**Comment by scanny** [comment]
In this particular spot it will be required for properly assigning page-number and hash-element-id metadata to TIFF (scanned image) files that are fragmented for parallel processing.
