### ISSUE TITLE
A bug when parsing pdf!!!

### ISSUE THREAD

**Issue by idiotTest** [Unstructured-IO/unstructured#2994]
**Describe the bug**
I found a bug when i use func `partition_pdf(file=io.BytesIO(file.file.read()), languages=["chi_sim"])` to parse a pdf.
It has two bugs,the one is i found the a element duplicated in elements which is in file `unstructured\documents\elements.py `and in func`wrapper line 447 `,there two  elements are same. 
The another one is in the same file and in func `assign_and_map_hash_ids`. It raises a key error.
**To Reproduce**
I use a big pdf over 10M.It  occurs the bug.And the pdf file is a book about deep learning,which has many pictures and formulas in content.

**Expected behavior**
One is the two element are the same.The other is a key error occurs.
**Screenshots**
![image](https://github.com/Unstructured-IO/unstructured/assets/143317520/defcd517-e724-42aa-9f78-40aeeb23fe7c)

**Comment by idiotTest** [comment]
And I notice that the error key is not in `old_to_new_mapping`'s key,but in it's value?

**Comment by idiotTest** [comment]
and i found that the error key is not in `old_to_new_mapping`'s key,but in it's value

**Comment by idiotTest** [comment]
I think the bug's reason is that: because the duplicated element,and they are the same object.Thus the first element step into the for loop,and it changes it's `e.metadata.parent_id`,Then the second element use the parent_id to search which is in old_to_new_mapping,So it raises a key error. 
In a word,the essential problem is that the elements contains duplicated element objects.I guess the func call happens in the file `unstructured\documents\elements.py`,func `wrapper`,line 558

**Comment by scanny** [comment]
@idiotTest please provide the full stack trace.

Also, try updating to the latest version. This sounds like a bug that was fixed a couple versions back. The stack trace would tell me for sure.

**Comment by idiotTest** [comment]
ok,when i upgrage the version.It fix the bug,thank you.

**Comment by scanny** [comment]
Glad you got it working @idiotTest :)
