### ISSUE TITLE
`partition_msg` is unable to process attachments

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#3006]
To reproduce

```python
from unstructured.partition.auto import partition
from unstructured.partition.msg import partition_msg
import traceback

filename = "example-docs/fake-email-multiple-attachments.msg"
try:
  elements = partition_msg(
    filename=filename, process_attachments=True, attachment_partitioner=partition
  )
except RuntimeError as e:
  print(e)
except:
    print("ERROR about attachments")
    traceback.print_exc()

output_filename = "msg_mul_attach.json"
elements_to_json(elements, filename=output_filename)
```

The error tha arise is:
ValueError: Invalid file /tmp/tmpo99fe8l4/Engineering Onboarding.pptx. The FileType.ZIP file type is not supported in partition.

**Comment by scanny** [comment]
@MthwRobinson This appears to be either a corrupted message or a defect or limitation in `msg_parser` in how it extracts attachments. I'd say next step is either to chalk this up to a fluke and wait for recurrence or to try another `.msg` file that is "known good" (shown to work with Outlook). In any case, this probably shouldn't be a file in `example-docs/` unless it's to demonstrate how we handle this sort of failure and named accordingly.

---

### Diagnostics
I'm able to reproduce this error.

I was able to detach the attachment using `msg_parser`, as `partition_msg()` does. However the attachment is not a valid PPTX file and cannot be opened with PowerPoint.

On attempt to open it with PowerPoint it signals a "repair error":
> PowerPoint found a problem with content in Engineering Onboarding.pptx.
>PowerPoint can attempt to repair the presentation.
>If you trust the source of this presentation, click Repair.

When clicking "Repair" it states:
> Sorry, PowerPoint can't read Engineering Onboarding.pptx.

On inspection, the attachment binary appears to be a zip archive (first two bytes of file are "PK"). However it cannot be unzipped and fails with this message:
```bash
$ unzip Engineering\ Onboarding.pptx
Archive:  Engineering Onboarding.pptx
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Engineering Onboarding.pptx or
        Engineering Onboarding.pptx.zip, and cannot find Engineering Onboarding.pptx.ZIP, period.
```

**Comment by MthwRobinson** [comment]
Sounds good, I'll update this issue to reflect removing that document from `example-docs`, and we can keep an eye out for other examples of corrupted files.

**Comment by MthwRobinson** [comment]
More info from the user:

>Any of the emails are processed as ok  if the attachments aren´t processed (process_attachments=False).
The email with one attachment in the official documentation is processed without error ([this email](https://github.com/Unstructured-IO/unstructured/blob/main/example-docs/fake-email-attachment.msg)). The attachment is a txt. The email has NO images.
The attached email "Sample_one_Attachments.msg" with a txt attached file retrieves me an error about an image (PIL.UnidentifiedImageError: cannot identify image file '/tmp/tmptfxudk4_/image004.png').  The attachment is a txt. The email has images. Be aware that if  process_attachments=False the email is processed without error, including the images  in the body of the email  .
The attached email "Sample_two_Attachments.msg" is the same email that in the previous bullet  but with two txt attached files, it retrieves me the same error about an image (PIL.UnidentifiedImageError: cannot identify image file '/tmp/tmptfxudk4_/image004.png').  The attachments are txt files. The email has images. Be aware that if  process_attachments=False the email is processed without error, including the images  in the body of the email  .
The attached email "Sample_Multiple_Attachments.msg" is the same email that in the previous bullet  but with 4 attachments, one txt, one image .png, one docx and one pptx. The processing of this email retrieves me the same error about an image (PIL.UnidentifiedImageError: cannot identify image file '/tmp/tmptfxudk4_/image004.png').  Be aware that if  process_attachments=False the email is processed without error, including the images in the body of the email.

**Comment by scanny** [comment]
This turned out to be a defect in `msg_parser`. When replaced with `python-oxmsg` for parsing MSG files this and other attachments are extracted fine.
