### ISSUE TITLE
partition_pdf is loading the model at every call

### ISSUE THREAD

**Issue by SkanderHellal** [Unstructured-IO/unstructured#3058]
I am using partition_pdf to extract content from pdf file.
However, object detection models and table structure recognition are loaded at every call.
In addition to that, we  cannot change models with table extraction for example.

**Comment by MthwRobinson** [comment]
Thanks for the issue @SkanderHellal . We'll discuss and follow up

**Comment by amadeusz-ds** [comment]
Hi @SkanderHellal, how did you notice that the model is loaded every time?
What are the steps to reproduce?

**Comment by amadeusz-ds** [comment]
@SkanderHellal I was not able to reproduce this issue - both detection and table transformer models initialized for only a single time.
Please share steps to reproduce your issue.
