### ISSUE TITLE
Add support for pinecone serverless indexes

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#3068]
#3067 updates the `pinecone-client` version to v4 to support attribution. Per the [pinecone docs](https://docs.pinecone.io/reference/pinecone-clients#initialize), this will also allow us to support serverless specs for serverless indexes. The goal of this issue is to add serveless specs to the connector, and also add a CLI kwarg for users to pass the spec in as a JSON string.

**Comment by potter-potter** [comment]
@MthwRobinson Definitely a good idea. I asked @ahmetmeleq what the lift for this was a couple months ago:
"We'll need to introduce modes (serverless / pod), control some parameters depending on the mode, and bump pinecone from 2.x to 3.x . Doesn't seem like it requires other major changes but bumping the version might introduce other incompatibility with our previous implementation, there is uncertainty there"

**Comment by MthwRobinson** [comment]
@potter-potter - Yeah #3067 takes care of the migration (actually from 2.x to 4.x) so we should be in good shape to support this now.
