### ISSUE TITLE
Support additional options in the Reddit connector

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#308]
The [Reddit connector](https://github.com/Unstructured-IO/unstructured/pull/293) is great for fetching posts from subreddit's with a search query. However, there are some capabilities that could be added. This issue is to track potential additions, but note that PR's may be submitted for any one of these at a time!

* also ingest comments for all processed posts
* README suggestions on how to format search strings, e.g. by flair_name
* Filtering by date

There are certainly more!

**Comment by tomaarsen** [comment]
Wonderful suggestions! I considered the inclusion of comments. How would you recommend formatting them within the temporary markdown file? For example, with or without the inclusion of usernames? And how about nested comments? Or should we only fetch top-level comments?

- Tom Aarsen

**Comment by cragwolfe** [comment]
Those are good questions! One way to look at is there are couple of end use cases that are highly different: 1/ curating LLM training content and 2/ building hierarchal well-defined structured data (sort of like wikidata).

For 1/ the easy way out is to actually introduce text like "Comment by <user2> in response to .... [some end delimiter] Comment by <user5>.... [some end delimiter]  " appended to the markdown (ignoring nested for now for the sake of discussion).

For 2/, the above idea (1/) is awful, actually "editing" the data in some sense. To do this correctly, the metadata needs to be tracked somehow. One way to do this is:

* store the comment text or markdown in its own file (similar to how posts are stored now) in the download dir, e.g. `comment_12452.md`
* store a metadata file beside it in the download dir beside it, e.g. `comment_12452.md-metadata.json` This file could include `"comment_on": <post_id>`, ...`

When the structured data gets written, the attributes in the metadata files are passed on as additional fields in the metadata of elements in the structured data. E.g., "comment_on": <post_id>.
 
These aren't mutually exclusive. I have pretty firm conviction that metadata will get added to elements to represent herirarcy and context that is domain specific, however anything that is capable downstream of just processing the basic `Elements` can still do so and just ignore that extra metadata.
 
 1 and 2 aren't mutually exclusive. IMO, 1 is perfectly fine in the short term, as long as it is clear to the user what they are getting.
