### ISSUE TITLE
docx  - error while parsing table with merged cells

### ISSUE THREAD

**Issue by veredmm** [Unstructured-IO/unstructured#3139]
**Describe the bug:**

error while parsing table with merged cells : 

**AttributeError: '_Row' object has no attribute 'grid_cols_before'**

**To Reproduce**
Provided a sample word file with table and spanned cells 

[table_span.docx](https://github.com/user-attachments/files/15533653/table_span.docx)

noting that the error is raised in version 0.14.3 and didn't show up when i used version 0.12.6

**Comment by scanny** [comment]
Closing since I'm pretty confident that's going to solve the problem, but feel free to reopen if you're still getting an error.
