### ISSUE TITLE
feat/Retain text indentations in PDF files

### ISSUE THREAD

**Issue by ChiNoel-osu** [Unstructured-IO/unstructured#3146]
**Is your feature request related to a problem? Please describe.**
All text indentations and some line breaks are lost in partitioned PDF files. If there're code blocks in the PDF file, the extracted elements can't represent them.

**Describe the solution you'd like**
Retain indentations and line breaks in documents.

**Describe alternatives you've considered**
I see that there's a PR related: https://github.com/Unstructured-IO/unstructured/pull/2428. But idk.

**Additional context**
My test PDF is as simple as this:
![image](https://github.com/Unstructured-IO/unstructured/assets/39649720/2b83b897-587a-46b4-84ea-f9fb705911a0)

After `partition_pdf()`, the element's text looks like this:
![image](https://github.com/Unstructured-IO/unstructured/assets/39649720/96f9042c-9755-4048-9960-9d550fbc4f52)
Which does not retain any format that might be crucial for understanding what a block of text means.

**Comment by MthwRobinson** [comment]
Hi @ChiNoel-osu - closing this one in favor of #711, which would track indent level as a metadata field
