### ISSUE TITLE
Local API Error: `by_similarity` Chunking Strategy Not Recognized

### ISSUE THREAD

**Issue by eduardolundgren** [Unstructured-IO/unstructured#3155]
**Describe the bug**
When running the Docker image `quay.io/unstructured-io/unstructured-api:0.0.68` locally, the chunking strategy `by_similarity` fails to work as expected.

**To Reproduce**
1. Start the Docker container with `quay.io/unstructured-io/unstructured-api:0.0.68`.
2. Run the following `curl` command:

```bash
curl -X POST http://localhost:30000/general/v0/general \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'unstructured-api-key: <YOUR_API_KEY>' \
  -F 'files=@Sample.pdf' \
  -F 'strategy=auto' \
  -F 'chunking_strategy=by_similarity'
```

**Expected behavior**
The API should process the request using the by_similarity chunking strategy without errors.

**Actual behavior**
The API returns an error indicating that the chunking_strategy should be by_title:

```
{
  "detail": [
    {
      "type": "literal_error",
      "loc": ["body", "chunking_strategy"],
      "msg": "Input should be 'by_title'",
      "input": "by_similarity",
      "ctx": {"expected": "'by_title'"}
    }
  ]
}
```

**Environment**

Docker Image: quay.io/unstructured-io/unstructured-api:0.0.68
Local machine setup

**Additional context**
This issue occurs consistently with the latest image. It seems that the API does not recognize the by_similarity chunking strategy, even though it is documented.

**Comment by shreyanid** [comment]
Hi @eduardolundgren ! The `by_similarity` chunking strategy is only available through the Unstructured hosted APIs, not locally (mentioned [here](https://docs.unstructured.io/api-reference/api-services/chunking#by-similarity-chunking-strategy) at the top of the section of that strategy)

**Comment by tangkunyin** [comment]
> Hi @eduardolundgren ! The `by_similarity` chunking strategy is only available through the Unstructured hosted APIs, not locally (mentioned [here](https://docs.unstructured.io/api-reference/api-services/chunking#by-similarity-chunking-strategy) at the top of the section of that strategy)

So, is there any way to use a local embedding model by input any config fields? If not, hopefully it will be supported,great thanks to you
