### ISSUE TITLE
LangChain + Unstructured: Failed to load file ${filePath} using unstructured loader.

### ISSUE THREAD

**Issue by ajaykrupalk** [Unstructured-IO/unstructured#3158]
I am using LangChain's Azure Storage Blob Container Loader to load some JSON files but I am not able to do the same. But the same files as .txt works. 

I am getting the below mentioned error for JSON files:
`Failed to load file ${filePath} using unstructured loader. Error: Failed to load file C:\Users\DELL\AppData\Local\Temp\azureblobfileloader-ePGCee\log2.json using unstructured loader.`

My files are primarily JSON files which are logs for APIs. Also is there a way to just get a particular key from JSON rather than the whole JSON file. The code that I have used is as below

```js
import { AzureBlobStorageContainerLoader } from "@langchain/community/document_loaders/web/azure_blob_storage_container"
import { UnstructuredLoader } from "@langchain/community/document_loaders/fs/unstructured";

const loader = new AzureBlobStorageContainerLoader({
    azureConfig: {
        connectionString: "<connection_string>",
        container: "<container>",
    },
    unstructuredConfig: {
        apiUrl: "http://localhost:8000/general/v0/general",
        apiKey: "<api_key>", // this will be soon required
        logging: true
    },
});
```

**Comment by tbs17** [comment]
hi @ajaykrupalk , thanks for bringing up the issue. Would you mind also pasting code about how you  load in your `${filePath}` using unstructured?

**Comment by ajaykrupalk** [comment]
Closing this, used an alternative to this by using a custom function and changed the unstructured module to a native JSON loader from LangChain
