### ISSUE TITLE
TypeError: UnstructuredClient.__init__() got an unexpected keyword argument 'retry_connection_errors'

### ISSUE THREAD

**Issue by Neel-132** [Unstructured-IO/unstructured#3172]
just trying to use the code from here 
![image](https://github.com/Unstructured-IO/unstructured/assets/71507677/c0dc4a3f-ae73-4314-8b81-477e36950a47)
But getting this error
TypeError: UnstructuredClient.__init__() got an unexpected keyword argument 'retry_connection_errors'

My environment
PyMuPDF==1.24.4
unstructured[all-docs]==0.14.0
nltk==3.8.1
pandas==2.2.2
llama-index==0.10.38
llama-parse==0.4.3
PyPDF2==3.0.1
fastapi==0.111.0
minio==7.2.7
uvicorn==0.29.0
psutil==5.9.8
boto3==1.34.109
botocore==1.34.109

**Comment by awalker4** [comment]
Ah, looks like there's a typo in the retries section! The retry_connection_errors is meant to go in the RetryConfig object

**Comment by Neel-132** [comment]
Yes. Also there is again the same network issue. Please confirm whether you guys are fixing something or not

**Comment by awalker4** [comment]
I believe the majority of the issues have been resolved, but I can double check your account for you. Can you please send a note to support@unstructured.io with your custom url?

**Comment by Neel-132** [comment]
Hi, it worked.
