### ISSUE TITLE
Sensitive data security issues

### ISSUE THREAD

**Issue by arkim822** [Unstructured-IO/unstructured#3178]
Hello,

I am trying out the local installation of unstructured 

`pip install unstructured`

and I see it has some interaction with Hugging Face. Is the data being that is being parsed (pdfs) being sent their to run on Hugging Face's servers or is everything being run locally?

Thank you.

**Comment by MthwRobinson** [comment]
Hi @arkim822 - all processing with the `unstructured` library is performed locally. The only interaction with huggingface is to download document understanding models for processing PDFs and images. Once the model files are downloaded, no network connection is required. See below for the recommended pattern for downloading the required models.

https://github.com/Unstructured-IO/unstructured/blob/c822e3fd10026639b8183846008263ff5b6b02a9/Dockerfile-amd64#L36-L39

**Comment by arkim822** [comment]
Hi @MthwRobinson, I appreciate the quick response. That's great to hear :) 

I'll let my peers know.
