### ISSUE TITLE
Unstructured paid API stuck again

### ISSUE THREAD

**Issue by Neel-132** [Unstructured-IO/unstructured#3181]
**My current environment is:**
PyMuPDF==1.24.4
unstructured[all-docs]==0.14.0
nltk==3.8.1
pandas==2.2.2
llama-index==0.10.38
llama-parse==0.4.3
PyPDF2==3.0.1
fastapi==0.111.0
minio==7.2.7
uvicorn==0.29.0
psutil==5.9.8
boto3==1.34.109
botocore==1.34.109

**My retry config parameters are:**
![image](https://github.com/Unstructured-IO/unstructured/assets/71507677/a6230b91-01f0-4038-b10b-8fd4713c1dc3)

**My unstructured client object is:**
![image](https://github.com/Unstructured-IO/unstructured/assets/71507677/f5da5edb-cc9d-47f0-b31a-c19a9225765a)

**This is the logs from the API:**
![Screenshot 2024-06-11 110657](https://github.com/Unstructured-IO/unstructured/assets/71507677/9e761d2e-e152-402f-993e-529039323f4e)

Its just stuck from the last half and hour.

Please assist with this. Its urgent as the servers are stuck because of this

**Comment by awalker4** [comment]
Apologies for all the issues here. We've stabilized the service and it should be working again. For transparency, we're very close to a brand new release of the hosted api. We've revamped the architecture to avoid these problems happening again. I'd recommend jumping into our [community slack](https://short.unstructured.io/pzw05l7) for updates.
