### ISSUE TITLE
bug/<ocr-agent> call PartitionPdf error: no ocr_agent found

### ISSUE THREAD

**Issue by ZephryLiang** [Unstructured-IO/unstructured#3202]
**Describe the bug**
my code:
os.environ["OCR_AGENT"] = "unstructured.partition.utils.ocr_models.paddle_ocr.OCRAgentPaddle"
elements = partition_pdf(file=f, ocr_agent=ocr_agent,strategy='ocr_only')
error :
Environment variable OCR_AGENT must be set to an existing OCR agent module, not unstructured.partition.utils.ocr_models.paddle_ocr.OCRAgentPaddle.

**Expected behavior**
i want to extract elements from pdf, how can do this?

**Comment by LiangZeFenglzf** [comment]
error message in the source code :   
 def get_agent(cls) -> OCRAgent:
        """Get the configured OCRAgent instance.

        The OCR package used by the agent is determined by the `OCR_AGENT` environment variable.
        """
        ocr_agent_cls_qname = cls._get_ocr_agent_cls_qname()
        try:
            return cls.get_instance(ocr_agent_cls_qname)
        except (ImportError, AttributeError):
            raise ValueError(
                f"Environment variable OCR_AGENT must be set to an existing OCR agent module,"
                f" not {ocr_agent_cls_qname}."
            )
what agent can i use? please!

**Comment by MthwRobinson** [comment]
Closing in favor of #3187. Looks like the same issue.

**Comment by christinestraub** [comment]
Hi @LiangZeFenglzf, You need to install additional dependencies to use PaddleOCR. You can use the following shell script to use those dependencies:
```
#!/usr/bin/env bash

# aarch64 requires a custom build of paddlepaddle
if [ "${ARCH}" = "aarch64" ]; then
  python3 -m pip install unstructured.paddlepaddle
else
  python3 -m pip install paddlepaddle
fi
pyth
```on3 -m pip install unstructured.paddleocr

Also, you don't need to pass the `ocr_agent` param, so
```
os.environ["OCR_AGENT"] = "unstructured.partition.utils.ocr_models.paddle_ocr.OCRAgentPaddle"
elements = partition_pdf(file=f, strategy='ocr_only')
```

**Comment by LiangZeFenglzf** [comment]
soryy about this.it doesn't work

**Comment by LiangZeFenglzf** [comment]
> Hi @LiangZeFenglzf, You need to install additional dependencies to use PaddleOCR. You can use the following shell script to use those dependencies:
> 
> ```
> #!/usr/bin/env bash
> 
> # aarch64 requires a custom build of paddlepaddle
> if [ "${ARCH}" = "aarch64" ]; then
>   python3 -m pip install unstructured.paddlepaddle
> else
>   python3 -m pip install paddlepaddle
> fi
> python3 -m pip install unstructured.paddleocr
> ```
> 
> Also, you don't need to pass the `ocr_agent` param, so
> 
> ```
> os.environ["OCR_AGENT"] = "unstructured.partition.utils.ocr_models.paddle_ocr.OCRAgentPaddle"
> elements = partition_pdf(file=f, strategy='ocr_only')
> ```

it doesn't work.pip list found: paddlepaddle                             2.6.1

**Comment by christinestraub** [comment]
@ZephryLiang, please mention how you installed unstructured and what versions of libraries (`unstructured`, `unstructured-inference`) and OSS you're on (Linux, macOS).

**Comment by liuxu4567** [comment]
I'm having the same issue with the latest container version I'm using，the error stack is 
"ImportError: /home/notebook-user/.local/lib/python3.11/site-packages/paddle/fluid/libpaddle.so: cannot open shared object file: No such file or directory"  ,  but the libpaddle.so file is exists

**Comment by christinestraub** [comment]
@ZephryLiang We've updated exception handling when getting an OCR agent here: https://github.com/Unstructured-IO/unstructured/issues/3202. Can you please run your code again and provide us error traces?

**Comment by ZephryLiang** [comment]
> @ZephryLiang We've updated exception handling when getting an OCR agent here: #3202. Can you please run your code again and provide us error traces?

you`re so nice! i try again,no error happens!
