### ISSUE TITLE
Images in headers

### ISSUE THREAD

**Issue by famda** [Unstructured-IO/unstructured#3216]
Hi,

Is it possible to detect if an image is part of a header when partition a pdf?

Thanks in advance.

**Comment by MthwRobinson** [comment]
`Header` and `Image` are different types are mutually exclusive, so an image in a document will be tagged as one or the other. Both elements return coordinates though. My recommendation would be to check if an `Image` element appears in the uppermost 5% or 10% of the document based on the `metadata.coordinates` since the position would likely indicate that it's a header.

**Comment by huangpan2507** [comment]
> `Header` and are different types are mutually exclusive, so an image in a document will be tagged as one or the other. Both elements return coordinates though. My recommendation would be to check if an element appears in the uppermost 5% or 10% of the document based on the since the position would likely indicate that it's a header.`Image``Image``metadata.coordinates`

hi， @MthwRobinson , I had a question about to get the coordinates, does it must use model="elements"  to get coordinates?

            ```
loader = UnstructuredPDFLoader(file_path=file_name, 
                                            mode="elements",
                                            include_page_break=False,
                                            infer_table_structure=True,
                                            languages=["Eng","chi_sim"],
                                            strategy="hi_res",
                                            extract_images_in_pdf=True,
                                            # Post processing to aggregate text once we have the title
                                            extract_image_block_output_dir=self._img_path,
                                            form_extraction_skip_tables = False,
                                            include_metadata=True,
                                            max_characters=3500,
                                            new_after_n_chars=1500,
                                            combine_text_under_n_chars=250)
            documents = loader.load()
```
