### ISSUE TITLE
Process Attachments available via Paid API

### ISSUE THREAD

**Issue by jeremydiba** [Unstructured-IO/unstructured#3243]
**Is your feature request related to a problem? Please describe.**
Currently, the paid API lacks a number of features that the open source version handles.
One such feature is the ability for emails to process their attachments

**Describe the solution you'd like**
adding an email_process_attachments parameter to the api

**Describe alternatives you've considered**
supporting kwargs (python) that can pass to the underlying function (ex. parse_email)

**Comment by MthwRobinson** [comment]
Thanks @jeremydiba . I'm going to close this out since it relates to the paid API and not the open source library. However, I've opened an issue internally with our API team requesting this feature.

**Comment by josaum** [comment]
any updates on when this will be available in API?
