### ISSUE TITLE
BUG - PPTX doesn't recognize text within slide notes

### ISSUE THREAD

**Issue by veredmm** [Unstructured-IO/unstructured#3256]
pptx/ppt parsing.  the text inside the notes of the slide does not appear in the elements output

Unstructured 0.14.3,  python-pptx         0.6.23

Reproduce:

Parse example file, notice the text of the notes in slide 2 does not appear in elements array

[test_remark.pptx](https://github.com/user-attachments/files/15908686/test_remark.pptx)

**Comment by scanny** [comment]
Thanks for reporting @veredmm, I'll have a look.

**Comment by scanny** [comment]
@veredmm `partition_pptx()` only includes slide notes when so instructed with an `include_slide_notes=True` argument. The default is `False`.

This file partitions as expected on my machine when using that argument.
