### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ishansuhail** [Unstructured-IO/unstructured#3260]
I am utilizing an Unstructured API key with a custom endpoint. Yesterday, the API functioned correctly, extracting content from a PDF. However, today, I am encountering an error message:

HTTPSConnectionPool(host='******', port = 443): Max retires exceeded with url: /general/v0/general (Caused by SSLEOFError(8, 'EOF occured in violation of protocol (_ssl.c:2427)')))

This is how I am calling the API: 
`

                 data = file.read()
                filename = file.name

                req = operations.PartitionRequest(
                        partition_parameters=shared.PartitionParameters(
                            files=shared.Files(
                                content=data,
                                file_name=filename,
                            ),
                           
                            
                            strategy = "hi_res",
                            languages=['eng'],
                        ),
                )
    

                try:
                    res = fileClient.general.partition(request=req)
                   
                    json_content = json.dumps(res.elements, indent=2)
               except Exception as e:
                   print(e)

`

![image](https://github.com/Unstructured-IO/unstructured/assets/134439038/b138bc88-35ae-4190-8fd2-60361feeb522)

Any help would greatly appreciate :)

**Comment by kamgreenwald** [comment]
I am having this same issue, any help would be great.

**Comment by badGarnet** [comment]
> _ssl.c:2427

Hi @ishansuhail ,

Thanks for submitting this issue. You mentioned custom endpoint so I assume you are trying to reach an URL that was sent to you with your API key when you first created your account with SaaS API? If that was the case you should update the URL to our new endpoint `api.unstructuredapp.io`. If you did not receive an email notifying the change please email support@unstructured.io so we can make sure your account is properly migrated to the new cluster.

Thanks,
Yao

**Comment by ishansuhail** [comment]
Hi @badGarnet, our endpoint looks like this https://******.api.unstructuredapp.io

**Comment by MthwRobinson** [comment]
Going to close this out since it relates to the paid API and not the open source library. @ishansuhail - please reach out to support@unstructured.io if you need additional assistance with the API.
