### ISSUE TITLE
bug/<tables getting cut off at the edges when using hi res strategy>

### ISSUE THREAD

**Issue by rchen19** [Unstructured-IO/unstructured#3262]
**Describe the bug**
I'm using unstructured to partition pdfs and extract tables. I'm using the `hi_res` strategy and `yolox` model, and still a lot of the images and tables are being extracted with the edges cut off resulting in a loss of information. And this is true for both extracted tables as images and recognized text content where the first letter of each row would be missing from the html table code block.

I am aware of environment variables `EXTRACT_IMAGE_BLOCK_CROP_HORIZONTAL_PAD` and `EXTRACT_IMAGE_BLOCK_CROP_VERTICAL_PAD` and have experimented with them. Adjusting them only affect the extracted image, where with large paddings, I was able to obtain complete screenshots of the tables, but the recognized texts (as html table block) were still missing the first letter of each row. Is this intended behavior, i.e., these padding env variables only affect the crop box used to crop the tables out as images, but not the text recognition?

I am aware of this [issue](https://github.com/Unstructured-IO/unstructured/issues/2561) but it does not address this problem.

For example, with both padding set to 50:

the extracted table as image looks like this:
<img width="660" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/29267183/966eca9c-f472-41c7-a15c-fcbcec934dbe">

and recognized table texts as html table looks like this after rendered in browser:

<img width="319" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/29267183/6e5087a2-2218-436c-9f40-ee91bdbdeedc">

**Comment by christinestraub** [comment]
Similar to https://github.com/Unstructured-IO/unstructured/issues/2997, recommend using the API for access to higher performance table extraction models.

**Comment by MthwRobinson** [comment]
Per @christinestraub 's suggestion, please try our new [serverless API](https://unstructured.io/api-key-hosted) if you need better performance for table extraction.
