### ISSUE TITLE
Clean up warning table transformer warning statements statements 

### ISSUE THREAD

**Issue by magallardo** [Unstructured-IO/unstructured#3288]
Using table transformer in `unstructured` produces the following warning statement. The goal of this issue is to clean up the warnings. The original issue description is posted below.

```
Some weights of the model checkpoint at microsoft/table-transformer-structure-recognition were not used when initializing TableTransformerForObjectDetection: ['model.backbone.conv_encoder.model.layer2.0.downsample.1.num_batches_tracked', 'model.backbone.conv_encoder.model.layer3.0.downsample.1.num_batches_tracked', 'model.backbone.conv_encoder.model.layer4.0.downsample.1.num_batches_tracked']
- This IS expected if you are initializing TableTransformerForObjectDetection from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TableTransformerForObjectDetection from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
```

---------
Original issue

**Describe the bug**
I am getting the following when calling partition_pdf

from unstructured.partition.pdf import partition_pdf
path = "/app/example-docs/"
fname = "list-item-example.pdf"
raw_pdf_documents = partition_pdf(
...         filename=path + fname,
...         extract_images_in_pdf=False,
...         infer_table_structure=True,
...         chunking_strategy="by_title",
...         max_characters=4000,
...         new_after_n_chars=3800,
...         combine_text_under_n_chars=2000,
...         image_output_dir_path=path,
... )
Some weights of the model checkpoint at microsoft/table-transformer-structure-recognition were not used when initializing TableTransformerForObjectDetection: ['model.backbone.conv_encoder.model.layer2.0.downsample.1.num_batches_tracked', 'model.backbone.conv_encoder.model.layer3.0.downsample.1.num_batches_tracked', 'model.backbone.conv_encoder.model.layer4.0.downsample.1.num_batches_tracked']
- This IS expected if you are initializing TableTransformerForObjectDetection from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TableTransformerForObjectDetection from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

**To Reproduce**
Just run the code above

**Expected behavior**
No errors or warnings when running partition_pdf

**Screenshots**

**Environment Info**
Docker image running on MacPro Intel Core i9

Docker container is started as follow:

create the container
docker run -dt --name unstructured downloads.unstructured.io/unstructured-io/unstructured:latest

this will drop you into a bash shell where the Docker image is running
docker exec -it unstructured bash

**Additional context**

**Comment by MthwRobinson** [comment]
Hi @magallardo - are you using the `arm64` image? And are you getting an error or just warnings?

**Comment by MthwRobinson** [comment]
@magallardo - Were you able to get output from `partition_pdf`? `raw_pdf_documents` should be a list of `Element` objects

**Comment by magallardo** [comment]
@MthwRobinson Thanks for the update.  
As for your question, the operation is getting some output.  I just wanted to make sure if this is actually returning valid responses or if the operation was not completing as the message is not very clear.

Thanks
Marcelo

**Comment by MthwRobinson** [comment]
Got it, thanks for clarifying @magallardo . Yeah your output is valid.  We run the unit tests from inside the docker container during our build process and the outputs get checked then.

That said, we should suppress those warning statements so people don't worry. I'll update the scope of this issue to reflect that.

**Comment by atangsyd** [comment]
@MthwRobinson this is giving me different outputs to what I had before, when it did not give me that warning and the quality of outputs is slightly worse. Can you please look into this further as it might be a bigger issue than initially thought. This issue seems to have only come up recently so may be some of the underlying packages you are using might have changed?

**Comment by MthwRobinson** [comment]
Thanks @atangsyd we'll take a look. FYI @leah1985

**Comment by hasansalimkanmaz** [comment]
I also get the warning and receive relevant outputs. However, this warning message from HuggingFace seems to be an important one in my opinion. Though the model outputs relevant elements, I believe it is not performing with its full potential as not the all parameters are loaded correctly.

**Comment by scanny** [comment]
Closing, assumed resolved.
