### ISSUE TITLE
bug/issue parsing html file

### ISSUE THREAD

**Issue by JulioBarros** [Unstructured-IO/unstructured#332]
**Describe the bug**
With 0.4.13 I'm able to parse http://paulgraham.com/getideas.html and get "January 2023(Someone fed my ..." but with 0.5.1 I only get the text "January 2023Someone". Note the paren is missing and it may be confusing the system.

**To Reproduce**
import requests
from unstructured.partition.auto import partition

filename = "paul.html"
res = requests.get("http://paulgraham.com/getideas.html")
with open(filename, "wt") as f:
    f.write(res.text)

elements = partition(filename=filename)
print("\n\n".join([str(el) for el in elements]))

<outputs> January 2023(Someone

**Expected behavior**
I expect the whole content of the html file.  Version 0.4.13 generates a 789 character string of the whole document.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Na
 - Python version 3.11 and 3.10

**Additional context**
None, other than I did not try the other intermediate versions.
[EDIT] Actually I just tried it with 0.5.0 and it worked so the issue may be with 0.5.1

Thanks.
Julio

**Comment by alvarobartt** [comment]
Can this be related somehow to https://github.com/Unstructured-IO/unstructured/pull/309? @MthwRobinson

**Comment by LaverdeS** [comment]
Maybe this is relate to this changes introduced in [this](https://github.com/Unstructured-IO/unstructured/commit/350c4230eeca1b317b85668940df1d2103b3dede) commit.

**Comment by MthwRobinson** [comment]
@JulioBarros - Will have a fix up for this shortly. By the way, you can use `partition_html` to partition via a URL directly like this so you don't need save the file locally:

```python
from unstructured.partition.html import partition_html

url = http://paulgraham.com/getideas.html 
elements = partition_html(url=url)
```
