### ISSUE TITLE
Add support for parsing tables from documents

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#334]
The goal of this issue is to add support for parsing information from tables in documents.

**Comment by gracew99** [comment]
+1

**Comment by glecorve** [comment]
+1

**Comment by mosnicholas** [comment]
+1

**Comment by pk-lit** [comment]
+1

**Comment by tomaarsen** [comment]
What is the expected output for tabular data?

**Comment by glecorve** [comment]
Thanks for taking this ticket.

As far as I have seen in other tools, this can be either simply tabulated texts or more structured (e.g., list of lists where each sublist is a row and details the content of each colum, information about merged rows...).

**Comment by zzy9v4** [comment]
+1

**Comment by savicbo** [comment]
+1. Would also like to add a +1 for the idea of including support for merged rows, especially in headers. I have found JSON output format very flexible for this use case and easily interpretable by LLMs though at the cost of a few more tokens.

**Comment by MthwRobinson** [comment]
Closing this issue out since most document types support table extraction now
