### ISSUE TITLE
partition_xlsx for  table -  split the table to multiple  sub tables and cell values recognized as text 

### ISSUE THREAD

**Issue by veredmm** [Unstructured-IO/unstructured#3357]
**Describe the bug**

A "sparse" table (but in unifed structured)  is splited into multiple tables 

in the attached example i got 4 different table

**and also another issue :**
when the is a **single cell with value** in the table it became a text element and not part of the table as it should ( see elements with value 13,14,31 in rows (11,12,15)

**To Reproduce**
file for example 
[part_table.xlsx](https://github.com/user-attachments/files/16125675/part_table.xlsx)

**Expected behavior**
one table with all the data inside

**Screenshots**
table :
![image](https://github.com/Unstructured-IO/unstructured/assets/169882103/acc3e0ad-397a-45d6-a682-57a0d3f24cc2)
output :

![image](https://github.com/Unstructured-IO/unstructured/assets/169882103/83137a5c-6f99-4b1a-9878-55dadf1120d6)

unstructured                            0.14.3

**Comment by scanny** [comment]
@veredmm this is the expected "find-subtables" behavior.

If you prefer to have each worksheet parsed as a single table, add a `find_subtable=False` argument to your call to `partition_xlsx()`.
https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/xlsx.py#L56
