### ISSUE TITLE
Unable to process two docs under example-docs/

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#338]
**Describe the bug**

Attempting to parse `example-docs/factbook.xml` or `example-docs/fake-email-header.eml` results in an error, "File type not support in partition." All other docs in `example-docs/` are able to be partitioned without an error.

**To Reproduce**

```
from unstructured.partition.auto import partition
>>> partition("example-docs/factbook.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cragwolfe/r/unstructured/unstructured/partition/auto.py", line 72, in partition
    raise ValueError(f"{msg}. File type not support in partition.")
ValueError: Invalid file example-docs/factbook.xml. File type not support in partition.
```

Discovered by running the script: https://github.com/Unstructured-IO/unstructured/blob/main/examples/ingest/github/ingest.sh

**Expected behavior**
The call to `.partition()` succeeds

**Desktop (please complete the following information):**

 - OS: mac m1
 - Python version 3.8.15
 - on `main` `HEAD` which is currently 
 ```
 f5af87a Tom Aarsen      2023-03-02      feat: Expose Wikipedia `auto_suggest` argument to the ingest CLI (#336)
 ```

**Comment by MthwRobinson** [comment]
For this one `example-docs/factbook.xml` isn't a bug, we don't support partitioning that file type at the moment. We'll take a look at `example-docs/fake-email-header.eml`.

**Comment by tomaarsen** [comment]
For context, `example-docs/fake-email-header.eml` is considered `message/rfc822` by libmagic, whereas all of the other email files are considered `text/plain` instead.
