### ISSUE TITLE
partition_pdf does not work without HF connectivity 

### ISSUE THREAD

**Issue by niravshah** [Unstructured-IO/unstructured#3428]
Hi Team,

We are behind a corporate proxy and unable to access HF. We do have the unstructured libraries and ecosystem scanned and secure downloaded to our internal artifactory. However, when I use partition_pdf, the kernel just hangs without any output or errors. After some research today, I discovered that unstructured tries to download Detectron from HF and I believe this is what is causing the hanging kernel.

Is there a way to just use text detection without it trying to download from HF?

**Comment by scanny** [comment]
Closing as I believe this has been resolved. @niravshah please feel free to reopen if you're still having trouble.
