### ISSUE TITLE
bug/ partition_pdf omits extractable text

### ISSUE THREAD

**Issue by JMTarraga** [Unstructured-IO/unstructured#3430]
partition_pdf() correctly detects the table, but it does not include within the element the numbers as text in the table. These numbers are indeed detected by the **process_file_with_pdfminer()** function.

![image](https://github.com/user-attachments/assets/092079fb-7c35-4e60-83b7-bbf776efaba5)

This information dissapears with the clean_pdfminer_inner_elements() and clean_pdfminer_duplicate_image_elements() functions.

Element text: 

'Affectations to houses and public buildings Quantity Houses affected Houses flooded Houses destroyed Other buildings affected Collapsed walls'

**To Reproduce**
elements = partition_pdf(filename=pdf_path, 
                        include_page_breaks=True, 
                        strategy="hi_res",  
                        extract_image_block_types=['Image', 'Table'],
                        model_name="yolox",
                        infer_table_structure=False, 
                        extract_image_block_to_payload=True)

**Expected behavior**
Output the table numbers in the unstructured element text. 

[18466.pdf](https://github.com/user-attachments/files/16345111/18466.pdf)

**Comment by christinestraub** [comment]
Addressed in https://github.com/Unstructured-IO/unstructured/pull/3618
