### ISSUE TITLE
bug/astra-rebrand

### ISSUE THREAD

**Issue by erichare** [Unstructured-IO/unstructured#3447]
**Describe the bug**
Astra should be rebranded to Astra DB

**To Reproduce**
Attempt to install or import the package, note that the name is Astra

**Expected behavior**
It should be Astra DB / astradb to better fit the DataStax branding

**Comment by scanny** [comment]
The ingest code where this occurs moved to the `unstructured-ingest` project and it appears the desired changes were made as part of that migration.
