### ISSUE TITLE
bug/Unable to parse EML files with MSIP Labels

### ISSUE THREAD

**Issue by TaylorN15** [Unstructured-IO/unstructured#3449]
**Describe the bug**
When processing an e-mail in EML format using `partition_email` no content is extracted when there are MSIP (Microsoft Information Protection) Labels in the header.

**To Reproduce**
[ExampleEmail.eml.txt](https://github.com/user-attachments/files/16433935/ExampleEmail.eml.txt)
```
from unstructured.partition.email import partition_email
elements = partition_email(filename="ExampleEmail.eml")
print(elements)
```

I'm not really sure why this is occuring, but when I remove the `msip_labels` from the file, it get's parsed properly. Otherwise, it seems to only extract `multipart/mixed`, `multipart/related`, `multipart/alternative` into the `content_map` in `email.py` which is not in `VALID_CONTENT_SOURCES`

**Comment by TaylorN15** [comment]
Some debugging I have done, I added the below to line 361 in [email.py](https://github.com/Unstructured-IO/unstructured/blob/8fd216cc9fbb25704281e50f498a92f169b462b6/unstructured/partition/email.py#L361)

```
    for part in msg.walk():
        print(f"Content Disposition Type: {part.get_content_disposition()}")
        print(f"Content Type: {part.get_content_type()}")
        print(f"Content Main Type: {part.get_content_maintype()}")
        print(part.get_payload())
```

Which produces the following output:

```
Content Disposition Type: None
Content Type: multipart/mixed
Content Main Type: multipart
[<email.message.Message object at 0x000001FC5317F5D0>]
Content Disposition Type: None
Content Type: multipart/related
Content Main Type: multipart
[<email.message.Message object at 0x000001FC5317D5D0>]
Content Disposition Type: None
Content Type: multipart/alternative
Content Main Type: multipart
[<email.message.Message object at 0x000001FC5317F8D0>]
Content Disposition Type: inline
Content Type: text/plain
Content Main Type: text
Hi

=20

Please find attached a project proposal.

Please let us know if you have any questions or would like to discuss=
 anything at this stage.

=20

Kind regards

User

=20
```

But it doesn't add the `text/plain` part to the content_map here `content_map[content_type] = part.get_payload()`.

**Comment by scanny** [comment]
@TaylorN15 I expect this is a limitation in the Python email parser.

You can see the partitioning code starts off with parsing the email using the Python stdlib `email` module:
https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/email.py#L370

I suppose I would start by trying the various `partition_email()` options for specifying the email file, like file-path, file open binary ("rb"), file open text ("r"), and text/str modes just to rule out that being a factor.

Then I'd open it directly with Python to see what I could learn by poking around and inspecting the `EmailMessage` object produced by parsing directly.

Then I'd search Google for known problems with Python's `email` module parsing these particular headers.

Then I suppose I'd be looking for a way to strip those particular headers out automatically as a pre-step before partitioning.

Let me know how you go and maybe I'll think of something else :)

**Comment by TaylorN15** [comment]
I will have a crack if/when I find some time :)
I did already try the various options for loading the file and the result was the same.

**Comment by TaylorN15** [comment]
So I think it's just an issue with the assumption [here](https://github.com/Unstructured-IO/unstructured/blob/24a1f298e50b466c3350ac7c4faf8b94a3dddc1f/unstructured/partition/email.py#L390). I don't think we should be ignoring the part if the Content Disposition isn't `None`. In this case, Content Disposition is `inline` and Content Description is `Message text` which I believe is valid for an EML file, no?

After looking at this again, it might not have anything to do with the MSIP labels, I am thinking because I removed those headers, it began reading from "Received: " then the entire file is processed as `text/plain`. 

Example code:

```
for part in msg.walk():
    content_disposition = part.get_content_disposition()
    content_description = part.get('Content-Description')
    
    # Include parts with None disposition or inline disposition with Message text description
    if not (content_disposition is None or (content_disposition == 'inline' and content_description == 'Message text')):
        continue
```

**Comment by scanny** [comment]
Hmm, that sounds right to me. `"inline"` means "show this text on the screen" as I read the spec, as opposed to others like `"attachment"` that mean "show it as available for download" or whatever.

I'm guessing that `None` or "omitted" essentially means "inline" by default, at least that's the way that code seems to be treating it.

If you just change that test to `if part.get_content_disposition() not in (None, "inline):`, does that produce the behavior you would expect?

**Comment by TaylorN15** [comment]
Yes that seems to work well. My proposed solution only includes the latest message/email, yours includes all the text within the e-mail chain (my actual e-mail I am testing with is different than the sample I provided, I just cut it down for testing/debugging).

I shall create a PR :)

**Comment by scanny** [comment]
This SO question seems to confirm this theory: https://stackoverflow.com/questions/48975613/content-disposition-for-email-body

Only question in my mind is whether it could also be used for other things, like maybe an image, and if that would screw anything up if we added that to the content-map. A quick review seems to indicate it wouldn't be a problem though, just a dict entry we would never go looking for.

It sounds like a fix to me :)

**Comment by TaylorN15** [comment]
I just tested with an e-mail that had an image in it. I see an image added to the content_map but it didn't seem to cause any issues.
