### ISSUE TITLE
bug/multipage_sections not working

### ISSUE THREAD

**Issue by KOG-Nisse** [Unstructured-IO/unstructured#3453]
**Describe the bug**
The chunk contains elements from more than one page even though 

**To Reproduce**
        chunks = chunk_by_title(
            data,
            max_characters=self.character_limit,
            multipage_sections=False,
            include_orig_elements=True,
        )

        for c in chunks:
            page_size = None
            last_e = None
            for e in c.metadata.orig_elements:
                new_page_size = e.metadata.coordinates.system.__dict__
                new_e = e
                print("page", e.metadata.page_number)
                if page_size is not None and page_size != new_page_size:
                    raise ValueError("BUG")
                page_size = new_page_size
                last_e = new_e

**Expected behavior**
Only one page number for all elements in the chunk.

**Environment Info**
OS version:  Windows-10-10.0.22631-SP0
Python version:  3.11.9
unstructured version:  0.14.10
unstructured-inference version:  0.7.36
pytesseract version:  0.3.10
Torch version:  2.4.0+cu121
Detectron2 is not installed
PaddleOCR version:  2.8.1
Libmagic is not installed

**Additional context**
I have libmagic installed with pip.

The two page pdf is image based. No text highlighting.

**Comment by KOG-Nisse** [comment]
Quick FIX       
      
      pages: dict[int, list[Element]] = {}
      for element in data:
          if element.metadata.page_number not in pages:
              pages[element.metadata.page_number] = []
          pages[element.metadata.page_number].append(element)
      for _, elements in pages.items():
          yield from self._chunk_page(elements)

    def _chunk_page(self, data: Iterable[Element]) -> Iterable[Chunk]:
        chunks = chunk_elements(
            data,
            max_characters=self.character_limit,
            include_orig_elements=True,
        )
       return chunks

**Comment by scanny** [comment]
This is a side-effect of the `combine_text_under_n_chars` parameter on `chunk_by_title()` which defaults to whatever value is provided for `max_characters`. This essentially removes the segregation guarantee added by `multipage_sections=False`. To ensure two elements from different pages do not appear in the same chunk, set `combine_text_under_n_chars` to `0`.
