### ISSUE TITLE
OCR needs improvement for some scanned images

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#347]
At least for images similar to a scanned 1980's fax, OCR is not working especially well.

See https://github.com/Unstructured-IO/unstructured/issues/346 for details.

This is with regard to OCR on a JPG, whereas #346 relates to OCR on PDFs.

**Comment by MthwRobinson** [comment]
Per @benjats07 , this could be related to bounding boxes not containing the text in the image.

**Comment by SimranJha2408** [comment]
Can we close this @MthwRobinson @cragwolfe ?

**Comment by cragwolfe** [comment]
This is completed now, there is a file in the ingest tests that falls into that category that has the .json output here: https://github.com/Unstructured-IO/unstructured/blob/main/test_unstructured_ingest/expected-structured-output/azure/IRS-form-1987.pdf.json
