### ISSUE TITLE
bug/pdf-splitting-not-case-sensitive

### ISSUE THREAD

**Issue by jeremydiba** [Unstructured-IO/unstructured#3485]
**Describe the bug**
When a file extension is .PDF instead of .pdf, file splitting does not work as intended 

```
INFO: Preparing to split document for partition.
WARNING: Given file doesn't have '.pdf' extension. Continuing without splitting.
WARNING: File could not be split. Partitioning without split.
parsing data/Douglas Corp/Hazardous Waste/Remedial Investigation Report - 5-14-2010 - DOUGLAS CORP PLATING DIVISION - RCRA1186.PDF
```

**To Reproduce**
take a pdf file and give extension .PDF
process file setting split_pdfs=true

**Expected behavior**
PDF file is split

**Screenshots**

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

**Additional context**

**Comment by scanny** [comment]
This is actually a behavior of the `unstructured-python-client` library, but closing it as assumed resolved because I see some activity over there to address this.
