### ISSUE TITLE
bug/chunking table header is extracted in the text but not in the metadata.text_as_html

### ISSUE THREAD

**Issue by ajpanyteam** [Unstructured-IO/unstructured#3487]
**Describe the bug**
Using TS SDK, chunking 'by_title'.  For some tables, header is missing.

 Header is extracted in the text but not in the metadata.text_as_html, instead the header has **e** in it.

` 'metadata': {'text_as_html': '<table><thead><tr><th></th><th>**e**</th><th>**e**</th></tr></thead><tbody><tr><td>R...
`
**To Reproduce**

PDF File has already been shared with internal team by Ronny.  I am unable to post the file publicly.

**Expected behavior**
The header getting extracted.

**Screenshots**
<img width="2014" alt="image" src="https://github.com/user-attachments/assets/09195000-2b59-4b43-9a70-5aa4a3155d54">

**Environment Info**
 Nodejs sdk "unstructured-client": "^0.14.0"

**Additional context**
I suspect it has to do with the format

**Comment by scanny** [comment]
Closing as inactive. Please feel free to reopen if you're still having trouble :)
