### ISSUE TITLE
`partition_image` function always generates a `figures` folder

### ISSUE THREAD

**Issue by johnathanchiu** [Unstructured-IO/unstructured#3503]
Is there a way to prevent `partition_image` imported by `from unstructured.partition.image import partition_image` to not create a `figures` folder. I looked through the source code and docs briefly but can't seem to find where this is coming from.

**Comment by scanny** [comment]
@johnathanchiu can you provide the minimum source code that produces this behavior?

**Comment by johnathanchiu** [comment]
The following will output a `figures` directory inside the running directory.

```
from unstructured.partition.image import partition_image
image_file = "" # Set path to any image
partition_image(
    filename=image_file,
    strategy="hi_res",
    extract_image_block_types=["Image", "Table"],
    extract_image_block_to_payload=True,
)
```
