### ISSUE TITLE
bug/Error installing pdf extra - unstructured 0.15.3

### ISSUE THREAD

**Issue by kaushikabhishek87** [Unstructured-IO/unstructured#3521]
**Describe the bug**
While running pip install "unstructured[pdf]==0.15.3" getting below error 
```
ERROR: No matching distribution found for pytesseract>=0.3.12; extra == "pdf"
```

pytesseract 0.3.10 is latest https://pypi.org/project/pytesseract/#history

**To Reproduce**
pip install "unstructured[pdf]==0.15.3"

**Expected behavior**
PDF dependencies should get installed as were iin 0.15.1 or prior

**Screenshots**

**Environment Info**
Python version:  3.12.3

**Additional context**

**Comment by cbornet** [comment]
Is it possible to publish 0.15.4 to pypi ?

**Comment by kaushikabhishek87** [comment]
Waiting for same

**Comment by cbornet** [comment]
It will probably be 0.15.5 on pypi. See https://github.com/Unstructured-IO/unstructured/pull/3528

**Comment by MthwRobinson** [comment]
Hi everyone - `0.15.5` is now available on PyPI. Appreciate the patience, there were a few issues that popped up this week that we were juggling simultaneously.
