### ISSUE TITLE
Google Drive Ingest: Unable to process Google Doc (linux only)

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#354]
**Describe the bug**

When using`unstructured-ingest` to process a Google Drive folder, Google Doc's within that folder are not successfully processed on Linux only. On Mac, no problem. Other file types (PDF, DOCX, etc) are successfully processed on both platforms.

**To Reproduce**
```
PYTHONPATH=. ./unstructured/ingest/main.py \
    --drive-id 1-tmwZFqlXFJXg0urvmbNcnBdIb92TuKc \
    --drive-service-account-key <path-to-service-account-creds.json> \
    --structured-output-dir google-drive-ingest-output \
    --num-processes 2 \
    --drive-recursive \
    --verbose 
```

**Expected behavior**
Google Doc's are processed normally, text elements are extracted.

**Linux**
 - Python 3.8.15
 - Unstructured commit [c51adb2](https://github.com/Unstructured-IO/unstructured/commit/c51adb21e31ff05ae7b70dcaf45eadf809105f72)

**Comment by HAKSOAT** [comment]
Hi @cragwolfe What was the error here? It seems to work on my Linux machine (WSL). Python 3.9.
