### ISSUE TITLE
chore: add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/unstructured#3540]
This repo does not have a CONTRIBUTING.md doc. Contributors have [noted this](https://github.com/Unstructured-IO/unstructured/pull/3267#issuecomment-2295566629) and suggested info that would be useful to include in it. We have an [existing guide](https://github.com/Unstructured-IO/community/blob/main/CONTRIBUTING.md) in the community repo, but that repo has been archived and we do not have any links pointing to that guide.

**Comment by ribhu97** [comment]
I can take this up

**Comment by Coniferish** [comment]
Thanks @ribhu97! Feel free to reach out if you have any questions
