### ISSUE TITLE
bug/confusion - 0.15.7, 0.15.6, 0.15.8-dev0

### ISSUE THREAD

**Issue by kaushikabhishek87** [Unstructured-IO/unstructured#3552]
**Describe the bug**
Hi, I am trying to download the latest version of unstructured io with NLTK vulnerability removed, seems like there is difference between changelog & pypi release. 
As per change log - Version 0.15.6 resolved NLTK vulnerability.
But on pypi there is a new version 0.15.7 that has no mention in change log
There is another version 0.15.8-dev0 in change log talking about issues with NLTK. Should we wait for 0.15.8 to be released for issues resolution around NLTK, looking for some pointers. Thanks for all the hard work. 

**To Reproduce**
Provide a code snippet that reproduces the issue.

**Expected behavior**

**Screenshots**

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

**Additional context**

**Comment by kaushikabhishek87** [comment]
Not actually a bug not sure what is the right label

**Comment by MthwRobinson** [comment]
Hi @kaushikabhishek87 - you should upgrade to `unstructured>=0.15.7` and `nltk>=3.9.0` to resolve the vulnerability.
