### ISSUE TITLE
algorithm underlying table extract and parsing

### ISSUE THREAD

**Issue by naarkhoo** [Unstructured-IO/unstructured#3576]
Hi, 

I tried to search on your website, also here within the code; basically, how can I figure out what algorithm are you using for detecting, extracting tables and turning them into html tags. Or what algorithm are you using to parse the layout of a page. 

I am asking, because I am benchmarking multiple methods, and I wonder if I should cite/use your pipeline or rather the original model. 

Thank you

**Comment by MthwRobinson** [comment]
Hi @naarkhoo - the open source library uses table transformer for table extraction. Check out the model card below for details.

- https://github.com/Unstructured-IO/model-cards/blob/main/TATR/model_card_tatr_opensource.md

**Comment by naarkhoo** [comment]
Thanks for the answer and sorry to bring up this again; 
But I also meant the content and of the table which is turned into HTML;
seems TATR is only doing 1)table detection 2)table structure recognition (rows, columns). so I wonder how text/numbers from tables are extracted and eventually compiled into HTML
