### ISSUE TITLE
bug/Docker image import unstructured failed

### ISSUE THREAD

**Issue by guici123** [Unstructured-IO/unstructured#3590]
**Describe the bug**
I downloaded the latest image, but failed to import unstructured，how should I operate？

**To Reproduce**
Provide a code snippet that reproduces the issue.
![image](https://github.com/user-attachments/assets/07732e43-b0c3-45d5-8c51-6c6708516e12)

**Comment by guici123** [comment]
urgent，urgent，urgent

**Comment by MthwRobinson** [comment]
@guici123 - Could you share the command you're using to start the container?

**Comment by guici123** [comment]
> @guici123 - Could you share the command you're using to start the container?@guici123 - Could you share the command you're using to start the container?@guici123 - 您能否分享用于启动容器的命令？

# create the container
docker run -dt --name unstructured downloads.unstructured.io/unstructured-io/unstructured:latest

# this will drop you into a bash shell where the Docker image is running
docker exec -it unstructured bash

**Comment by guici123** [comment]
> > @guici123 - Could you share the command you're using to start the container?@guici123 - Could you share the command you're using to start the container?@guici123 - 您能否分享用于启动容器的命令？

> docker run -dt --name unstructured downloads.unstructured.io/unstructured-io/unstructured:latest
> docker exec -it unstructured bash

@MthwRobinson Looking forward to your reply

**Comment by vignesht30** [comment]
You should run python3 in a different directory, possibly under /app. For me, it worked because you can see the unstructured folder there.

**Comment by scanny** [comment]
Closing as inactive, assumed resolved.
