### ISSUE TITLE
bug/file type detection fallback strategy not working

### ISSUE THREAD

**Issue by WHALEEYE** [Unstructured-IO/unstructured#3596]
**Describe the bug**
The following line tried to detect whether `libmagic` has been installed, but it actually only detects the installation of python-magic package instead of the true `libmagic` dependency.

https://github.com/Unstructured-IO/unstructured/blob/acd070c5d5064bcf6b98106e335e8145a5f183a3/unstructured/file_utils/filetype.py#L58

Therefore, as long as python-magic is installed, LIBMAGIC_AVAILABLE will always be True, and if libmagic is not installed, import magic will cause an error.

**Comment by scanny** [comment]
Fixed by #3828, out later this week.
