### ISSUE TITLE
bug/Unable to download NLTK data

### ISSUE THREAD

**Issue by TaylorN15** [Unstructured-IO/unstructured#3617]
**Describe the bug**
Since the change was made to no longer use nltk.download() my application cannot download the required NLTK packages. The application is behind a firewall and we are only allowed to except specific traffic, and a public S3 bucket is proving difficult to get approved. 

I get an error when it attempts to download the packages:

`<urlopen error [Errno 104] Connection reset by peer>`

**To Reproduce**
Use a partitioner that requires NLTK

**Expected behavior**
NLTK package download doesn't fail

**Additional context**
Perhaps there is a way to include the required NLTK packages or pre-download them before the application is zipped and deployed?

**Comment by Falven** [comment]
This sounds like an IT problem, if you're behind a firewall how do you expect to download any NLTK packages?
I would recommend you Dockerize and cache the dependencies, building your container somewhere with internet access.
`RUN python -m nltk.downloader -d $NLTK_DATA stopwords punkt averaged_perceptron_tagger`

**Comment by TaylorN15** [comment]
We already have an exception for the NLTK packages as they are downloaded from GitHub, and this exception was already in place to allow certain Python packages and Oryx builds to work. 

I'm just saying that someone else may encounter this same issue, as most IT departments won't allow access to an unknown public S3 bucket.

**Comment by scanny** [comment]
Closing as inactive. Please feel free to reopen if you're still having trouble. Some changes since the last comment seem to have remedied this.
