### ISSUE TITLE
error in reading and parsing elements from file

### ISSUE THREAD

**Issue by prashanthin** [Unstructured-IO/unstructured#3640]
Hi,

I am using unstructured for Multimodal rag use case, for below code I am getting below error.
However I have pytesseract installed, path defined and added in system properties and working fine for individual images too. 

error-
unstructured_pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

Code -
- raw_pdf_elements = partition_pdf(
    filename="IF10244.pdf",
    extract_images_in_pdf=True,
    infer_table_structure=True,
    chunking_strategy="by_title",
    max_characters=4000,
    new_after_n_chars=3800,
    combine_text_under_n_chars=2000,
    image_output_dir_path="/",
)

Can you please help in resolving this issue for me?

**Comment by scanny** [comment]
@prashanthin Tesseract is a separate OCR package that must be installed on your machine. On a Mac it's `brew install tesseract`. Otherwise have a Google on "install tesseract" for the operating system you're using :)
