### ISSUE TITLE
bug/html parsing incorrectly categorizing text

### ISSUE THREAD

**Issue by bhoppeadoy** [Unstructured-IO/unstructured#3666]
**Describe the bug**
The html parser is incorrectly categorizing a set of divs as different text types. There are three divs, one right after each other and each div is categorized as UncategorizedText, Title, and NarrativeText. These should all be the same text category and definitely not a title category.

**To Reproduce**
Parse the attached html file. Examine the elements created for these three div ids SBOS510440, SBOS5102933, SBOS5105314

< div id="SBOS510440" class="textnote">< span class="section-label">1. </ span>V< sub>IN</ sub> = +V< sub>S</ sub> + 500 mV.</ div>

< div id="SBOS5102933" class="textnote">< span class="section-label">2. </ span>TVS: +V< sub>S(max)</ sub> &gt; V< sub>TVSBR (Min)</ sub> &gt; +V<sub>S</ sub> </ div>

< div id="SBOS5105314" class="textnote">< span class="section-label">3. </ span>Suggested value is approximately 5 k&#937; in overvoltage conditions.</ div>

` 
elements = partition_html(text=html_text)
`
[electrical-overstress-sbos8126148.zip](https://github.com/user-attachments/files/17152101/electrical-overstress-sbos8126148.zip)

**Expected behavior**
Expect these to three divs to be the same text category, but not a title category

**Screenshots**
Here's the list of elements for the three divs:

![elements](https://github.com/user-attachments/assets/a5fc1226-cfee-4569-baba-b559695a2168)

**Environment Info**
OS version:  Linux-6.1.83-4.ph5-x86_64-with-glibc2.28
Python version:  3.10.14
unstructured version:  0.15.13
unstructured-inference is not installed
pytesseract is not installed
Torch is not installed
Detectron2 is not installed
PaddleOCR is not installed
Libmagic version: file-5.33
magic file from /etc/magic:/usr/share/misc/magic

**Comment by scanny** [comment]
Yep, good call. I'll sort this out.
