### ISSUE TITLE
bug/Names of interface elements in text output after partition

### ISSUE THREAD

**Issue by SlawaLoev-KSO** [Unstructured-IO/unstructured#3725]
**Describe the bug**
When partitioning `partition("/path/file.doc")` I seem to receive also names of interface elements (from libreoffice?) in the text output such as:  

- `Luisteren`
- `Fonetisch lezen`
- `Woordenboek - Gedetailleerd woordenboek weergeven`

Note: The text itself is in English, as is my system -- these elements are for some reason in Dutch (I am indeed in the Netherlands).

**To Reproduce**
```
from unstructured.partition.auto import partition

elements = partition("/path/file.doc")

print("\n".join([str(el) for el in elements[:100]]))
```

**Expected behavior**
I would not expect interface elements to be part of the processed output.

**Comment by scanny** [comment]
@SlawaLoev-KSO can you be more specific about what you mean by "interface elements"? For example, do you mean menu-bar options perhaps? or something like form-field labels?

**Comment by SlawaLoev-KSO** [comment]
tbh I don't exactly know what it is -- just weird words (sounding like it could be interface elements) in the text output that are not in the .doc itself, I just guessed at what it is.

**Comment by scanny** [comment]
Can you share an example document?

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by scanny** [comment]
Closing as inactive. Please feel free to reopen if you're still having trouble :)
