### ISSUE TITLE
Minio + Unstructured + Weaviate

### ISSUE THREAD

**Issue by naelsen** [Unstructured-IO/unstructured#3726]
Hey everyone,

I have 2 questions:
Is it possible to establish a connection directly between my self-hosted unstructured API and S3 via a connector ? The goal would be to request the API with s3 url instead of local file, which will allow the API to access my s3 data provider.

Also I need something else but is it possible to set up a streaming unstructured ETL? For example when I add new data in S3 then unstructured process it immediately and could ingest data in an another database (weaviate in my case)

I have one weaviate container, an unstructured-api container running and my minio container that is S3 compatible.

Thank you for your help !

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by scanny** [comment]
Closing as inactive, but @naelsen you might ask on the Unstructured Slack channel as that is monitored by more folks :)
