### ISSUE TITLE
PDF partitioner duplicates text

### ISSUE THREAD

**Issue by ivan-p92** [Unstructured-IO/unstructured#374]
Hi, while using `UnstructuredPDFLoader`, we noticed that the text content gets duplicated in the PDF partitioner. First, all elements are added one by one with the page's metadata, and then again, without metadata:

https://github.com/Unstructured-IO/unstructured/blob/f6d787d95ba7abea0fa14c089dbd7f18a8541b87/unstructured/partition/pdf.py#L253-L257

The last line in this snippet should probably be removed, right?

**Comment by cragwolfe** [comment]
Thanks for reporting this @ivan-p92!
