### ISSUE TITLE
feat/html_parser - adding "verify=False" for URL getting 

### ISSUE THREAD

**Issue by ventz** [Unstructured-IO/unstructured#383]
**Is your feature request related to a problem? Please describe.**

Yes - When utilizing unstructured's URL parser (with LangChain's) to parse URLs, certain urls produce a `unable to get local issuer certificate`, due to a missing chain/older CA (this is the case with many .GOV urls).

Python's `certifi` is up to date.

This is not a unstructured problem obviously -- there is clearly a CA chain missing. The same happens with Python's `requests` module (even though `certifi` is up to date), and wget, etc obviously. 

However, there is no way to pass/override the requests `verify` parameter with unstructured's implementation.

**Describe the solution you'd like**

Adding the ability to add a `verify=False` flag to pass thru to Python's `requests.get(url, verify=False)`
In instances where one does not control the remote website, this is very much needed in order to parse the html.

**Describe alternatives you've considered**

Downloading the html pages manually/directly, and parsing them as HTML files instead. However, when utilizing this with LangChain's, it is very convenient just to utilize the URL parser.

**Additional context**
```
.pyenv/versions/3.10.0/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
```

Example:

```
import requests

url = 'https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXV/Chapter93A/Section1'

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0  Safari/537.36'
}

response = requests.get(url, headers=headers)
print(response)
```

**Comment by MthwRobinson** [comment]
Thanks @ventz ! Have PR up for this, we'll push this out in the next release.

**Comment by ventz** [comment]
@MthwRobinson That's great to hear - thank you!
