### ISSUE TITLE
feat/Ability to read code files

### ISSUE THREAD

**Issue by techytushar** [Unstructured-IO/unstructured#387]
**Is your feature request related to a problem? Please describe.**
Can we add support for reading code files, currently when I try to read `.py` files it throws the following error:
```
The FileType.UNK file type is not supported in partition.
```

**Describe the solution you'd like**
It would be good to add support for all type of code files. We can treat them as basic text files maybe and add extra functionality later on. 

**Describe alternatives you've considered**
An alternative that I can currently see is to read the files manually and use the string to create documents

**Additional context**
NA

**Comment by robertofabrizi** [comment]
@techytushar Dear techytushar, may I ask you why you marked this as completed? From what I see in the docs, unstructured still doesn't support code files (splitting them on \n isn't really of any use). It's be nice for it to be able to parse a git repo and split java or xml or python with the proper code splitter.
