### ISSUE TITLE
feat/complexity-estimation

### ISSUE THREAD

**Issue by theZaX** [Unstructured-IO/unstructured#392]
**Is your feature request related to a problem? Please describe.**
I'd like to reject files that will take too long, even with the fast option I have one pdf that took 3 minutes, but was deceptively small (10mb) so my size limit didn't work, I'd like to have the option to reject that sort of file.
[CS 252 TEXTBOOK.pdf](https://github.com/Unstructured-IO/unstructured/files/11043433/CS.252.TEXTBOOK.pdf)

**Describe the solution you'd like**
a way to estimate the complexity of a file and throw if it's over a certain threshold (in unstructured-api)

**Describe alternatives you've considered**
We used to have a word limit when we did processing as a conversion -> partition -> embed process. Now we just use unstructured for conversion and partition and aren't able to know if it will take a long time before it does. 

**Additional context**
For the most part our users interact with Unstructured backed features in "interactive mode", waiting for it to process before moving on so processing time is a big deal for us.

**Comment by cragwolfe** [comment]
In this particular case, the PDF is ~480 pages. I think number of pages would be a rough heuristic here that the client could use to estimate the complexity / time to serve.

Closing for now as this is not likely something to be prioritized soon. In the weeks and months ahead, we also expect substantial performance (latency) gains.
