### ISSUE TITLE
feat/html-categorization

### ISSUE THREAD

**Issue by theZaX** [Unstructured-IO/unstructured#393]
**Is your feature request related to a problem? Please describe.**
When we start letting our users just give us a url (that we use puppeteer get the html of) there is a ton of garbage that’s also on the site that isn’t of interest. We don’t have the luxury of knowing that all the content of interest is inside of a certain tag. But we'd like to partition and embed the relevant pieces of it.

**Describe the solution you'd like**
A categorization of content based on their descendance of content of interest (main, section and article tags) this would allow content to be filtered and basic logic performed (when we search for relevance using semantic search we can prefer descendants of main content and only use auxiliary content if it doesn't have a lot of main content or if the auxiliary / garbage content is really the most relevant.)

**Describe alternatives you've considered**
preprocessing using JSOM. This is subideal because it isn't "partitioning aware" I'd like to add the filtering as a step during the search phase after embedding.

**Comment by MthwRobinson** [comment]
@theZaX - Just wanted to follow up and let you know we're tracking this one. Tag information is already tracked in the elements for HTML output, I think this would be a matter of adding that information to the element metadata so it's available downstream.
