### ISSUE TITLE
feat/html-recursive

### ISSUE THREAD

**Issue by zhqu1148980644** [Unstructured-IO/unstructured#401]
**Does your feature request address a specific problem? If so, please describe it.**

No, I simply want to be able to recursively parse a website's HTML and all of its hyperlinks, similar to the feature supported by wget.

**What solution would you like implemented?**

I would like options(depth, url pattern match, domains) added that enable recursive parsing, just as wget supports.。”

**Describe alternatives you've considered**

**Additional context**

**Comment by MthwRobinson** [comment]
@zhqu1148980644 - Just wanted to follow up and let you know we're tracking this one. The recursive fetching part may be a little out of scope for this library but at a minimum I think grabbing the hyperlinks makes sense.
