### ISSUE TITLE
feat/python-wheel

### ISSUE THREAD

**Issue by stanleychris2** [Unstructured-IO/unstructured#424]
Trying to add unstructured to the base image of our product (patterns.app) so all our customers can use it, but we need a wheel to do so. Any chance you can produce a wheel instead of a source only distribution for us?

**Comment by MthwRobinson** [comment]
@stanleychris2 - Thanks for the suggestion, we'll add a wheel along with the tar for upcoming releases. In the meantime you can generate a wheel if you clone the repo and run:
```
git checkout 0.5.8
python setup.py bdist_wheel
```

**Comment by MthwRobinson** [comment]
@stanleychris2 - We updated our package publishing job to produce a wheel along with the `.tar.gz` source distributions. We'll have a wheel available on PyPI starting with the next release.

**Comment by MthwRobinson** [comment]
In case you haven't seen them, the `unstructured` wheel is available on PyPI now:
- https://pypi.org/project/unstructured/#files

**Comment by stanleychris2** [comment]
Thank you!
