### ISSUE TITLE
Is this an unnecessary encode?

### ISSUE THREAD

**Issue by pandazki** [Unstructured-IO/unstructured#436]
When I tried to use partition_epub to process a Chinese book, I found that the output was incorrect. Through debugging, I found that this encode step caused the final error. However, I'm not sure if it's effective in other situations, so I dare not make a PR rashly.

[document_tree = etree.fromstring(content.encode(), self.parser)
](https://github.com/Unstructured-IO/unstructured/blame/b746cb0ab4c1693b3ee2bd8ddc25e6b5fa68b57e/unstructured/documents/xml.py#L58)

**Comment by pandazki** [comment]
I have only tested 2 EPUBs and the situation is the same.

Here is a screenshot of the code debugging for version 0.5.8.
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/754493/229557848-b4ed1b0d-265e-4a1c-af40-3d0d04c69a3d.png">

And just change the line which mentioned above `document_tree = etree.fromstring(content, self.parser)`
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/754493/229558939-0d609aa7-aefb-4ffc-a2b3-923683336a23.png">
Everything is correct.

**Comment by MthwRobinson** [comment]
Got it, thanks a lot!

**Comment by nakamichiworks** [comment]
I tried to process Japanese epub with `partition_epub()` and ran into the same problem.
I would appreciate if the problem could be fixed.

**Comment by MthwRobinson** [comment]
@pandazki @nakamichiworks - Just released the fix for this in `0.5.11`
