### ISSUE TITLE
 Error when installing "unstructured[local-inference]"

### ISSUE THREAD

**Issue by richard1912** [Unstructured-IO/unstructured#438]
Error when using >pip install "unstructured[local-inference]"

![image](https://user-images.githubusercontent.com/59070720/229402222-27dcedde-a9fb-4c69-a590-6161c1ee49e3.png)

**Comment by MthwRobinson** [comment]
@richard1912 - If you're running on Windows you'll need to install MSFT C++ Build tools for `pycocotools`.

refs:
- https://unstructured-io.github.io/unstructured/installing.html#installation-with-conda-on-windows
- https://visualstudio.microsoft.com/visual-cpp-build-tools/
- https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst
