### ISSUE TITLE
Update `partition_pdf` and `partition_image` to use GPUs when available and strategy is set to "hi_res"

### ISSUE THREAD

**Issue by DoctorSlimm** [Unstructured-IO/unstructured#441]
The goal of this issue is to update `partition_pdf` and `partition_image` to use GPUs when available. Currently, the model only runs against CPUs. This will entail updates to `unstructured-inference`.

**Comment by MthwRobinson** [comment]
@DoctorSlimm - `partition_pdf` and `partition_image` do not use GPUs at the moment. Updated this issue to add GPU support for `partition_pdf` and `partition_image`. Thanks for adding this issue! cc @qued .

**Comment by Balearica** [comment]
@SimranJha2408 Was this issue closed as completed properly?  I don't see evidence that this feature was added. 

Per the title, this issue appears to track whether GPUs are used in `partition_pdf` and `partition_image` when `strategy` is set to `HI_RES`.  The only PR that is linked (#865) was closed (not merged).  Additionally, that PR does not appear to be directly related to this issue.  It looks like that PR would change the default `strategy` to `HI_RES` if a GPU is detected and `strategy` is not set explicitly, which is distinct from whether or not GPU is used when `strategy` is set to `HI_RES` by the user.

**Comment by MthwRobinson** [comment]
Hi @Balearica - this feature was not added. We do plan to add GPU support for our API in spring or summer.

**Comment by ChiNoel-osu** [comment]
At the moment `tesseract` in `unstructured` is only using 1 CPU core and it's so slow. Would be great if we could have GPU accellerated OCR.
Even better, split document by page and run multiple `tesseract` at the same time.

**Comment by MthwRobinson** [comment]
Thanks for the comment @ChiNoel-osu . If you're interested in trying out our API, the [`unstructured-python-client`](https://github.com/Unstructured-IO/unstructured-python-client) splits up long PDFs so you can parallelize across pages within the doc.
