### ISSUE TITLE
partition_ppt parsing the ppt, the content is empty

### ISSUE THREAD

**Issue by chen-lee-li** [Unstructured-IO/unstructured#442]
When I use partition_ppt parsing the ppt file, the content cannot be parsed and the result is empty
```
[Document(page_content='', metadata={'source': '[./CV_Cheng](https://file+.vscode-resource.vscode-cdn.net/c%3A/code/parseppt/CV_Cheng) Binkui.pptx'})]
```

**Comment by MthwRobinson** [comment]
@chen-lee-li - We haven't been able to reproduce this error. Are you able to provide an example that reproduces it?

**Comment by MthwRobinson** [comment]
Closing this one because we weren't able to replicate. We can reopen it if someone provides an example or reproducible code snippet we can use for testing.
