### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 19: invalid start byte

### ISSUE THREAD

**Issue by mbalsam-refind** [Unstructured-IO/unstructured#444]
**Describe the bug**
When I attempt to process an EML messages using the html.py  i get this error

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 19: invalid start byte

from

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\unstructured\cleaners\core.py:137, in replace_mime_encodings(text)
130 def replace_mime_encodings(text: str) -> str:
131 """Replaces MIME encodings with their UTF-8 equivalent characters.
132
133 Example
134 -------
135 5 w=E2=80-99s -> 5 w’s
136 """
--> 137 return quopri.decodestring(text.encode()).decode("utf-8")

Im actually calling it from Langchain, but my guess is that its using HTML.py

**To Reproduce**
You would need an email file. I can provide if required.

**Expected behavior**
Not throw an exception 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows, mac, linux]
 - Python version [e.g. 3.8.15]
 
OS: windows 
Python: 3.10

**Additional context**
My guess is this is related to 

TODO(robinson) - There's likely a cleaner was to accomplish this and get all of the
unicode characters instead of just the quotes. Doing this for now since quotes are
an issue that are popping up in the SEC filings tests

One way to fix be to allow other decoder arguments other utf-8 

return quopri.decodestring(text.encode()).decode("utf-8")

I believe that 

https://stackoverflow.com/questions/46000191/utf-8-codec-cant-decode-byte-0x92-in-position-18-invalid-start-byte

says to  use ('ISO-8859-1')

**Comment by mbalsam-refind** [comment]
I cloned the project and made  that change and it worked.

**Comment by MthwRobinson** [comment]
@mbalsam-refind - Opened #453 to allow for passing through an `encoding` kwarg. I was trying to reproduce the `UnicodeDecodeError` exception but couldn't find a string that tripped it. Do you have an example of a string that raises the exception so we can add a test?

Thanks for reporting this issue!

**Comment by MthwRobinson** [comment]
Nevermind we're all good, found a good input to test against. We'll push the fix out in the next release.

**Comment by mbalsam-refind** [comment]
I think i found the file that does it.  I don't know if i can get a string.   I'll stop digging now.  But if you need it i can find it. 

Im using this from LangChain.  How would the author of LangChain add this fix, or could I being a user of LangChain.  

FYI, new to python.  :)

**Comment by MthwRobinson** [comment]
The `UnstructuredFileLoader` (source is [here](https://github.com/hwchase17/langchain/blob/master/langchain/document_loaders/unstructured.py#L82-L98)) in `langchain` accepts optional `unstructured` kwargs, so you can instantiate it like this:

```
loader = UnstructuredFileLoader("my-email.eml", encoding="ISO-8859-1")
loader.load()
```

if you need to change the encoding. There also the [email loader](https://github.com/hwchase17/langchain/blob/master/langchain/document_loaders/email.py#L13-L33) but that doesn't accept optional kwargs right now (we can PR that in tomorrow though, it's the same pattern as for the file loader).

**Comment by mbalsam-refind** [comment]
Great!  I searched for a code that would convert MSG to EML.  So now I can remove that step.  Thanks!

**Comment by sglebs** [comment]
This bug also happens with the LangChain Sitemap loader, which loads multiple file (mime) types, and there is no way for me to know in advance what encoding that is. Any hope in this case? A better auto detection?

**Comment by MthwRobinson** [comment]
@sglebs - Are you using `unstructured` code in conjunction with the Sitemap loader? We do have functionality now to detect encoding types. If you're error originals with our `partition_email` or another one of the `unstructured` functions, we likely just need to patch that in.

https://github.com/Unstructured-IO/unstructured/blob/6ec177e7c6d8e1b6c4eb88e8ebababa3750e606d/unstructured/file_utils/encoding.py#L52

**Comment by sglebs** [comment]
@MthwRobinson yes, Sitemap loader with unstructured. I can force a specific minimal version of unstructured in my requirements.txt and give it a try. What minimal version should I use? I am running unstructured==0.7.8 . Thanks!

**Comment by MthwRobinson** [comment]
Could you try with `0.7.12`? If you're getting errors with the latest version and can let us know what filetypes and/or MIME types are producing the errors, we can take a look. Thanks!

**Comment by sglebs** [comment]
Still happens. Maybe the page is malformed? This is the URL that crashed SitemamLoader: https://digix.com.br/quem-somos/

**Comment by MthwRobinson** [comment]
Thanks, we'll check that out and see if we can reproduce.

**Comment by sglebs** [comment]
Any news on this one? I still get the error on https://digix.com.br/quem-somos/ . Thanks for listening.

**Comment by christinestraub** [comment]
Hi @sglebs Which partition function did you try? When I tried `partition_html`, I didn't get any error.

```
elements = partition_html(url="https://digix.com.br/quem-somos/")
print("\n\n".join([str(el) for el in elements]))
```

**Comment by sglebs** [comment]
I just use Langchain Sitemap Loader. I do not call unstructured directly at all.
