### ISSUE TITLE
Capture section and chapter in the metadata for epubs

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#459]
The goal of this issue is to capture section and chapter in the metadata for epubs. Currently we're only capturing filename and page number.

**Comment by MthwRobinson** [comment]
For when we pick this up, worth checking to see if we can add this functionality to non EPUB documents as well (at least for sections, chapters may not be relevant to some other document types).

**Comment by camgreenburg** [comment]
Being able to split the epub along the sections of the spine, or better yet the toc, is really important when looking to do summarization or distillation of the ideas in an epub. Please add the ability to capture section and chapter in the metadata! Happy to give more details on our particular use case if interested.

**Comment by Coniferish** [comment]
Hi @camgreenburg. The epub books you're wanting to parse, will you have the entire epub zip or are you anticipating just having/providing the *.epub file? I ask because from what I'm finding, there's typically a *.opf file that comes packaged in the epub zip which contains the structure information for a book. It seems like that's going to be the best way to break a book into chapters.

**Comment by camgreenburg** [comment]
All the .epubs I have worked with (which is less than 10) have the OPF file. That is how I am pulling the book apart manually before sending it through unstructured. RN I ignore the images and just traverse the spine iterating through each html file. I am not an expert on EPUBs, but thought the opf was a standard part of the format. Not sure how you would handle a case where it was missing.

**Comment by camgreenburg** [comment]
Nice. Well let me know how I can support you. Happy to dive deeper here into our particular use case if desired.

**Comment by Coniferish** [comment]
What you described seems like it will be the easiest. Am I correct in assuming that you're using `ebooklib`? If so, can you share a code snippet of what you're doing? I've found the toc and matched those with the book items, which have the contents for each section, but I'm wondering how you were using the spine

**Comment by camgreenburg** [comment]
Sure here is the function that splits the epub by the spine with ebooklib. I have to do some gymnastics to get it back into unstructured's langchain loader, which there is probably a better way, but I think you get the sense for what I am doing here. 

`def split_epub_file(filepath):
    book = epub.read_epub(filepath)

    # Get all items in the spine
    spine_items = [item for item in book.spine]

    for i, item_id in enumerate(spine_items):
        # Some spine items may be tuple with second item as a linear flag
        if isinstance(item_id, tuple):
            item_id = item_id[0]

        # Retrieve the item from the book by its id
        item = book.get_item_with_id(item_id)
        
        if item is not None:
            # Convert the item content to a string
            html_content = item.get_content().decode()

            # Save the HTML content to a temporary file
            with tempfile.NamedTemporaryFile(suffix=".html", delete=False) as temp:
                temp.write(html_content.encode())
                temp_file_path = temp.name

            # Load the HTML content using the UnstructuredFileLoader
            loader = UnstructuredFileLoader(file_path=temp_file_path, mode="elements")
            documents = loader.load()
            
            # Filter documents to retain only those where the category is 'NarrativeText' or 'Title'
            documents = [doc for doc in documents if doc.metadata['category'] in ['NarrativeText', 'Title']]

            # Delete the temporary file
            os.remove(temp_file_path)

            yield documents`

**Comment by Coniferish** [comment]
Hey @camgreenburg 
Thanks for the function. I'm not seeing you capture the chapter or section name in this. I just want to make sure I'm not missing something and am wondering how you're doing that currently for these sections you're parsing via the `UnstructuredFileLoader`--I am looking at using the `book.toc` instead of the spine and retrieving the item based on the `href` because the toc seems to be where the title of each section or chapter you're looking for is.

**Comment by Coniferish** [comment]
@camgreenburg, are you aware that the table of contents doesn't completely align with the text of epub books? The book(s) I've been partitioning have toc elements that point to the same `book.item` (that is, the first few toc items like "Contents", "Images", and "Ch 1" all point to the same EpubHtml item) and I've found in at least one book that a section of text (EpubHtml item) was skipped by the toc elements.

**Comment by Coniferish** [comment]
This issue was closed when using a package that didn't fit with our license. That package and this functionality has been removed from Unstructured. Reopening so we can find another solution to this issue.

One consideration to explore:
https://pandoc.org/MANUAL.html#epub-metadata
