### ISSUE TITLE
Allow support for partitioning plain text and markdown from URLs

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#464]
Per [this comment](https://github.com/hwchase17/langchain/pull/979#issuecomment-1501022162) in `langchain`, there are users interested in partitioning non-HTML content from URLs. The goal of this issue is to add support for partitioning (at a minimum) plain text and markdown from URLs. We may actually be able to add a `url` parameter to the automatic `partition` function that will route the content to the appropriate partitioning break based on the MIME type from the request, in which case we could support other remote content such as PDFs as well.

**Comment by Boscop** [comment]
Also it would be nice to be able to specify how to treat a certain file (overriding the automatic detection), e.g. treating a .c file or .md as if it was a .txt file.

**Comment by MthwRobinson** [comment]
Got it yeah that makes sense. Should be able to support that.
