### ISSUE TITLE
Docker jupyter notebook

### ISSUE THREAD

**Issue by aamir-gmail** [Unstructured-IO/unstructured#504]
Please integrate jupyter notebook in your docker image , it would be easier than using bash command line .

**Comment by aamir-gmail** [comment]
any update on this one

**Comment by MthwRobinson** [comment]
Hi @aamir-gmail - we'll plan to update the docker image to include Jupyter Notebook. Thanks for adding the issue! cc: @cragwolfe

**Comment by MthwRobinson** [comment]
This was added in #651
