### ISSUE TITLE
Out of memory processing pdf

### ISSUE THREAD

**Issue by qued** [Unstructured-IO/unstructured#521]
Running `partition_pdf` on the following document resulted in a killed process due to running out of memory on Ubuntu. The machine has (only) 8 gigs of memory total.

Since pages are processed individually, only one page should sit in memory at a time. Maybe that's not true? Or is one particular page of this document causing an issue?

[irm02-003-059--2022-12-12.pdf](https://github.com/Unstructured-IO/unstructured/files/11337442/irm02-003-059--2022-12-12.pdf)

**Comment by qued** [comment]
Closing as addressed by [PR #136](https://github.com/Unstructured-IO/unstructured-inference/pull/136). Thanks @christinestraub !

**Comment by christinestraub** [comment]
@qued Created [PR #924](https://github.com/Unstructured-IO/unstructured/pull/924)
