### ISSUE TITLE
Pip install of unstructured[local-inference] failed on MacOS

### ISSUE THREAD

**Issue by syang** [Unstructured-IO/unstructured#526]
**Can install 'unstructured[local-inference]' on macOS**

 **Desktop** 
 - OS: MacOS Big Sur
 - Python version: anaconda3-2023.03 ("3.10.9")

**Command**
`# pipenv install 'unstructured[local-inference]'` 

**Error message** 
...
...
Installing unstructured...[36m  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      The Meson build system
      Version: 1.1.0
      Source dir: 
/private/var/folders/mp/flk_pnn1743f_y0f1jwcz6sm0000gp/T/pip-install-muzunhw4/scipy_23a3dc1a137546
1eb212e95477a66838
      Build dir: 
/private/var/folders/mp/flk_pnn1743f_y0f1jwcz6sm0000gp/T/pip-install-muzunhw4/scipy_23a3dc1a137546
1eb212e95477a66838/.mesonpy-za45p60y/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.1
      C compiler for the host machine: cc (clang 12.0.5 "Apple clang version 12.0.5 
(clang-1205.0.22.11)")
      C linker for the host machine: cc ld64 650.9
      C++ compiler for the host machine: c++ (clang 12.0.5 "Apple clang version 12.0.5 
(clang-1205.0.22.11)")
      C++ linker for the host machine: c++ ld64 650.9
      
      ../../meson.build:1:0: ERROR: Cython compiler 'cython' cannot compile programs
      
      A full log can be found at 
/private/var/folders/mp/flk_pnn1743f_y0f1jwcz6sm0000gp/T/pip-install-muzunhw4/scipy_23a3dc1a137546
1eb212e95477a66838/.mesonpy-za45p60y/build/meson-logs/meson-log.txt
      + meson setup --prefix=/Users/syang/.pyenv/versions/anaconda3-2023.03 
/private/var/folders/mp/flk_pnn1743f_y0f1jwcz6sm0000gp/T/pip-install-muzunhw4/scipy_23a3dc1a137546
1eb212e95477a66838 
/private/var/folders/mp/flk_pnn1743f_y0f1jwcz6sm0000gp/T/pip-install-muzunhw4/scipy_23a3dc1a137546
1eb212e95477a66838/.mesonpy-za45p60y/build 
--native-file=/private/var/folders/mp/flk_pnn1743f_y0f1jwcz6sm0000gp/T/pip-install-muzunhw4/scipy_
23a3dc1a1375461eb212e95477a66838/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2

**Comment by MthwRobinson** [comment]
@syang - Thanks for reporting this. Are you installing in `conda`? Noticed the `anaconda3` in your Python version.

**Comment by syang** [comment]
I think I managed to successfully install it.

the issue is that I was running MacOS 11.x, and I found that people has reported that upgrading it to 12 will fix it.

I updated it to macOS 13, this issue disappeared.

thanks

**Comment by MthwRobinson** [comment]
Great, will close out the issue since you were able to install. Thanks for posting solution in here.

**Comment by pavanjava** [comment]
I still see this issue in Mac 13.4 any sugestions, attaching screenshot for more clarity.
<img width="1254" alt="Screenshot 2023-06-09 at 9 01 50 AM" src="https://github.com/Unstructured-IO/unstructured/assets/25398886/58929ecc-c1a4-4859-92ac-f857a68605ea">

**Comment by MthwRobinson** [comment]
@pavanjava have you tried `pip install "unstructured[local-inference]"` (with the quotes around the package name)?

**Comment by pavanjava** [comment]
oohhh no i did not try with quotes, let me try and see.

**Comment by promeroreg** [comment]
Word of caution: using

`pip install unstructured_inference`

created an issue where unstructured couldn't find the inference module. By using

`pip install "unstructured[local-inference]"`

you make sure that unstructured finds the  inference module.
