### ISSUE TITLE
Enabled users to choose PaddleOCR instead of Tesseract for PDFs and images

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#527]
The goal of this issue is to provide users the ability to choose PaddleOCR instead of Tesseract for OCRing PDFs and images. Users are often interested in doing this due to speed or accuracy considerations.

**Comment by acul3** [comment]
+1

**Comment by doosenn** [comment]
+1

**Comment by yuanjie-ai** [comment]
+1
