### ISSUE TITLE
bug/parsing an html doc results in zero elements

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#543]
**Describe the bug**
`partition_html` does not extract elements for https://www.congress.gov/107/plaws/publ56/PLAW-107publ56.htm .

**To Reproduce**
Save the link locally.

The following code:
```
from unstructured.partition.auto import partition
from unstructured.partition.html import partition_html

elements = partition(filename="PLAW-107publ56.htm")
print(len(elements))
# see if different extension makes a difference
elements = partition(filename="PLAW-107publ56.html")
print(len(elements))
elements = partition_html(filename="PLAW-107publ56.htm")
print(len(elements))
```

has outputs of:
```
0
0
0
```

**Expected behavior**
Many elements are returned with all the text of the document represented.

**Desktop (please complete the following information):**
 - OS: mac
 - Python version: 3.8.15
 - Unstructured version: 0.6.3-dev1

**Comment by mu4farooqi** [comment]
All of the text is in <pre> tag which this library does not support which makes sense too. For 99% of the cases we don't put text in <pre> tags.

I can submit a quick fix if other agrees.

**Comment by cragwolfe** [comment]
ideally, the library would do the right automatically when parsing a \<pre> tag and extract natural language from the block if it looks like natural language. in any case, the user should also have a way overriding[ text tags](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/documents/html.py#L32) in addition to "auto" \<pre>-text detection.
