### ISSUE TITLE
feat/unstructured command line to print library information

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#544]
**Is your feature request related to a problem? Please describe.**
When debugging issues, it can help to know the various libraries and dependencies that are installed, including.

* OS version
* python version
* unstructured, unstructured-inference (if installed) versions
* tesseract versions and tesseract lang packages installed
* detectron2 version, torch version
* PaddleOCR versions
* other OS packages: libmagic, libreoffice
* Perhaps entire pip freeze packages output

**Describe the solution you'd like**
A CLI tool in the unstructured lib that a user can type to get the above info to cut and paste when creating / discussing an issue.

**Describe alternatives you've considered**
Doc-only is another solution, but it's easiest to just run a single command rather than multiple. Having it as a python commands helps it be OS agnostic.

**Comment by ryannikolaidis** [comment]
pytorch has a nice solution for this that could be some inspiration. In [their bug reporting flow](https://github.com/pytorch/pytorch/issues/new?assignees=&labels=&template=bug-report.yml)
they ask that you run [this script](https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py) to produce the debug info.
