### ISSUE TITLE
Recreate LabelStudio test fixture without vcr

### ISSUE THREAD

**Issue by ryannikolaidis** [Unstructured-IO/unstructured#554]
The vcr package was erroring on import with the bump to urllib3==2.0.2. It was needed to create a fixture for a single test. This was disabled [here](https://github.com/Unstructured-IO/unstructured/pull/551/files#diff-2e4771b30a1def5c79c7507bb2ec61fe1cec70c288ea71a40bb5d6bedf703895R12-R64). Recreate this fixture and/or test without the need for vcr.

**Comment by Coniferish** [comment]
Commenting to let other people know I'll work on this issue. I haven't used VCR before and am a bit rusty on tests and mocks, so it may take me a day or two.

**Comment by ryannikolaidis** [comment]
Hey @Coniferish, thanks for jumping in to this one! From reviewing I believe these test instructions are largely about generating "recording" the initial response from the service as a test artifact `test_unstructured/vcr_fixtures/cassettes/label_studio_upload.yaml`. This is then played back and tested against using that artifact in subsequent runs.

**Comment by Coniferish** [comment]
Hey @ryannikolaidis. I'm having trouble figuring out how to run this test with a live instance of label-studio, kill label-studio, and then run the same test again. I'm wondering if (and/or why) label-studio needs to be running initially. It will be a lot easier for me to make a test with pytest mocks based on the label_studio_upload.yaml if that info can be treated as static and isn't something that needs to be updated each time this test is supposed to run.

**Comment by ryannikolaidis** [comment]
Hey @Coniferish. If I am following correctly, I don't think this was intended to be re-generated every time the test ran, but rather these steps are a way of refreshing label_studio_upload.yaml in case at some point that response changes down the road. So when running the tests this is treated as a static artifact, but there is a nice way to refresh it outside of the test. That said, I don't think we need to be beholden to recreating the test exactly as-is, as long as we can recreate the coverage and update if/as needed.

**Comment by Coniferish** [comment]
Hey @ryannikolaidis. I'm still thinking through how to rewrite this test and just want to check in. There very well could be something obvious I'm missing/am simply not understanding because I haven't written tests for external services before but I'm wondering if I can get your thoughts. 

This is what (I understand) is currently happening in the test...
- We're creating an instance of the label_studio `Client` (which is from their sdk) and starting a fresh project.
- Then we create the `label_studio_data` from the `elements` fixture (which is tested in the other tests).
- We then import the data into the project we just created.
- Finally, a regex pattern is used to check that there's a `201` response in the `caplog` to test that we can successfully post the data via the `Client/project`.

I've been brushing up on mocks, patching, and I still want to read up more on the `vcr`, `responses`, and `pact` packages and "consumer contract testing" generally. That said, I'm thinking `project.import_task()` needs to be patched to _validate_ the data we're passing to it and I need to return/write to the log that it was successfully posted. How to validate the data and return the correct response depending on whether or not it is compliant with the sdk `client/project` is something I need to figure out and would appreciate any pointers on if you have any.

I'm also a little unsure about how this is functionally different from `test_convert_to_label_studio_data`, though, if that test ensures we're correctly converting the data. If `test_convert_to_label_studio_data` passes, then it seems like we should always be able to post to the `project`. I'm hoping you can help clarify what that difference should be for this test then... It feels like this test has a lot more setup for interacting with a running instance of Label Studio, but if that is going to be mocked, then it might just be a moot point to test POSTing data to it if we're verifying in another test that `unstructured.staging.label_studio` is correctly formatting data.

**Comment by ryannikolaidis** [comment]
Oh, good points! So I think the real value of this test (as opposed to `test_convert_to_label_studio_data`) is actually in that the mocked response can be regenerated simply by deleting that yaml. Agreed that if we just one-time hardcode the mock, this provides a lot less value. Peeking at docs, `responses` looks like a really promising alternative and seems to be well maintained. That seems like a smart route to head down.

@yuming-long I know this was a while since you originally wrote, but any other thoughts here?

**Comment by yuming-long** [comment]
Hi @Coniferish
The intention of this test is to show that LabelStudio staging brick works with the LabelStudio Python SDK, which means that you can install the LabelStudio SDK and upload the data processed by our brick function (which is `label_studio.stage_for_label_studio(elements)` using the LabelStudio SDK. I think thats the main difference between the vcr test and ` test_convert_to_label_studio_data`, as you can see the latter one didn't actually update the data to a LabelStudio instance.

Also for mock tests, you are right that this can be tested with a mock test and that was also my first thought. I think the reason why i didn't continue with that idea is that the data you uploaded must follow the project format you created, which is not captured (or hard to) by mock test. This the mock test i wrote before (which was too loose to capture the format): https://github.com/Unstructured-IO/unstructured/blob/d7f87bf4949781bf3d2fc9480f3465ea215bb4ae/test_unstructured/staging/test_label_studio.py#L34

With that, the idea we had is to test working against a running label studio, then recording the interactions with VCR. The good thing about vcr is wouldn’t need to run label-studio in CI, but you do record the vcr fixtures (cassettes) against an actual running label-studio locally. It’s also very easy to re-record if label-studio ever changes, you just update a fixture to record mode per test .

**Comment by Coniferish** [comment]
Hey @yuming-long,
I don't have much experience with logging, so I've been confused how messages were being captured by `caplog` and then used for the assert. I have the test working with `responses`, but nothing is being logged to caplog with it. I looked at `project.import_tasks` and it returns a list of int's, representing the Imported task IDs or raises and error or exception. Would it be okay to just assert that the IDs are returned?

```
    imported_ids = project.import_tasks(label_studio_data)
    # imported_ids >>> [1, 2]
```


`.../python3.8/site-packages/label_studio_sdk/project.py`:
```
def import_tasks(self, tasks, preannotated_from_fields: List = None):
        """Import JSON-formatted labeling tasks. Tasks can be unlabeled or contain predictions.

        Parameters
        ----------
        tasks: list of dicts | dict | path to file
            Tasks in <a href="https://labelstud.io/guide/tasks.html#Basic-Label-Studio-JSON-format">
            Label Studio JSON format</a>

        preannotated_from_fields: list of strings
            Turns flat task JSON formatted like: `{"column1": value, "column2": value}` into Label Studio prediction
            data format: `{"data": {"column1"..}, "predictions": [{..."column2"}]`
            Useful when all your data is stored in tabular format with one column dedicated to model predictions.

        Returns
        -------
        list of int
            Imported task IDs

        """
        params = {'return_task_ids': '1'}
        if preannotated_from_fields:
            params['preannotated_from_fields'] = ','.join(preannotated_from_fields)
        if isinstance(tasks, (list, dict)):
            response = self.make_request(
                method='POST',
                url=f'/api/projects/{self.id}/import',
                json=tasks,
                params=params,
            )
        elif isinstance(tasks, (str, Path)):
            # try import from file
            if not os.path.isfile(tasks):
                raise LabelStudioException(f'Not found import tasks file {tasks}')
            with open(tasks, mode='rb') as f:
                response = self.make_request(
                    method='POST',
                    url=f'/api/projects/{self.id}/import',
                    files={'file': f},
                    params=params,
                )
        else:
            raise TypeError(
                f'Not supported type provided as "tasks" argument: {type(tasks)}'
            )
        return response.json()['task_ids']
```

**Comment by yuming-long** [comment]
Well in my opinion i think a 200 code for a success POST is easier to understand. But if that's the only option, i am okay with that, just please make sure to comment note on that. But i am just curious since youa re testing with `responses`, i think you will have a success 200 code right?

**Comment by ryannikolaidis** [comment]
> Hey @yuming-long and/or @ryannikolaidis
> 
> Could one of you take a look at the requests and label-studio Client packages with me or something? I'm struggling to figure out how to make sure the response objects are being called correctly for this test. I found how to access the individual responses that are being mocked and how to check if they were called and the status code, but the one we're trying to check for this test (`/api/projects/.*/import`) isn't being called for some reason--I'm seeing this when I run the test and enter `pdb`, I am checking `response.call_count` and it is returning `0` while all the other mock responses are showing they're called once.
> 
> This is also confusing because `project.import_tasks(label_studio_data)` is correctly showing that 2 tasks were added.
> 
> I'm going trough the docs and using `dir(<object>)` to figure out what methods to potentially use, so any advice in terms of how to approach solving this would also be appreciated--I know I might not have the best strategy for approaching some of these problems.
> 
> ```
> # @_recorder.record(file_path=RESPONSES_YAML_PATH)
> @responses.activate
> def test_upload_label_studio_data_with_sdk(elements):
>     """
>     Testing Instructions
>     ====================
>     1. Remove file `test_unstructured/responses/label_studio_upload.yaml` if it exists.
>         It will be recreated later.
>     2. Install the label-studio package by running command `pip install -U label-studio`.
>     3. Run command `label-studio`, and login or set up label studio account on pop-up website.
>     4. Update the `LABEL_STUDIO_URL` and `API_KEY` below. You can find your API_KEY by
>         clicking into your account profile in Label Studio.
>     5. Run this test once, and Responses will record the HTTP request to the yaml file.
>     6. Kill the label studio instance, alternate (uncomment/comment) this test's decorators
>         and uncomment line 35 (responses._add_from_file(file_path=RESPONSES_YAML_PATH)), 
>         and run the test again. Responses will replay the response.
>     """
>     responses._add_from_file(file_path=RESPONSES_YAML_PATH) 
>     # Define the URL where Label Studio is accessible
>     LABEL_STUDIO_URL = "http://localhost:8080"
>     # API_KEY is a temporary key from local install not actually valid anywhere
>     # Update it if it is updated in your user account for Label Studio
>     API_KEY = "7b613506d5afa062fe33c9cd825f106c718b82a0"
>     # Connect to the Label Studio API and check the connection
>     ls = Client(url=LABEL_STUDIO_URL, api_key=API_KEY)
>     ls.check_connection()
>     ls.delete_all_projects()
>     # Create a sample project to classify types of texts
>     project = ls.start_project(
>         title="Text Type Classifications",
>         label_config="""
>         <View>
>         <Text name="text" value="$text"/>
>         <View style="box-shadow: 2px 2px 5px #999;
>                        padding: 20px; margin-top: 2em;
>                        border-radius: 5px;">
>             <Header value="Choose text type"/>
>             <Choices name="type" toName="text"
>                     choice="single" showInLine="true">
>             <Choice value="Title"/>
>               <Choice value="Narrative"/>
>             </Choices>
>         </View>
>         </View>
>         """,
>     )
>     label_studio_data = label_studio.stage_for_label_studio(elements)
>     imported_ids = project.import_tasks(label_studio_data)
>     pattern = re.compile(r"/api/projects/.*/import")
>     if responses.registered():
>         # Find the response for posting to the /imports api
>         for response in responses.registered():
>             if pattern.search(response.url):
>                 resp = response
>                 break
>             else:
>                 resp = None
>         import pdb; pdb.set_trace()
>         assert resp.status == 201
>     # If responses is not used and you are using a live instance of Label Studio (recording responses)
>     else:
>         assert len(imported_ids) == 2
> ```
> 
> More specifically, this is what I'm stuck on: https://stackoverflow.com/questions/76342385/how-do-you-test-a-response-thats-not-returned-by-lower-method

Hey @Coniferish! I just saw vcrpy got it's first (and immediately second) release since last August and looks like they have resolved urllib3 issues: https://github.com/kevin1024/vcrpy/releases/tag/v4.3.1. Maybe worth a peek to see if we can pull the latest and re-enable? 

Another note: on the main branch we've temporarily bumped back down to urllib3==1.26.16 for other conflict reasons, but I would like to resolve this issue for urllib>=2 regardless, because I'm sure it's a matter of time before we need to bump there again.

**Comment by Coniferish** [comment]
Hey @ryannikolaidis. Just seeing this, but sounds good! 
I'm unsure how to check that we can pull and use the latest version, though. Are you saying I should test it locally to see if the new version still works or should I be more detailed and look through their commits/updates (for both urllib3 v1 and v2)? I am noticing that they say there is an issue running urllib3 v2 on Python older than 3.10 and we are (or at least I am) using 3.8.15 (per Unstructure's env instructions). I haven't done much with making sure requirements are up to date and compatible for projects before, so any general guidance is appreciated.

**Comment by ryannikolaidis** [comment]
Hey @Coniferish. Oh I was thinking simpler than that. I was thinking of just re-enabling the vcr test and seeing if it still fails. according to the release notes over there, they have resolved the original urllib3 issue that was causing this to fail (which is why we needed to disable in the first place)

**Comment by Coniferish** [comment]
Hey @ryannikolaidis 

The test is passing, but I'm getting this warning:
```
test_unstructured/staging/test_label_studio.py ..................                   [100%]

==================================== warnings summary =====================================
../../.pyenv/versions/3.8.15/envs/unstructured/lib/python3.8/site-packages/requests/__init__.py:109
  /home/coni/.pyenv/versions/3.8.15/envs/unstructured/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================== 18 passed, 1 warning in 1.87s ==============================
```

and I checked that my `vcr` version was the latest one:
```
pip show vcrpy
Name: vcrpy
Version: 4.3.1
```

**Comment by ryannikolaidis** [comment]
sweet!

> Hey @ryannikolaidis
> 
> The test is passing, but I'm getting this warning:
> 
> ```
> test_unstructured/staging/test_label_studio.py ..................                   [100%]
> 
> ==================================== warnings summary =====================================
> ../../.pyenv/versions/3.8.15/envs/unstructured/lib/python3.8/site-packages/requests/__init__.py:109
>   /home/coni/.pyenv/versions/3.8.15/envs/unstructured/lib/python3.8/site-packages/requests/__init__.py:109: 
>   RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
>     warnings.warn(
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> ============================== 18 passed, 1 warning in 1.87s ==============================
> ```
> 
> and I checked that my `vcr` version was the latest one:
> 
> ```
> pip show vcrpy
> Name: vcrpy
> Version: 4.3.1
> ```

sweet! oh I _think_ that's unrelated to this change.
