### ISSUE TITLE
Include all metadata fields when converting to dataframe or CSV

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#555]
Currently, some metadata fields (like email subjects and to/from) are not included when you convert a list of elements to a dataframe. The goal of this issue is to update the `convert_to_dataframe` and `convert_to_csv` functions so that these fields appear in the output.

To reproduce / check:

```python
from unstructured.partition.auto import partition
from unstructured.staging.base import convert_to_dataframe

filename = "example-docs/fake-email.eml"
elements = partition(filename=filename)
elements_df = convert_to_dataframe(elements)
elements_df.head()
```

**Comment by MthwRobinson** [comment]
Thanks @Coniferish ! Feel free to reach out to me or @qued if you need any help getting up and running.

**Comment by MthwRobinson** [comment]
Yeah updating the `convert_to_isd` type to `List[Dict[str, Any]]` makes sense to me since some of the keys will no longer be strings.

Multiple "from" addresses actually is standards compliant, but very weird (see [this post](https://stackoverflow.com/questions/21480430/can-a-message-have-multiple-senders) on SO). That said, I think having it as a list makes filtering by sender more complicated than it needs to be, and that's probably the most common use case. What do you think about having keeping `sent_from` as a list for backward compatibility and adding `sender` as string?

**Comment by Coniferish** [comment]
That sounds good to me. I can use similar logic as the post you linked for assigning the `sender` string. Or, in the odd circumstance there is more than one sender, would you rather the whole list of `sent_from` be converted to a string?

**Comment by MthwRobinson** [comment]
I think `sender` can just be a single string. From the following it looks there can only be a single sender, even though there can be multiple "from" addresses. I think sender can just be `sent_from[0]` or `None` if it's not available.

- https://stackoverflow.com/questions/21480430/can-a-message-have-multiple-senders/21480962#21480962

**Comment by Coniferish** [comment]
I've updated the code, but want to take a minute to review your policies around contributions since this is my first, so it might be this afternoon that I get it to you. Here's what I've changed, though:

```
TABLE_FIELDNAMES: List[str] = [
    "type",
    "text",
    "element_id",
    "coordinates",
    "filename",
    "page_number",
    "url",
    "sent_from",
    "sent_to",
    "subject",
    "sender",
]
```
```
def convert_to_isd_csv(elements: List[Element]) -> str:
    """
    Returns the representation of document elements as an Initial Structured Document (ISD)
    in CSV Format.
    """
    rows: List[Dict[str, Any]] = convert_to_isd(elements)
    # NOTE(robinson) - flatten metadata and add it to the table
    for row in rows:
        metadata = row.pop("metadata")
        for key, value in metadata.items():
            if key in TABLE_FIELDNAMES:
                row[key] = value

        if row.get("sent_from"):
            row["sender"] = row.get("sent_from")
            if type(row["sender"]) == list:
                row["sender"] = row["sender"][0]

    with io.StringIO() as buffer:
        csv_writer = csv.DictWriter(buffer, fieldnames=TABLE_FIELDNAMES)
        csv_writer.writeheader()
        csv_writer.writerows(rows)
        return buffer.getvalue()
```

I've also changed the type hinting for both `convert_to_isd` and `convert_to_dict`

**Comment by MthwRobinson** [comment]
Awesome, that looks great. Thanks @Coniferish !

**Comment by MthwRobinson** [comment]
You probably have dependencies missing for some of the file types. I'd take a look at the [installing instructions](https://unstructured-io.github.io/unstructured/installing.html). For your PR, you can probably just run `test_unstructured/staging/test_base_staging.py` since your PR probably doesn't touch any of the partition code.

**Comment by Coniferish** [comment]
Thanks. Are those instructions in addition to the ones in the README [here](https://github.com/Unstructured-IO/unstructured#coffee-installation-instructions-for-local-development) using `make install`?

I was having trouble installing some of those, but wondered if it might have something with my using pipenv isntead of pyenv, so I am in the process of switching to pyenv since that's what yall use.

**Comment by MthwRobinson** [comment]
Some of those are systems dependencies that don't get installed when you run `make install`. If you're using Ubuntu, we have a setup script you can that will install all of that.

- https://github.com/Unstructured-IO/unstructured/blob/main/scripts/setup_ubuntu.sh

**Comment by Coniferish** [comment]
Hey @MthwRobinson. Should I be working off a feature branch for this (and similar small contributions) on my fork and then creating a PR to merge into the unstructured main branch or some other workflow?

I also need to add updates to the CHANGELOG, right? I haven't worked with a CHANGELOG before, so wanting to double-check that I should be editing it with something like this:

## 0.6.5-dev0

### Enhancements

* PLACEHOLDER - delete this line when there is an actual changelog item to report for 0.6.5

### Features

### Fixes
* Include all metadata fields when converting to dataframe or CSV

**Comment by MthwRobinson** [comment]
Yeah that looks like a good CHANGELOG update to me. You can also update `0.6.5-dev0` -> `0.6.5-dev1` and also update the version in `unstructured/__version__.py` to `0.6.5-dev1` (otherwise you'll see a failure in CI on the `changelog` job)

**Comment by MthwRobinson** [comment]
You can delete this one too while you're in there:
> PLACEHOLDER - delete this line when there is an actual changelog item to report for 0.6.5
