### ISSUE TITLE
feat/unstructured can parse and extract anchor tags from the body of a HTML page

### ISSUE THREAD

**Issue by sodafountain** [Unstructured-IO/unstructured#556]
**Is your feature request related to a problem? Please describe.**
I'm interested in crawling a website to collect information about it. Currently unstructured helps me extract textual content from the page only. I'm having resort to other techniques to identify out links from a body of page ignoring the headers and the footers.

**Describe the solution you'd like**
Similar to textual content extracted from a HTML page, it would be helpful to extract the out links of a page that could lead to similar content and ignore links like "About Us", "Contact Us" located in header / footer.

**Describe alternatives you've considered**
I'm using `lxml` and custom logic to extract that content.

**Additional context**
-

**Comment by MthwRobinson** [comment]
@sodafountain - Thanks for submitting this issue, we'll take a look at this as soon as we can.

**Comment by LiamK** [comment]
I also was looking for this feature.  In my case, I wanted to be able to extract links found in emails.
Posting here so I'll be notified if/when this is implemented.

**Comment by MthwRobinson** [comment]
@LiamK @sodafountain - Opened #959 to start tracking links.

@sodafountain - Are you wanting to ignore content in `<header>` and `<footer>` tags? If so we have that underlying functionality built in already and just need to patch that through to `partition_html`. Can take care of that in a separate PR.

**Comment by sodafountain** [comment]
Thanks @MthwRobinson for taking care of it. Much appreciated!! Yes for my current use case, I want to ignore links in the `<header>` and `<footer>` section.

**Comment by MthwRobinson** [comment]
@sodafountain - Sure thing! Added #1004 to capture that. We'll pick it up as soon as we can.

**Comment by MthwRobinson** [comment]
@sodafountain - FYI the ability to optionally ignore content in headers and footers will be available in the next release.
