### ISSUE TITLE
bug/400 Error when using the `partition_via_api`

### ISSUE THREAD

**Issue by homanp** [Unstructured-IO/unstructured#559]
**Describe the bug**
Currently trying out the hosted version of unstructured by passing in the contents of a remote CSV file. Passing the `file` and `filename` but getting an unexpected `400 Bad request` error

**To Reproduce**
```
import requests
import io

file_url = "https://my-hosted-file.com/myfile.csv"
file_response = requests.get(file_url)
file = file_response.content
file_object = io.BytesIO(file)

elements = partition_via_api(file=file_object, file_filename="myfile.csv")
```

**Expected behavior**
The API should accept the file and return `200 OK`

**Desktop (please complete the following information):**
 - Python version 3.9

**Additional context**
I have also tried this with `UnstructuredAPIFileIOLoader` LangChain wrapper but getting the same results there.

**Comment by 5inGularity** [comment]
It looks like the API expects content-type for fields within the form as well. Initialising the loader as following works - 
```
loader = UnstructuredAPIFileLoader(
        content_path,
        url="http://unstructured:4000/general/v0/general",
        content_type="text/html",
    )
```

**Comment by MthwRobinson** [comment]
Filetype detection for CSVs was added in `0.6.8`, this shouldn't be an issue any longer
