### ISSUE TITLE
Utility function to convert extracted tables to `pandas` dataframes

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#560]
The goal of this issue is to create a utility function for converting extracted tables to `pandas` dataframes.

**Comment by mariaKlv** [comment]
How is this one completed and yet an answer to be provided?

**Comment by MthwRobinson** [comment]
Updating to "closed as not planned". If a community member would like to contribute this functionality though, we'd be happy to review the PR.
