### ISSUE TITLE
Add a `stage_for_weaviate` staging brick and add Weaviate to the integrations page

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#566]
The goal of this issue is to add a `stage_for_weaviate` staging brick to the `unstructured` library and add a Weaviate section to the ecosystem page in the Unstructured docs. Check out [this notebook](https://github.com/weaviate/how-to-ingest-pdfs-with-unstructured/blob/master/notebooks/01_blog.ipynb) for an example of how to load `unstructured` outputs into Weaviate.

**Comment by Kate-Lyndegaard** [comment]
This is exactly what I am looking for.

**Comment by MthwRobinson** [comment]
Hi everyone - we released this in version `0.7.1` 😄
