### ISSUE TITLE
Compatibility with Python 3.7

### ISSUE THREAD

**Issue by nateraw** [Unstructured-IO/unstructured#57]
So related to #56 , Colab's environment uses Python 3.7. Since in the package you are using `typing.Final`, it makes this package unusable on Python 3.7 unfortunately, as that is only supported on Python >= 3.8

Would it be possible to not use this `typing` feature so the package works on Python < 3.8?

**Comment by nateraw** [comment]
This issue can be worked around rather easily by adding calls to import from `typing_extensions` if the version is less than 3.8. 

```python
import sys

if sys.version_info < (3, 8):
    from typing_extensions import Final
else:
    from typing import Final
```

**Comment by cragwolfe** [comment]
Thanks for the tip @nateraw , we will look into adding 3.7 support.

**Comment by firmai** [comment]
You might be happy to hear the Colab has recently updated to 3.8. I still run 3.7 environments, and stumbled accoross the following problem 

This should be changed:
```
if sys.version_info < (3, 8):
    from typing_extensions import Final, List, Optional
else:
    from typing import Final, List, Optional

```
To this:
```
from typing import  List, Optional
if sys.version_info < (3, 8):
    from typing_extensions import Final
else:
    from typing import Final
```


https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/text_type.py

**Comment by cragwolfe** [comment]
This was completed with https://github.com/Unstructured-IO/unstructured/pull/108 .
