### ISSUE TITLE
How does extract_text work ?

### ISSUE THREAD

**Issue by TerrenceVarada** [Unstructured-IO/unstructured#576]
Thanks for your work. It is really a very usefull tool. 
I did some test and I thought this function can extract tables from a pdf or a image if the upside or/and downside of a table or tables are paragraph or other contents. 
But after my testing, I get some different answers. I find that you use "microsoft/table-transformer-structure-recognition" to do the ocr. But I think the result may not be something you want. I tried  both microsoft/table-transformer-structure-recognition and microsoft/table-transformer-detection. I find the detection model can tag tables at 90% accuracy rate. But if you directly use the structure-recognition model the result may be different. 
Did I make a mistake about how this function work?

**Comment by MthwRobinson** [comment]
Hi @TerrenceVarada - thanks for posting this issues. The pattern for extracting tables from PDFs and images looks like:

```python
from unstructured.partition.pdf import partition_pdf

elements = partition_pdf(filename=filename, infer_table_structured=True
```

Note that `infer_table_structure` only works with the `"hi_res"` strategy. If you have examples of documents with bad extractions or show `structured-recognition` working better than `table-transformer-detection`, we'd be happy to take a look.

cc: @qued and @ajjimeno

**Comment by TerrenceVarada** [comment]
Hi,

Thanks for your reply. I tried your method and I found an interesting problem. The unstructured seems can work better with a pdf writing in English than writing in Chinese or other language which I didn’t test. 

Environment:
The latest version of unstructured and detectron2.

Data:
Meta’s financial report (Meta-Reports-Third-Quarter-2022-Results-2022 ) and A Chinese company’s financial report (600519_20230331_HPY9).
￼￼
Result:
For Meta’s financial report, the unstructured can get the right element type, which is 'table'. 
For the Chinese company’s financial report the type from the process_file_with_model is ‘figure'. You can find this from the layout of process_file_with_model on page 1 element 6. 
I tried to change the ocr_languages, but the results are the same.

￼
￼

I thought table detection is a language irrelevant work so I am a little confused.

**Comment by MthwRobinson** [comment]
@TerrenceVarada - Yeah, `ocr_language` will improve the quality of the OCR outputs, but doesn't impact the bounding box labels. The layout detection task isn't language specific, but it's possible there a subtle differences in the formatting of Chinese tables that trip up the model. If you have the document available, we'd be happy to take a look.

It's not available yet, but @ajjimeno is working on a new model that will handle images with Chinese characters better. That will roll out in the next few months.

**Comment by huangpan2507** [comment]
> Closing this one since it's a question rather than an issue. When we roll the new model out that should help improve the output on Chinese documents. If you're able to provide an example document, we're also happy to take a look at specific issues to help troubleshoot.

Hi,  @MthwRobinson , does the new model come out? I see the `from unstructured.partition.pdf import partition_pdf`
partition_pdf has  languages parameter, how can I use it to process pdf(English and Chinese text inside) with `partition_pdf` func
>```
def partition_pdf(
    filename: Optional[str] = None,
    file: Optional[IO[bytes]] = None,
    include_page_breaks: bool = False,
    strategy: str = PartitionStrategy.AUTO,
    infer_table_structure: bool = False,
    ocr_languages: Optional[str] = None,  # changing to optional for deprecation
    languages: Optional[list[str]] = None,
    include_metadata: bool = True,  # used by decorator
    metadata_filename: Optional[str] = None,  # used by decorator
    metadata_last_modified: Optional[str] = None,
    chunking_strategy: Optional[str] = None,  # used by decorator
    hi_res_model_name: Optional[str] = None,
    extract_images_in_pdf: bool = False,
    extract_image_block_types: Optional[list[str]] = None,
    extract_image_block_output_dir: Optional[str] = None,
    extract_image_block_to_payload: bool = False,
    date_from_file_object: bool = False,
    starting_page_number: int = 1,
    extract_forms: bool = False,
    form_extraction_skip_tables: bool = True,
    **kwargs: Any,
) -> list[Element]:
>```
