### ISSUE TITLE
Table extraction for `partition_pdf` using the "fast" strategy

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#579]
Currently, `partition_pdf` only extract table information when using the `"hi_res"` strategy. The goal of this issue is to extract table information when using the the `"fast"` strategy. Some of this information in [this SO post](https://stackoverflow.com/questions/46222918/how-to-extract-tables-from-a-pdf-with-pdfminer) may be helpful.

**Comment by julian-espressive** [comment]
I see this marked as completed. Does this mean current release should support this? If I select strategy="fast" and infer_table_structure=True should it work?

**Comment by MthwRobinson** [comment]
Hi @julian-espressive - we were cleaning up issues that didn't have activity for six months. We're actually working on a faster and potentially more accurate table extraction technique now. We're still evaluating that but should have that available in the next month or two.

**Comment by LGuddatPan** [comment]
Hi. was there a solution to this?

**Comment by marellayaseskar** [comment]
Any resolution to the issue?
