### ISSUE TITLE
bug/HTML files with extension `.htm`  raises Invalid file error `File type not support in partition.`

### ISSUE THREAD

**Issue by obi-a** [Unstructured-IO/unstructured#584]
**Describe the bug**
Cannot partition HTML files with file extension `.htm`. It raises the error 
```
File "/usr/local/lib/python3.10/site-packages/unstructured/partition/auto.py", line 72, in partition
    raise ValueError(f"{msg}. File type not support in partition.")
ValueError: Invalid file example.htm. File type not support in partition.
```

**To Reproduce**
Partition a html file with extension `.htm` the following code
```
from unstructured.partition.auto import partition
file_path = `example.htm`
partition(filename=file_path)
```
A workaround is to rename the file from `example.htm` to `example.html`. This makes it accept the file as a valid HTML file.

**Expected behavior**
It should return the partitions for the HTML file.

**Desktop (please complete the following information):**
 - OS: Linux and Mac. 
 - Python version: 3.10.11

**Comment by yuming-long** [comment]
Hi @obi-a, thanks for reporting this bug! I've fixed it, cheers.
