### ISSUE TITLE
feat: Add support for XLSX filetype

### ISSUE THREAD

**Issue by ptkinvent** [Unstructured-IO/unstructured#587]
Some users want to process XLSX filetypes which are currently unsupported. It's a bit of a gap since DOCX and PPTX _are_ currently supported. My use case is as a langchain user who wants an LLM to ingest text from DOCX, PPTX, and XLSX files. Other libraries such as pandas can be used for this, but would be great to bridge this gap in unstructured itself.

**Comment by MthwRobinson** [comment]
@ptkinvent - Thanks for adding this issue. Use case definitely makes sense. We're planning to pick up #570 shortly for CSV support and can take a look at XLSX as well.

**Comment by MthwRobinson** [comment]
@ptkinvent - Excel file support is merged now, will include it in the next release! Plan to release in the next couple days.

**Comment by ptkinvent** [comment]
Incredible, thank you! Once it's released I'll file a feature request in langchain to add a wrapper, as well.

**Comment by MthwRobinson** [comment]
Just released this in `0.6.7`!
