### ISSUE TITLE
Filetype detection if a CSV has a `text/plain` MIME type

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#621]
Sometimes the detected MIME type for CSV files is `text/plain`. This causes `partition` (and our docker tests) to fail because it treats the file like a plain text file instead of a CSV. The goal of this issue is to add logic that looks at the first few lines of a file to determine if it's a CSV. One possibility is to look for the same comma count for the first `n` rows. This would be similar to the checks we do for JSON and EML.

**Comment by Coniferish** [comment]
I'll look into this one
