### ISSUE TITLE
bug/cannot-read-python-files-with-auto

### ISSUE THREAD

**Issue by startakovsky** [Unstructured-IO/unstructured#624]
I have a bug when importing because `py` is not an extension in the `file_types.py` module. I run into the problem on the code path while using Langchain. 

(https://github.com/hwchase17/langchain/issues/5025)

Here's a screenshot in a notebook. 
<img width="1115" alt="image" src="https://github.com/Unstructured-IO/unstructured/assets/689723/de98809c-c4ce-4316-91cf-0f43bb195159">

I believe the issue can be fixed by adding something related to a python plain-text file to lines 71 and 133, https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/file_utils/filetype.py. I do understand that this is not sustainable and perhaps there may be cleaner ways to open things up to code or something different altogether.

This is the line that errors out: https://github.com/Unstructured-IO/unstructured/blob/fda51d6ead85af49cc38133da71065375c30bb94/unstructured/partition/auto.py#L206

**Comment by MthwRobinson** [comment]
@startakovsky - Thanks for opening this issue, we'll take a look as soon as we can. In the meantime, you can work around this issue by either using `partition_text` or doing `partition(filename="myfile.py", content_type="text/plain")`. Both of those workarounds will treat the Python file like a plain text file.

**Comment by eilone** [comment]
Hi. 
I'm using the same method `DirectoryLoader(repo_path, glob=glob_pattern)` to load, for example, .py files, but gets the same error:
` The FileType.UNK file type is not supported in partition.`

What should I do to fix that?

Here is a snippet:
```
def load_and_index_files(repo_path):
    extensions = ['txt', 'md', 'markdown', 'rst', 'py', 'js', 'java', 'c', 'cpp', 'cs', 'go', 'rb', 'php', 'scala', 'html', 'htm', 'xml', 'json', 'yaml', 'yml', 'ini', 'toml', 'cfg', 'conf', 'sh', 'bash', 'css', 'scss', 'sql', 'gitignore', 'dockerignore', 'editorconfig', 'ipynb']

    file_type_counts = {}
    documents_dict = {}

    for ext in extensions:
        glob_pattern = f'**/*.{ext}'
        try:
            loader = None
            if ext == 'ipynb':
                loader = NotebookLoader(str(repo_path), include_outputs=True, max_output_length=20, remove_newline=True)
            else:
                loader = DirectoryLoader(repo_path, glob=glob_pattern)

            loaded_documents = loader.load() if callable(loader.load) else []

        except Exception as e:
            print(f"Error loading files with pattern '{glob_pattern}': {e}")
            continue 
```

**Comment by MthwRobinson** [comment]
Try this in `DirectoryLoader`. That will optional kwargs to the loader you specify in `loader_cls`, which is `UnstructuredFileLoader` by default.

```python
loader = DirectoryLoader(repo_path, glob=glob_pattern, loader_kwargs={"content_type": "text/plain"})
```

**Comment by MthwRobinson** [comment]
We'll take a look at it. Could you let us know what `unstructured` version and operating system you're using? In addition, it would be helpful if you could let us know the output of the following snippets.

```python
import magic

mime_type = magic.from_file("myfile.py", mime=rue)
print(mime_type)
```

```python
import magic

with open("myfile.py", "rb") as f:
    mime_type = magic.from_buffer(f.read(4096), mime=True)
print(mime_type)
```

**Comment by eilone** [comment]
**For both Scripts:**

```
Traceback (most recent call last):
  File "/Users/eeilstein/Desktop/Code/Python/Repos/RepoReader/test.py", line 1, in <module>
    import magic
  File "/Users/eeilstein/Desktop/Code/Python/Repos/RepoReader/venv/lib/python3.9/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "/Users/eeilstein/Desktop/Code/Python/Repos/RepoReader/venv/lib/python3.9/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

```


Although, `magic` is alreay installed
`Requirement already satisfied: python-magic in ./venv/lib/python3.9/site-packages (0.4.27)`


**My setup:**
Mac iOS 16 M1 chip

```
unstructured==0.5.11
unstructured-inference==0.3.2
```

**Comment by MthwRobinson** [comment]
Could you upgrade to the latest version of `unstructured` (`0.8.1`) and try again? Filetype detection for code files was released in [`0.7.2`](https://github.com/Unstructured-IO/unstructured/blob/main/CHANGELOG.md#fixes-13).

**Comment by eilone** [comment]
That worked like a charm! 
Thank you so much!

The only thing that doesn't work is the `NotebookLoader` loader:
```
            if ext == 'ipynb':
                loader = NotebookLoader(str(repo_path), include_outputs=True, max_output_length=20,
                                        remove_newline=True,  loader_kwargs={"content_type": "text/plain"})
```

Yet I don't know how to pass the `glob_pattern` to this loader, resulting in going to the base dir and not being able to look for the notebook files...

```
[Errno 21] Is a directory: 'stat_path_repos'
```

**Comment by MthwRobinson** [comment]
Fantastic! Glad it worked. We didn't write the `NotebookLoader`. I'd recommend opening an issue in `langchain` for that. Here's the original PR for reference:

- https://github.com/hwchase17/langchain/issues/1248

**Comment by eilone** [comment]
TYSM
