### ISSUE TITLE
bug/diacritics

### ISSUE THREAD

**Issue by ginixsan** [Unstructured-IO/unstructured#629]
**Describe the bug**
when using languages with diacritics it removes them or it changes the letter. e.g: día changes to dfa

**To Reproduce**
`from unstructured.partition.auto import partition`
`elements = partition("document_in_spanish.pdf", ocr_languages="es")`
`for element in elements:`
    `if isinstance(element, NarrativeText) and sentence_count(element.text) > 2:`
       `print(element.text)`
        `print("\n")`

**Expected behavior**
It should not remove diacritics and recognize them

**Screenshots**
![CleanShot 2023-05-22 at 11 38 16@2x](https://github.com/Unstructured-IO/unstructured/assets/1665208/66e64038-f7a1-4ac6-b6c6-2c8e26ced550)

**Desktop (please complete the following information):**
 - macos
 - Python version 3.10

**Comment by ginixsan** [comment]
Besides that, save_as_jsonl neither does preserve diacritics:
`def save_as_jsonl(data: List[Dict], filename: str) -> None:
    with open(filename, "w+", encoding='utf-8') as output_file:
        output_file.writelines(json.dumps(datum, ensure_ascii=False) + "\n" for datum in data)`

**Comment by MthwRobinson** [comment]
@ginixsan - Thanks for flagging this issue. Is there an example document you can attach that we could use for testing?
