### ISSUE TITLE
bug/mismatched library versions in some requirements/*.txt files

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured#631]
**Describe the bug**
Some extras libraries potentially have different versions of libraries installed.

For instance, currently, requirements/ingest-s3.txt has 
[requests==2.28.2](https://github.com/Unstructured-IO/unstructured/blob/a78719666a745fb63a389e2c82cf5fa431109366/requirements/ingest-s3.txt#L190), as do some others, while other .txt files have 2.30.2

```
$ grep 'requests==' *txt
base.txt:requests==2.30.0
build.txt:requests==2.30.0
huggingface.txt:requests==2.30.0
ingest-azure.txt:requests==2.28.2
ingest-discord.txt:requests==2.28.2
ingest-github.txt:requests==2.28.2
ingest-gitlab.txt:requests==2.28.2
ingest-google-drive.txt:requests==2.28.2
ingest-reddit.txt:requests==2.28.2
ingest-s3.txt:requests==2.28.2
ingest-slack.txt:requests==2.28.2
ingest-wikipedia.txt:requests==2.28.2
local-inference.txt:requests==2.30.0
test.txt:requests==2.30.0
test.txt:types-requests==2.30.0.0
```

This leads to potentially unpredictable behaviour depending what extras are installed

There should be a CI job that fails for such mismatches to prevent these inconsistencies from occurring in the first place. (that's the enhancement)

* Note: it is conceivable there could be 2 mutually exclusive extras that require different versions that should not be installed at the same time, but this doesn't currently exist in the library.

**Comment by qued** [comment]
Closing as addressed by #636
