### ISSUE TITLE
bug/Slack signup restricted to unstructured.io addresses

### ISSUE THREAD

**Issue by th5** [Unstructured-IO/unstructured#634]
Signup for Slack via the button on the README won't accept my work or personal email. It appears to require an unstructured.io address.

Would you send me an invite to your Slack?

**Comment by amanda103** [comment]
Hey there, thanks for letting us know! We're checking out our workspace settings but in the meantime this link should work. Please let me know if you have any trouble.

https://join.slack.com/t/unstructuredw-kbe4326/shared_invite/zt-1vrmwdw1f-YtVfPuaGFiJMcNm2jGhGZA
