### ISSUE TITLE
A small mistake in the documentation

### ISSUE THREAD

**Issue by hasan-sayeed** [Unstructured-IO/unstructured#679]
In [group_broken_paragraph](https://unstructured-io.github.io/unstructured/bricks.html#group-broken-paragraphs) section of the documentation, `para_split_re = re.compile(r"(\s*\n\s*){3}")` was used to change the behavior of the function `group_broken_paragraphs` using `paragraph_split` kwarg. While it seems like it should be `para_split_re = re.compile(r"(\s*\nn\\s*){3}")` instead.

**Comment by MthwRobinson** [comment]
@hasan-sayeed - Thanks for flagging, we'll get this fixed shortly!
