### ISSUE TITLE
Enable MIME type detection if libmagic is not available

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#682]
The goal of this issue is to enable MIME type detection if `libmagic` is not available. We can use [`filetype`](https://github.com/h2non/filetype.py/tree/master) as a fallback if `libmagic` is not present. `libmagic` is still preferred if it's available since it's more accurate and covers more file types.

If `libmagic` is not available, you'll get the following error if your run `import magic`:

```python
ImportError: failed to find libmagic.  Check your installation
```

**Comment by MthwRobinson** [comment]
@Coniferish is going to take a look at this one.

**Comment by Coniferish** [comment]
This is the only test I have failing right now with my local changes:
```
def test_detect_filetype_from_file_raises_without_libmagic(monkeypatch):
    monkeypatch.setattr(filetype, "LIBMAGIC_AVAILABLE", False)
    filename = os.path.join(EXAMPLE_DOCS_DIRECTORY, "fake-text.txt")
    with open(filename, "rb") as f, pytest.raises(ImportError):
        detect_filetype(file=f)
```

The `ImportError` comes from this conditional:
```
elif file is not None:
        extension = None
        # NOTE(robinson) - the python-magic docs recommend reading at least the first 2048 bytes
        # Increased to 4096 because otherwise .xlsx files get detected as a zip file
        # ref: https://github.com/ahupp/python-magic#usage
        if LIBMAGIC_AVAILABLE:
            mime_type = magic.from_buffer(file.read(4096), mime=True)
        else:
            mime_type = ft.guess_mime(file.read(4096))
        if mime_type == None:
            raise ImportError(
                "libmagic is unavailable. "
                "Filetype detection on file-like objects requires libmagic. "
                "Please install libmagic and try again.",
            )
```

Should filetype.py still raise an ImportError if Libmagic is unavailable (and filetype is unable to guess the mimetype)?

**Comment by Coniferish** [comment]
@MthwRobinson This is the only test I have failing right now with my local changes:
```
def test_detect_filetype_from_file_raises_without_libmagic(monkeypatch):
    monkeypatch.setattr(filetype, "LIBMAGIC_AVAILABLE", False)
    filename = os.path.join(EXAMPLE_DOCS_DIRECTORY, "fake-text.txt")
    with open(filename, "rb") as f, pytest.raises(ImportError):
        detect_filetype(file=f)
```

The `ImportError` comes from this conditional:
```
elif file is not None:
        extension = None
        # NOTE(robinson) - the python-magic docs recommend reading at least the first 2048 bytes
        # Increased to 4096 because otherwise .xlsx files get detected as a zip file
        # ref: https://github.com/ahupp/python-magic#usage
        if LIBMAGIC_AVAILABLE:
            mime_type = magic.from_buffer(file.read(4096), mime=True)
        else:
            mime_type = ft.guess_mime(file.read(4096))
        if mime_type == None:
            raise ImportError(
                "libmagic is unavailable."
                "Filetype detection on file-like objects requires libmagic."
                "Please install libmagic and try again.",
            )
```

Should filetype.py still raise an ImportError if Libmagic is unavailable (and Filetype is unable to guess the mimetype)? I'm unsure what kind of error to raise here since we're using Filetype as a fallback (making Libmagic not technically _required_ any more).

**Comment by MthwRobinson** [comment]
Yeah I don't think we need to raise an error there anymore since this will be the fallback if `libmagic` isn't available. For `file`s we can probably return `FileType.UNK` if `mime_type` is `None` after trying both methods. If `libmagic` isn't installed and `mime_type` turns out as `None`, if would be nice to have a `logger.warning` statement that suggest installing `libmagic` for better results. Check out [this test](https://github.com/Unstructured-IO/unstructured/blob/80f0b4a1328195cbb6e927c53018f836e25a5589/test_unstructured/documents/test_xml.py#L59) for an example of how to test that the warning was logged.
