### ISSUE TITLE
Add more documentation on table extraction

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#693]
Currently there is not much documentation on table extraction and how it works. The goal of this issue is to add a table extraction section to the documentation. We should also add an example to the `partition_pdf` docs that shows how to use the `infer_table_structure` kwarg.

**Comment by Buckler89** [comment]
It would be very helpful to document also how to use infer_table_structure with partition_via_api function

[unstructured-api#138](https://github.com/Unstructured-IO/unstructured-api/issues/138#issue-1782338087)
