### ISSUE TITLE
Add indentation level as a metadata field

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#711]
The goal of this issue is to add indentation level as a metadata field. For documents such as PDFs, we can detect this based on the position of the bounding boxes. For MS office documents this may be available as an attribute with the document xml.

**Comment by newelh** [comment]
This is in progress with #1433

**Comment by orlandounstructured** [comment]
Older than 180 days old but keeping active due to recent reference in #2428
