### ISSUE TITLE
Add support for enumerated lists in the `ListItem` detection logic

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#712]
The goal of this issue is to update the `ListItem` detection logic to include enumerates lists with formats such as `(a)`, `(1)` and `(i)`. Currently we only detect unicode bullet characters.

**Comment by cragwolfe** [comment]
Are there specific files that would be good to use as test cases?

**Comment by SimranJha2408** [comment]
is this done?

**Comment by orlandounstructured** [comment]
Closing because longer than 180 days; reopen with comment if the issue is still relevant
