### ISSUE TITLE
bug/<partition_email extract_datetimetz not working with gmail .eml files>

### ISSUE THREAD

**Issue by btconway** [Unstructured-IO/unstructured#719]
**Describe the bug**
converted a .mbox file to .eml files.  Continually getting this error:
```
in extract_datetimetz
    return datetime.datetime.strptime(date_string[0], "%a, %d %b %Y %H:%M:%S %z")
IndexError: list index out of range
```

**To Reproduce**
`

# Initialize staged_elements
staged_elements = None

    with open(file_path, "rb") as f:  # Open the file in binary mode
        try:
            elements = partition_email(file=f, include_headers=True)
            unstructured_class = create_unstructured_weaviate_class(class_name="unstructured class")
            schema = {"classes": [unstructured_class]}
            data_objects = stage_for_weaviate(elements)  # Added line
            # Print staged_elements
            print(data_objects)
        except ValueError as e:
            logging.warning(f"Failed to partition email: {e}")
            continue`

**Expected behavior**
Should be able to process these files as they are vanilla gmail emails

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac Ventura 13.4
 - Python version 3.10.9

**Additional context**

**Comment by MthwRobinson** [comment]
@btconway - Thanks for reporting this. I don't think this is related to the `.mbox` file, I think we need logic to handle the case where there aren't any date strings. We'll pick this up as soon as we can.
