### ISSUE TITLE
bug/`fake-text-utf-16-be.txt` file gets changed when tests are run

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#741]
**Describe the bug**
The `example-docs/fake-text-utf-16-be.txt` changes when tests are run.

**To Reproduce**
- Run`make test`
- Run `git status`, it will show the file as modified

**Expected behavior**
The file should not change

**Desktop (please complete the following information):**
 - `unstructured==0.7.4`

**Comment by qued** [comment]
I included a [fix](https://github.com/Unstructured-IO/unstructured/blob/enhancement/coordinate-overhaul/test_unstructured/staging/test_base_staging.py#L143-L145) for this in my [active PR](https://github.com/Unstructured-IO/unstructured/pull/774).
