### ISSUE TITLE
Skipping sentence because does not exceed x tokens 

### ISSUE THREAD

**Issue by shufanhao** [Unstructured-IO/unstructured#744]
when load a markdown file, it gives me multiple logs:
```
2023-06-14 09:46:22,274 - DETAIL - Skipping sentence because does not exceed 5 word tokens
Quick Tutorial
2023-06-14 09:46:31,057 - DETAIL - Skipping sentence because does not exceed 5 word tokens
Get started
```
Also hit error when trying to load a markdown file. 

```
2023-06-14 09:46:31,057 - DETAIL - Not narrative. Text does not contain a verb:
python app.py --debug --users=1000 --env=qa
```
How can I not skip sentence because does not exceed 5 word tokens ? I also want to keep less than 5 word tokens.

**Comment by cragwolfe** [comment]
Hi @shufanhao , see the description of this PR https://github.com/Unstructured-IO/unstructured/pull/561 for how to set logging levels, focusing especially on the lines with `trace_logger`.

**Comment by shufanhao** [comment]
@cragwolfe you may misunderstand my question. My question is not related to log. I want to know how can I not skip sentence because does not exceed 5 word tokens ? I also want to keep less than 5 word tokens.

**Comment by cragwolfe** [comment]
My mistake. That sentence will still be included in the list of elements returned by `partition()`. That log message has to do with classifying it as an element with type `Title` or another [element type](https://unstructured-io.github.io/unstructured/getting_started.html#document-elements) such as `NarrativeText`.

**Comment by shufanhao** [comment]
sorry, @cragwolfe , my understanding is that skip sentence that less than 5 tokens, is it right ? if correct, how to avoid it ?

**Comment by qued** [comment]
Hi @shufanhao , I have put in a PR to update the log message to hopefully be more clear in #1410 . If you're asking whether the sentence is skipped in the output, the answer is no. Sentences with less than 5 words are not counted during one of the steps we use internally to determine whether an element it a title, but they are included in the output.

If, on the other hand, you're asking if you can change the internal text-based logic on how elements are classified as titles, we don't currently expose parameters at a high level to control that logic.
