### ISSUE TITLE
Add support for processing `.mbox` files

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#755]
The goal of this issue is to add support for processing `.mbox` files so that users can process an entire mailbox instead each `.eml` file individually.

**Comment by kafkasl** [comment]
any suggestion on how to implement this? I've been using other people's repository to do the conversion before using this repo. They were not too reliable so I was not going to test this one https://github.com/noelmartinon/mboxzilla.git.

**Comment by SimranJha2408** [comment]
did we implement this?

**Comment by orlandounstructured** [comment]
Closing because longer than 180 days; reopen with comment if the issue is still relevant
