### ISSUE TITLE
bug/Malformed pptx template preventing pptx parsing

### ISSUE THREAD

**Issue by arms3** [Unstructured-IO/unstructured#760]
**Describe the bug**
Certain elements in PowerPoint templates that have no shape.top and shape.left cause the function `unstructured.partition.pptx._order_shapes` to fail. I have multiple files where this issue has somehow occurred. I'm not sure how to reproduce from scratch but I have attached an example file.

**To Reproduce**
Run:
`partition_pptx(filename='fake-power-point-malformed.pptx')`
With input file: 
[fake-power-point-malformed.pptx](https://github.com/Unstructured-IO/unstructured/files/11760706/fake-power-point-malformed.pptx)

**Desktop (please complete the following information):**
 - OS: windows
 - Python version: 3.11.4

**Additional context**
- Issue seems to be cleared when the theme / template is changed for the source document.
- Issue results in a placeholder at top left of the slide but with `top` and `left` attributes == None.

**Comment by MthwRobinson** [comment]
@arms3 - Thanks for reporting this! We're tracking it and will pick it up as soon as we can. Appreciate you adding the example malformed file.

**Comment by arms3** [comment]
@MthwRobinson I actually have a fix see [PR 761](https://github.com/Unstructured-IO/unstructured/pull/761)

**Comment by MthwRobinson** [comment]
Closed by #761
