### ISSUE TITLE
Detect list items in MS Word Documents

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#768]
Currently, bulleted and enumerated lists are not detected in MS Word documents. They are currently detected as either Narrative Text or Titles. The goal of this issue is to update `partition_docx` so that these elements are detected. This may require a check of the element XML for the section of text in question.

**Comment by Coniferish** [comment]
Can you tell me more about this issue? Looking at the `expected_elements` fixture in `test_docx.py`, it seems like we are detecting bulleted lists. Is this issue specific to MS Word documents?

**Comment by MthwRobinson** [comment]
Here's an example document where the bullet points are identified as NarrativeText.

- [list-item-missing.docx](https://github.com/Unstructured-IO/unstructured/files/11906186/list-item-missing.docx)

**Comment by saeedesmaili** [comment]
I also have this issue. I have downloaded a bunch of docs files from google drive (google exports them as `docx` files when downloading a directory on google drive. The documents have many normal and nested bullet points, but they're identified either as `NarrativeText` or `Title` when I use `unstructured`.

**Comment by MthwRobinson** [comment]
Thanks for the additional detail @saeedesmaili . @Coniferish is working on this issue now
