### ISSUE TITLE
bug/`partition` identifies codes blocks as narrative text 

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#771]
**Describe the bug**
In some cases, `partition` misidentifies code snippets as `NarrativeText`, limiting the ability of users to find natural language text within documents.

**To Reproduce**
Using the attached image:

```python
from unstructured.partition.auto import partition

filename = "my-doc.jpg"
elements = partition(filename=filename)
```

However, note that the original document that had this issue was a PDF.

**Expected behavior**
This text should be identified ideally as `CodeBlock`. If code blocks are difficult to identify, these could be `UncategorizedText` to solve the immediate issue. 

**Screenshots**
![image](https://github.com/Unstructured-IO/unstructured/assets/1635179/145702a2-e389-49fc-af3d-6052e5663db3)

**Desktop (please complete the following information):**
 - `unstructured==0.7.6`

**Comment by sudarshansivakumar** [comment]
Are there any updates on this? 
Still noticing that codeblocks get picked up as Narrative Text even in a markdown file?

**Comment by orlandounstructured** [comment]
Closing because longer than 180 days; reopen with comment if the issue is still relevant

**Comment by karaimin** [comment]
Reproducing it with markdown and html documents
