### ISSUE TITLE
Bug/None Type error

### ISSUE THREAD

**Issue by dknamikaze** [Unstructured-IO/unstructured#782]
**Describe the bug**
While Processing XML using Langchain which uses Unstructured Package, it gives an None-Type Error at leaf nodes Line 39 in Unstructured.Partition.xml.py under function get_leaf_elements()

**To Reproduce**

from langchain.document_loaders import UnstructuredXMLLoader
loader = UnstructuredXMLLoader(
            file_path=file_path            #file path to an XML doc.
        )
raw_documents = loader.load()  #gives error on this line

**Expected behavior**
Just process the documents and return string
<img width="855" alt="Screenshot 2023-06-21 130522" src="https://github.com/Unstructured-IO/unstructured/assets/88419852/56116644-f8ac-411b-a385-516e97f81498">

**Screenshots**
Attached a screenshot

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Python version 3.11.3

**Additional context**
I was trying to upload xml documents and get all information from them to store it in my vectored database. I m using langchain framework.

<img width="855" alt="Screenshot 2023-06-21 130522" src="https://github.com/Unstructured-IO/unstructured/assets/88419852/fa5513dc-cd6d-4730-920d-b3090f3e6ff3">

**Comment by MthwRobinson** [comment]
@dknamikaze - Thanks for reporting this issue, we'll take a look at it. Are you able to provide an example of a document that causes the issue?

**Comment by MthwRobinson** [comment]
Got it, thanks @dknamikaze! We'll take a look at this as soon as we can.

**Comment by dknamikaze** [comment]
I can work on it, I think I may have corrected the issue, at least for my project use-case.

**Comment by dknamikaze** [comment]
@MalteHB recent contribution  #[68aa2f4](https://github.com/Unstructured-IO/unstructured/pull/734/commits/68aa2f428d8872967ebec80c4dd3c6cf206ac686) should fix this issue. It's the same thing i used for my project use-case.
@MthwRobinson
