### ISSUE TITLE
How to extract numbered items in a PDF?

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [Unstructured-IO/unstructured#783]
Hi,

I am working with PDF documents that contain a lot of numbered entries such as:
![grafik](https://github.com/Unstructured-IO/unstructured/assets/36956461/aea9789f-e212-478f-b2da-0c5887be8734)

It would be nice to extract chunks of text for each numbered entry. I have looked at the document elements [here](https://unstructured-io.github.io/unstructured/getting_started.html#document-elements), however I am not sure how to do this. I am following [this tutorial](https://weaviate.io/blog/ingesting-pdfs-into-weaviate), because I'd like to get these PDFs into a db.

Example file: 
[295488_textliche_festsetzungen.pdf](https://github.com/Unstructured-IO/unstructured/files/11817203/295488_textliche_festsetzungen.pdf)

Can you recommend an approach, or some related documentation/tutorials?

Kind regards

**Comment by qued** [comment]
What comes to mind is using a regex pattern to find the section markers, and then extracting everything after the marker and before the next marker into some data structure.

I think this would get you in the vicinity of what you want:

```python
import re
from unstructured.partition.auto import partition

p = partition('295488_textliche_festsetzungen.pdf')

section_pattern = re.compile(r'[A-Z]$|[0-9]+(\.[0-9]+)*$')

sections = []
current_section = None
current_entry = None

for el in p:
    found = re.match(section_pattern, el.text)
    if found:
        if current_entry is not None:
            sections.append(current_entry)
        current_section = found.string
        current_entry = {}
        current_entry[current_section] = []
    elif current_section is not None:
        current_entry[current_section].append(el.text)

```

This results in:
```python
[{'A': ['Planungsrechtliche Festsetzungen (§ 9 Baugesetzbuch (BauGB) und Baunutzungsverordnung (BauNVO))']},
 {'1': ['Art der baulichen Nutzung (§ 9 Abs. 1 Nr. 1 BauGB in Verbindung mit (i. V. m.) § 1 Abs. 5, 6 und 9 BauNVO)']},
 {'1.1': ['Flächen für den Gemeinbedarf (§ 9 Abs. 1 Nr. 5 BauGB)',
   'Die Flächen für den Gemeinbedarf mit der Kennzeichnung „Gebäude und Einrichtungen für soziale Zwecke“ dienen vorwiegend dem Betrieb einer Schule. Zulässig sind Schulgebäude, ergänzende Gebäude und Anlagen für soziale und sportliche Zwecke, nutzungsbezogene Stellplatzanlagen und Fahrradabstellplätze. Eine Nutzung zu sonstigen Bildungs-, sozialen, kulturellen und sportlichen Zwecken sowie als öffentlicher Kinderspielplatz ist zulässig. Wohnungen sind nicht zulässig.']}, ...}
```

**Comment by Kate-Lyndegaard** [comment]
Dear @qued,

Wow. That's perfect. Thank you very much for your support, I really appreciate it.

Kind regards,
Kate
