### ISSUE TITLE
To not throw exception "text/plain content not found in email" In the case of empty eml message body

### ISSUE THREAD

**Issue by slavag** [Unstructured-IO/unstructured#794]
Hi,
I have many emails that their parsing throws "text/plain content not found in email" In the case of empty eml message body (emails just with attachments).
Maybe you can consider not to throw that exception, as such emails are not problematic, they're mostly empty, but they're not "exceptional" ?

Thanks

**Comment by MthwRobinson** [comment]
Thanks @slavag ! We'll take a look at this ASAP and get a fix in.
