### ISSUE TITLE
bug/very large text partitions

### ISSUE THREAD

**Issue by theZaX** [Unstructured-IO/unstructured#808]
**Describe the bug**
I am using `partition_text` with this file and getting only one `narrative_text` segment back. https://storage.googleapis.com/mindsmith/uploads%2Ff4403857-5e6d-41b7-83d1-cb1c68db516a%2F369378ff-20bf-470f-ba47-809fbe9ff98d.txt
This breaks our downstream embedding process, and is not a very good partitioning of the underlying content.

**To Reproduce**
It seems like the partition_text is simply using \n\n to determine where to partition the text. So any text document that doesn't use that as a way to separate content will have very large partitions / only one partition.

**Expected behavior**
Some sort of partitioning that breaks apart lines that are long or some sort of max partition size. Looking at the document it seems like one could have a more intelligent way of partitioning it, maybe something to do with line length.

In general since partitioning often takes place in same context as embedding it might make sense to have something like a `max_partition` size. Since embedding models can only take a maximum size of content and the semantic search works better with smallish partitions.

**Comment by MthwRobinson** [comment]
@theZaX - Thanks for flagging this! Will take a look as soon as we can.

**Comment by MthwRobinson** [comment]
@theZaX - Opened a PR that adds in a `max_partition` kwarg with a default value of 1500. Will think on the line length idea too. If you have any suggestions on that, definitely let us know!

**Comment by MthwRobinson** [comment]
For the minimum partition size, would it be more helpful to filter those or combine them into a larger element?

**Comment by theZaX** [comment]
Filtration would be very easy to do as a postprocessing step, so it's not super helpful / necessary that unstructured do it. So I think combining makes more sense.

**Comment by MthwRobinson** [comment]
Yeah that makes sense to me. Opened #822 to address that. Thanks!
