### ISSUE TITLE
feat/external links to source code in documentation

### ISSUE THREAD

**Issue by LaverdeS** [Unstructured-IO/unstructured#813]
**Description**

Currently we provide code-snippets in our documentation to exemplify one-liners and the use of methods. Even though they are very useful, many times is necessary or preferred to go to directly the source code of the method. Therefore, the goal of this ticket is to add _external links to source code_ for all [Unstructured 🧱s](https://unstructured-io.github.io/unstructured/bricks.html) in our [documentation](https://github.com/Unstructured-IO/unstructured/tree/main/docs/source) so it's straight forward to follow the implementation.

**Describe the solution you'd like**

Simple and visually appealing 🔥

**Describe alternatives you've considered**

Any ideas are welcome 🎨

**Comment by MthwRobinson** [comment]
@fran-unstructured added this to the docs
