### ISSUE TITLE
bug/.csv file been recognized as txt

### ISSUE THREAD

**Issue by LeslieWongCV** [Unstructured-IO/unstructured#815]
**Describe the bug**
csv file been recognized as txt

mime_type at filetype.py is shown as text/plain
at pkg magic, the output of the magic_file() shows b'text/plain',
then later output will be FileType.TXT,

**To Reproduce**
elements = partition(filename='template.csv')
table_format = elements[0].metadata.text_as_html  # None

elements = partition_csv(filename='template.csv')
table_format = elements[0].metadata.text_as_html  # *Table Content

**Expected behavior**
same output for partition and partition_csv
I disable the LIBMAGIC, it shows the right filetype as csv.
**Desktop**
linux

**Comment by MthwRobinson** [comment]
Thanks @LeslieWongCV ! Are you able to provide the CSV for testing? If the data is sensitive, you could also provide the first few rows with fake data substituted in. 

Could you also confirm what `unstructured` version you're using? @Coniferish added logic a few weeks back to detect if a file is a CSV when the MIME type is detected as `text/plain`. If you're on the latest version there may be something we need to update in there.
