### ISSUE TITLE
Include all metadata fields when converting to dataframe or CSV

### ISSUE THREAD

**Issue by saeedesmaili** [Unstructured-IO/unstructured#888]
I found [this issue](https://github.com/Unstructured-IO/unstructured/issues/555), and I wonder why other metadata (like `filetype` and `file_directory`) are still missing when using `convert_to_dataframe` function. It would be great and useful to have them as well.

**Comment by MthwRobinson** [comment]
@saeedesmaili - Thanks for flagging this, we'll pick it up as soon as we're able.
