### ISSUE TITLE
Include parents info in the metadata

### ISSUE THREAD

**Issue by saeedesmaili** [Unstructured-IO/unstructured#889]
Given the following markdown example (which can be replicated in docx and other formats as well):

```
## My 1s project

### Intro

some text.

### Todo

some other text.

## My 2nd project

### Intro

... etc
```

It would be great to have some kind of `parents` field in the metadata to include the ids of all the parents (so there should be one parent id for `### Intro` and two parent ids for `some text.`. This can help a lot with accessing the elements and differentiating between parts of the text, especially when feeding back the data to an LLM.

**Comment by MthwRobinson** [comment]
@saeedesmaili - Appreciate this suggestions, will take a look at this as soon as we can.
