### ISSUE TITLE
`sent_tokenize` should fall back to splitting on punctuation if `punkt` isn't available

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#892]
To give users an option for a slimmer installation, the goal of this issue is to update `sent_tokenize` to fall back to splitting on a punctuation regex if the NLTK `punkt` package is not installed.

**Comment by SimranJha2408** [comment]
update?

**Comment by jscheel** [comment]
This appears to be downloaded, even if you don't use any tokenization

**Comment by orlandounstructured** [comment]
Closing because longer than 180 days; reopen with comment if the issue is still relevant
