### ISSUE TITLE
OCR library - proposition

### ISSUE THREAD

**Issue by AmineDiro** [Unstructured-IO/unstructured#904]
Hello there,
I am an ML engineer working on large-scale Document AI and have deployed pipelines processing millions of pdfs. I recently found this project and I would be happy to contribute if this is something it is possible 😄 ?

I took a look at the OCR part of the unstructured library and I saw that it is using [`pytesseract` for OCR and `pdf2img` for rasterization](https://github.com/Unstructured-IO/unstructured/blob/79f734d3f90669057be08facf255062e60b61b7a/unstructured/partition/pdf.py#L363). I have found that using these wrapper libraries can cause a lot of issues when processing documents at scale because of the added process spawning.  

IMO, I think that using `mupdf` library yields better performance and stability. It also offers the possibility to get image pixmap directly (reading the files once) and calling in the Tesseract library from C API. You can also partially OCR the pdf. 

Feel free to correct me if I missed something here, and I would be more than happy to contribute to the project 😄 !

**Comment by qued** [comment]
Hi @AmineDiro ! We're aware of `mupdf`, but as we want to maintain our Apache 2.0 license, we're not able to pick them up as a dependency due to their incompatible license. However, we are considering making things a bit more modular so that it's easy to specify your own option for OCR, rendering, or element detection.

**Comment by AmineDiro** [comment]
Hello, 
Thnks for your response. I see this makes a lot sense ! Modularising the OCR would makes things nice. The latest ‘PaddleOCR’ models showed a lot of promise and could offload OCR to GPU.

**Comment by tkumpumak** [comment]
Has anybody tested throwing that poppler based pdf2image out and replacing it with the pypdfium2?

**Comment by qued** [comment]
@tkumpumak as far as I know no one has tried it... I'll make a note to test it at some point, but feel free to give it a try yourself and report back!

**Comment by tkumpumak** [comment]
@qued I may not have time to test it soon. But if somebody tests it, on quick look, I would test if there is differences in page rotation handling. Currently it looks like pytesseract is configured to handle pages with correct orientation -> uses psm=3 by default. If pages are not expected to be correctly oriented, pytesseract should run in psm=1 which would do auto rotation for pages.
