### ISSUE TITLE
feat/keep inferred element type 

### ISSUE THREAD

**Issue by mnsRG** [Unstructured-IO/unstructured#927]
The `normalize_layout_element` function results in some "information loss", as the inferred element type is replaced by pre-specified categories (Title, NarrativeText etc)

For many use cases it would be quite useful to include the inferred type in the output.

It could be an additional `Element` property, like `inferred_type` or similar. Therefore, if you use an object detection model that predicts whether a layout element is a page-footer you will still be able to keep this information.

One of the reasons I came across this problem was because I wanted to post-process extracted layout elements that were not only texts, but also images. However, even if this was supported by the inference model (`yolox` in that case) the information was lost in the final output (being `UncategorizedText`). Probably images (or figures) could be additional classes of the same level as Text and Checkbox.

**Comment by MthwRobinson** [comment]
@mnsRG - Thanks for the issue, we'll take a look at this. @qued and @benjats07 have worked most closely on the model side and may have some thoughts on how to approach this.

**Comment by SimranJha2408** [comment]
Any status update?
