### ISSUE TITLE
feat/link category in metadata

### ISSUE THREAD

**Issue by sommohapatra** [Unstructured-IO/unstructured#941]
**Is your feature request related to a problem? Please describe.**
It's often important in my use case to understand when a text is a hyperlink. Currently, it doesn't seem possible to do this with this library

**Describe the solution you'd like**
Example: 

```
page_content='[Sources](http://wikipedia.org)' metadata={'source': 'filename.docx', 'filetype': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'page_number': 4, 'category': 'Link'}
```

**Describe alternatives you've considered**
I;m currently just going without doing this

**Comment by MthwRobinson** [comment]
@sommohapatra - Thanks for flagging this. As of `0.8.2`, we're pulling out links for HTML and a few other document types (see #959). From your example, it looks like you need hyperlinks tracker in Word documents, is that correct?

**Comment by scanny** [comment]
This is added by PR#1746. Should be merged within a week or so.

**Comment by scanny** [comment]
Merged to `main` on October 13, 2023.
