### ISSUE TITLE
feat/s3-for-all-clouds

### ISSUE THREAD

**Issue by ianpurton** [Unstructured-IO/unstructured#950]
**Is your feature request related to a problem? Please describe.**

I can't connect unstructured to s3 services other than those provided by amazon.

The boto library seems to be hardcoded for aws and I couldn't find a way to override that.

We use https://min.io for obect storage on site.

**Describe the solution you'd like**

Ability to set the URL for where we have object storage.

**Possible solution**

Use the min.io python library https://min.io/docs/minio/linux/developers/python/minio-py.html

This doesn't tie you into Amazon as many cloud providers provide storage with an s3 compatible protocol.

**Comment by MthwRobinson** [comment]
Thanks @ianpurton ! We'll take a look at this. cc: @ron-unstructured @jackretterer

**Comment by SimranJha2408** [comment]
Has this been resolved?

**Comment by MthwRobinson** [comment]
This was closed by #1606
