### ISSUE TITLE
feat/stage-for-pgvector

### ISSUE THREAD

**Issue by ianpurton** [Unstructured-IO/unstructured#951]
**Is your feature request related to a problem? Please describe.**

I'd like unstrcutured to generate embeddings and store them in pgVector

**Describe the solution you'd like**

Similar to the weaviate brick but for pgVector

**Describe alternatives you've considered**

The alternative is to write a solution by hand.

**Comment by MthwRobinson** [comment]
Hi @ianpurton , we'll take a look at this as soon as we can. In the meantime, the example notebook [here](https://github.com/Unstructured-IO/unstructured/tree/main/examples/pgvector) shows a workflow for connecting to pgvector and may be helpful. cc @ron-unstructured and @jackretterer
