### ISSUE TITLE
feat/stage-for-cassandra-brick

### ISSUE THREAD

**Issue by phact** [Unstructured-IO/unstructured#953]
**Is your feature request related to a problem? Please describe.**
Support to store vectors in [Apache Cassandra vector store](https://cwiki.apache.org/confluence/display/CASSANDRA/CEP-30%3A+Approximate+Nearest+Neighbor%28ANN%29+Vector+Search+via+Storage-Attached+Indexes) and AstraDB

**Describe the solution you'd like**
A stage for cassandra brick that prepares data to be loaded to c* or astra using the cassandra python driver.

**Describe alternatives you've considered**
Maybe dump to csv and load from there using custom code or loader like [dsbulk](https://github.com/datastax/dsbulk)?

**Additional context**
Would you accept a PR for this?

**Comment by MthwRobinson** [comment]
Thanks @phact ! We'll take a look at this. cc: @ron-unstructured @jackretterer

**Comment by SimranJha2408** [comment]
update?
