### ISSUE TITLE
Unable to extract tables from SEC filings 10-k/10-q

### ISSUE THREAD

**Issue by fernandobeast** [Unstructured-IO/unstructured#958]
there is no function under from unstructured.partition.auto import partition which can extract table content, I've looped and searched elements but no luck!

can someone help me?

**Comment by MthwRobinson** [comment]
Hi @fernandobeast, do you have a particular filing / table you're looking at that we could test against? By the way, if you haven't seen it before, we do have an [SEC filings extraction repo](https://github.com/Unstructured-IO/pipeline-sec-filings), though it predates the `partition` function. cc: @qued

**Comment by fernandobeast** [comment]
thanks for the reply @MthwRobinson, I am trying to extract data from 10-Q like numbers in balance sheet, cash flows, etc.. and I've followed the instruction in SEC filings extraction repo, for example looping the text from sec_document.get_table_of_contents() however it returns empty list.
