### ISSUE TITLE
Add support for `.tiff` files in `partition_image`

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#977]
Currently `partition_image` only supports `.jpg` and `.png`. The goal of this issue is to update `partition_image` to support `.tiff` as well.

**Comment by kravetsmic** [comment]
`partition_image` support `.tiff` files, I have just tried

**Comment by MthwRobinson** [comment]
If `.tiff` files work already, this issue can just update the documentation to reflect that.

**Comment by cragwolfe** [comment]
what about .tiff's that include multiple images? we'd probably want to include the image sequence number in element metadata.
See: https://docs.fileformat.com/image/tiff/#ifd-entry

**Comment by MthwRobinson** [comment]
Closed in #1131
