### ISSUE TITLE
feat/google-sheets

### ISSUE THREAD

**Issue by happysalada** [Unstructured-IO/unstructured#984]
**Is your feature request related to a problem? Please describe.**
I've seen support for xslx, but not yet google sheets.

**Describe the solution you'd like**
native support for google sheets would be nice

**Describe alternatives you've considered**
transforming first into a csv and then going through unstructured is the alternative at the moment

**Additional context**
There might be authentification problems to consider additionally.

**Comment by MthwRobinson** [comment]
Thanks @happysalada , we'll take a look at this. We already handle auth with Google Drive in our [Google Drive Connector](https://unstructured-io.github.io/unstructured/connectors.html#google-drive-connector). Adding support for Google sheets/docs should be doable. cc @ryannikolaidis @rbiseck3

**Comment by cragwolfe** [comment]
Yes, the Google Drive Connector[ converts google docs to other formats](https://github.com/Unstructured-IO/unstructured/blob/a5c7e5b/unstructured/ingest/connector/google_drive.py#L108) before processing. This may just work now for Google Sheets, I know was working for Google Docs.
CC @rbiseck3

**Comment by ryannikolaidis** [comment]
Yep, just confirmed that using the Google Drive Connector to process Google Sheets, as-is, does work. You will see the output partitioned sheet is processed as xlsx.

**Comment by MthwRobinson** [comment]
@happysalada - [Here](https://github.com/Unstructured-IO/unstructured/blob/a5c7e5b41ea891444c6774992160bc7fa37ef5ce/examples/ingest/google_drive/ingest.sh) is an example of how to use the Google Drive Connector.

**Comment by happysalada** [comment]
Thanks a lot!
