### ISSUE TITLE
bug/issue with downloading punkt/tokenizers

### ISSUE THREAD

**Issue by erikmuttersbach** [Unstructured-IO/unstructured#990]
**Describe the bug**
Since 0.8.5 a bug in `nlp/tokenize.py` leads to this error message:
```
[nltk_data] Error loading tokenizers: Package 'tokenizers' not found
[nltk_data]     in index
```

**To Reproduce**
```
from langchain.document_loaders import UnstructuredPDFLoader
loader = UnstructuredPDFLoader(file)
loader.load()
```

**Expected behavior**
No error message should appear on the console

**Desktop (please complete the following information):**
 - Python version 3.11

**Additional context**
Looking into the source code the problem is in 
https://github.com/Unstructured-IO/unstructured/blob/e7f2f1e3ebd1b709cdf8dde72d88e0a8bc9b71a0/unstructured/nlp/tokenize.py#L27

Until 0.8.4 `_download_nltk_package_if_not_present` would have been called with parameters `("punkt", "tokenizers")`, but in the most recent version the parameters are turned around. This leads to a tried download of a package `tokenizers`.

This is correct I believe: https://github.com/Unstructured-IO/unstructured/blob/5eb1466accc1fed044d5fec467cc635796619307/unstructured/nlp/tokenize.py

**Comment by MthwRobinson** [comment]
Thanks for the report @erikmuttersbach , we'll get this fixed and released shortly.

**Comment by tomaarsen** [comment]
Related: https://github.com/nltk/nltk/issues/3177

**Comment by MthwRobinson** [comment]
This is fixed in `0.8.7`

**Comment by tomaarsen** [comment]
Appreciate it 💪

Glad to see this project is still going strong. I remember when it had ~300 stars not that long ago!

**Comment by MthwRobinson** [comment]
Apologies for the scramble on the NLTK side @tomaarsen - appreciate the support over there!

**Comment by tomaarsen** [comment]
No worries, it happens - that's open source for you 😄
