### ISSUE TITLE
Update `test_json.py` so that it doesn't use `partition`

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#993]
Currently, the `test_json.py` module calls `partition`, which means the tests need more that the JSON dependency in order to run. This makes it hard to test `partition_json` in isolation. The goal of this issue is to update the tests so that `test_json.py` only tests functionality in the `json.py` module.

These tests show partition’ing an unstructured output .json results in deserialized elements that are equivalent to the original input.
E.g. in pseudo code:
partition(foo.pdf) = partition(save_as_json(partition(foo.pdf)))
 
So, these tests are still important, they just should be moved elsewhere.

**Comment by orlandounstructured** [comment]
Complete per Jira
